#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/vis
rm /stmpp1/Geoffrey.Manikin/meg/vis/*
cd /stmpp1/Geoffrey.Manikin/meg/vis
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
month=`cut -c 5-7 holddate`
day=`cut -c 9-10 holddate`

ymdh=2014111121
ymd=`echo $ymdh | cut -c1-8`
day=`echo $ymdh | cut -c7-8`
dayoweek=hold

times="00 03 06 09 12 15"
times="00 03 06 09 12"
times="06 09 12"
for fhr in $times; do

fmdl1=/com/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(quo(vsby,1000),0.62137) 
 CINT     = 1;2;3;4;5;10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|${cyc}raphrrrvisz${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = de
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 1;2;3;4;5;10 
 FLINE    = 2;17;5;21;26;28;0 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR  RAP VISIBILITY (miles)
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = mmsl
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 4/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR HRRR  VISIBILITY (miles)
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = mul(quo(vsby,1000),0.62137) 
 TITLE    = 0
 CINT     = 1;2;3;4;5;10 
r

ex
EOF

gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
