#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wz
rm /stmpp1/Geoffrey.Manikin/meg/10wz/*
cd /stmpp1/Geoffrey.Manikin/meg/10wz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2019071000
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="120" 
for fhr in $times; do

fmdl1=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f${fhr}
fmdl2=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl
 CINT     = 4 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ECMWF SLP 1000-500 THK 
 DEVICE   = GIF|compare10slp_${ymd}${cyc}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-92;25;/1;1;1;1
 GAREA    = 20.;-110.;40.;-84.
 GAREA    = 24.;-95.;54.;-53. 
 GAREA    = 35.;-104.;42.;-92.
 GAREA    = 28.;-95.;35.;-85. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1025-1060;920-1018/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDPFUN   = kntv(wind)
 WIND     = BK15/0.6/1/2/1
 TYPE     = b
r

 GDFILE   = $fmdl2
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = emsl
 CINT     = 4 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SLP 1000-500 THK 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1025-1060;920-1018/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GVCORD   = hght
 GLEVEL   = 10
 GDPFUN   = kntv(wind)
 WIND     = BK15/0.6/1/2/1
 TYPE     = b
r
 
 
ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
