#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/60pcp
rm /stmpp1/Geoffrey.Manikin/meg/60pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/60pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013092000
ymd=20130920
dayoweek=Wed
hours="36 60"

fmdl1=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namxnestpcp_${ymdh}

for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM NEST 24-HR TOTAL PCP
 DEVICE   = GIF|24pcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 25.;-105.;37.;-87.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.9;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5;15;17.5;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;16;17;10;19;5;32;1
# FINT     = .01;.1;.25;.5;1;1.5;2;2.5;3;4;5;6;8;10
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1/-1/~   NAMX NEST 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
r

ex
EOF
done

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f60
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p60i 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  4KM NAM 60-HR TOTAL PCP 
 DEVICE   = GIF|60pcpmodels_f60.gif|750;900
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.9;.03/1 
 CONTUR   = 0
 SKIP     = 0
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f60
 TITLE    = 1/-1/~  4KM NAMX 60-HR TOTAL PCP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f60
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(p60i+2,p60i)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 60-HR TOTAL PCP   4KM NAM - NAMX 
 DEVICE   = GIF|60pcpdiff_f60.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -2.5;-2;-1.5;-1;-0.5;0.5;1;1.5;2.;2.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 24pcpmodels_f${fhr}.gif 24pcp1.gif
$CONV/convert -crop 0x0 24pcpdiff_f${fhr}.gif 24pcp2.gif
$CONV/montage -geometry 700x750 24pcp1.gif 24pcp2.gif ${cyc}24nestxpcp${fhr}.gif
done

$CONV/convert -crop 0x0 60pcpmodels_f60.gif 60pcp1.gif
$CONV/convert -crop 0x0 60pcpdiff_f60.gif 60pcp2.gif
$CONV/montage -geometry 700x750 60pcp1.gif 60pcp2.gif ${cyc}60nestxpcp${fhr}.gif

#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdnamx/.
#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/20130920/.
exit
