#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/84cpcpz
rm /stmpp1/Geoffrey.Manikin/meg/84cpcpz/*
cd /stmpp1/Geoffrey.Manikin/meg/84cpcpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013092000
ymd=20130920
dayoweek=Fri

if [ $cyc -eq 00 ]; then
 hours="36 60 84"
elif [ $cyc -eq 06 ]; then
 hours="30 54 78"
elif [ $cyc -eq 12 ]; then
 hours="24 48 72"
else
 hours="42 66"
fi

fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}

for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = c24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 24-HR CONVECTIVE PCP
 DEVICE   = GIF|24cpcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 25.;-105.;37.;-87.    
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5;15;17.5;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;16;17;10;19;5;32;1
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  GFS 24-HR CONVECTIVE PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GFUNC    = sub(c24i+2,c24i)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 24-HR CONVECTIVE PCP   NAM - GFS
 DEVICE   = GIF|24cpcpdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.06;.9/.87;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f84
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = c84i 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 84-HR CONVECTIVE PCP 
 DEVICE   = GIF|84cpcpmodels_f84.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5;15;17.5;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;16;17;10;19;5;32;1
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f84
 TITLE    = 1/-1/~  GFS 84-HR CONVECTIVE PCP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f84
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(c84i+2,c84i)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 84-HR CONVECTIVE PCP   NAM - GFS
 DEVICE   = GIF|84cpcpdiff_f84.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 24cpcpmodels_f${fhr}.gif 24cpcp1.gif
$CONV/convert -crop 0x0 24cpcpdiff_f${fhr}.gif 24cpcp2.gif
$CONV/montage -geometry 700x750 24cpcp1.gif 24cpcp2.gif ${cyc}24cpcpz${fhr}.gif
done

$CONV/convert -crop 0x0 84cpcpmodels_f84.gif 84cpcp1.gif
$CONV/convert -crop 0x0 84cpcpdiff_f84.gif 84cpcp2.gif
$CONV/montage -geometry 700x750 84cpcp1.gif 84cpcp2.gif ${cyc}84cpcpz.gif

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/${ymd}
mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
#rm *gif
exit
