#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/6pcp
rm /stmp/Geoffrey.Manikin/meg/6pcp/*
cd /stmp/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016012300
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4
cyc=`echo $ymdh | cut -c9-10`

hours="18"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 CINT     = 4 
 GDPFUN   = p06i
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 6-HR PCP 
 DEVICE   = GIF|namslp6pcp_${ymd1}f${fhr1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 32.;-84.;48.;-62. 
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl1
 GDPFUN   = pmsl 
 TITLE    = 0 
 CLEAR    = n
 CINT     = 4
 LINE     = 4/1/2/3
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r


 GDFILE   = $fmdl2
 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 PANEL    = lr
 GDATTIM  = f$fhr4
 GDFILE   = $fmdl4 + $fmdl4b
 GDPFUN   = add(p03i^${ymd4}/${cyc4}f${fhr4b}+2,p03i^${ymd4}/${cyc4}f$fhr4) 
 HILO     = 0
 HLSYM    = 0
 TYPE     = f
 TITLE    = 1/-1/~   NAM4 6-HR PCP
r

 GDFILE   = $fmdl4
 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

ex
EOF

done
gpend

exit
