#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2015041012
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold

mkdir /stmpp1/Geoffrey.Manikin/meg/basez
cd /stmpp1/Geoffrey.Manikin/meg/basez
rm /stmpp1/Geoffrey.Manikin/meg/basez/*
cp /meso/save/Geoffrey.Manikin/meg/coltbl.xwp .

times="00 01 02 03 06 09"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymd}${cyc}f0${fhr}
fmdl1=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hrrr.${ymd}/hrrr_${ymd}${cyc}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = cldl 
 GDPFUN   = quo(mul(sub(hght,hght@0%none),3.281),1000)
 CINT     = 5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/ ${fhr}-HR NAM4 AGL CLOUD BASE HEIGHT (ft/1000) 
 DEVICE   = GIF|comparebasehires_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = md+ 
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0;.1;.3;.5;1;5;10;15;20;25;30;35;40;45
 FLINE    = 0;15;2;17;10;5;20;21;22;23;25;4;24;29;30
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2 
 CLEAR    = n
 PANEL    = b
 GDPFUN   = quo(mul(sub(hght,hght@0%none),3.281),1000)
 TITLE    = 1/-1/ ${fhr}-HR HRRR AGL CLOUD BASE HEIGHT (ft/1000) 
 CLRBAR   = 0
r

ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
