#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/sref500
rm /stmpp1/Geoffrey.Manikin/meg/sref500/*
cd /stmpp1/Geoffrey.Manikin/meg/sref500
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 03 09 15 21 27 33 39 45 51 57 63 69 75 81 87"
for fhrs in $times; do

fhrnew=`expr $fhrs - 3`
typeset -Z2 fhrs fhrnew

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhrnew}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhrnew}
fmdl3=/com2/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean

    gdplot2 << EOF

 GDFILE   = $fmdl3
 GDATTIM  = f$fhrs
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = quo(hghtenmw,10) 
 CINT     = 6 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF MEAN 500 MB HGT 
 DEVICE   = GIF|500sref_f0${fhrs}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 18.;-130.;58.;-60. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = avor
 CINT     = 2/10/46
 CLEAR    = n
 SCALE    = 5
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 TYPE     = f
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl3
 GDATTIM  = f${fhrnew}
 GLEVEL   = 500 
 GVCORD   = pres 
 GFUNC    = sub(hghtenmw^${ymds}/${cycs}f${fhrs}+2,hght)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//500Z  ${cycs}z SREF f${fhrs}   -   ${cyc}z NAM f${fhrnew}
 DEVICE   = GIF|500diff_f0${fhrs}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = t
 TEXT     = 1./11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.12;.45/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -150;-120;-90;-60;-30;30;60;90;120;150
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2 + $fmdl3
 GFUNC    = sub(hghtenmw^${ymds}/${cycs}f${fhrs}+2,hght)
 TITLE    = 1//500Z  ${cycs}z SREF f${fhrs}   -   ${cyc}z GFS f${fhrnew}
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
r

ex
EOF
gpend
done

for fhrs in $times; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 500sref_f0${fhrs}.gif 5002.gif
$CONV/convert -crop 0x0 500diff_f0${fhrs}.gif 5001.gif
$CONV/montage -geometry 800x850 5001.gif 5002.gif ${cycs}500sref${fhrs}.gif
done
 
mv ${cycs}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
