#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymd=`cut -c 7-14 /com/date/t${cyc}z`
cyc=`cut -c 15-16 /com/date/t${cyc}z`
ymd=20130514
dayoweek=Tue
DAPATH=/com/nam/prod/nam.${ymd}

mkdir /stmpp1/Geoffrey.Manikin/meg/msav
cd /stmpp1/Geoffrey.Manikin/meg/msav
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

times="00"

for fhr in $times; do

wgrib -i -d 105 ${DAPATH}/nam.t${cyc}z.awip12${fhr}.tm00 -grib -o mdl1

  nagrib << EOF
GBFILE  = mdl1
INDXFL  =
GDOUTF  = mdl1.gem
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

fmdl1=mdl1.gem
fmdl2=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0:100
 GVCORD   = dpth 
 GDPFUN   = msav 
 CINT     = 2;10;20;30;40;50;60;70;80;90;100  
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/ ${fhr}-HR NAM SOIL MOISTURE AVAILABILITY 
 DEVICE   = GIF|msav2_${ymd}${cyc}f0${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 25.;-118.;49.;-70. 
 GAREA    = ut-
 GAREA    = us
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.04;0.9/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 2;10;20;30;40;50;60;70;80;90;100 
 FLINE    = 0;8;10;9;17;19;21;22;23;25;26;4 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GLEVEL   = 0
 GVCORD   = none
 CLEAR    = n
 PANEL    = b
 TITLE    = 1/-1/ ${fhr}-HR RAP SOIL MOISTURE AVAILABILITY
r

ex
EOF

gpend
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
