#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dewmr
rm /stmpp1/Geoffrey.Manikin/meg/2dewmr/*
cd /stmpp1/Geoffrey.Manikin/meg/2dewmr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 24 48 72 96 108 120 132 144 156 168 180 192"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f${fhr}
fmdl2=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = dwpf 
 CINT     = 5
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ECMWF 2-M DWPF 
 DEVICE   = GIF|2dewmodels_f${fhr}.gif|900;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 14.;-122.;50;-62
 CLEAR    = y
 PANEL    = t
 TEXT     = 1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.1;0.4/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;54;58;62;66;70;74;78;82
 FLINE    = 0;21;22;23;28;29;30;2;15;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GLEVEL   = 2
 GVCORD   = HGHT
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~   GFS 2-M DWPF 
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = f 
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(dwpf%hght@2+2,dwpf)
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M DWPF   GFS - ECMWF
 DEVICE   = GIF|2dewdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.06;.6/.55;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -25;-20;-15;-10;-5;5;10;15;20;25
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2dewmodels_f${fhr}.gif 2dew1.gif
$CONV/convert -crop 0x0 2dewdiff_f${fhr}.gif 2dew2.gif
$CONV/montage -geometry 800x850 2dew1.gif 2dew2.gif ${cyc}2dew${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdmedr/.
exit
