#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/pw
rm /stmpp1/Geoffrey.Manikin/meg/pw/*
cd /stmpp1/Geoffrey.Manikin/meg/pw
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
mon=`cut -c 5-7 holddate`
day=`cut -c 9-10 holddate`
gtime=`cut -c 12-24 holddate`
gdate=`cut -c 1-10 holddate`
gcent=`cut -c 25-28 holddate`
echo $dayoweek

#ymdh=2013092000
#ymd=20130920
#dayoweek=Fri

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
for fhr in $times; do

fmdl1=/gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam32_${ymdh}f0${fhr}
cp /gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f0${fhr} fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(pwtr,25.4)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  PCP WATER 
 DEVICE   = GIF|pwmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .25;.5;.75;1.;1.25;1.5;1.75;2.;2.25;2.5
 FLINE    = 0;21;22;23;28;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS  PCP WATER 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none  
 GFUNC    = quo(sub(pwtr+2,pwtr),25.4)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ PW   NAM - GFS
 DEVICE   = GIF|pwdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.;-.8;-.6;-.4;-.2;.2;.4;.6;.8;1.
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 pwmodels_f0${fhr}.gif pw1.gif
$CONV/convert -crop 0x0 pwdiff_f0${fhr}.gif pw2.gif
$CONV/montage -geometry 800x850 pw1.gif pw2.gif ${cyc}pw${fhr}.gif
done

cat > info.html <<EOFmet
<HTML>
<BODY bgcolor="FFCC99">
<CENTER><H2><b><u>NCEP MEG SHORT-RANGE FORECASTING PAGE</H2></CENTER></u></b>
<p>
<CENTER>
The current forecast cycle is <b><font face="Times New Roman,Times"><font size=+1><font color="#CC000
0">${cyc}Z ${day} ${mon} </font><font color="#FF6600"></font></font></font></b> with graphics finished at $gtime $gdate $gcent
</CENTER>
<p>

<H4>NOTE: All displayed winds are in knots.  Precipitation values are in inches.</H4>
<p>
<img src ="../../../www_images/graysquare_line.gif"> </a>
<p>
<H4><i>EMC DISCLAIMER : This web page is not "operational" and therefore
not subject to 24-h monitoring by NCEP's Central Operations staff.</i></H4>
<p>
<img src ="../../../www_images/graysquare_line.gif"> </a>
<p>
<H2> Get the forecasts for the previous 7 days here (link opens a new window):</H2><p>
<TABLE BORDER>
<THEAD>
<TR>
<TH>SUNDAY</TH>
<TH>MONDAY</TH>
<TH>TUESDAY</TH>
<TH>WEDNESDAY</TH>
<TH>THURSDAY</TH>
<TH>FRIDAY</TH>
<TH>SATURDAY</TH>
</TR>
<TBODY>
<TR>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Sun.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Mon.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Tue.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Wed.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Thu.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Fri.html"TARGET=_blank>X</A></TH>
<TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/gmanikin/meg/short/index_Sat.html"TARGET=_blank>X</A></TH>
</TR>
</BODY>
</TABLE>
<p>
<p>
<img src ="../../../www_images/graysquare_line.gif"> </a>
<p>
<b><font face="Times New Roman,Times"><font size=+1><font color="#993399">CHECK OUT THESE OTHER EMC WEB PAGES WITH FORECAST PLOTS </font>
<p>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><a href="http://www.emc.ncep.noaa.gov/mmb/mmbpll/ncepmods"TARGET=_blank> Eric Rogers' NCEP Models Page</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/opsnam"TARGET=_blank> Eric Rogers' Enhanced NAM Page</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/soundings.nam/snding.html"TARGET=_blank> NAM Forecast Soundings</A></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/nam_conusnest"TARGET=_blank> NAM CONUS Nest</A></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/firewx"TARGET=_blank> Fire Wx Nest Graphics</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mpyle/spcprod/00_zeus"TARGET=_blank> Matt Pyle's 4 km NMM Run</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/SREF/SREF.html"TARGET=_blank> SREF</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/namsst"TARGET=_blank> NAM SST</a></H4></TH>
<img src ="../../../www_images/graysquare_line.gif"> </a>
<p>
<b><font face="Times New Roman,Times"><font size=+1><font color="#993399">CHECK OUT THESE OTHER EMC WEB PAGES WITH VERIFICATION INFO </font>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/ylin/pcpverif/daily"TARGET=_blank> Ying Lin's Daily Pcp Verification</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/ylin/pcpverif/scores"TARGET=_blank> Ying Lin's Monthly Pcp Verification</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/zverif_ops"TARGET=_blank> NAM/GFS 500 mb Verification</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://www.emc.ncep.noaa.gov/mmb/mmbpll/mmbverif"TARGET=_blank> EMC Verification Stats</a></H4></TH>
<H4><img src ="../../../www_images/eye_dot.gif"></a><TH><A HREF="http://rtvs.noaa.gov/ncep_models/stats"TARGET=_blank> RTVS Model Verification</a></H4></TH>
<p>
</HTML>
EOFmet

cat > info_$dayoweek.html <<EOFmet
<HTML>
<BODY bgcolor="FFCC99">
<CENTER><H2><b><u>NCEP MEG SHORT-RANGE FORECASTING PAGE</H2></CENTER></u></b>
<p>
<CENTER>
These are graphics for <b><font face="Times New Roman,Times"><font size+1><font color="#CC0000"> ${day} ${mon} </font><font color="#FF6600"></font></font></font></b> 
</CENTER>
<p>
</BODY>
</HTML>
EOFmet

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
mv *html /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
