#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wsmart
rm /stmpp1/Geoffrey.Manikin/meg/10wsmart/*
cd /stmpp1/Geoffrey.Manikin/meg/10wsmart
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014110212
ymd=20141102
dayoweek=hold

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="06"
for fhr in $times; do

fmdl1=/ptmpd1/Geoffrey.Manikin/com/nawips/para/nam.${ymd}/namsmartoldops2p5_${ymdh}f0${fhr}
fmdl2=/ptmpd1/Geoffrey.Manikin/com/nawips/para/nam.${ymd}/namsmartpara2p5_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = knts(sped)
 CINT     = 10 
 LINE     = 0 
 DEVICE   = GIF|${ymdh}_10wsmart2p5${fhr}oldops.gif | 800;850
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = 37.;-80.;41.;-74. 
 TITLE    = 1//~  NAM OLD OPS 2.5 SMART WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 1.1/11/2
 FINT     = 10;15;20;25;30;35;40;45;50;55;60
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = AK1/0.5/1/122
 GDPFUN   = kntv(wnd)
 SKIP     = /40;40
 TYPE     = a
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = knts(sped)
 CINT     = 5
 LINE     = 0
 TITLE    = 1//~  NAM PARA 2.5 SMART WIND (KT)
 CLEAR    = n
 PANEL    = b
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 1.1/11/2
 TYPE     = f
r

 CINT     =
 WIND     = AK1/0.6/1/122
 GDPFUN   = kntv(wnd)
 TYPE     = a
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
