#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/spcuphl3
rm /stmpp1/Geoffrey.Manikin/meg/spcuphl3/*
cd /stmpp1/Geoffrey.Manikin/meg/spcuphl3
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013061300
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Thu

hours="10 11 12 13 14 15 16 17 18"
hours="21 22 23 24 25 26 27 28 29 30"
hours="18 21 24"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

areas="1"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="md+"
proj="lcc/25.;-75.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = uphl 
 CINT     = 5 
 LINE     = 1 
 DEVICE   = GIF|${cyc}nestcountyuphl${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 MAP      = 1/1/2;1
 \$MAPFIL = county
 TITLE    = 1//~  4 KM NAM  2-5 KM UPDR HLCY 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0 
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.07;0.95/0.85;.03/1
 TEXT     = 0.9/11/2
 FINT     = 2;5;10;25;50;75;100;125;150
 FLINE    = 0;21;23;4;26;2;15;16;10;5
 TYPE     = f 
r

ex
EOF
done
done
gpend

exit
