#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
ymdh=2012072200
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/capeexp
rm /stmpp1/Geoffrey.Manikin/meg/capeexp/*
cd /stmpp1/Geoffrey.Manikin/meg/capeexp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="27 30 33 36"
for fhr in $times; do

fmdl1=/ptmpp1p1/Geoffrey.Manikin/gfs/gfs40_${ymdh}f0${fhr}
fmdl2=/ptmpp1p1/Geoffrey.Manikin/gfs/gfsexp_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 180:0 
 GVCORD   = pdly 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   OPS GFS BEST CAPE 
 DEVICE   = GIF|bcapemodels_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-120.;51.;-66. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  EXP GFS BEST CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 180:0
 GVCORD   = pdly 
 GFUNC    = sub(cape+2,cape)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 DEVICE   = GIF|bcapediff_f0${fhr}.gif | 600;650
 TITLE    = 1//  180 mb BEST CAPE  GFS   OPS - EXP 
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;.9/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1500;-1000;-750;-500;-250;250;500;750;1000;1500 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

/usrx/local/im_beta/bin/convert -crop 0x0 bcapemodels_f0${fhr}.gif bcape1.gif
/usrx/local/im_beta/bin/convert -crop 0x0 bcapediff_f0${fhr}.gif bcape2.gif

CONV=/usrx/local/imajik/bin
$CONV/montage -geometry 700x750 bcape1.gif bcape2.gif ${cyc}expbestcape${fhr}.gif
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

rm *gif
exit
