#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slpgefs
rm /stmpp1/Geoffrey.Manikin/meg/slpgefs/*
cd /stmpp1/Geoffrey.Manikin/meg/slpgefs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 24 48 72 96 108 120 132 144 156 168 180 192"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/com2/nawips/prod/gefs.${ymd}/geavg_${ymdh}f${fhr}
#fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_${ymdh}f${fhr}
fmdl2=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 4
 LINE     = 4/1/4/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GEFS MEAN SLP 
 DEVICE   = GIF|slpmodels_f${fhr}.gif|900;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 10.;-144.;72.;-36. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1/11/2/SW
 SCALE    = 0
 LATLON   = 0 
 HILO     = 23;23/S12#;S13#/1015-1060;920-1014/5/4;4/yes
 HLSYM    = 1;1/3/21;21/1;1/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = c
 LUTFIL   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~   GFS SLP 
 PANEL    = b
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(pmsl+2,pmsl)
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~  SLP  GFS - GEFS MEAN 
 DEVICE   = GIF|slpdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 10.;-144.;72.;-36.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.06;.6/.55;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -25;-20;-15;-10;-5;5;10;15;20;25
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 slpmodels_f${fhr}.gif slp1.gif
$CONV/convert -crop 0x0 slpdiff_f${fhr}.gif slp2.gif
$CONV/montage -geometry 800x850 slp1.gif slp2.gif ${cyc}slpgefs${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdmedr/.
#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
