#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefcx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018060700
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold7

areas="8"
#garea="36.;-98.;50.;-78."
garea="32.;-104.;41.;-92."
proj="lcc/25.;-98.;25./1;1;1;1"

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="00 03 06 09 12 15 18 21 24"
hours="18 21 24 27 30"
hours="03 06 09 12"
hours="15 18 21 24"
for fhr in $hours; do

DAPATH=/com2/nawips/prod/nam.${ymd}/
DAPATH2=/gpfs/hps/nco/ops/com/hiresw/prod/hiresw.${ymd}/
DAPATH2=/meso/save/Geoffrey.Manikin/meg/
fmdl1=${DAPATH}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/hiresw_conusarw_${ymdh}
fmdl3=${DAPATH2}/hiresw_conusnmmb_${ymdh}
fmdl4=${DAPATH2}/hiresw_conusmem2arw_${ymdh}
#fmdl4=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hiresrefc${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  NAM CONUS NEST  REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  REFC 
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMMB  REFC 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  HIRESW ARW2  REFC 
 CLRBAR   = 0
r

ex
EOF
done

hours=""
for fhr in $hours; do

fmdl5=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl6=/meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl7=/ptmpd1/Geoffrey.Manikin/com/nawips/para/nam.${ymd}/namrr_conusnest_${ymdh}f0${fhr}
fmdl8=/meso/save/Geoffrey.Manikin/meg/nsslwrf_${ymdh}

#fmdl5=/ptmpp1/Geoffrey.Manikin/hold2/nam_conusnest_${ymdh}f0${fhr}
#fmdl6=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
#fmdl7=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
#fmdl8=/ptmpp1/Geoffrey.Manikin/hold2/hrrr_${ymdh}f0${fhr}00

   gdplot2 << EOF
 GDFILE   = $fmdl5
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = refc
 CINT     = 5
 LINE     = 0
 DEVICE   = GIF|${ymd}${cyc}hires2refc${region}_f${fhr}.gif | 800;850
 PROJ     = $proj
 GAREA    = $garea
 TITLE    = 1//~  NAM CONUS NEST  REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f
r

 GDFILE   = $fmdl6
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  NAMX NEST REFC
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl7
 PANEL    = lr
 TITLE    = 1//~  NAMRR NEST  REFC
 CLRBAR   = 0
r

 GDFILE   = $fmdl8
 PANEL    = ur
 TITLE    = 1//~  NSSL WRF  REFC
 CLRBAR   = 0
r

ex
EOF
done

for fhr in $hours; do

fmdl9=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl10=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
#fmdl9=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
#fmdl10=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl11=/com2/nawips/para/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl12=/com2/nawips/para/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}

   gdplot2 << EOF
 GDFILE   = $fmdl9
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = refc
 CINT     = 5
 LINE     = 0
 DEVICE   = GIF|${ymd}${cyc}hires3refc${region}_f${fhr}.gif | 800;850
 PROJ     = $proj
 GAREA    = $garea
 TITLE    = 1//~  HIRESW ARW  REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f
r

 GDFILE   = $fmdl11
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  REFC
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl12
 PANEL    = lr
 TITLE    = 1//~  HIRESW NMMB  REFC
 CLRBAR   = 0
r

 GDFILE   = $fmdl10
 PANEL    = ur
 TITLE    = 1//~   HIREWS NMMB  REFC
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefc/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
