#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/swem
rm /stmpp1/Geoffrey.Manikin/meg/swem/*
cd /stmpp1/Geoffrey.Manikin/meg/swem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2020022012
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

fhr=24
fhr6=`expr $fhr - 24`
typeset -Z3 fhr fhr6

DAPATH1=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak
fmdl1=${DAPATH1}/gfs_0p25_${ymdh}f${fhr6}
cp ${DAPATH1}/gfs_0p25_${ymdh}f${fhr} fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1 + fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sub(sndm+2,sndm^${ymd}/${cyc}f${fhr6}),100),2.54) 
 CINT     = 2 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//~ ${fhr}-HR GFS SNOW DEPTH (IN) 
 DEVICE   = GIF|gfs6sndm_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-76.;25./2;2;1;1
 GAREA    = 33.4;-87.;44.4;-69. 
 GAREA    = 23.;-136.;67.;-48.
 GAREA    = 33.;-88.;43.;-74. 
 GAREA    = nc+
 CLEAR    = y
 PANEL    = b
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.1;0.9/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.1;1;3;5;7.5;10;15;20;25;50;75;100;125
 FINT     = 0.1;1;2;4;6;8;10;12;15;20;25
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;9
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(mul(sub(swem+2,swem^${ymd}/${cyc}f${fhr6}),10),25.4)
 TITLE    = 1//~ ${fhr}-HR GFS SNOW ACCUM 10:1 (IN) 
 PANEL    = t
 CLEAR    = n
r

exit
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
