#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefd3
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefd3/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefd3
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014111800
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

hours="10 11 12 13 14 15 16 17 18"
hours="21 22 23 24 25 26 27 28 29 30"
hours="21"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl4=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

areas="1"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="40.;-84.;46.;-74"
proj="lcc/25.;-77.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 5 
 LINE     = 1 
 DEVICE   = GIF|${ymdh}hirescape${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 MAP      = 1/1/2;1
 TITLE    = 1//~  NAM CONUS NEST  SFC CAPE 
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 100;250;500;750;1000;1250;1500
 FLINE    = 0;28;27;25;23;21;5;10;17;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  SFC CAPE 
 CLRBAR   = 1/H/UL/.46;0.94/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMMB  SFC CAPE 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  HRRR  SFC CAPE 
 CLRBAR   = 0
r

ex
EOF

done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefd/.
exit
