#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrrpcpx
rm /stmpp1/Geoffrey.Manikin/meg/hrrrpcpx/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrrpcpx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016041802
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

hours="15"
garea="26.;-102.;34.;-92."
proj="lcc/25.;-97.;25./2;2;1;1"

for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

typeset -Z2 fhr1 fhr2 fhr3
DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
DAPATHX=/com2/nawips/para
fmdl1=${DAPATH}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl1x=${DAPATHX}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=${DAPATH}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr}00
fmdl2x=${DAPATHX}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr}00
fmdl3=${DAPATH}/hrrr.${ymd2}/hrrr_${ymdh2}f0${fhr}00
fmdl3x=${DAPATHX}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr}00
fmdl4=${DAPATH}/hrrr.${ymd3}/hrrr_${ymdh3}f0${fhr}00
fmdl4x=${DAPATHX}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p15i 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrxpcp_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z HRRR   15-HR TOT PCP
 CLEAR    = y
 \$MAPFIL = county
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 0.8/11/2
# FINT     = .01;.1;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;6;8
  FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;19;5
 TYPE     = f 
r

 GDFILE   = $fmdl1x
 PANEL    = ll 
 CLEAR    = n
 TITLE    = 1//~  ${cyc}z HRRRX   15-HR TOT PCP 
 CLRBAR   = 1/H/UL/.1;.98/1.8;.03|.7
r

 GDFILE   = $fmdl2
 PANEL    = ur 
 TITLE    = 1//~  ${cyc1}z HRRR   15-HR TOT PCP 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl2x
 PANEL    = lr 
 TITLE    = 1//~  ${cyc1}z HRRRX   15-HR TOT PCP 
 CLRBAR   = 0 
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
