#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/cslp
rm /stmpp1/Geoffrey.Manikin/meg/cslp/*
cd /stmpp1/Geoffrey.Manikin/meg/cslp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015091200
dayoweek=hold3
ymd=`echo $ymdh | cut -c1-8`

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
#times="12 15 18 21 24 27"
times="21 24"
for fhr in $times; do

DAPATH=/com/nawips/prod/nam.${ymd}/
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/
fmdl1=${DAPATH}/nam12_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam_conusnest_${ymdh}f0${fhr}
echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 2 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ NAM SLP
 DEVICE   = GIF|parentnestslp${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = oh 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 18;18/S12#;S13#/1015-1060;920-1014/5/2;2/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~ 4 KM NAM SLP
 PANEL    = b
 CLEAR    = n
r

ex
EOF
done
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
for fhr in $times; do
$CONV/convert -crop 0x0 parentnestslp${fhr}.gif ${cyc}parentnestslp${fhr}.gif
done
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
