#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefc
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefc/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015103012
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

hours="03 06 09 12 15 18 21 24"
#hours="09 12 15 33 36 39"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

garea="tx"
proj="lcc/25.;-97.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|namnestrefc${region}_${ymdh}f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  NAM REFC 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.6/1.2;.03/1
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b 
 CLEAR    = n
 TITLE    = 1//~  NAM CONUS NEST REFC 
 CLRBAR   = 0 
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
