#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcp
rm /stmpp1/Geoffrey.Manikin/meg/6pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015082612
ymd=20150826
dayoweek=hold3
times="33"
for fhr in $times; do

fhr3=`expr $fhr - 3`
typeset -Z2 fhr3

fmdl1=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = p03i
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 3-HR PCP 
 DEVICE   = GIF|3pcprategfsf0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = fl 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = mul(pr03,425.2)
 TITLE    = 1/-1/~  GFS 3-HR PCP via RATE
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
