#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/sref48pcp
rm /stmpp1/Geoffrey.Manikin/meg/sref48pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/sref48pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdhs=`cut -c 7-16 /com/date/t${cyc}z`
ymds=`cut -c 7-14 /com/date/t${cyc}z`

ymdhs=2014021021
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Mon

if [ $cycs -eq 21 ]; then
 hours="39 63 87"
elif [ $cycs -eq 03 ]; then
 hours="33 57 81"
elif [ $cycs -eq 09 ]; then
 hours="27 51 75"
else
 hours="45 69"
fi

hours="87"
for fhrs in $hours; do

fmdl1=/com/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean
fmdl2=/com/nawips/para/sref.${ymds}/sref212_${ymdhs}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(p48menmw,25.4) 
 CINT     = 4 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF MEAN 48-HR PCP  
 DEVICE   = GIF|${cycs}srefx48meanpcp_f0${fhrs}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 18.;-128.;58.;-62. 
 GAREA    = de-
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 1/h/UL/.06;.95/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 PANEL    = b
 TITLE    = 1/-1/~   SREFX MEAN 48-HR PCP 
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
