#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slpz
rm /stmpp1/Geoffrey.Manikin/meg/slpz/*
cd /stmpp1/Geoffrey.Manikin/meg/slpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014110712
ymd=20141107
dayoweek=hold

times="00 06 12 18 24 30 36 42 48 54 60"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/nam.${ymd}/nam_alaskanest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = knts(gust)
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM GUST 
 DEVICE   = GIF|gustnest_${ymdh}f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = str/90;-145;0;/1;1;1;1
 GAREA    = 35.;-190.;75.;-118.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.02;0.5/0.9;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;20;30;40;50;60;70;80;90
 FLINE    = 0;29;25;21;23;5;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM NEST  GUST 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 0
 SCALE    = 0
 LATLON   = 0
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
