#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850z
rm /stmpp1/Geoffrey.Manikin/meg/850z/*
cd /stmpp1/Geoffrey.Manikin/meg/850z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014111300
ymd=20141113
dayoweek=hold

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 06"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = relh 
 CINT     = 10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 850 mb  RELH 
 DEVICE   = GIF|850models_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ok- 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/.8;.02/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 1;5;10;20;30;40;50;60;70;80;90 
 FLINE    = 0;9;12;7;30;28;4;25;27;21;23;5;20;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 WIND     = 0
 TITLE    = 1/-1/~   GFS 850 mb RELH 
 CLRBAR   = 0 
 CLEAR    = n
 PANEL    = b
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 850
 GVCORD   = pres
 GFUNC    = sub(relh+2,relh)
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 850 Z   NAM - GFS
 DEVICE   = GIF|850diff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.88/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -50;-40;-30;-20;-10;10;20;30;40;50 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 850models_f0${fhr}.gif 8501.gif
$CONV/convert -crop 0x0 850diff_f0${fhr}.gif 8502.gif
$CONV/montage -geometry 800x850 8501.gif 8502.gif ${cyc}850relh${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
