#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/srefcape
rm /stmpp1/Geoffrey.Manikin/meg/srefcape/*
cd /stmpp1/Geoffrey.Manikin/meg/srefcape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 03 09 15 21 27 33 39 45 51 57 63 69 75 81 87"
for fhrs in $times; do

fhrnew=`expr $fhrs - 3`
typeset -Z2 fhrs fhrnew

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhrnew}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhrnew}
fmdl3=/com2/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean

    gdplot2 << EOF

 GDFILE   = $fmdl3
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = capeenmw 
 CINT     = 500 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF MEAN SFC-BASED CAPE 
 DEVICE   = GIF|capesref_f0${fhrs}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 18.;-130.;58.;-60. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.9/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl3
 GDATTIM  = f${fhrnew}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(capeenmw^${ymds}/${cycs}f${fhrs}+2,cape)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//SLP  ${cycs}z SREF f${fhrs}   -   ${cyc}z NAM f${fhrnew}
 DEVICE   = GIF|capediff_f0${fhrs}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = t
 TEXT     = 1./11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.12;.45/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1500;-1000;-750;-500;-250;250;500;750;1000;1500
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2 + $fmdl3
 GFUNC    = sub(capeenmw^${ymds}/${cycs}f${fhrs}+2,cape)
 TITLE    = 1//SLP  ${cycs}z SREF f${fhrs}   -   ${cyc}z GFS f${fhrnew}
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
r

ex
EOF
done
gpend

for fhrs in $times; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 capesref_f0${fhrs}.gif cape2.gif
$CONV/convert -crop 0x0 capediff_f0${fhrs}.gif cape1.gif
$CONV/montage -geometry 800x850 cape1.gif cape2.gif ${cycs}sfccapesref${fhrs}.gif
done

#scp ${cycs}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
mv ${cycs}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
