#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/bcape
rm /stmpp1/Geoffrey.Manikin/meg/bcape/*
cd /stmpp1/Geoffrey.Manikin/meg/bcape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015082500
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold3

times="24"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM SFC-BASED CAPE 
 DEVICE   = GIF|cape_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-120.;51.;-66. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 180:0
 GVCORD   = pdly
 TITLE    = 1/-1/~  NAM BEST CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GLEVEL   = 180:0
 GVCORD   = pdly 
 GFUNC    = sub(cape,cape@0%none)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 DEVICE   = GIF|capediff_f0${fhr}.gif | 600;650
 TITLE    = 1//  BEST - SFC CAPE 
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;.9/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1500;-1000;-750;-500;-250;-50;50;250;500;750;1000;1500 
 FLINE    = 30;28;26;27;23;21;0;5;20;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 cape_f0${fhr}.gif cape1.gif
$CONV/convert -crop 0x0 capediff_f0${fhr}.gif cape2.gif
$CONV/montage -geometry 700x750 cape1.gif cape2.gif ${ymdh}cape2comp${fhr}.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
