#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wz
rm /stmpp1/Geoffrey.Manikin/meg/10wz/*
cd /stmpp1/Geoffrey.Manikin/meg/10wz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015020900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 12 18 24" 
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00             

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10
 GVCORD   = hght 
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 CINT     = 0 
 LINE     = 0 
 DEVICE   = GIF|10wv2mthires_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-70.;25./2;2;1;1
 GAREA    = 28.;-86.;46.;-54. 
 GAREA    = 27.;-90.8;34.4;-82.4 
 GAREA    = 40.8;-72.8;43.6;-68.8
 TITLE    = 1//~  4 KM NAM  10M WIND (KT) 2-M T
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 0.8/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = b 
r

 GLEVEL   = 2
 CLEAR    = n
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
 CINT     = 2;5;8;11;14;17;20;23;26;29;32;35;38;41;44 
 LINE     = 4/1/2/1
r

 GDFILE   = $fmdl4
 TITLE    = 1//~  HRRR  10M WIND (KT) 2-M T 
 PANEL    = ur 
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 TYPE     = b
r

 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  HIRESW ARW  10M WIND (KT) 2-M T 
 PANEL    = ll 
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 TYPE     = b
r

 GLEVEL   = 2
 CLEAR    = n
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
r

 GDFILE   = $fmdl3
 TITLE    = 1//~  HIRESW NMMB  10M WIND (KT) 2-M T 
 PANEL    = lr
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 TYPE     = b
r

 GLEVEL   = 2
 CLEAR    = n
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
