#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/1hyblt
rm /stmpp1/Geoffrey.Manikin/meg/1hyblt/*
cd /stmpp1/Geoffrey.Manikin/meg/1hyblt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014091618
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Tue

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="27 30 33 36"
times="03 06"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
fmdl1=/ptmpp1/Geoffrey.Manikin/hold/nam40_${ymdh}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/hold/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 1 
 GVCORD   = hybl 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 1st LEV TEMP 
 DEVICE   = GIF|1hybltmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = 28.;-100.;48.;-64. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r


 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS 1st LEV TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 TYPE     = f
 LINE     = 1
 CINT     = 4
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r


ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 1  
 GVCORD   = hybl
 GFUNC    = sub(tmpf+2,tmpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 1st LEV TEMP (F)   NAM - GFS
 DEVICE   = GIF|1hybltdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 1hybltmodels_f0${fhr}.gif 1hyblt1.gif
$CONV/convert -crop 0x0 1hybltdiff_f0${fhr}.gif 1hyblt2.gif
$CONV/montage -geometry 800x850 1hyblt1.gif 1hyblt2.gif ${cyc}1hyblt2z${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
