#!/bin/sh
echo 'into'
#.gempak
./nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/type
rm /stmpp1/Geoffrey.Manikin/meg/type/*
cd /stmpp1/Geoffrey.Manikin/meg/type
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2019030812
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold9

times="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="36"
for fhr in $times; do

fmdl1=/gpfs/hps/nco/ops/com/nawips/para/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl1=/stmpp1/Geoffrey.Manikin/fv3_${cyc}/fv3_0p25_${ymdh}f0${fhr}
div=`expr $fhr % 6`
 if [ $div -eq 0 ]
 then
 gfsvar="06"
 else
 gfsvar="03"
 fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   FV3 INST PCP TYPE 
 DEVICE   = GIF|fv3type_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 26.;-125.;52.;-67. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  FV3 AVG PCP TYPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 GDPFUN   = wxtr${gfsvar}
 FLINE    = 0;3
r

 GDPFUN   = wxts${gfsvar}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar}
 FLINE    = 0;2
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
