#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrruphl
rm /stmpp1/Geoffrey.Manikin/meg/hrrruphl/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrruphl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016092812
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold2

hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
hours="00 03 06 09 12"
#hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
for fhr in $hours;do

DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hrrr.${ymd}
fmdl1=${DAPATH}/hrrr_${ymdh}f0${fhr}00
fmdl2=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrrnamrr_2mt_${ymdh}f${fhr}.gif | 800;850
 GAREA    = 34.;-105.;40.;-96.
 GAREA    = md+ 
 PROJ     = lcc/25.;-76.;25./2;2;1;1
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z HRRR  F${fhr} 2-M TEMPS 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.02;0.6/1.2;.03/1
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FINT     = 28;32;36;40;44;48;52;56;60;64;68;72;76;80;84;88;92
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b
 TITLE    = 1//  ${cyc}z NAM4   F${fhr} 2-M TEMPS
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
