#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/84pcp
rm /stmpp1/Geoffrey.Manikin/meg/84pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/84pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20160122
fhr1=60
dayoweek=hold5

cycles="00 06 12 18"
for cyc in $cycles; do

fmdl1=/meso/noscrub/Geoffrey.Manikin/blizzard/gfspcp_${ymd}${cyc}
fmdl2=/meso/noscrub/Geoffrey.Manikin/blizzard/gfsxpcp_${ymd}${cyc}

if [ $cyc -eq 00 ]; then
  fhr=$fhr1
elif [ $cyc -eq 06 ]; then
  fhr=`expr $fhr1 - 6`
elif [ $cyc -eq 12 ]; then
  fhr=`expr $fhr1 - 12`
else
  fhr=`expr $fhr1 - 18`
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p48i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 48-HR TOTAL PCP
 DEVICE   = GIF|48pcpmodels_${cyc}f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-79;25;/1;1;1;1
 GAREA    = 32.;-90.;48.;-68.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  GFS TEST 48-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GFUNC    = sub(p48i+2,p48i)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 48-HR TOTAL PCP   GFS - GFS TEST
 DEVICE   = GIF|48pcpdiff_${cyc}f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.06;.94/.87;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
for cyc in $cycles; do
rm 48pcp1.gif
rm 48pcp2.gif
if [ $cyc -eq 00 ]; then
  fhr=$fhr1
elif [ $cyc -eq 06 ]; then
  fhr=`expr $fhr1 - 6`
elif [ $cyc -eq 12 ]; then
  fhr=`expr $fhr1 - 12`
else
  fhr=`expr $fhr1 - 18`
fi

$CONV/convert -crop 0x0 48pcpmodels_${cyc}f${fhr}.gif 48pcp1.gif
$CONV/convert -crop 0x0 48pcpdiff_${cyc}f${fhr}.gif 48pcp2.gif
$CONV/montage -geometry 700x750 48pcp1.gif 48pcp2.gif ${ymd}${cyc}f${fhr}_48pcpgfsx.gif
done

scp ${ymd}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/48pcp/${ymd}/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdnamx/.
#rm *gif
exit
