#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slpz
rm /stmpp1/Geoffrey.Manikin/meg/slpz/*
cd /stmpp1/Geoffrey.Manikin/meg/slpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015101900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 30"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pres 
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM SURFACE PRESSURE 
 DEVICE   = GIF|slp2_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 36.;-138.;58.;-98. 
 GAREA    = nj 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 990;993;996;999;1002;1005;1008;1011;1014;1017;1020;1023;1026;1029 
 FLINE    = 11;30;29;28;27;26;25;23;22;21;20;19;17;10;2;15 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~   GFS  SFC PRESSURE 
 PANEL    = b
 CLRBAR   = 0 
 CLEAR    = n
r

ex
EOF
done
gpend

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
