#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500gfs
rm /stmpp1/Geoffrey.Manikin/meg/500gfs/*
cd /stmpp1/Geoffrey.Manikin/meg/500gfs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh1=2016123112
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
ymdh2=2016123012
ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
dayoweek=hold7

hours="24 48 72 96 120 144 156 168 192"

for fhr in $hours; do
fhr2=`expr $fhr + 24`
typeset -Z3 fhr fhr2 

fmdl1=/com2/nawips/prod/gfs.${ymd1}/gfs_0p50_${ymdh1}f${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd2}/gfs_0p50_${ymdh2}f${fhr2}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = quo(hght,10) 
 CINT     = 6 
 LINE     = 4/1/4/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  GFS 500z  $ymd1 ${cyc1}z  F${fhr}
# DEVICE   = GIF|2zgfs500_${ymdh1}f0${fhr}.gif | 800;850
 DEVICE   = GIF|500models_f0${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-115;25;/1;1;1;1
# GAREA    = 4.;-178.;80.;-52.
 GAREA    = 8.;-158.;68.;-78.
# GAREA    = grid 
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 PANEL    = b
 CLEAR    = n
 TITLE    = 1//  GFS 500z  $ymd2 ${cyc2}z  F${fhr2}
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 500
 GVCORD   = pres
 GFUNC    = sub(hght+2,hght^${ymd2}/${cyc2}f${fhr2})
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 500 Z   GFS NEW - GFS OLD
 DEVICE   = GIF|500diff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.88/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -150;-120;-90;-60;-30;30;60;90;120;150
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 500models_f0${fhr}.gif 5001.gif
$CONV/convert -crop 0x0 500diff_f0${fhr}.gif 5002.gif
$CONV/montage -geometry 800x850 5001.gif 5002.gif 2zgfs500_${ymdh1}f${fhr}.gif
done

scp 2*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
