#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg/soilm
rm /stmpp1/Geoffrey.Manikin/meg/soilm/*
cd /stmpp1/Geoffrey.Manikin/meg/soilm
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20150815
cyc=12
dayoweek=hold4
DAPATH=/com/gfs/prod/gfs.${ymd}
times="00"
for fhr in $times; do

wgrib -i -d 221 ${DAPATH}/gfs.t${cyc}z.pgrbf${fhr} -grib -o new.grd

   nagrib << EOF
GBFILE  = new.grd
INDXFL  =
GDOUTF  = gfssoilmf${fhr}.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

#fmdl1=/ptmpp1p1/Geoffrey.Manikin/gfs/nam40_${ymd}${cyc}f0${fhr}
#fmdl2=/ptmpp1p1/Geoffrey.Manikin/gfs/gfs40_${ymd}${cyc}f0${fhr}
fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymd}${cyc}f0${fhr}
fmdl2=gfssoilmf${fhr}.grd

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 0:10 
 GVCORD   = dpth 
 GDPFUN   = soilm 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ OPS NAM @ SOIL MOISTURE
 DEVICE   = GIF|${cyc}soimz_${ymd}${cyc}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-99;25;/1;1;1;1                
 GAREA    = 38.;-107.;50.;-89.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .02;.05;.1;.15;.2;.25;.3;.35;.4;.45;.5 
 FLINE    = 0;18;16;17;10;5;20;21;22;23;27;4
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1/-1/~ OPS GFS @ SOIL MOISTURE
 CLRBAR   = 1/H/UL/.08;0.96/.8;.02/2 
 PANEL    = b
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0:10
 GVCORD   = dpth 
 GFUNC    = sub(soim+2,soim)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 0:10 SOILM   NAM - GFS
 DEVICE   = GIF|${cyc}soilmdiffz_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -.2;-.16;-.12;-.08;-.04;.04;.08;.12;.16;.20 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
