#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/resopcp
rm /stmpp1/Geoffrey.Manikin/meg/resopcp/*
cd /stmpp1/Geoffrey.Manikin/meg/resopcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014030300
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Sun

fmdl1=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl4=/meso/save/Geoffrey.Manikin/meg/namfirewxnest_${ymdh}

hours="24 30"
for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 24-HR TOTAL PCP
 DEVICE   = GIF|${cyc}24pcpreso${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 34.;-88.;46.;-62.
 GAREA    = md
# GAREA    = 22.;-120.;52.;-64.
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.9/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM 24-HR TOTAL PCP
 PANEL    = ur 
 CLEAR    = n
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  4 KM NAM 24-HR TOTAL PCP
 PANEL    = ll 
 CLRBAR   = 1/H/UL/.1;0.95/1.8;.03/1
r

 GDFILE   = $fmdl4
 TITLE    = 1/-1/~  FIRE WX NEST 24-HR TOTAL PCP
 PANEL    = lr 
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
