#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10w
rm /stmpp1/Geoffrey.Manikin/meg/10w/*
cd /stmpp1/Geoffrey.Manikin/meg/10w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017091912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="18 21 24"
times="00"
for fhr in $times; do

DAPATH=/com/nawips/prod/nam.${ymd}/
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/
DAPATH=/ptmpp1/Geoffrey.Manikin/hold
fmdl1=${DAPATH}/nam12_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam_priconest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nestnam10w_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-81.;25./2;2;1;1
 GAREA    = 40.;-84.;44.;-77.6
# GAREA    = 29.;-84.;43.;-62. 
# GAREA    = 17.0;-67.4;19.8;-64.2
 GAREA     = 17.0;-67.4;20.;-63.
 GAREA    = grid
 PROJ     = mer
 MAP      = 1/1/2 + 1/1/1
 \$MAPFIL = 0
# \$MAPFIL = states
 TITLE    = 1//~  NAM 10m WIND (KT) / SLP
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/1 
 TEXT     = 1.0/11/2
 FINT     = 10;20;30;40;50;60;70;80;90;100
 FINT      = 15;25;35;45;55;65;75;85;95
# FINT      = 15;20;25;30;35;40;45;50;55
 FLINE    = 0;29;4;26;22;5;10;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /6;6
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GLEVEL   = 0
 GVCORD   = none
 LINE     = 1/1/2/2
 CINT     = 4
 GDPFUN   = emsl
 TYPE     = c
r

 GDFILE   = $fmdl2
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = knts(sped)
 CINT     = 5
 LINE     = 0
 TITLE    = 1//~  NAM4  10m WIND (KT) / SLP
 SCALE    = 0
 PANEL    = b
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 TEXT     = 1.0/11/2
 TYPE     = f
r

 CINT     =
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /6;6
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GLEVEL   = 0
 GVCORD   = none
 LINE     = 1/1/3/2
 CINT     = 4
 GDPFUN   = pmsl
 TYPE     = c
r


ex
EOF

done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
