#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/3hiresslp
rm /stmpp1/Geoffrey.Manikin/meg/3hiresslp/*
cd /stmpp1/Geoffrey.Manikin/meg/3hiresslp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014092400
ymd=20140924
dayoweek=hold

hours="03 06 09 12 15"
hours="24" 
for fhr in $hours; do

fmdl1=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl4=/com/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00 

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = pmsl 
 CINT     = 2
 LINE     = 4/1/2/4 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   HIRESW ARW  SLP 
 DEVICE   = GIF|4pan3slp_${ymdh}f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 21.;-121.;51.;-65.
 GAREA    = 31.;-82.;40.;-68.
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = ;2/;S13#/;920-1024/5/2;3/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 4 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  HIRESW NMMB SLP
 PANEL    = ll 
 CLEAR    = n
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  4 KM NAM SLP
 PANEL    = ur 
 CLRBAR   = 0
r

 GDFILE   = $fmdl4
 TITLE    = 1/-1/~  HRRR SLP
 PANEL    = lr 
 GDATTIM  = f0${fhr}00
r

ex
EOF
done
gpend

#rm fmdl3*
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
