#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/type
rm /stmpp1/Geoffrey.Manikin/meg/type/*
cd /stmpp1/Geoffrey.Manikin/meg/type
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012121709
ymd=20121217
dayoweek=Mon
times="87"
for fhr in $times; do

fmdl1=/ptmpp1p1/Geoffrey.Manikin/srefpost/sref212_2012121709_em_ctl
fmdl2=/ptmpp1p1/Geoffrey.Manikin/srefpost/sref40oldnwprod_2012121709f087
#fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
#fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF OPS PCP TYPE 
 DEVICE   = GIF|typemodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  SREF OLD NWPROD PCP TYPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = add(wxtr+2,wxts)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~  PCP TYPE   OPS/TEST DIFFERENCES
 DEVICE   = GIF|typediff_f0${fhr}.gif | 500;550
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0;1.1 
 FLINE    = 0;0;2
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 GFUNC    = add(wxtr+2,wxtz)
 CLEAR    = n
r

 GFUNC    = add(wxtr+2,wxtp)
r

 GFUNC    = add(wxts+2,wxtr)
r
 
 GFUNC    = add(wxts+2,wxtz)
r

 GFUNC    = add(wxts+2,wxtp)
r

 GFUNC    = add(wxtz+2,wxtr)
r

 GFUNC    = add(wxtz+2,wxts)
r

 GFUNC    = add(wxtz+2,wxtp)
r

 GFUNC    = add(wxtp+2,wxtr)
r

 GFUNC    = add(wxtp+2,wxts)
r

 GFUNC    = add(wxtp+2,wxtz)
r


ex
EOF
gpend
done

for fhr in $times; do
/usrx/local/im_beta/bin/convert -crop 0x0 typemodels_f0${fhr}.gif type1.gif
/usrx/local/im_beta/bin/convert -crop 0x0 typediff_f0${fhr}.gif type2.gif

CONV=/usrx/local/imajik/bin
$CONV/montage -geometry 800x850 type1.gif type2.gif ${cyc}test3type${fhr}.gif
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
