#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/pw
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/pw/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/pw
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

ymdh=2022072800
ymd=`echo $ymdh | cut -c1-8`

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="24 25 26 27 28 29 30"
hours="06"
for fhr in $hours; do

fmdl1=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/hrrr_${ymdh}f0${fhr}00
fmdl3=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/arw_${ymdh}f0${fhr}
fmdl4=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/arw2_${ymdh}f0${fhr}
fmdl5=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/fv3_${ymdh}f0${fhr}
fmdl6=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(pwtr,25.4) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrefpw1_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-85.;25./2;2;1;1
# GAREA    = 34.;-92.;46.;-70. 
 GAREA    = ky 
 TITLE    = 1//~  NAM CONUS NEST PWAT 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/1
 TEXT     = 1.1/11/2
 FINT     = .25;.5;.75;1.;1.25;1.5;1.75;2.;2.25;2.5
 FLINE    = 0;21;22;23;28;30;2;15;10;5;31
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 0
 TITLE    = 1//~  HRRR PWAT
r

 GDFILE   = $fmdl3
 PANEL    = t
 CLEAR    = y
 DEVICE   = GIF|hrefpw2_${ymdh}f0${fhr}.gif | 800;850
 TITLE    = 1//~  ARW PWAT
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/1
r

  GDFILE   = $fmdl4
  PANEL    = b
  TITLE    = 1//~  ARW2 PWAT
  CLRBAR   = 0
  CLEAR    = n
 r

 GDFILE   = $fmdl5
 PANEL    = t
 CLEAR    = y
 DEVICE   = GIF|hrefpw3_${ymdh}f0${fhr}.gif | 800;850
 TITLE    = 1//~  FV3 PWAT
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/1
r

  GDFILE   = $fmdl6
  PANEL    = b
  TITLE    = 1//~  GFS PWAT
  CLRBAR   = 0
  CLEAR    = n
r

ex
EOF

done
gpend

#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.

exit
