#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg/soilt
rm /stmpp1/Geoffrey.Manikin/meg/soilt/*
cd /stmpp1/Geoffrey.Manikin/meg/soilt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .
cp /meso/save/Geoffrey.Manikin/gempak/nagrib/ncepgrib2.tbl .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013051612
ymd=20130516
cyc=12
dayoweek=Thu

DAPATH=/com/gfs/prod/gfs.${ymd}
times="00"
for fhr in $times; do

wgrib -i -d 212 ${DAPATH}/gfs.t${cyc}z.pgrbf${fhr} -grib -o new.grd

/nwprod/gempak/nawips1/os/aix5/bin/nagrib_nc << EOF
GBFILE  = new.grd
INDXFL  =
GDOUTF  = gfssoiltf${fhr}.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=gfssoiltf${fhr}.grd

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 0:10 
 GVCORD   = dpth 
 GDPFUN   = sltk 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ OPS NAM @ SOIL TEMP 
 DEVICE   = GIF|${cyc}soilt_${ymd}${cyc}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1 
 GAREA    = 14;-124.;56.;-50. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 261;265;269;273;277;281;285;289;293;297;301;305 
 FLINE    = 30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14
 FLINE  
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 GDPFUN   = tmpk
 TITLE    = 1/-1/~ OPS GFS @ SOIL TEMP 
 CLRBAR   = 1/H/UL/.08;0.96/.8;.02/2 
 PANEL    = b
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0:10
 GVCORD   = dpth 
 GFUNC    = sub(sltk+2,tmpk)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 0:10 SOIL T   NAM - GFS
 DEVICE   = GIF|${cyc}soiltdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1
 GAREA    = 14;-124.;56.;-50.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -10;-8;-6;-4;-2;2;4;6;8;10 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

exit
