#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtak
rm /stmpp1/Geoffrey.Manikin/meg/2mtak/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtak
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014120712
ymd=20141207
dayoweek=hold

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="00 03 06"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/rap.${ymd}/rap32_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 2-M  TEMP 
 DEVICE   = GIF|2mtmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = str/90;-140;0;/1;1;1;1
 GAREA    = 42.;-172.;70.;-106.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -40;-35;-30;-25;-20;-15;-10;5;0;5;10;15;20;25;30;35;40;45;50;55;60
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  RAP 2-M TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(tmpf+2,tmpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M TEMP (F)   NAM - RAP 
 DEVICE   = GIF|2mtdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2mtmodels_f0${fhr}.gif 2mt1.gif
$CONV/convert -crop 0x0 2mtdiff_f0${fhr}.gif 2mt2.gif
$CONV/montage -geometry 800x850 2mt1.gif 2mt2.gif ${cyc}2mtaknamrap${fhr}.gif

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
done
