#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/type
rm /stmpp1/Geoffrey.Manikin/meg/type/*
cd /stmpp1/Geoffrey.Manikin/meg/type
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017031312
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

times="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

div=`expr $fhr % 6`
 if [ $div -eq 0 ]
 then
 gfsvar="06"
 elif [ $div -eq 1 ]
 then
 gfsvar="01"
 elif [ $div -eq 2 ]
 then
 gfsvar="02"
 elif [ $div -eq 3 ]
 then
 gfsvar="03"
 elif [ $div -eq 4 ]
 then
 gfsvar="04"
 else
 gfsvar="05"
 fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM4 PCP TYPE 
 DEVICE   = GIF|typemodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 38.;-78;42.;-72. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS PCP TYPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 GDPFUN   = wxtr${gfsvar}
 FLINE    = 0;3
r

 GDPFUN   = wxts${gfsvar}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar}
 FLINE    = 0;2
r

ex
EOF

gpend
done

/usrx/local/ImageMagick/6.8.3-3/bin/convert -loop 0 -delay 100 type*gif ${ymdh}_nam4gfstypeloop.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
