#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefd9
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefd9/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefd9
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013041612
#ymd=`echo $ymdh | cut -c1-8`
#dayoweek=Tue

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="33 34 35 36"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl2=/gpfs/hps/nco/ops/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/gpfs/hps/nco/ops/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
#fmdl4=/meso/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
if [ $cyc -eq 00 ]; then
fmdl4=/meso/save/Geoffrey.Manikin/meg/nsslwrf_${ymdh}
title4="1//~  NSSL WRF  1 KM REFD"
elif [ $cyc -eq 12 ]; then
fmdl4=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f01500
title4="1//~  HRRR  1 KM REFD"
fi

areas="1 2 3 4 5 6 7"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="36.;-84.;47.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="24.5;-92.;37.5;-74."
proj="lcc/25.;-85.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="38.;-108.;50.;-90."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="26.;-109.;40.;-91."
proj="lcc/25.;-99.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="33.9;-111.4;42.9;-98."
proj="lcc/25.;-105.;25./2;2;1;1"
elif [ $region -eq 7 ]
then
garea="39;-128.;51;-108."
proj="lcc/25.;-115.;25./2;2;1;1"
elif [ $region -eq 8 ]
then
garea="31.;-124.;43.;-108."
proj="lcc/25.;-115.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 1000 
 GVCORD   = hght 
 GDPFUN   = refd 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hires1refd${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  NAM CONUS NEST  1 KM REFD
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  1 KM REFD 
 CLRBAR   = 1/H/UL/.46;0.94/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMMB  1 KM REFD 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = $title4 
 CLRBAR   = 0
r

ex
EOF

done
done
gpend

mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefd/.
exit
