#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dewrap
rm /stmpp1/Geoffrey.Manikin/meg/2dewrap/*
cd /stmpp1/Geoffrey.Manikin/meg/2dewrap
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014012800
ymd=20140128
dayoweek=Tue

times="00 03 06 09 12 15 18"
times="00 03 06"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/rap.${ymd}/rap_${ymdh}f0${fhr}
#fmdl2=/ptmpp1p1/Geoffrey.Manikin/data/rap13_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 2-M  DEW PT 
 DEVICE   = GIF|2dewmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-102;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
# GAREA    = 32.;-106.;46.;-88.
# GAREA    = 30.;-122.;48.;-98. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.45/0.9;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -28;-20;-12;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68
 FINT     = -76;-68;-60;-52;-44;-36;-28;-20;-12;-4;4;12;20;28;36;44;52;60;68;76
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  RAP 2-M DEW PT 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(dwpf+2,dwpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M DEW PT (F)   NAM - RAP 
 DEVICE   = GIF|2dewdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.92/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -30;-25;-20;-15;-10;-5;5;10;15;20;25;30
 FLINE    = 30;28;26;27;23;21;0;5;20;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
for fhr in $times; do

$CONV/convert -crop 0x0 2dewmodels_f0${fhr}.gif 2dew1.gif
$CONV/convert -crop 0x0 2dewdiff_f0${fhr}.gif 2dew2.gif
$CONV/montage -geometry 800x850 2dew1.gif 2dew2.gif ${cyc}2dewdryrap${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
