#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresuphl3
rm /stmpp1/Geoffrey.Manikin/meg/hiresuphl3/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresuphl3
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014111612
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="06 07 08 09 10 11 12 13 14 15"
hours="15 18 21 24"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
#fmdl4=/meso/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

areas="1"
for region in $areas; do

garea="ga"
proj="lcc/25.;-85.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = MXUPHL01
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hiresuphl${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 MAP      = 1/1/2;1
 TITLE    = 1//~  4 KM NAM  2-5 KM MAX UPDRAFT HLCY 
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 2;5;10;25;50;75;100;125;150
 FLINE    = 0;21;23;4;26;2;15;16;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  2-5 KM MAX UPDRAFT HLCY 
 CLRBAR   = 1/H/UL/.46;0.94/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMM  2-5 KM MAX UPDRAFT HLCY 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  HRRR 2-5 KM MAX UPDRAFT HLCY  
 CLRBAR   = 0
r

ex
EOF

done
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
