#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500res
rm /stmpp1/Geoffrey.Manikin/meg/500res/*
cd /stmpp1/Geoffrey.Manikin/meg/500res
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2014120600
#ymd=20141206
#dayoweek=Sat

times="24 36"
for fhr in $times; do

fmdl1=/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs_0p50_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/gfs.${ymd}/gfs_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = p06i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 0.25  6-HR PCP 
 DEVICE   = GIF|gfs6pcp_0p25v0p5_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 10.;-140.;70.;-50. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.22/.4;.02/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 LINE     = 0
 MAP      = 1
 WIND     = 0
 CLEAR    = n
 TITLE    = 1/-1/~   GFS 0.5   6-HR PCP 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 CLRBAR   = 0 
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   GFS 0.25  6-HR PCP
 DEVICE   = GIF|gfs6pcp_0p25v1p0_f0${fhr}.gif|850;950
r
 
 GDFILE   = $fmdl3
 CLEAR    = n
 TITLE    = 1/-1/~   GFS 1.0  6-HR PCP
 PANEL    = b
r
 
ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/res/.
exit
