#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wz
rm /stmpp1/Geoffrey.Manikin/meg/10wz/*
cd /stmpp1/Geoffrey.Manikin/meg/10wz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017061512
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold5

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 09 12" 
times="01 02 03 04 05 06"
times="00"
for fhr in $times; do

DAPATH=/com2/nawips/prod
DAPATH2=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
DAPATH2=/meso/noscrub/Geoffrey.Manikin
fmdl1=${DAPATH}/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10
 GVCORD   = hght 
 GDPFUN   = kntv(wind)
 WIND     = BK4/0.7/2/122
 CINT     = 10 
 LINE     = 0 
 DEVICE   = GIF|10v_hrrrnam3_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-97.;25./2;2;1;1
 GAREA    = 28.;-86.;46.;-54. 
 GAREA    = ks+
 TITLE    = 1//~  NAM3  10M  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 TYPE     = B 
 SKIP     = /45;45
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  HRRR  10M  WIND (KT)
 CLEAR    = n
 PANEL    = b
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
