#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/1pcp
rm /stmpp1/Geoffrey.Manikin/meg/1pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/1pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2019080518
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
dayoweek=hold9

hours="06"
for fhr1 in $hours; do

fmdl1=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd1}/${cyc1}/gempak/gfs_0p25_${ymdh1}f0${fhr1}
echo $fmdl1

#fmdl1=/meso/noscrub/Geoffrey.Manikin/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr1}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = pmsl 
 CINT     = 4 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS  PMSL
 DEVICE   = GIF|comparegfsslp_${ymdh1}f${fhr1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-114;25;/1;1;1;1
 GAREA    = nv 
 CLEAR    = y
 PANEL    = t 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = ;2/;S13#/;920-1008/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = emsl
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~   GFS  EMSL
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
