#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/capemr
rm /stmpp1/Geoffrey.Manikin/meg/capemr/*
cd /stmpp1/Geoffrey.Manikin/meg/capemr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016060900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

times="24 36 48 60 72 84 96 108 120 132 144 156 168 180 192"
times="138 141 144"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = prxx 
 CINT     = 50
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ECMWF SFC-BASED CAPE 
 DEVICE   = GIF|capemodels_f${fhr}.gif|900;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-92;25;/1;1;1;1
 GAREA    = mo- 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.1;0.6/1.2;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
# FINT     = 500;1000;1500;2000;2500;3000;3500;4000;4500;5000;7500
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = cape 
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~   GFS  SFC-BASED CAPE 
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = f 
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(cape+2,prxx)
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SFC-BASED CAPE   GFS - ECMWF
 DEVICE   = GIF|capediff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.09;.75/.55;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1500;-1000;-750;-500;-250;250;500;750;1000;1500
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 capemodels_f${fhr}.gif cape1.gif
$CONV/convert -crop 0x0 capediff_f${fhr}.gif cape2.gif
$CONV/montage -geometry 800x850 cape1.gif cape2.gif ${cyc}cape${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
