#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hires24pcp
rm /stmpp1/Geoffrey.Manikin/meg/hires24pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/hires24pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014112000
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

hours="10 11 12 13 14 15 16 17 18"
hours="24"
for fhr in $hours; do

fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswnmmbpcp_$ymdh
fmdl3=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
if [ $cyc -eq 00 ]; then
fmdl4=/meso/save/Geoffrey.Manikin/meg/nsslwrfpcp_${ymdh}
title4="1//~  NSSL WRF 24-HR TOT PCP"
title4a="1//~  NSSL WRF 36-HR TOT PCP"
ftime=$fhr
pcpamt=p24i
elif [ $cyc -eq 12 ]; then
fmdl4=/com/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f01500
title4="1//~  HRRR 15-HR TOT PCP"
ftime=15
pcpamt=p15i
fi

areas="1"
for region in $areas; do

if [ $region -eq 1 ]
then
#garea="33.9;-111.4;42.9;-98."
#proj="lcc/25.;-105.;25./2;2;1;1"
garea="40.;-84.;46.;-74"
proj="lcc/25.;-78.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p24i 
 CINT     = 5 
 LINE     = 1 
 DEVICE   = GIF|${cyc}hirescounty24pcp${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL = county
 MAP      = 1/1/2;1
 TITLE    = 1//~  NAM CONUS NEST  24-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;12;17;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  24-HR TOT PCP 
 CLRBAR   = 1/H/UL/.05;0.96/1.9;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMM  24-HR TOT PCP 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$ftime
 GDPFUN   = $pcpamt
 PANEL    = ur
 TITLE    = $title4 
 CLRBAR   = 0
r

ex
EOF
done

   gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p48i
 CINT     = 5
 LINE     = 1
 DEVICE   = GIF|${cyc}hirescounty48pcp${region}.gif | 800;850
 PROJ     = $proj
 GAREA    = $garea
 \$MAPFIL = county
 MAP      = 1/1/2;1
 TITLE    = 1//~  NAM CONUS NEST  48-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  48-HR TOT PCP
 CLRBAR   = 1/H/UL/.05;0.95/1.9;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr
 TITLE    = 1//~  HIRESW NMM  48-HR TOT PCP
 CLRBAR   = 0
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~    48-HR TOT PCP
 CLRBAR   = 0
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
