#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/skint
rm /stmpp1/Geoffrey.Manikin/meg/skint/*
cd /stmpp1/Geoffrey.Manikin/meg/skint
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018051712
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="27 30 33 36"
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
times="132" 
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/hold/fv3_${ymdh}f${fhr}
DAPATH=/meso/noscrub/Geoffrey.Manikin/alberto
fmdl1=${DAPATH}/gfs_0p25_${ymdh}f${fhr}
fmdl2=${DAPATH}/fv3_0p25_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SKIN  TEMP 
 DEVICE   = GIF|skintmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = 20.;-82.;32.;-74. 
 GAREA    = 8.;-95.;32.;-65. 
# \$MAPFIL = county
# GAREA    = 28.8;-96.6;31.;-93.
# GAREA    = 33.0;-85.6;34.4;-83.2
# GAREA    = 32.6;-113.5;34.;-111.
# GAREA     = 28.5;-99.8;30.9;-96.8
# GAREA    = 22.;-118.;32.;-106. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = 30;33;36;39;42;45;48;51;54;57;60;63;66;69;72;75;78;81;84;87;90
# FINT     = 6;9;12;15;18;21;24;27;30;33;36;39;42;45;48;51;54;57;60
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  FV3  SKIN TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 TYPE     = f
 LINE     = 1
 CINT     = 4
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(tmpf+2,tmpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SKIN TEMP (F)  GFS - FV3 
 DEVICE   = GIF|skintdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.95/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 skintmodels_f0${fhr}.gif skint1.gif
$CONV/convert -crop 0x0 skintdiff_f0${fhr}.gif skint2.gif
$CONV/montage -geometry 800x850 skint1.gif skint2.gif ${ymdh}_skintfv3${fhr}.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
