#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/700x
rm /stmpp1/Geoffrey.Manikin/meg/700x/*
cd /stmpp1/Geoffrey.Manikin/meg/700x
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2013082612
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Mon
DAPATH=/com/nam/prod/nam.${ymd}

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="00 03 06 09 12"

for fhr in $times; do
wgrib ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00 | grep kpds7=700  | wgrib ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00  -i -grib -o new.fil

  nagrib << EOF
GBFILE  = new.fil
INDXFL  =
GDOUTF  = nest.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF

fmdl1=nest.grd
fmdl2=/meso/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 700 
 GVCORD   = pres 
 GDPFUN   = relh 
 CINT     = 10 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   4 KM NAM 700 mb RH/VV 
 DEVICE   = GIF|700_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 21.;-121.;51.;-65. 
 GAREA    = ny 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;60;70;80;90
 FLINE    = 0;20;5;21;22;23
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDPFUN   = mul(omeg,1000)
 CINT     = 3/-50/-1
 LINE     = 2/1/2/0
 TYPE     = c
r

 CINT     = 3/1/50
 LINE     = 4/1/2/0
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  4 KM NAMX 700 mb RH/VV 
 GDPFUN   = relh
 PANEL    = b
 CLRBAR   = 0
 TYPE     = f
r

 CLEAR    = n
 GDPFUN   = mul(omeg,1000)
 CINT     = 3/-50/-1
 LINE     = 2/1/2/0
 TYPE     = c
r

 CINT     = 3/1/50
 LINE     = 4/1/2/0
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
