#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/925w
rm /stmpp1/Geoffrey.Manikin/meg/925w/*
cd /stmpp1/Geoffrey.Manikin/meg/925w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015091200
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="21 24"
for fhr in $times; do

DAPATH=/com/nawips/prod/nam.${ymd}/
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/
fmdl1=${DAPATH}/nam12_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 925 
 GVCORD   = pres 
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nestnam925w_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-81.;25./2;2;1;1
 GAREA    = 40.;-84.;44.;-77.6
# GAREA    = 29.;-84.;43.;-62. 
 TITLE    = 1//~  NAM 925 WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/1 
 TEXT     = 1.0/11/2
# FINT     = 10;20;30;40;50;60;70;80;90;100
 FINT      = 15;25;35;45;55;65;75;85;95
 FINT      = 15;20;25;30;35;40;45;50;55
 FLINE    = 0;29;4;26;22;5;10;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /6;6
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDPFUN   = knts(sped)
 CINT     = 5
 LINE     = 0
 TITLE    = 1//~  NAM4  925 WIND (KT) 
 SCALE    = 0
 PANEL    = b
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 TEXT     = 1.0/11/2
 TYPE     = f
r

 CINT     =
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /6;6
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
