#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcp
rm /stmpp1/Geoffrey.Manikin/meg/6pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016012300
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold6
times="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="06 12 18 24 30 36"
times="36 42 48 54 60"
times="12 18 24"
for fhr in $times; do

fhr3=`expr $fhr - 3`
typeset -Z2 fhr3

DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
fmdl1=${DAPATH}/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=${DAPATH}/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
cp ${DAPATH}/nam.${ymd}/nam32_${ymdh}f0${fhr3} file3
fmdl3=file3

    gdplot2 << EOF
 GDFILE   = $fmdl1 + $fmdl3
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = add(p03i^${ymd}/${cyc}f${fhr3}+2,p03i^${ymd}/${cyc}f$fhr)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 6-HR PCP 
 DEVICE   = GIF|6pcpslpnamgfs_${ymdh}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-70;25;/1;1;1;1
 GAREA    = 31.;-82.;47.;-62. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;4.;5.;6.;7.
 FLINE    = 0;21;22;23;25;4;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = pmsl
 CLEAR    = n
 LINE     = 1/1/2/2
 TYPE     = c
 CLRBAR   = 0
 HILO     = ;2/;S13#/;920-1008/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TITLE    = 0
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GDPFUN   = p06i
 TITLE    = 1/-1/~  GFS 6-HR PCP 
 PANEL    = b
 HILO     = 0
 HLSYM    = 0 
 TYPE     = f
r

 GDPFUN   = pmsl
 CLEAR    = n
 LINE     = 1/1/2/2
 TYPE     = c
 HILO     = ;2/;S13#/;920-1008/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
