#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2017061512
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=724518

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/snd
rm /stmpp1/Geoffrey.Manikin/meg/snd/*
cd /stmpp1/Geoffrey.Manikin/meg/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold5

fmdl1=/com2/nawips/prod/nam.${ymd}/nam_${ymdh}.snd.tm00
fmdl2=/com2/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}.snd.tm00
fmdl3=/com2/nawips/prod/gfs.${ymd}/gfs_${ymdh}.snd
fmdl4=/com2/nawips/para/gfs.${ymd}/gfs_${ymdh}.snd
fmdl5=/com2/nawips/prod/rap.${ymd}/rap_${ymdh}.snd
fmdl6=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}.snd

times="00 03 06 07 08 09 12"
times="05 06 07 08 09 12"
for time in $times; do

validtime="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//~  NAM 
 DEVICE   = gif|${ymdh}snd${stnm}_namf$fhr.gif | 800;850
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -10/45/5/;1
 FILTER   = n 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = y
 TITLE    = 1//~  NAM3
 DEVICE   = gif|${ymdh}snd${stnm}_nam3f$fhr.gif | 800;850
r

 SNFILE   = $fmdl3
 TITLE    = 1//~  GFS 
 DEVICE   = gif|${ymdh}snd${stnm}_gfsf$fhr.gif | 800;850
r

 SNFILE   = $fmdl4
 TITLE    = 1//~  GFSX 
 DEVICE   = gif|${ymdh}snd${stnm}_gfsxf$fhr.gif | 800;850
r

 SNFILE   = $fmdl5
 TITLE    = 1//~  RAP
 DEVICE   = gif|${ymdh}snd${stnm}_rapf$fhr.gif | 800;850
r

 SNFILE   = $fmdl6
 TITLE    = 1//~  HRRR
 DEVICE   = gif|${ymdh}snd${stnm}_hrrrf$fhr.gif | 800;850
r

ex
EOF

done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
