#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/compcp
rm /stmpp1/Geoffrey.Manikin/meg/compcp/*
cd /stmpp1/Geoffrey.Manikin/meg/compcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015020912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

hours="24"
fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp12_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/nampcp20_${ymdh}
fmdl3=/meso/save/Geoffrey.Manikin/meg/nampcp40_${ymdh}

for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 24-HR TOTAL PCP  12 km 
 DEVICE   = GIF|24pcp2${fhr}_nam12.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-115;25;/1;1;1;1
 GAREA    = 34.;-88.;46.;-62.
 GAREA    = or- 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 0.9/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.94/0.9;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.25;1.5;1.75;2;2.5;3;3.5;4;5;6;7
 FLINE    = 0;21;22;23;4;25;27;28;29;30;14;15;2;12;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM 24-HR TOTAL PCP  20 km 
 DEVICE   = GIF|24pcp2${fhr}_nam20.gif|750;900
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  NAM 24-HR TOTAL PCP  40 km 
 DEVICE   = GIF|24pcp2${fhr}_nam40.gif|750;900
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
