#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrruphl
rm /stmpp1/Geoffrey.Manikin/meg/hrrruphl/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrruphl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015122318
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold4
lasthr=15

hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
#hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
for fhr in $hours;do

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = MXUPHL01
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrrnamuphl_${ymdh}f${lasthr}.gif | 800;850
 GAREA    = 34.;-105.;40.;-96.
 GAREA    = tn
 PROJ     = "lcc/25.;-90.;25./2;2;1;1"
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z HRRR  2-5 KM MAX UPDRAFT HLCY 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.02;0.6/1.2;.03/1
 TEXT     = 0.9/11/2
 FINT     = 25;50;75;100;125;150;175;200
 FLINE    = 0;4;26;2;15;17;10;20;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b
 TITLE    = 1//  ${cyc}z NAM4  2-5 KM MAX UPDRAFT HLCY
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
