#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wz
rm /stmpp1/Geoffrey.Manikin/meg/10wz/*
cd /stmpp1/Geoffrey.Manikin/meg/10wz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015020900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="12" 
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00             

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 WIND     = 0 
 CINT     = 0 
 LINE     = 0 
 DEVICE   = GIF|10wvrefchires_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-70.;25./2;2;1;1
 GAREA    = 28.;-86.;46.;-54. 
 GAREA    = 27.;-90.8;34.4;-82.4 
 GAREA    = 40.8;-72.8;43.6;-68.8
 TITLE    = 1//~  4 KM NAM  10M  WIND (KT) REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 0.8/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 TYPE     = b
 CLEAR    = n
r

 GDFILE   = $fmdl4
 TITLE    = 1//~  HRRR  10M  WIND (KT) REFC
 PANEL    = ur
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = refc
 TYPE     = f
r

 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 TYPE     = b
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  HIRESW ARW  10M  WIND (KT) REFC
 PANEL    = ll 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = refc
 CLRBAR   = 1/H/UL/.3;0.95/1.4;.03/2
 TYPE     = f
r

 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 TYPE     = b
r

 GDFILE   = $fmdl3
 TITLE    = 1//~  HIRESW NMMB  10M  WIND (KT) REFC
 PANEL    = lr
 GLEVEL   = 0
 GVCORD   = none
 CLRBAR   = 0
 GDPFUN   = refc
 TYPE     = f
r

 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 TYPE     = b
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
