#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/skin
rm /stmpp1/Geoffrey.Manikin/meg/skin/*
cd /stmpp1/Geoffrey.Manikin/meg/skin
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013040312
ymd=20130403
dayoweek=Wed

fhr1=42
fhr2=48
fhr3=54

fmdl0=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f000
fmdl0a=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f000

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr1}
fmdl1a=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr1}

fmdl2=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr2}
fmdl2a=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr2}

fmdl3=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr3}
fmdl3a=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr3}

    gdplot2 << EOF
 GDFILE   = $fmdl0
 GDATTIM  = f$f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = tmpf
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM SKIN T   PMSL F${fhr1} F${fhr2}  F${fhr3} 
 DEVICE   = GIF|skinlows_${ymdh}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-70;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
 GAREA    = 28.;-84.;44.;-60.
# GAREA    = de 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.08;.4/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -5;0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1}
 GDPFUN   = pmsl
 HILO     = ;2/;S13#/;920-1012/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
 CLEAR    = n
 TITLE    = 0
 TYPE     = c
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 HILO     = ;3/;S13#/;920-1012/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 HILO     = ;4/;S13#/;920-1012/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r
 
 GDFILE   = $fmdl0a
 GDATTIM  = f00
 GDPFUN   = tmpf
 CINT     = 5 
 LINE     = 0 
 CLEAR    = n
 TITLE    = 1/-1/~   GFS SKIN T    PMSL F${fhr1} F${fhr2}  F${fhr3}
 PANEL    = b
 HILO     = 0
 CLRBAR   = 0 
 TYPE     = f
r

 GDFILE   = $fmdl1a
 GDATTIM  = f${fhr1}
 GDPFUN   = pmsl
 HILO     = ;2/;S13#/;920-1012/5/2;2/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
 TITLE    = 0
 TYPE     = c
r

 GDFILE   = $fmdl2a
 GDATTIM  = f${fhr2}
 HILO     = ;3/;S13#/;920-1012/5/2;2/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

 GDFILE   = $fmdl3a
 GDATTIM  = f${fhr3}
 HILO     = ;4/;S13#/;920-1012/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

ex
EOF
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

rm *gif
exit
