#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2012072200
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/84pcp
rm /stmpp1/Geoffrey.Manikin/meg/84pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/84pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

hours="36"

fmdl1=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/gfsexppcp_${ymdh}

for fhr in $hours; do

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 24-HR TOTAL PCP
 DEVICE   = GIF|24pcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65.
 GAREA    = wi-
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  GFS EXP 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GFUNC    = sub(p24i+2,p24i)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 24-HR TOTAL PCP   GFS  OPS - EXP
 DEVICE   = GIF|24pcpdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
# GAREA    = 21.;-121.;51.;-65.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.06;.9/.87;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $hours; do

/usrx/local/im_beta/bin/convert -crop 0x0 24pcpmodels_f${fhr}.gif 24pcp1.gif
/usrx/local/im_beta/bin/convert -crop 0x0 24pcpdiff_f${fhr}.gif 24pcp2.gif

CONV=/usrx/local/imajik/bin
$CONV/montage -geometry 700x750 24pcp1.gif 24pcp2.gif ${cyc}24pcp${fhr}.gif
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*10*gif
bye
EOF

rm *gif
exit
