#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dew
rm /stmpp1/Geoffrey.Manikin/meg/2dew/*
cd /stmpp1/Geoffrey.Manikin/meg/2dew
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013032300
#ymd=20130323
#dayoweek=Sat

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl1=/gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam32_${ymdh}f0${fhr}
cp /gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f0${fhr} fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 2-M  DWPF 
 DEVICE   = GIF|2dewmodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
# FINT     = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FINT     = -30;-24;-18;-12;-6;0;6;12;18;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS 2-M DWPF 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(dwpf+2,dwpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M DWPF (F)   NAM - GFS
 DEVICE   = GIF|2dewdiff_f0${fhr}.gif | 500;550
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2dewmodels_f0${fhr}.gif 2dew1.gif
$CONV/convert -crop 0x0 2dewdiff_f0${fhr}.gif 2dew2.gif
$CONV/montage -geometry 800x850 2dew1.gif 2dew2.gif ${cyc}2dew${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp ${cyc]*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
