#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/omeg
rm /stmpp1/Geoffrey.Manikin/meg/omeg/*
cd /stmpp1/Geoffrey.Manikin/meg/omeg
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2013050812
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Wed

times="06 09 12"

for fhr in $times; do
fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/rap.${ymd}/rap_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 700 
 GVCORD   = pres 
 GDPFUN   = mul(omeg,1000) 
 CINT     = 1/-50/-2
 LINE     = 2/1/2/0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 700 mb VV (red-up, green-down)
 DEVICE   = GIF|700models_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ok 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 CINT     = 1/2/50
 LINE     = 3/1/2/0
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  RAP 700 mb VV 
 PANEL    = b
 
r
 CINT     = 1/-50/-2
 LINE     = 2/1/2/0 
 TITLE    = 0
r

ex
EOF

done
gpend

for fhr in $times; do
/usrx/local/im_beta/bin/convert -crop 0x0 700models_f0${fhr}.gif ${cyc}vvrap${fhr}.gif 
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
