#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg/soilm
rm /stmpp1/Geoffrey.Manikin/meg/soilm/*
cd /stmpp1/Geoffrey.Manikin/meg/soilm
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .
cp /meso/save/Geoffrey.Manikin/gempak/nagrib/ncepgrib2.tbl .

ymdh=2018060318
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold7

DAPATH=/gpfs/hps/nco/ops/com/gfs/prod/gfs.${ymd}
DAPATH=/ptmpp1/Geoffrey.Manikin/hold

times="198"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=${DAPATH}/gfs_${ymdh}f${fhr}
fmdl2=${DAPATH}/fv3_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0:0
 GVCORD   = dpth 
 GDPFUN   = soim 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  GFS SOIL MOISTURE
 DEVICE   = GIF|${cyc}soim2_${ymd}${cyc}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-78;25;/1;1;1;1 
 GAREA    = fl 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .02;.05;.1;.15;.2;.25;.3;.35;.4;.45;.5 
 FLINE    = 0;18;16;17;10;5;20;21;22;23;27;4
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1/-1/~   FV3GFS @ SOIL MOISTURE
 CLRBAR   = 1/H/UL/.08;0.98/.8;.02/2 
 PANEL    = b
r

ex
EOF

    gdcntr << EOF
 GDFILE   = fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GFUNC    = sub(soim+2,soim)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 0:10 SOILM   GFS - FV3 
 DEVICE   = GIF|${cyc}soilmdiff2_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -.2;-.16;-.12;-.08;-.04;.04;.08;.12;.16;.20 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
