#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/nestpcp
rm /stmpp1/Geoffrey.Manikin/meg/nestpcp/*
cd /stmpp1/Geoffrey.Manikin/meg/nestpcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015110912
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold2

hours="30"
fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 24-HR TOTAL PCP
 DEVICE   = GIF|${ymdh}pcp24nestzf${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = de 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.03;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6;7;8
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM CONUS NEST 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
