#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/scape4
rm /stmpp1/Geoffrey.Manikin/meg/scape4/*
cd /stmpp1/Geoffrey.Manikin/meg/scape4
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015091200
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="15 18"
for fhr in $times; do

DAPATH=/com/nawips/prod/nam.${ymd}/
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/
fmdl1=${DAPATH}/nam12_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE 
 DEVICE   = GIF|${cyc}scapenest${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-81.;25./2;2;1;1                     
 GAREA    = 40.;-84.;44.;-77.6        
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  CONUS NEST  SFC-BASED CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend

#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
