#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak


mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/scape
rm /stmpp1/Geoffrey.Manikin/meg/scape/*
cd /stmpp1/Geoffrey.Manikin/meg/scape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015091200
ymd=`echo $ymdh | cut -c1-8`
fhr1=18
fhr2=21
fhr3=24
fhr4=27
dayoweek=hold3

DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}
fmdl1=${DAPATH}/nam12_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/nam12_${ymdh}f0${fhr2}
fmdl3=${DAPATH}/nam12_${ymdh}f0${fhr3}
fmdl4=${DAPATH}/nam12_${ymdh}f0${fhr4}

echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE 
 DEVICE   = GIF|namscape_${ymdh}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = oh+
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.3;0.95/1.6;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 TITLE    = 1/-1/~  NAM  SFC-BASED CAPE 
 PANEL    = ur 
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 TITLE    = 1/-1/~  NAM  SFC-BASED CAPE
 PANEL    = ll 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 TITLE    = 1/-1/~  NAM  SFC-BASED CAPE
 PANEL    = lr
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
