#!/bin/sh
echo 'into'

cyc=$1

ymdh=2020081009
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=726530
#stnm=744550
#stnm=045142

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/snd
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/snd/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/snd
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold8

DAPATH=/com2/nawips/prod
#DAPATH=/meso/noscrub/Geoffrey.Manikin/
DAPATH=/gpfs/dell2/emc/verification/noscrub/Geoffrey.Manikin/derecho/
DAPATH=/gpfs/dell1/ptmp/Geoffrey.Manikin/rap
fmdl1=${DAPATH}/nam.${ymd}/nam_${ymdh}.snd
#fmdl2=${DAPATH}/rap.${ymd}/rap_${ymdh}.snd
fmdl2=${DAPATH}/rap_${ymdh}.snd

times="00 03 06 07 08 09 12"
times="00 03 06 09"
times="00 03 06 09 12"
times="00"
for time in $times; do

validtime="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM 
 DEVICE   = gif|${ymdh}snd${stnm}_namrap$fhr.gif | 800;850
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -10/45/5/;1
 FILTER   = n 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//  RAP 
 PANEL    = b
r

ex
EOF

done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
