#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresrefc1
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresrefc1/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresrefc1
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2022011912
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

hours="23 24 25 26"
for fhr in $hours; do

fmdl1=/gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam32_${ymdh}f0${fhr}
fmdl2=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymdh}f0${fhr}
fmdl3=/gpfs/hps/nco/ops/com/cmc/prod/cmc.${ymd}/gempak/cmc_${ymdh}f0${fhr}
fmdl4=/gpfs/hps/nco/ops/com/hiresw/prod/hiresw.${ymd}/gempak/hiresw_conusfv3_${ymdh}f0${fhr}

garea="md+"
proj="lcc/25.;-77.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(refc,wxtr) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|refc_${ymdh}f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  NAM  REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 CLEAR    = n
 TITLE    = 0
 GDPFUN   = mul(refc,wxts)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;6;27;26;25;24;4;7
r

 GDPFUN   = mul(refc,wxtz)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;11;12;16;13;2;15;14
r

 GDPFUN   = mul(refc,wxtp)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;28;28;29;29;30;30
r

 GDFILE   = $fmdl2
 PANEL    = ll
 TITLE    = 1//~  GFS  REFC 
 GDPFUN   = mul(refc,wxtr)
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
r

 TITLE    = 0
 GDPFUN   = mul(refc,wxts)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;6;27;26;25;24;4;4;7
r

 GDPFUN   = mul(refc,wxtz)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;11;12;16;13;2;15;14
r

 GDPFUN   = mul(refc,wxtp)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;28;28;29;29;30;30
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  CMC  REFC 
 GDPFUN   = mul(refc,wxtr)
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
r

 CLEAR    = n
 TITLE    = 0
 GDPFUN   = mul(refc,wxts)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;6;27;26;25;24;4;7
r

 GDPFUN   = mul(refc,wxtz)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;11;12;16;13;2;15;14
r

 GDPFUN   = mul(refc,wxtp)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;28;28;29;29;30;30
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  HIRESW FV3  REFC
 GDPFUN   = mul(refc,wxtr)
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
r

 CLEAR    = n
 TITLE    = 0
 GDPFUN   = mul(refc,wxts)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;6;27;26;25;24;4;7
r

 GDPFUN   = mul(refc,wxtz)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;11;12;16;13;2;15;14
r

 GDPFUN   = mul(refc,wxtp)
 FINT     = 5;10;15;20;25;30;35
 FLINE    = 0;28;28;29;29;30;30
r


ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test5/.
exit
