#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtak
rm /stmpp1/Geoffrey.Manikin/meg/2mtak/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtak
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018031612
dayoweek=hold10


fmdl1=/ptmpp1/Geoffrey.Manikin/hold/hrrrsmartakold_2018031612f008
fmdl2=/ptmpp1/Geoffrey.Manikin/hold/hrrrsmartaknew_2018031612f008

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   OLD HRRR SMART 2-M  TEMP 
 DEVICE   = GIF|2mtmodels.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = str/90;-150;0;/1;1;1;1
 GAREA    = 42.;-172.;70.;-106.
 GAREA    = 54.;-162.;70.;-120.
 GAREA    = 60.;-156.;64.;-148.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95
 FINT     = -24;-20;-16;-12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NEW HRRR SMART 2-M TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2mtmodels.gif hrrrsmarttestzoom_12zf08.gif 
scp h*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
