#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtskin
rm /stmpp1/Geoffrey.Manikin/meg/2mtskin/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtskin
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017021800
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

times="12"
for fhr in $times; do

fmdl1=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = tmpc 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SKIN TEMP 
 DEVICE   = GIF|2mtskinmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-150;25;/1;1;1;1
 GAREA    = ak 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105
# FINT     = -30;-27;-24;-21;-18;-15;-12;-9;-6;-3;0;3;6;9;12;15;18;21
 FINT     = -40;-36;-32;-28;-24;-20;-16;-12;-8;-4;0;4;8;12;16;20;24
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
# FINT     = 24;28;32;36;40;44;48;52;56;60;64;68;72;76;80;84;88;92;96
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GVCORD   = hght
 GLEVEL   = 2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS 2-M TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(tmpc@0%none,tmpc)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~  GFS TMPC   SKIN - 2M 
 DEVICE   = GIF|2mtskindiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -18;-14;-10;-6;-2;2;6;10;14;18
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2mtskinmodels_f0${fhr}.gif 2mtskin1.gif
$CONV/convert -crop 0x0 2mtskindiff_f0${fhr}.gif 2mtskin2.gif
$CONV/montage -geometry 800xskin 2mtskin1.gif 2mtskin2.gif ${cyc}2mtskin${fhr}.gif
done

#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp 2*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

rm *gif
exit
