#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefd2
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefd2/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefd2
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015042612
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="21 22 23 24 25 26 27 28 29 30"
hours="03 04 05  06 07 08 09 10 11 12"
hours="01 02 03 04 05 06 07 08 09 10 11 12"
hours="06 09 12 15"
for fhr in $hours; do

fmdl1=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=/meso/save/Geoffrey.Manikin/meg/nsslwrf_${ymdh}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}
fmdl3=/meso/save/Geoffrey.Manikin/meg/hireswarw_${ymdh}
fmdl4=/meso/save/Geoffrey.Manikin/meg/hireswnmmb_${ymdh}
fmdl1=/ptmpd2/Geoffrey.Manikin/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
#fmdl2=/ptmpd1/Geoffrey.Manikin/hold2/arw_${ymdh}f0${fhr}
#fmdl3=/ptmpd1/Geoffrey.Manikin/hold2/nmmb_${ymdh}f0${fhr}

echo $fmdl1
echo $fmdl2

garea="27.;-100.5;34.;-91.5"
#garea="la+"
proj="lcc/25.;-96.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 1000 
 GVCORD   = hght 
 GDPFUN   = refd 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymdh}hires1refd2_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL = county
 TITLE    = 1//~  HRRR 1 KM REFD
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl4
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW NMMB  1 KM REFD 
 CLRBAR   = 1/H/UL/.46;0.94/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW ARW  1 KM REFD 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl2
 PANEL    = ur
 TITLE    = 1//~  NSSL WRF  1 KM REFD 
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/hold/.
exit
