#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/nestpcp
rm /stmpp1/Geoffrey.Manikin/meg/nestpcp/*
cd /stmpp1/Geoffrey.Manikin/meg/nestpcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2014122212
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold2

hours="18 24 30 36 42"
hours="30 36 42 48"
for fhr1 in $hours; do

fhr3=`expr $fhr1 - 3`
typeset -Z2 fhr3

cp /com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr1} fmdl1
cp /com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr3} fmdl1b
cp /com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr1} fmdl2
cp /com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr3} fmdl2b

    gdplot2 << EOF
 GDFILE   = fmdl1 + fmdl1b
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = add(p03i^${ymd}/${cyc}f${fhr3}+2,p03i^${ymd}/${cyc}f$fhr1)
 CINT     = 0.1 
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  NAM 6-HR TOTAL PCP
 DEVICE   = GIF|${ymdh}pcp6nestparentf${fhr1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ    = lcc/25;-90;25;/1;1;1;1
# GAREA    = 34.;-126.;44.;-114. 
 GAREA    = 29.;-84.;43.;-62.
 GAREA    = la-
 CLEAR    = y
 PANEL    = t 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.2;.3;.4;.5;.75;1;1.25;1.5;2;2.5;3
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdl2 + fmdl2b
 PANEL    = b 
 CLRBAR   = 1/H/UL/.04;0.97/0.9;.03/1
 CLEAR    = n
 TITLE    = 1/-1/~  4 KM NAM 6-HR TOTAL PCP
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
