#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/700w
rm /stmpp1/Geoffrey.Manikin/meg/700w/*
cd /stmpp1/Geoffrey.Manikin/meg/700w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015012612
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

hours="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
hours="00 03 06 09 12 15"
hours="12 18 24"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 700
 GVCORD   = pres
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|700models_f0${fhr}.gif | 800;700
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = 20.;-124.;50.;-62. 
 GAREA    = 36.;-80.;46.;-62. 
 TITLE    = 1//~  NAM  700 MB  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 1.1/11/2
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;26;4;23;21;5;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.8/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /7;7
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 700
 GVCORD   = pres
 GDPFUN   = knts(sped)
 CINT     = 5
 LINE     = 0
 TITLE    = 1//~  ECMWF  700 MB  WIND (KT)
 CLEAR    = n
 PANEL    = b
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 1.1/11/2
 TYPE     = f
r

 CINT     =
 WIND     = BK1/0.8/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /7;7
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 700
 GVCORD   = pres
 GFUNC    = knts(sub(sped+2,sped))
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 700 WIND SPEED (KT)   NAM - ECMWF 
 DEVICE   = GIF|700diff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.92/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -50;-40;-30;-20;-10;10;20;30;40;50
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 700models_f0${fhr}.gif 7001.gif
$CONV/convert -crop 0x0 700diff_f0${fhr}.gif 7002.gif
$CONV/montage -geometry 800x700 7001.gif 7002.gif  ${ymdh}_700wsnamecz$fhr.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
