#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/84pcp
rm /stmpp1/Geoffrey.Manikin/meg/84pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/84pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013010812
ymd=20130108
dayoweek=Tue

if [ $cyc -eq 00 ]; then
 hours="36"
elif [ $cyc -eq 12 ]; then
 hours="24 48"
fi

for fhr in $hours; do
fmdl1=/com/nawips/prod/hiresw.${ymd}/hiresw_eastarw_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_eastnmm_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   HIRESW ARW 24-HR TOTAL PCP
 DEVICE   = GIF|24pcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  HIRESW NMM 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GFUNC    = sub(p24i+2,p24i)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 24-HR HIRESW TOTAL PCP  NMM-ARW
 DEVICE   = GIF|24pcpdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.06;.9/.87;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done

gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 24pcpmodels_f${fhr}.gif 24pcp1.gif
$CONV/convert -crop 0x0 24pcpdiff_f${fhr}.gif 24pcp2.gif
$CONV/montage -geometry 700x750 24pcp1.gif 24pcp2.gif ${cyc}24pcphiresw${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
