#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850z
rm /stmpp1/Geoffrey.Manikin/meg/850z/*
cd /stmpp1/Geoffrey.Manikin/meg/850z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013032212
ymd=20130322
dayoweek=Fri

hours="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850 
 GVCORD   = pres 
 GDPFUN   = quo(hght,10)
 CINT     = 3/104/164
 LINE     = 4/1/3/2
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 850 MB HEIGHT 
 DEVICE   = GIF|850zmodels_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = grid 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CINT     = 0/0/0
 GDPFUN   = tmpc
 LINE     = 2/1/4/1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GDPFUN   = quo(hght,10)
 CINT     = 3/104/164
 LINE     = 4/1/3/3
 TITLE    = 1/-1/~  GFS 850 MB HEIGHT 
 PANEL    = b
r

 GDPFUN   = tmpc
 CINT     = 0/0/0
 LINE     = 2/1/4/1
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 850  
 GVCORD   = pres 
 GFUNC    = sub(hght+2,hght)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 850 MB HEIGHT    NAM - GFS
 DEVICE   = GIF|850zdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -100;-80;-60;-40;-20;20;40;60;80;100
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $hours; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
/usrx/local/im_beta/bin/convert -crop 0x0 850zmodels_f0${fhr}.gif 850z1.gif
/usrx/local/im_beta/bin/convert -crop 0x0 850zdiff_f0${fhr}.gif 850z2.gif

CONV=/usrx/local/imajik/bin
$CONV/montage -geometry 700x750 850z1.gif 850z2.gif ${cyc}850z${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
