#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/gustwz
rm /stmpp1/Geoffrey.Manikin/meg/gustz/*
cd /stmpp1/Geoffrey.Manikin/meg/gustwz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016100617
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold6

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 06 09 12 15 18 21 24 36 48 60"
times="12 15 18" 
for fhr in $times; do

DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
DAPATH1=/com/nawips/prod
DAPATH2=/com2/nawips/prod
fmdl1=${DAPATH1}/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = knts(gust)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nam4hrrrgust_f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-85.;25./2;2;1;1
 \$MAPFIL = county
 GAREA    = 44.;-112.;50.;-102. 
 GAREA    = fl 
 TITLE    = 1//~  NAM4  SFC GUST (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 1.1/11/2
 FINT     = 20;30;40;50;60;70;80;90;100;110;120
# FINT      = 10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;30;28;27;25;23;21;5;10;17;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  HRRR  SFC GUST (KT)
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
