#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/84pcpz
rm /stmpp1/Geoffrey.Manikin/meg/84pcpz/*
cd /stmpp1/Geoffrey.Manikin/meg/84pcpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016041700
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold6

if [ $cyc -eq 00 ]; then
 hours="36 60 84"
elif [ $cyc -eq 06 ]; then
 hours="30 54 78"
elif [ $cyc -eq 12 ]; then
 hours="06 48 72"
else
 hours="48 60"
fi

hours="66 72"
fmdl1=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}

for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p06i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 06-HR TOTAL PCP
 DEVICE   = GIF|6pcpgfs_${ymdh}f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
# GAREA    = 25.;-105.;37.;-87.    
 GAREA    = tx 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5;15;17.5;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;16;17;10;19;5;32;1
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6;8
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;19;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = c06i 
 TITLE    = 1/-1/~  GFS 06-HR CNVCT PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
exit
