#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefd3
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefd3/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefd3
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013053112
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Fri

hours="10 11 12 13 14 15 16 17 18"
hours="21 22 23 24 25 26 27 28 29 30"
hours="09 12 15 18"
for fhr in $hours; do

fmdl1=/ptmpp1p1/Geoffrey.Manikin/test/spcprod_${ymdh}f0${fhr}

areas="1"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="ok+"
proj="lcc/25.;-96.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 1000 
 GVCORD   = hght 
 GDPFUN   = refd 
 CINT     = 5 
 LINE     = 1 
 DEVICE   = GIF|${cyc}spccountyrefd${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 MAP      = 1/1/2;1
 \$MAPFIL = county
 TITLE    = 1//~  EMC SPC RUN  1 KM REFD
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

ex
EOF
done
done
gpend

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdrefd/.
exit
