#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/bcape
rm /stmpp1/Geoffrey.Manikin/meg/bcape/*
cd /stmpp1/Geoffrey.Manikin/meg/bcape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2018072800
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

times="21"
for fhr in $times; do

fmdl1=/ptmpp1/Geoffrey.Manikin/post/hrrrtest_${ymdh}f0${fhr}00

   gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = cape
 CINT     = 500
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   HRRR SFC-BASED CAPE
 DEVICE   = GIF|rcape1_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-120.;51.;-66.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 180:0
 GVCORD   = pdly
 TITLE    = 1/-1/~  HRRR BEST CAPE
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

 GLEVEL   = 255:0
 GVCORD   = pdly
 TITLE    = 1/-1/~  HRRR BEST CAPE
 PANEL    = t
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2
 CLEAR    = y
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2
 DEVICE   = GIF|rcape2_f0${fhr}.gif|750;900
r


 GLEVEL   = 0:3000
 GVCORD   = hght
 TITLE    = 1/-1/~  HRRR  0-3 KM CAPE
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r


 GLEVEL   = 90:0
 GVCORD   = pdly
 TITLE    = 1/-1/~  HRRR MIXED LAYER CAPE
 PANEL    = t
 CLEAR    = y
 CLRBAR   = 1/V/UL/.01;0.9/0.8;.03/2
 DEVICE   = GIF|rcape3_f0${fhr}.gif|750;900
r

 GLEVEL   = 400:0
 GVCORD   = pdly
 GDPFUN   = dcap
 TITLE    = 1/-1/~  HRRR DOWNDRAFT CAPE
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 1/V/UL/.01;0.9/0.8;.03/2
 FINT     = 200;400;600;800;1000;1250;1500
r

 GLEVEL   = 0:500
 GVCORD   = hght
 GDPFUN   = cang
 TITLE    = 1/-1/~  HRRR  CRITICAL ANGLE
 PANEL    = b
 FINT     = 20;40;60;80;100;120;140
 FLINE    = 0;29;4;22;2;22;4;29;0
 CLEAR    = y
 DEVICE   = GIF|rcape4_f0${fhr}.gif|750;900
r

 GLEVEL   = 0:3000
 GVORD    = hght
 GDPFUN   = ensp
 TITLE    = 1/-1/~   HRRR ENH STRETCH POTENTIAL
 PANEL    = t
 CLEAR    = n
 CLRBAR   = 1/V/UL/.01;0.9/0.8;.03/2
 FINT     = 1;2;3;4;5
 FLINE    = 0;29;26;22;5;10;2
r

 GLEVEL   = 3000:0
 GVCORD   = hght
 GDPFUN   = hlcy
 TITLE    = 1/-1/~  HRRR 0-3 KM SRH
 PANEL    = t
 CLEAR    = y
 CLRBAR   = 1/V/UL/.01;0.9/0.8;.03/2
 FINT     = 50;100;150;200;300;400;500
 DEVICE   = GIF|rcape5_f0${fhr}.gif|750;900
r

 GLEVEL   = 255:0
 GVCORD   = pdly
 TITLE    = 1/-1/~  HRRR  ERSH
 PANEL    = b
 CLEAR    = n
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/hrrr/test/.
exit
