#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/10wz
rm /stmpp1/Geoffrey.Manikin/meg/10wz/*
cd /stmpp1/Geoffrey.Manikin/meg/10wz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016092912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 09" 
for fhr in $times; do

fmdl1=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
#fmdl2=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|10wvmedr_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-74.;25./2;2;1;1
 GAREA    = 28.;-86.;46.;-54. 
 GAREA    = 27.;-90.8;34.4;-82.4 
 GAREA    = de+
 TITLE    = 1//~  ECMWF  10M  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 SKIP     = 0
 TEXT     = 1.0/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = b 
r

 GDFILE   = $fmdl2
 GLEVEL   = 10
 GVCORD   = hght
 TITLE    = 1//~  GFS  10M  WIND (KT)
 CLEAR    = n
 PANEL    = b 
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
