#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/gustwz
rm /stmpp1/Geoffrey.Manikin/meg/gustz/*
cd /stmpp1/Geoffrey.Manikin/meg/gustwz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017030112
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold5

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 06 09 12 15 18 21 24 36 48 60"
times="27 30 33" 
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = knts(gust)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|gustmodels_f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-72.;25./2;2;1;1
 GAREA    = 44.;-136.;56.;-118. 
 GAREA    = ma+ 
 TITLE    = 1//~  NAM  SFC GUST (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 1.1/11/2
# FINT     = 20;30;40;50;60;70;80;90;100
 FINT      = 10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;30;28;27;25;23;21;5;10;17;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  GFS  SFC GUST (KT)
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0
 GVCORD   = none 
 GFUNC    = knts(sub(gust+2,gust))
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SFC GUST (KT)   NAM - GFS
 DEVICE   = GIF|gustdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.92/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -25;-20;-15;-10;-5;5;10;15;20;25
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 gustmodels_f0${fhr}.gif gust1.gif
$CONV/convert -crop 0x0 gustdiff_f0${fhr}.gif gust2.gif
$CONV/montage -geometry 800x850 gust1.gif gust2.gif ${cyc}gustwz${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
