#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrrcape
rm /stmpp1/Geoffrey.Manikin/meg/hrrrcape/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrrcape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017012218
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

times="03"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 700 
 GVCORD   = pres 
 GDPFUN   = relh 
 CINT     = 50;60;70;80;90 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ NAM 700 MB RH/OMEG (rising motion in red)
 DEVICE   = GIF|700_${ymdh}f${fhr}.gif|700;850
 SATFIL   =
 RADFIL   =
 PROJ     = 
 GAREA    = fl 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.15;0.92/.5;.02/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;60;70;80;90
 FLINE    = 0;20;5;21;22;23
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDPFUN   = mul(omeg,1000)
 CINT     = 1/-21/-1
 LINE     = 2/1/2/0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 1/-50/-21
 LINE     = 15/1/3/0
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~ GFS 700 MB RH/OMEG (rising motion in red)
 CLEAR    = n
 PANEL    = b
r

 CINT     = 1/-21/-1
 LINE     = 2/1/2/0
r

 GDPFUN   = relh
 TYPE     = c
 FINT     = 50;60;70;80;90
 FLINE    = 0;20;5;21;22;23
r
 
ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
