#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/rate
rm /stmpp1/Geoffrey.Manikin/meg/rate/*
cd /stmpp1/Geoffrey.Manikin/meg/rate
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012120315
ymdh2=2012120415

times="09"
for fhr in $times; do

#fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
#fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

fmdl1=/ptmpp1p1/Geoffrey.Manikin/hold/emctl_${ymdh}f0${fhr}
fmdl2=/ptmpp1p1/Geoffrey.Manikin/hold/emctl_${ymdh2}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = prxx 
 CINT     = 1 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   EM PRATE 
 DEVICE   = GIF|ratemodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 26.;-125.;60.;-55. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 8 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~   EM PRATE 
 PANEL    = b
r

ex
EOF
gpend
done

for fhr in $times; do
/usrx/local/im_beta/bin/convert -crop 0x0 ratemodels_f0${fhr}.gif ${cyc}emrate${fhr}.gif
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
