#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/nestpcp
rm /stmpp1/Geoffrey.Manikin/meg/nestpcp/*
cd /stmpp1/Geoffrey.Manikin/meg/nestpcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014120812
ymd=20140226
dayoweek=hold2

DAPATH=/com/nam/prod/nam.${ymd}
DAPATH2=/com/nam/prod/nam.${ymd}

export DAPATH DAPATH2
. /nwprod/gempak/.gempak

fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $fhrs
do

wgrib -i -d 16 ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00 -grib -o new.fil
wgrib -i -d 17 ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00 -grib -o newc.fil

  nagrib << EOF
GBFILE  = new.fil
INDXFL  =
GDOUTF  = dummynest.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = newc.fil
r

exit
EOF

rm new*.fil
done
mv dummynest.grd /meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}

for fhr in $fhrs
do

wgrib -i -d 16 ${DAPATH2}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00 -grib -o new.fil
wgrib -i -d 17 ${DAPATH2}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00 -grib -o newc.fil

   nagrib << EOF
GBFILE  = new.fil
INDXFL  =
GDOUTF  = dummynest2.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = newc.fil
r

exit
EOF
rm new*.fil
done
mv dummynest2.grd /meso/save/Geoffrey.Manikin/meg/namxnestpcp_${ymdh}

if [ $cyc -eq 00 ]; then
 hours="36 60"
elif [ $cyc -eq 06 ]; then
 hours="30 54"
elif [ $cyc -eq 12 ]; then
 hours="24 48"
else
 hours="42"
fi

fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namxnestpcp_${ymdh}
for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 24-HR TOTAL PCP
 DEVICE   = GIF|${cyc}24pcpnest${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 34.;-88.;46.;-62.
# GAREA    = 22.;-120.;52.;-64.
# PROJ     = lcc/25;-98;25;/1;1;1;1
# GAREA    = 33.;-104.;43.;-90.
 GAREA    = de-
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.02;0.5/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6;7;8;10;12
 FLINE    = 0;21;22;23;4;25;27;28;29;30;14;15;2;12;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM CONUS NEST 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done

for fhr in $hours; do

    gdplot2 << EOF
 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p24i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   4 KM NAM 24-HR TOTAL PCP
 DEVICE   = GIF|${cyc}24pcpnestx${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.02;0.5/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6;7;8;10;12
 FLINE    = 0;21;22;23;4;25;27;28;29;30;14;15;2;12;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  4 KM NAMX 24-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f60 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p60i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 60-HR TOTAL PCP
 DEVICE   = GIF|${cyc}60pcpnest.gif|750;900
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.02;0.5/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6;7;8;10;12
 FLINE    = 0;21;22;23;4;25;27;28;29;30;14;15;2;12;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM CONUS NEST 60-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdplot2 << EOF
 GDFILE   = $fmdl2
 GDATTIM  = f60 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p60i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   4 KM NAM 60-HR TOTAL PCP
 DEVICE   = GIF|${cyc}60pcpnestx.gif|750;900
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.02;0.5/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;3;4;5;6;7;8;10;12
 FLINE    = 0;21;22;23;4;25;27;28;29;30;14;15;2;12;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  4 KM NAMX 60-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

gpend
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
