#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/swrd
rm /stmpp1/Geoffrey.Manikin/meg/swrd/*
cd /stmpp1/Geoffrey.Manikin/meg/swrd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015081512
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="06 12"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = swrd06 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM AVG SW DOWN SFC 
 DEVICE   = GIF|swrdmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-99;25;/1;1;1;1                
 GAREA    = 38.;-107.;50.;-89.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;200;300;400;500;600;700;800;900;1000
 FLINE    = 30;28;26;4;23;21;5;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS  AVG SW DOWN SFC 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none  
 GFUNC    = sub(swrd06+2,swrd06)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SW DOWN   NAM - GFS
 DEVICE   = GIF|swrddiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -250;-200;-150;-100;-50;50;100;150;200;250 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin/
${CONV}/convert -crop 0x0 swrdmodels_f0${fhr}.gif swrd1.gif
${CONV}/convert -crop 0x0 swrddiff_f0${fhr}.gif swrd2.gif
${CONV}/montage -geometry 800x850 swrd1.gif swrd2.gif ${cyc}swrd${fhr}.gif
done
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
