#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/cape
rm /stmpp1/Geoffrey.Manikin/meg/cape/*
cd /stmpp1/Geoffrey.Manikin/meg/cape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
ymdh=2012080800
ymd=20120808
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="18 21"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE 
 DEVICE   = GIF|capemodels_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-120.;51.;-66. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 90:0
 GVCORD   = pdly 
 TITLE    = 1/-1/~  NAM MIXED-LAYER CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(cape@none%0,cape)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ NAM CAPE   SFC - MIX 
 DEVICE   = GIF|capediff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;.9/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1500;-1000;-750;-500;-250;250;500;750;1000;1500 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

/usrx/local/im_beta/bin/convert -crop 0x0 capemodels_f0${fhr}.gif cape1.gif
/usrx/local/im_beta/bin/convert -crop 0x0 capediff_f0${fhr}.gif cape2.gif

CONV=/usrx/local/imajik/bin
$CONV/montage -geometry 700x750 cape1.gif cape2.gif ${cyc}cape${fhr}.gif
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
