#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/swem
rm /stmpp1/Geoffrey.Manikin/meg/swem/*
cd /stmpp1/Geoffrey.Manikin/meg/swem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013010200
#ymd=20130102
#dayoweek=Wed

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = swem 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM SNOW WATER EQUIV 
 DEVICE   = GIF|swemmodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-100;25;/1;1;1;1
 GAREA    = 31.;-104.;47.;-80. 
# GAREA    = 36.;-117.;56.;-81. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.08;.4/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 1.;2.5;5.;10.;15.;20;25;50;75
 FLINE    = 0;25;26;24;5;20;10;17;15;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = swem 
 CINT     = 4 
 LINE     = 4/1/3/2 
 CLEAR    = n
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS  SNOW WATER EQUIV 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 CLRBAR   = 0 
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(swem+2,swem)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SWEM   NAM - GFS
 DEVICE   = GIF|swemdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -10;-7;-5;-3;-1;1;3;5;7;10
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 swemmodels_f0${fhr}.gif swem1.gif
$CONV/convert -crop 0x0 swemdiff_f0${fhr}.gif swem2.gif
$CONV/montage -geometry 800x850 swem1.gif swem2.gif ${cyc}swem${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
