#!/bin/sh
echo 'into'

ymdh=2023031600
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=725266

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/snd
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/snd/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/snd
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold3

cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/nam_conusnest_${ymdh}.snd fmdl1
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/hrrr_${ymdh}.snd fmdl2

times="00 03 06 09 12 15 18 21 24 27 30 33 36"
times="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
times="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
times="108 109 110 111 112 113 114"
times="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21"
#times="72 75 78 81 84"
#times="105 108 111 114 117 120"
times="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
times="12 15 18 21 24 27"
for time in $times; do

validtime="`/lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = capv;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM NEST
 DEVICE   = gif|${ymdh}_nesthrrrsnd${stnm}_${fhr}.gif | 800;850
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -35/25/5/;1
 FILTER   = 0.9 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = fmdl2
 CLEAR    = n
 TITLE    = 1//  HRRR 
 PANEL    = b
r

ex
EOF

done
gpend

#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test9/.
exit
