#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresw2mt
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresw2mt/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hiresw2mt
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2021062800
ymd=`echo $ymdh | cut -c1-8`

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="00 03 06 09 12 13 14 15 16 17 18"
hours="00 01 02 03 06 09 12 21 24 27 30 33 36" 
hours="24"
for fhr in $hours; do

fmdl1=/gpfs/dell1/ptmp/Geoffrey.Manikin/hiresw/arw_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hiresw2mt${region}_f${fhr}.gif | 800;850
 PROJ     = lcc/25;-115;25;/1;1;1;1
 GAREA    = wa+ 
 TITLE    = 1//~  ARW  2-m DEW
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.4/0.8;.03/2 
 TEXT     = 0.9/11/2
 FINT     = 20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110;115;120;125
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f 
r

 GDPFUN   = dwpf 
 PANEL    = b 
 CLEAR    = n
 TITLE    = 1//~  ARW 2-M  2-m DEW 
 CLRBAR   = 0 
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
