#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/48hirespcp
rm /stmpp1/Geoffrey.Manikin/meg/48hirespcp/*
cd /stmpp1/Geoffrey.Manikin/meg/48hirespcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016100712
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

if [ $cyc -eq 00 ]; then
 hours="36"
elif [ $cyc -eq 12 ]; then
 hours="24 48"
fi

hours="48"
for fhr in $hours; do
fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswnmmbpcp_$ymdh

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p48i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 \$MAPFIL = county
 WIND     = 0
 TITLE    = 1/-1/~   HIRESW ARW 48-HR TOTAL PCP
 DEVICE   = GIF|48pcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
# PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 21.;-121.;51.;-65.
# GAREA    = 33.;-104.;43.;-90. 
 PROJ     = lcc/25;-79;25;/1;1;1;1                     
 GAREA    = 31.;-82.;37.;-74. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8;12
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;16;15;17;10;5
 FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5;1
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  HIRESW NMMB 48-HR TOTAL PCP
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GFUNC    = sub(p48i+2,p48i)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 48-HR HIRESW TOTAL PCP  NMMB-ARW
 DEVICE   = GIF|48pcpdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.06;.9/.87;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.5;-1.;-0.75;-0.5;-0.25;0.25;0.5;0.75;1.;1.5
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done

gpend

for fhr in $hours; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 48pcpmodels_f${fhr}.gif 48pcp1.gif
$CONV/convert -crop 0x0 48pcpdiff_f${fhr}.gif 48pcp2.gif
$CONV/montage -geometry 700x750 48pcp1.gif 48pcp2.gif ${cyc}48pcphiresw${fhr}.gif
done
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
