#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slpz
rm /stmpp1/Geoffrey.Manikin/meg/slpz/*
cd /stmpp1/Geoffrey.Manikin/meg/slpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016022312
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="12"
for fhr in $times; do

#fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
#fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hiresw.${ymd}/hiresw_arw_${ymdh}f0${fhr}
fmdl2=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hiresw.${ymd}/hiresw_nmmb_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = emsl 
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ARW SLP 1000-500 THK 
 DEVICE   = GIF|slpmodels_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-88;25;/1;1;1;1
 GAREA    = 28.;-84.;50.;-52.
 GAREA    = ms 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 2;2/S12#;S13#/1015-1060;920-1014/5/1;1/yes
 HLSYM    = 3;3/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = emsl 
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NMMB  SLP 1000-500 THK 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1015-1060;920-1014/5/1;1/yes
 HLSYM    = 3;3/3/21;21/4;2/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(emsl+2,emsl)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ SLP   ARW - NMMB 
 DEVICE   = GIF|slpdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -15;-12;-9;-6;-3;3;6;9;12;15
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 slpmodels_f0${fhr}.gif slp1.gif
$CONV/convert -crop 0x0 slpdiff_f0${fhr}.gif slp2.gif
$CONV/montage -geometry 800x850 slp1.gif slp2.gif ${ymdh}_hireswslp${fhr}.gif
done
scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
