#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrrbase
rm /stmpp1/Geoffrey.Manikin/meg/hrrrbase/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrrbase
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016050912
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
hours="08"
#hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
for fhr in $hours;do

#fmdl1=/com2/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/namrr.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = cldl 
 GDPFUN   = pres 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrrxnamrr_cdbp_${ymdh}f${fhr}.gif | 800;850
 GAREA    = 34.;-105.;40.;-96.
 GAREA    = ok+ 
 PROJ     = "lcc/25.;-97.;25./2;2;1;1"
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z HRRRX   F${fhr} CLOUD BASE P 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.02;0.6/1.2;.03/1
 TEXT     = 0.9/11/2
 FINT     = 300;400;500;600;700;800;900;1000
 FLINE    = 0;30;28;4;26;23;21;20;10;17;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b
 TITLE    = 1//  ${cyc}z NAMRR   F${fhr} CLOUD BASE P 
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
