#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtmr
rm /stmpp1/Geoffrey.Manikin/meg/2mtmr/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtmr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013121000
ymd=20131210
dayoweek=Tue

times="18"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/com/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = tmpf 
 CINT     = 5
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ECMWF 2-M TMPF 
 DEVICE   = GIF|2mtmodels_f${fhr}.gif|900;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = md 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.1;0.4/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = -15;-10;-5;0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r

 GDFILE   = $fmdl2
 GLEVEL   = 2
 GVCORD   = HGHT
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~   GFS 2-M TMPF 
 PANEL    = b
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = f 
 LINE     = 1
 CINT     = 5
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(tmpf%hght@2+2,tmpf)
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M TMPF   GFS - ECMWF
 DEVICE   = GIF|2mtdiff_f${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.05;.6/.55;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -25;-20;-15;-10;-5;5;10;15;20;25
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2mtmodels_f${fhr}.gif 2mt1.gif
$CONV/convert -crop 0x0 2mtdiff_f${fhr}.gif 2mt2.gif
$CONV/montage -geometry 800x850 2mt1.gif 2mt2.gif ${cyc}2mtz${fhr}.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/medr/images_medr/$dayoweek/.
rm *gif
exit
