#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz
cp /meso/save/geoffrey.manikin/casework/coltbl.xwp .

version=v16.2
ymdh=2022092412
ymd=`echo $ymdh | cut -c1-8`

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 12 18 24" 
times="24 48 72 96"
for fhr in $times; do

fmdl1=/lfs/h1/ops/prod/com/gfs/${version}/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f0${fhr}
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10
 GVCORD   = hght 
 GDPFUN   = kntv(wind)
 WIND     = AK15/0.6/1/2/1
 CINT     = 0 
 LINE     = 0 
 DEVICE   = GIF|10wv2mt_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-70.;25./2;2;1;1
 GAREA    = 28.;-86.;46.;-54. 
 GAREA    = 27.;-90.8;34.4;-82.4 
 GAREA    = 40.8;-72.8;43.6;-68.8
 TITLE    = 1//~  NAM  10M WIND (KT) 2-M T
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 TEXT     = 0.8/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = b 
r

 GLEVEL   = 2
 CLEAR    = n
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
 CINT     = 2;5;8;11;14;17;20;23;26;29;32;35;38;41;44 
 LINE     = 4/1/2/1
r

 GDFILE   = $fmdl2
 TITLE    = 1//~  GFS  10M WIND (KT) 2-M T 
 PANEL    = b 
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wind)
 TYPE     = b
r

 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = tmpf
 TYPE     = c
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
