#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/pw
rm /stmpp1/Geoffrey.Manikin/meg/pw/*
cd /stmpp1/Geoffrey.Manikin/meg/pw
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
mon=`cut -c 5-7 holddate`
day=`cut -c 9-10 holddate`
gtime=`cut -c 12-24 holddate`
gdate=`cut -c 1-10 holddate`
gcent=`cut -c 25-28 holddate`
echo $dayoweek

ymdh=2019071312
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold8

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 09 12 15 18 21 24"
times="00 03 06 09"
for fhr in $times; do

fmdl1=/com2/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(pwtr,25.4)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  PCP WATER 
 DEVICE   = GIF|pwmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1
 GAREA    = la 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .25;.5;.75;1.;1.25;1.5;1.75;2.;2.25;2.5
 FLINE    = 0;21;22;23;28;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  GFS  PCP WATER 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none  
 GFUNC    = quo(sub(pwtr+2,pwtr),25.4)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ PW   NAM - GFS
 DEVICE   = GIF|pwdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-70.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 GAREA    = ri-
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.;-.8;-.6;-.4;-.2;.2;.4;.6;.8;1.
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 pwmodels_f0${fhr}.gif pw1.gif
$CONV/convert -crop 0x0 pwdiff_f0${fhr}.gif pw2.gif
$CONV/montage -geometry 800x850 pw1.gif pw2.gif ${ymdh}f0${fhr}pw.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
