#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/swem
rm /stmpp1/Geoffrey.Manikin/meg/swem/*
cd /stmpp1/Geoffrey.Manikin/meg/swem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20121210
ymd2=20121211
month=12
day=11
dayoweek=Tue

fmdl1=/ptmpp1p1/Geoffrey.Manikin/hold/namsnow_${ymd}06f000
fmdl2=/ptmpp1p1/Geoffrey.Manikin/hold/namsnow_${ymd2}06f000

echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sndm,100),2.54) 
 CINT     = 2 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|sndm${ymd}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = mn 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.1;1;5;10;15;20;25;50;75;100;125
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ $ymd AWFA 06z SNOW COVER (IN)
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

# TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
# TEXT     = 1.1/11/1/SW
#r

 TITLE    = 1/1/ $ymd2  AFWA 06z  SNOW COVER
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2
 GDPFUN   = quo(mul(sndm,100),2.54) 
 TITLE    = 0
 CINT     = 2 
r

ex
EOF
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit

