#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresw850w
rm /stmpp1/Geoffrey.Manikin/meg/hiresw850w/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresw850w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015122712
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="00 03 06 09 12 13 14 15 16 17 18"
hours="00 01 02 03 06 09 12 21 24 27 30 33 36" 
hours="36"
for fhr in $hours; do

fmdl1=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}

#fmdl1=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
#fmdl2=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}

areas="1"
for region in $areas; do
if [ $region -eq 1 ]
then
garea="il-"
proj="lcc/25.;-92.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850 
 GVCORD   = pres 
 GDPFUN   = knts(sped) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hiresw850w${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ARW  850 WIND SPEED 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.4/0.8;.03/2 
 TEXT     = 0.9/11/2
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;26;4;23;21;5;17;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b 
 CLEAR    = n
 TITLE    = 1//~  NMMB  850 WIND SPEED 
 CLRBAR   = 0 
r

ex
EOF

done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
