#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcp
rm /stmpp1/Geoffrey.Manikin/meg/6pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013020412
#ymd=20130204
#dayoweek=Mon
times="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
for fhr in $times; do

fhr3=`expr $fhr - 3`
typeset -Z2 fhr3

fmdl1=/com2/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
cp /com2/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr3} file3
fmdl3=file3

    gdplot2 << EOF

 GDFILE   = $fmdl1 + $fmdl3
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = add(p03i^${ymd}/${cyc}f${fhr3}+2,p03i^${ymd}/${cyc}f$fhr)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 6-HR PCP 
 DEVICE   = GIF|6pcpmodels_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GDPFUN   = p06i
 TITLE    = 1/-1/~  GFS 6-HR PCP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1 + $fmdl3
 GDATTIM  = f${fhr}
 GLEVEL   = 0  
 GVCORD   = none 
 GFUNC    = sub(add(p03i^${ymd}/${cyc}f$fhr+2,p03i^${ymd}/${cyc}f${fhr3}+3),p06i^${ymd}/${cyc}f${fhr})
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~  6-HR PCP   NAM - GFS
 DEVICE   = GIF|6pcpdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 21.;-121.;51.;-65. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -1.;-0.75;-0.5;-0.25;-0.1;0.1;0.25;0.5;0.75;1. 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 6pcpmodels_f0${fhr}.gif 6pcp1.gif
$CONV/convert -crop 0x0 6pcpdiff_f0${fhr}.gif 6pcp2.gif
$CONV/montage -geometry 700x750 6pcp1.gif 6pcp2.gif ${cyc}6pcp${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
