#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2020021912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold7

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="27 30 33 36"
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
times="57 60 63 78 81 84"
times="33 36 39 54 57 60 63"
times="09 12 15 33 34 35 36 39"
times="06 07 08 09 10 11 12 13 14 15"
times="45 48 66 69 72 75"
times="12 13 14 15 16 17 18"
times="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21"
times="36"
for fhr in $times; do

DAPATH1=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/nawips/
DAPATH2=/gpfs/hps/nco/ops/com/hrrr/prod/hrrr.${ymd}/conus/nawips
DAPATH1=/meso/noscrub/Geoffrey.Manikin/feb20ncstorm
cp ${DAPATH1}/rap13_${ymdh}f0${fhr} fmdl1
cp ${DAPATH1}/hrrr_${ymdh}f0${fhr}00 fmdl2

    gdplot2 << EOF
 GDFILE   = fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP 2-M  TEMP 
 DEVICE   = GIF|2mtmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 30.;-104.;40.;-88.
 GAREA    = 33.;-103;49.;-81.
 GAREA    = nc+ 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FINT     = 12;15;18;21;24;27;30;33;36;39;42;45;48;51;54;57;60;63;66;69;72
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
# FINT     = 48;51;54;57;60;63;66;69;72;75;78;81;84;87;90;93;96;99;102;105;108
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 FINT     = 12;15;18;21;24;27;30;33;36;39;42;45;48;51;54;57;60;63;66;69;72
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r


 GDFILE   = fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  HRRR 2-M TEMP 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 TYPE     = f
 LINE     = 1
 CINT     = 4
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r


ex
EOF

    gdcntr << EOF
 GDFILE   = fmdl2 + fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(tmpf+2,tmpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M TEMP (F)   RAP - HRRR 
 DEVICE   = GIF|2mtdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.96/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
# FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FINT     = -15;-12;-9;-6;-3;3;6;9;12;15
 FINT     = -10;-8;-6;-4;-2;2;4;6;8;10
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2mtmodels_f0${fhr}.gif 2mt1.gif
$CONV/convert -crop 0x0 2mtdiff_f0${fhr}.gif 2mt2.gif
$CONV/montage -geometry 800x850 2mt1.gif 2mt2.gif ${ymdh}_2mtraphrrr${fhr}.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
