#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresw2mt
rm /stmpp1/Geoffrey.Manikin/meg/hiresw2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresw2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015041012
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="00 03 06 09 12 13 14 15 16 17 18"
hours="00 01 02 03 06 09 12 21 24 27 30 33 36" 
hours="03 06 09"
for fhr in $hours; do

#fmdl1=/com/nawips/prod/hiresw.${ymd}/hiresw_eastarw_${ymdh}f0${fhr}
#fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_eastnmm_${ymdh}f0${fhr}

fmdl1=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl2=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}

areas="1"
for region in $areas; do
if [ $region -eq 1 ]
then
garea="md+"
proj="lcc/25.;-75.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hiresw2mt${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ARW  2-M TMPF 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.4/0.8;.03/2 
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = b 
 CLEAR    = n
 TITLE    = 1//~  NMMB  2-M TMPF 
 CLRBAR   = 0 
r

ex
EOF

done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
