#!/bin/sh
echo 'into'
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hires24pcp
rm /stmpp1/Geoffrey.Manikin/meg/hires24pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/hires24pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013121112
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Wed

hours="36"

for fhr in $hours; do

fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/namfirewxnest_${ymdh}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl4=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}

areas="1 2 3 4 5 6"
areas="7"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="36.;-84.;47.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="24.5;-92.;37.5;-74."
proj="lcc/25.;-85.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="38.;-110.;50.;-92."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="26.;-109.;40.;-91."
proj="lcc/25.;-99.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="33.9;-111.4;42.9;-98."
proj="lcc/25.;-105.;25./2;2;1;1"
elif [ $region -eq 7 ]
then
proj="lcc/25;-80;25;/1;1;1;1"
garea="43.;-77.9;45.;-74.1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p36i 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hires36pcp${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ARW HIRESW 36-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = .01;.1;.25;.5;1;1.5;2;3;4;5;6;8;10;12
 FINT     = .01;.1;.25;.5;0.75;1.;1.25;1.5;1.75;2;2.5;3
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  FIRE WX NEST  36-HR TOT PCP 
 CLRBAR   = 1/H/UL/.01;0.98/2.0;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  4KM NAM  36-HR TOT PCP 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  NAM  36-HR TOT PCP 
 CLRBAR   = 0
r

ex
EOF
done
done
gpend

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
