#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/3pcp
rm /stmpp1/Geoffrey.Manikin/meg/3pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/3pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013020412
#ymd=20130204
#dayoweek=Mon
times="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="21 24"
for fhr in $times; do

fhr3=`expr $fhr - 3`
typeset -Z2 fhr3

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = p03i
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 3-HR PCP 
 DEVICE   = GIF|nam_3pcpswem_f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = va 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(swem03,25.4)
 TITLE    = 1/-1/~  NAM 3-HR  SNOW WATER EQUIV 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test2
exit
