#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500z
rm /stmpp1/Geoffrey.Manikin/meg/500z/*
cd /stmpp1/Geoffrey.Manikin/meg/500z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016022312
ymd=20160223
dayoweek=hold2

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="12 18 24 30"
#times="00 03 06 09 12 15 18 21 24 27 30"
for fhr in $times; do

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hiresw.${ymd}/hiresw_arw_${ymdh}f0${fhr}
fmdl2=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hiresw.${ymd}/hiresw_nmmb_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 500
 GVCORD   = pres
# GDPFUN   = avor
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   ARW 500 mb  Z/AVOR
 DEVICE   = GIF|500models_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 GAREA    = 18.;-128.;62.;-58.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
# CLRBAR   = 1/V/UL/.04;0.22/.4;.02/2
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/2
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 WIND     = bk1/0.6/1/122/0.7
# GDPFUN   = wnd
 TYPE     = b
 HILO     = 0
 HLSYM    = 0
 CLEAR    = n
 CLRBAR   = 0
 SCALE    = 0
 SKIP     = /7;7
 FINT     = 0
 FLINE    = 0
 TEXT     = 0
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 500
 GVCORD   = pres
# GDPFUN   = avor
 GDPFUN   = blurk
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  NMMB 500 mb Z/AVOR
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/2
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 WIND     = bk1/0.6/1/122/0.7
# GDPFUN   = wnd
 TYPE     = b
 HILO     = 0
 HLSYM    = 0
 CLEAR    = n
 CLRBAR   = 0
 SCALE    = 0
 FINT     = 0
 FLINE    = 0
 SKIP     = /7;7
 TEXT     = 0
r

ex
EOF

done
gpend

for fhr in $times; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 500models_f0${fhr}.gif ${ymdh}_hiresw500z${fhr}.gif 
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
rm *gif
exit
