#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500w
rm /stmpp1/Geoffrey.Manikin/meg/500w/*
cd /stmpp1/Geoffrey.Manikin/meg/500w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014031606
dayoweek=Sat

ymd=`echo $ymdh | cut -c1-8`
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="00 06 12 24 30 36 48 60"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = knts(sped) 
 CINT     = 0 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 500 WIND SPEED 
 DEVICE   = GIF|500models_f0${fhr}.gif|800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 18.;-118.;46.;-74. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CONTUR   = 0
 SKIP     = 0
 CLRBAR   = 1/V/UL/.08;0.5/1.0;.03/2
 FINT     = 10;20;30;40;50;60;70;80;90 
 FLINE    = 0;30;28;25;23;21;5;10;17;11;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 
 WIND     = bK1/0.7/1/122
 GDPFUN   = kntv(wnd)
 SKIP     = /18;18
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl2
 PANEL    = b
 TITLE    = 1/-1/~   GFS 500 WIND SPEED
 GDPFUN   = knts(sped)
 TYPE     = f
 CLRBAR   = 0
r

 GDPFUN   = kntv(wnd) 
 TYPE     = b
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 500
 GVCORD   = pres
 GFUNC    = knts(sub(sped+2,sped))
 CINT     = 10
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 500 WIND SPEED (KT)   NAM - GFS
 DEVICE   = GIF|500diff_f0${fhr}.gif|600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.92/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -50;-40;-30;-20;-10;10;20;30;40;50
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
for fhr in $times; do
$CONV/convert -crop 0x0 500models_f0${fhr}.gif 5001.gif
$CONV/convert -crop 0x0 500diff_f0${fhr}.gif 5002.gif
$CONV/montage -geometry 800x850 5001.gif 5002.gif  ${cyc}500w$fhr.gif
done

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
exit
