#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresuphl3
rm /stmpp1/Geoffrey.Manikin/meg/hiresuphl3/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresuphl3
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013111612
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Sat

hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
hours="27 30 33 36"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/hiresw.${ymd}/hiresw_eastarw_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/hiresw.${ymd}/hiresw_eastnmm_${ymdh}f0${fhr}
fmdl4=/meso/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswarw_${ymdh}
fmdl3=/meso/save/Geoffrey.Manikin/meg/hireswnmm_${ymdh}

areas="1 2 3 4 5 6 7"
areas="8"

for region in $areas; do
if [ $region -eq 1 ]
then
garea="36.;-84.;46.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="24.5;-92.;37.5;-74."
proj="lcc/25.;-85.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="38.;-110.;50.;-92."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="26.;-108.;40.;-90."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="22.;-124.;50.;-64."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 7 ]
then
garea="32.;-126.;43.;-110."
proj="lcc/25.;-115.;25./2;2;1;1"
elif [ $region -eq 8 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = uphl 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hires1uphl${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  4 KM NAM  2-5 KM UPDRAFT HELICITY 
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 2;5;10;25;50;75;100;125;150
 FLINE    = 0;21;23;4;26;2;15;16;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW ARW  2-5 KM UPDRAFT HELICITY 
 CLRBAR   = 1/H/UL/.46;0.94/1.1;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  HIRESW NMM  2-5 KM UPDRAFT HELICITY 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  4 KM NAMX 2-5 KM UPDRAFT HELICITY  
 CLRBAR   = 0
r

ex
EOF

done
done
gpend

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
