#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hires24pcp
rm /stmpp1/Geoffrey.Manikin/meg/hires24pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/hires24pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2014042900
ymd=`echo $ymdh | cut -c1-8`
#dayoweek=Tue

if [ $cyc -eq 00 ]; then
 hours="36"
elif [ $cyc -eq 06 ]; then
 hours="30"
elif [ $cyc -eq 12 ]; then
 hours="24 48"
else
 hours="42"
fi

for fhr in $hours; do

fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswnmmpcp_$ymdh
fmdl3=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl4=/meso/save/Geoffrey.Manikin/meg/namxnestpcp_${ymdh}

areas="1 2 3 4 5 6"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="36.;-84.;47.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="24.5;-92.;37.5;-74."
proj="lcc/25.;-85.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="38.;-110.;50.;-92."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="26.;-109.;40.;-91."
proj="lcc/25.;-99.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="33.9;-111.4;42.9;-98."
proj="lcc/25.;-105.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p24i 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${cyc}hires24pcp${region}_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  HIRESW ARW  24-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = .01;.1;.25;.5;1;1.5;2;3;4;5;6;8;10;12
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW NMM  24-HR TOT PCP 
 CLRBAR   = 1/H/UL/.01;0.98/2.0;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr 
 TITLE    = 1//~  NAM CONUS NEST  24-HR TOT PCP 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  NAMX CONUS NEST  24-HR TOT PCP 
 CLRBAR   = 0
r

ex
EOF
done
done

for region in $areas; do

if [ $region -eq 1 ]
then
garea="36.;-84.;47.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="24.5;-92.;37.5;-74."
proj="lcc/25.;-85.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="38.;-110.;50.;-92."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="26.;-109.;40.;-91."
proj="lcc/25.;-99.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="37.;-95.;47.;-80."
proj="lcc/25.;-90.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="33.9;-111.4;42.9;-98."
proj="lcc/25.;-105.;25./2;2;1;1"
fi

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f48 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p48i
 CINT     = 5
 LINE     = 0
 DEVICE   = GIF|${cyc}hires48pcp${region}.gif | 800;850
 PROJ     = $proj
 GAREA    = $garea
 TITLE    = 1//~  HIRESW ARW  24-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 TEXT     = 0.8/11/2
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;7.5;10;12.5;15
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  HIRESW NMM  48-HR TOT PCP 
 CLRBAR   = 1/H/UL/.01;0.98/2.0;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = lr
 TITLE    = 1//~  NAM CONUS NEST  48-HR TOT PCP
 CLRBAR   = 0
r

 GDFILE   = $fmdl4
 PANEL    = ur
 TITLE    = 1//~  NAMX CONUS NEST   48-HR TOT PCP 
 CLRBAR   = 0
r

EOF
done
gpend

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv *gif /stmpp1/Geoffrey.Manikin/meg/hold/.
exit
