#!/bin/sh
echo 'into'

ymdh=2022120100
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/sst/
cd /lfs/h2/emc/stmp/geoffrey.manikin/sst/
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

times="00"
for fhr in $times; do

fmdl1=/lfs/h1/ops/prod/com/gfs/v16.3/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymd}${cyc}f0${fhr}
fmdl2=/lfs/h1/ops/prod/com/nam/v4.2/nam.${ymd}/gempak/nam20_${ymd}${cyc}f0${fhr}
echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = tmpf 
 CINT     = 5
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/ ${fhr}-HR OPS GFSv16.3 SKIN TEMP 
 DEVICE   = GIF|compareskingfsnam_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-74.;25./2;2;1;1
 GAREA    = nc+
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.05;0.5/1.0;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
 FINT     = 29;32;35;38;41;44;47;50;53;56;59;62;65;68;71;74;77;80;83;85;88
 FLINE    = 0;11;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 PANEL    = b
 TITLE    = 1/-1/ ${fhr}-hr OPS NAM SKIN TEMP
 CLRBAR   = 0
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test/.
exit
