#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dew
rm /stmpp1/Geoffrey.Manikin/meg/2dew/*
cd /stmpp1/Geoffrey.Manikin/meg/2dew
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018040906
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="27 30 33 36"
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
times="00 06"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/hold/fv3_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 5 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 2-M  DWPT 
 DEVICE   = GIF|2dewmodels_f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = ny+
# \$MAPFIL = county
  PROJ     = lcc/25;-108;25;/1;1;1;1
 GAREA    = 33.;-108.;51.;-84. 
 GAREA    = 18.;-122.;40.;-94. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -76;-68;-60;-52;-44;-36;-28;-20;-12;-4;4;12;20;28;36;44;52;60;68;76
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  FV3  2-M  DWPT 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
 TYPE     = f
 LINE     = 1
 CINT     = 4
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(dwpf+2,dwpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M DWPT (F)  GFS - FV3 
 DEVICE   = GIF|2dewdiff_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.95/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $times; do

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2dewmodels_f0${fhr}.gif 2dew1.gif
$CONV/convert -crop 0x0 2dewdiff_f0${fhr}.gif 2dew2.gif
$CONV/montage -geometry 800x850 2dew1.gif 2dew2.gif ${ymdh}_2dewfv3zz${fhr}.gif
done

scp ${ymdh}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
