#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2015031606
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
ymdh2=2015031612
ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
dayoweek=hold2

fhr1=06
fhr2=00

fmdl1=/com/nawips/prod/gfs.${ymd1}/gfs_0p25_${ymdh1}f0${fhr1}
fmdl2=/com/nawips/prod/gfs.${ymd2}/gfs_0p25_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd1}/nam20_${ymdh1}f0${fhr1}
fmdl4=/com/nawips/prod/nam.${ymd2}/nam20_${ymdh2}f0${fhr2}

echo $fmdl1
echo $fmdl3

    gdplot2 << EOF
 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f$fhr1
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = sub(tmpf^${ymd2}/${cyc2}f0${fhr2}+2,tmpf) 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 2-M  TEMP 
 DEVICE   = GIF|2mt2times_f${fhr1}f${fhr2}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ks- 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.6/1.2;.03/2 
 CONTUR   = 0
 SKIP     = 0
 TYPE     = f
 LUTFIL   =
 STNPLT   =
 FINT     = -10;-8;-6;-4;-2;2;4;6;8;10
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
r

 GDFILE   = $fmdl3 + $fmdl4
 CLEAR    = n
 PANEL    = b
 TITLE    = 1/-1/~   NAM 2-M  TEMP
 CLRBAR   = 0
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today/.

exit
