#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/3hirespcp
rm /stmpp1/Geoffrey.Manikin/meg/3hirespcp/*
cd /stmpp1/Geoffrey.Manikin/meg/3hirespcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014092400
ymd=20140924
dayoweek=hold

hours="03 06 09 12 15"
hours="24"
for fhr in $hours; do

fhr3=`expr $fhr - 3`
typeset -Z2 fhr3

fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswnmmbpcp_$ymdh
fmdl3=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
cp /com/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00 fmdl4
cp /com/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr3}00 fmdl4a

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p03i
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   HIRESW ARW 3-HR TOTAL PCP
 DEVICE   = GIF|4pan3pcp_${ymdh}f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 21.;-121.;51.;-65.
 GAREA    = 33.;-104.;43.;-90. 
 GAREA    = 29.;-84.;41.;-66. 
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  HIRESW NMMB 3-HR TOTAL PCP
 PANEL    = ll 
 CLRBAR   = 1/H/UL/0.1;0.95/1.8;.03/1 
 CLEAR    = n
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~  4 KM NAM 3-HR TOTAL PCP
 PANEL    = ur 
 CLRBAR   = 0
r

 GDFILE   = fmdl4a + fmdl4
 GDPFUN   = sub(p${fhr}i^${ymd}/${cyc}f0${fhr}00+2,p${fhr3}i^${ymd}/${cyc}f0${fhr3}00)
 TITLE    = 1/-1/~  HRRR 3-HR TOTAL PCP
 PANEL    = lr 
 CLRBAR   = 0
 GDATTIM  = f${fhr}00
r

ex
EOF
done
gpend

#rm fmdl3*
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
