#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak


mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2019122200
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21"
hours="12 15 18"
#hours="03 04 05 06 07 08 09 10 11 12 13 14"
for fhr in $hours; do

cp /gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam32_${ymdh}f0${fhr} fmdl1
cp /gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam_conusnest_${ymdh}f0${fhr} fmdl2

    gdplot2 << EOF
 GDFILE   = fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nam2mt_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = 32.;-95.;46.;-69. 
 GAREA    = 36.;-82.;44.;-68.
 TITLE    = 1//~  NAM 2-M TMPF 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.1;0.4/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105
 FINT     = 14;17;20;23;26;29;32;35;38;41;44;47;50;53;56;59;62;65;68
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 FINT     = 12;15;18;21;24;27;30;33;36;39;42;45;48;51;54;57;60;63;66;69;72
# FINT     = 48;51;54;57;60;63;66;69;72;75;78;81;84;87;90;93;96;99;102;105;108
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32

 TYPE     = f 
r

 CINT     = 1/32/32
 TYPE     = c
 CLEAR    = n
 LINE     = 1/1/4/0
r

 GDFILE   = fmdl2
 CLEAR    = n
 TYPE     = f
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1//~  NAM3 2-M TMPF
r

 CINT     = 1/32/32
 TYPE     = c
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
