#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2013022012
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stn=dca
stnm=724050

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/snd
rm /stmpp1/Geoffrey.Manikin/meg/snd/*
cd /stmpp1/Geoffrey.Manikin/meg/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Sun

fmdl1=/com/nawips/prod/nam.${ymd}/nam_${ymdh}.snd
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs_${ymdh}.snd

times="54"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/nam.${ymd}/nam_${ymdh}.snd

validtime="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $fhr -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

    gdprof << EOF
 GPOINT   = $stn 
 GDATTIM  = LAST
 GVCORD   = pres
 GFUNC    = dwpc 
 GVECT    = WND
 GDFILE   = $fmdl1 
 LINE     = 2/1/7 
 MARKER   = 0
 BORDER   = 1//2
 PTYPE    = skewt
 SCALE    = 0
 YAXIS    = 1050/400/50/1;1;1
 XAXIS    = -35/25/10/;1
 WIND     = 0 
 REFVEC   =
 WINPOS   = 1
 FILTER   = YES
 TITLE    = 1// DWPC  80grid-red  40grid-green  bufr-blue
 PANEL    = 0
 CLEAR    = YES
 TEXT     = 1
 DEVICE   = gif|gdprof.gif | 800;850
 OUTPUT   = t
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 GDFILE   = $fmdl2
 CLEAR    = n
 LINE     = 3/1/7
 TITLE    = 0
r

ex
EOF

    snprof << EOF
 SNFILE   = $fmdl3
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = dwpc 
 LINE     = 4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = 0 
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 0
 DEVICE   = gif|gdprof.gif | 800;850
 YAXIS    = 1050/400/50/1;1;1
 XAXIS    = -35/25/10/;1
 FILTER   = n
 CLEAR    = n
 PANEL    = 0
 TEXT     = 1.0 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

ex
EOF

done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/test2
mput *gif
bye
EOF

exit
