#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500z
rm /stmpp1/Geoffrey.Manikin/meg/500z/*
cd /stmpp1/Geoffrey.Manikin/meg/500z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017100412
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
#times="00 06 12 18 21 24 27 30 33 36 42 48 54 60"
times="00 03 06 09 12 15 18 21 24 27 30"
times="03"
for fhr in $times; do

fmdl1=/com2/nawips/prod/nam.${ymd}/nam_priconest_${ymdh}f0${fhr}
fmdl1=/ptmpp1/Geoffrey.Manikin/hold/nam_priconest_${ymdh}f0${fhr}
fmdl2=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = hght 
 CINT     = 100 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM3 SFC HGT 
 DEVICE   = GIF|sfcz2_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-68;25;/1;1;1;1
# GAREA    = 24.;-155.;68.;-75.
 PROJ     = 
 GAREA    = 17.;-68.;19.2;-64.4
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 CLRBAR   = 1/V/UL/.04;0.4/.8;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 25;100;250;500;750;1000;1250
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM SFC HGT 
 SATFIL   =
 RADFIL   =
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
