#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2013103009
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Wed

mkdir /stmpp1/Geoffrey.Manikin/pbl
rm /stmpp1/Geoffrey.Manikin/pbl/*
cd /stmpp1/Geoffrey.Manikin/pbl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl1=/ptmpp1p1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymdh}f012

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = zpbl 
 CINT     = 0
 LINE     = 0 
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~   RAP  THETA-V PBL 
 DEVICE   = GIF|rappbl_${ymdh}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-96.;25./2;2;1;1
 GAREA    = 23.;-124.;51.;-68. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.07;.25/.7;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500
 FLINE    = 2;17;10;5;21;23;26;27;29;30;0 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GLEVEL   = 0
 GVCORD   = pblx
 GDPFUN   = hght
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1//~   RAP  RICH NO PBL 
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
