#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold2

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/type
rm /stmpp1/Geoffrey.Manikin/meg/type/*
cd /stmpp1/Geoffrey.Manikin/meg/type
cp /meso/save/Geoffrey.Manikin/meg/coltbl.xwp .

times="03"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymd}${cyc}f0${fhr}
fmdl2=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymd}${cyc}f0${fhr}00
fmdl1=/ptmpd1/Geoffrey.Manikin/hold3/nam_conusnest_${ymd}${cyc}f0${fhr}
#fmdl2=/ptmpd1/Geoffrey.Manikin/hold4/hrrr_${ymd}${cyc}f0${fhr}00
echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = popz 
 CINT     = 10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparenesthrrrfrz_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = de 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.1;0.4/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;30;50;70;80;90 
 FLINE    = 0;30;27;22;5;10;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR  NAM4  % FRZ PCP 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 17/-1/ FCST MADE ${cyc}Z  ${month}/$day  
 TEXT     = 0.8/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR HRRR  % FRZ PCP 
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDPFUN   = frzpc 
 TITLE    = 0
 TITLE    = 0
r

ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
