#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold4

mkdir /stmpp1/Geoffrey.Manikin/refc
rm /stmpp1/Geoffrey.Manikin/refc/*
cd /stmpp1/Geoffrey.Manikin/refc
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="12"
for fhr in $times; do

fmdl1=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymd}${cyc}f0${fhr}
fmdl2=/com2/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymd}${cyc}f0${fhr}
echo $fmdl1
echo $fmdl2

    gdcntr << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = refc 
 CINT     = 5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparehireswrefc_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-79.;25./2;2;1;1
 GAREA    = ri+ 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;.45/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65 
 FLINE    = 0;24;4;26;23;22;21;20;5;10;17;2;15;29 
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 100/100/100
 LINE     = 1/1/2/0
 CTYPE    = c
 CLEAR    = n
r

 TITLE    = 1/1/ ${fhr}-HR ARW COMPOSITE REFLECTIVITY
 TEXT     = 1.2/11/2
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 TYPE     = f/c
 CLRBAR   = 0
r

 TITLE    = 29/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 GDFILE   = $fmdl2
 PANEL    = 0;0;1;.49
 CINT     = 5
 TITLE    = 1/-1/ ${fhr}-HR NMMB COMPOSITE REFLECTIVITY 
 PANEL    = 0;0;1;.49
 TEXT     = 1.2/11/2/SW
 CTYPE    = f
r

ex
EOF

gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/. 
echo abouttoexitrefc
exit
