#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg/slmm
rm /stmpp1/Geoffrey.Manikin/meg/slmm/*
cd /stmpp1/Geoffrey.Manikin/meg/slmm
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20120705
cyc=12
dayoweek=Thu

times="60"
for fhr in $times; do

fmdl1=/ptmpp1p1/Geoffrey.Manikin/gfs/nam40_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1p1/Geoffrey.Manikin/gfs/gfsflux_${ymd}${cyc}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 0:200 
 GVCORD   = dpth 
 GDPFUN   = slmm 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ OPS NAM TOTAL SOIL MOISTURE
 DEVICE   = GIF|${cyc}slmmz_${ymd}${cyc}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1 
 GAREA    = md- 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;200;300;400;500;600;700;800 
 FLINE    = 0;18;16;17;10;5;20;21;22;23;27;4
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1/-1/~ OPS GFS TOTAL SOIL MOISTURE
 CLRBAR   = 1/H/UL/.08;0.96/.8;.02/2 
 PANEL    = b
r

ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0:200
 GVCORD   = dpth 
 GFUNC    = sub(slmm+2,slmm)
 CINT     = 2
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 0:10 SLMM   NAM - GFS
 DEVICE   = GIF|${cyc}slmmdiffz_f0${fhr}.gif | 600;650
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1
 GAREA    = in- 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -400;-300;-200;-100;100;200;300;400 
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif 
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

exit
