#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
storm="sandy18l"

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slp
rm /stmpp1/Geoffrey.Manikin/meg/slp/*
cd /stmpp1/Geoffrey.Manikin/meg/slp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012102900
ymd=20121029
dayoweek=Mon

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f000
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f000
fmdl3=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000
fmdl4=/com/nawips/prod/hwrf.${ymd}/${storm}/hwrfc_${ymdh}f000_${storm}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 0 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  RED-nam  BLUE-gfs  OR-hwrf  GREEN-obs 
 DEVICE   = GIF|slpplot_f000.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 28.;-76.;36.;-66. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.9/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 0 
 HILO     = ;4/;S13#/;920-1000/5/2;2/yes 
r

 GDFILE   = $fmdl3
 CLEAR    = n
 HILO     = ;17/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl4
 HILO     = ;21/;S13#/;920-1000/5/2;2/yes
r

ex
EOF
gpend

/usrx/local/im_beta/bin/convert -crop 0x0 slpplot_f000.gif initslp_${ymdh}.gif

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput in*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput in*gif
bye
EOF

exit
