#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dew
rm /stmpp1/Geoffrey.Manikin/meg/2dew/*
cd /stmpp1/Geoffrey.Manikin/meg/2dew
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015071115
ymdhv=2015071500
fhr=81
ymd=`echo $ymdh | cut -c1-8`
ymdv=`echo $ymdhv | cut -c1-8`
dayoweek=hold

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/sref.${ymd}/sref_arwp1_${ymdh}f0${fhr}
fmdl2=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/rap.${ymdv}/rap13_${ymdhv}f000

echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREFX ${fhr}-HR 2-M DWPF 
 DEVICE   = GIF|sref2mdew_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ia 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80;84;88;92
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f00
 TITLE    = 1/-1/~  RAP ANL 2-MDWPF 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
gpend

#mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
