#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2013042922
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=745600
#stnm=744550
stnm=724400
fhr1=00
fhr2=01

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/snd
rm /stmpp1/Geoffrey.Manikin/meg/snd/*
cd /stmpp1/Geoffrey.Manikin/meg/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Mon

fmdl1=/com/nawips/prod/rap.${ymd}/rap_${ymdh}.snd

validtime1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $fhr1 -1 x`"
dattim1=`echo $validtime1 | cut -c5-11`

validtime2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $fhr2 -1 x`"
dattim2=`echo $validtime2 | cut -c5-11`

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $dattim1
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  RAP 
 DEVICE   = gif|${ymdh}snd${stnm}_${fhr1}${fhr2}.gif | 800;850
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -20/35/5/;1
 FILTER   = n 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 DATTIM   = $dattim2
 CLEAR    = n
 TITLE    = 1// RAP 
 PANEL    = b
r

ex
EOF
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
