#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2019121612
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold10

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="27 30 33 36"
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
times="57 60 63 78 81 84"
times="33 36 39 54 57 60 63"
times="09 12 15 33 34 35 36 39"
times="06 07 08 09 10 11 12 13 14 15"
times="12 18 24 30"
for fhr in $times; do

cp /gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak/nam32_${ymdh}f0${fhr} fmdl1
cp /gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/gempak/gfs_0p25_${ymdh}f0${fhr} fmdl2

dattim="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $fhr -1 x`"
validtime=`echo $dattim | cut -c1-11`
vymd=`echo $validtime | cut -c1-8`
vcyc=`echo $validtime | cut -c10-11`

cp /gpfs/dell2/nco/ops/com/rtma/prod/rtma2p5.${vymd}/gempak/rtma2p5_${vymd}${vcyc}f000 fmdl3

    gdplot2 << EOF
 GDFILE   = fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 3 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 2-M  TEMP 
 DEVICE   = GIF|namgfs2mt_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 34.;-85;44.;-69.
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.9/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.45;0.95/1.3;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FINT     = 15;18;21;24;27;30;33;36;39;42;45;48;51;54;57;60;63;66;69;72
# FINT     = 48;51;54;57;60;63;66;69;72;75;78;81;84;87;90;93;96;99;102;105;108
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdl2
 TITLE    = 1/-1/~  GFS 2-M TEMP 
 PANEL    = ur 
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = fmdl3
 GDATTIM  = last 
 TITLE    = 1/-1/~  RTMA 2-M TEMP
 PANEL    = lr 
r

 GDFILE   = fmdl2 + fmdl1
 GDATTIM  = f${fhr}
 GDPFUN   = sub(tmpf+2,tmpf)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M TEMP (F)   NAM - GFS
 SATFIL   =
 RADFIL   =
 PANEL    = ll 
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.96/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
# FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FINT     = -15;-12;-9;-6;-3;3;6;9;12;15
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

#for fhr in $times; do

#CONV=/usrx/local/ImageMagick/6.8.3-3/bin
#$CONV/convert -crop 0x0 2mtmodels_f0${fhr}.gif 2mt1.gif
#$CONV/convert -crop 0x0 2mtdiff_f0${fhr}.gif 2mt2.gif
#$CONV/montage -geometry 800x850 2mt1.gif 2mt2.gif ${ymdh}_2mtzmw${fhr}.gif
#done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
