#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
cd /stmpp1/Geoffrey.Manikin/meg

/meso/save/Geoffrey.Manikin/meg/compare_500_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_850t_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_2dew_medr ${cyc} &
wait

echo beforeexit
exit


