#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/make_24pcptrends_nam ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_24pcptrends_gfs ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_24pcptrends_nam_diff ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_24pcptrends_gfs_diff ${cyc} &
/meso/save/Geoffrey.Manikin/meg/verify_500_models ${cyc} &
wait

echo beforeexit14
exit


