#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_2dew ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_2mt ${cyc} &
wait

echo beforeexit3
exit


