#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
cd /stmpp1/Geoffrey.Manikin/meg

/meso/save/Geoffrey.Manikin/meg/compare_2mt_rap ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_2dew_rap ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_sfccape_rap ${cyc} &
wait

echo beforeexit17
exit


