#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/make_500trends_gfs_diff_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_slptrends_gfs_diff_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_24pcptrends_gfs_medr ${cyc} &
wait

echo beforeexit
exit


