#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg
/meso/save/Geoffrey.Manikin/meg/compare_swem ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_type ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_250w ${cyc} &
wait

echo beforeexit6
exit


