#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_slp_gfsgefs_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_slptrends_gefs_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_cape_gfsx_medr ${cyc} &
wait

echo beforeexit
exit


