#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_slp_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_24pcp_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_2mt_medr ${cyc} &
wait

echo beforeexit
exit


