#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
cd /stmpp1/Geoffrey.Manikin/meg

/meso/save/Geoffrey.Manikin/meg/compare_500 ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_850t ${cyc} &
wait

echo beforeexit1
exit


