#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/make_slptrends_nam_diff ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_slptrends_gfs_diff ${cyc} &
wait

echo beforeexit13
exit


