#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg
/meso/save/Geoffrey.Manikin/meg/compare_24pcp_sref ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_500_sref ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_slp_sref ${cyc} &
wait

echo beforeexit10
exit


