#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_2mt_gfsx ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_2dew_gfsx ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_84pcp_gfsx ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_500_gfsx ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_slp_gfsx ${cyc} &
wait

echo beforeexit18
exit
