#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/make_500trends_nam ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_500trends_gfs ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_500trends_diff ${cyc} &
wait

echo beforeexit8
exit


