#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_850w ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_slp ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_pw ${cyc} &
wait

echo beforeexit2
exit


