#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
cd /stmpp1/Geoffrey.Manikin/meg

/meso/save/Geoffrey.Manikin/meg/compare_24pcp_srefx ${cyc} &
/meso/save/Geoffrey.Manikin/meg/make_srefxprob_24pcp ${cyc} &
wait

echo beforeexit
exit
