#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

cd /stmpp1/Geoffrey.Manikin/meg/

/meso/save/Geoffrey.Manikin/meg/compare_2mt_gfsx_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_84pcp_gfsx_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_500_gfsx_medr ${cyc} &
/meso/save/Geoffrey.Manikin/meg/compare_slp_gfsx_medr ${cyc} &
wait

echo beforeexit
exit


