#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcptrecmwf
rm /stmpp1/Geoffrey.Manikin/meg/6pcptrecmwf/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcptrecmwf
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymd1=20151002
ymdh1=${ymd1}12
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold3
hours="18"

cyc1=12
ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} ${fhr1} -1`"
fhr2=`expr $fhr1 + 12`
typeset -Z2 fhr2 fhr3 fhr4

fhrminus6=`expr $fhr1 - 6`
fhr2minus6=`expr $fhr2 - 6`
typeset -Z2 fhrminus6 fhr2minus6 

fhrminus6=`expr $fhr1 - 6`
fhr2minus6=`expr $fhr2 - 6`
typeset -Z2 fhrminus6 fhr2minus6

fmdl1=/com/nawips/prod/ecmwf.${ymd1}/ecmwf_hr_${ymdh1}f0${fhr1}
cp /com/nawips/prod/ecmwf.${ymd1}/ecmwf_hr_${ymdh1}f0${fhrminus6} file1a
fmdl2=/com/nawips/prod/ecmwf.${ymd2}/ecmwf_hr_${ymdh2}f0${fhr2}
cp /com/nawips/prod/ecmwf.${ymd2}/ecmwf_hr_${ymdh2}f0${fhr2minus6} file2a
fmdl3=/com/nawips/prod/ecmwf.${ymd3}/ecmwf_hr_${ymdh3}f0${fhr3}

    gdplot2 << EOF
 GDFILE   = file1a + $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sub(pxxm^${ymd1}/${cyc1}f$fhr1+2,pxxm^${ymd1}/${cyc1}f${fhrminus6}),1000),25.4)
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  ECMWF 6-HR PCP  ${ymd1} ${cyc1}z  F${fhr1}
 DEVICE   = GIF|ecmwf6pcptr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-73;25;/1;1;1;1
 GAREA    = 18.;-84.;30.;-66.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.92/1.5;.03/1
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
  FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;4.;5.;6.;7.
 FLINE    = 0;21;22;23;25;4;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl1
 GDPFUN   = pmsl
 CINT     = 4
 CLEAR    = n
 LINE     = 1/1/1/0
 CLRBAR   = 0
 TITLE    = 0
 TYPE     = c
r

 GDFILE   = file2a + $fmdl2 
 GDATTIM  = f${fhr2}
 TITLE    = 1//  ECMWF 6-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = quo(mul(sub(pxxm^${ymd2}/${cyc2}f$fhr2+2,pxxm^${ymd2}/${cyc2}f${fhr2minus6}),1000),25.4)
 CLRBAR   = 0
 TYPE     = f
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
