#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcptrgfs
rm /stmpp1/Geoffrey.Manikin/meg/6pcptrgfs/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcptrgfs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2017020318
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold8

hours="144"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z3 fhr1 fhr2 fhr3 fhr4

fmdl1=/com2/nawips/prod/gfs.${ymd1}/gfs_0p25_${ymdh}f${fhr1}
fmdl2=/com2/nawips/prod/gfs.${ymd2}/gfs_0p25_${ymdh2}f${fhr2}
fmdl3=/com2/nawips/prod/gfs.${ymd3}/gfs_0p25_${ymdh3}f${fhr3}
fmdl4=/com2/nawips/prod/gfs.${ymd4}/gfs_0p25_${ymdh4}f${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p06i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  GFS 6-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|gfs6pcptr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-76;25;/1;1;1;1
 GAREA    = 31.;-85.;47.;-61. 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.92/1.5;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 GDPFUN   = p06i
 TITLE    = 1//  GFS 6-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
 TYPE     = f
r

 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3 
 GDPFUN   = p06i
 GDATTIM  = f${fhr3}
 TITLE    = 1//  GFS 6-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
 TYPE     = f
r

 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 GDPFUN   = p06i
 TITLE    = 1//  GFS 6-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
 TYPE     = f
r

 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

ex
EOF
gpend
done
#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
