#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefcx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20180429
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold10

hours="33 34 35 36"
for fhr1 in $hours; do

cyc1=12
cyc2=00

fhr2=`expr $fhr1 + 12`

typeset -Z2 fhr1 fhr2
export DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
export DAPATH=/gpfs/hps/nco/ops/com/nawips/prod
fmdl1=${DAPATH}/hiresw.${ymd}/hiresw_conusarw_${ymd}12f0${fhr1}
fmdl2=${DAPATH}/hiresw.${ymd}/hiresw_conusarw_${ymd}00f0${fhr2}
fmdl3=${DAPATH}/hiresw.${ymd}/hiresw_conusnmmb_${ymd}12f0${fhr1}
fmdl4=${DAPATH}/hiresw.${ymd}/hiresw_conusnmmb_${ymd}00f0${fhr2}
fmdl5=${DAPATH}/hiresw.${ymd}/hiresw_conusmem2arw_${ymd}12f0${fhr1}
fmdl6=${DAPATH}/hiresw.${ymd}/hiresw_conusmem2arw_${ymd}00f0${fhr2}
echo $fmdl1
echo $fmdl2

garea="40.;-102.;50.;-82."
garea="24.;-104.;34.;-92."
garea="34.;-101.;43.;-89"
garea="28.;-87.;37.;-75."
garea="ks+"
garea="32.;-105;41;-93"
#garea="34.;-105;43.;-93."
proj="lcc/25.;-98.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hireswrefc_${ymd}f${fhr1}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  12z ARW   REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = ur 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 PANEL    = lr 
 CLEAR    = n
 TITLE    = 1//~  00z ARW   REFC 
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr1
 PANEL    = ul 
 TITLE    = 1//~  12z NMMB   REFC 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr2
 PANEL    = ll
 TITLE    = 1//~  00z NMMB  REFC 
 CLRBAR   = 0
r

 GDFILE   = $fmdl5
 GDATTIM  = f$fhr1
 PANEL    = ul 
 DEVICE   = GIF|${ymd}${cyc}hiresw2refc_${ymd}f${fhr1}.gif | 800;850
 TITLE    = 1//~  12z ARW2   REFC
 CLEAR    = y
 CLRBAR   = 0
r

 GDFILE   = $fmdl6
 GDATTIM  = f$fhr2
 PANEL    = ll
 TITLE    = 1//~  00z ARW2  REFC
 CLEAR    = n
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
