#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/circ
rm /stmp/Geoffrey.Manikin/meg/circ/*
cd /stmp/Geoffrey.Manikin/meg/circ
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014021200
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
dayoweek=Tue

DAPATH1=/com/nawips/prod/nam.${ymd}
DAPATH2=/com/nawips/prod/gfs.${ymd}

times="24 27 30 33 36"
for fhr in $times; do

fmdl1=${DAPATH1}/nam40_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/gfs40_${ymdh}f0${fhr}
echo $fmdl1

    gdcross << EOF
 CXSTNS   =  39.3;-81.4 > 38.5;-70.7
 GDATTIM  =  f${fhr}
 GVCORD   =  pres
 GFUNC    =  tmpc
 GVECT    =  circ(wnd;omeg) 
 GDFILE   =  $fmdl1 
# WIND     =  bm6//2
 WIND     =  am6//2//.75
# REFVEC   =  10
 REFVEC   =  5;.05;.2
 PTYPE    =  log
 YAXIS    =  
 CINT     =
 SCALE    =  0 
 LINE     =  1/1/1
 BORDER   =  1
 TITLE    =  1
 CLEAR    =  yes
 DEVICE   =  GIF|namcross_${ymdh}f0${fhr}.gif|850;950
 TEXT     =  1
 PANEL    =  0
 CLRBAR   =  1/h/cc/.5;.03/.6;.01
 CONTUR   =  3
 FINT     =
 FLINE    =  30-8-2
 CTYPE    =  c/f
r

 GDFILE   =  $fmdl2
 CLEAR    =  yes
 DEVICE   =  GIF|gfscross_${ymdh}f0${fhr}.gif|850;950
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit

