#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/24pcptrsref
rm /stmpp1/Geoffrey.Manikin/meg/24pcptrsref/*
cd /stmpp1/Geoffrey.Manikin/meg/24pcptrsref
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh1=2016012121
ymd1=`echo $ymdh1 | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold4

if [ $cyc -eq 00 ]; then
 hours="24 39 63"
elif [ $cyc -eq 06 ]; then
 hours="33 57 81"
elif [ $cyc -eq 12 ]; then
 hours="27 51 75"
else
 hours="45 69"
fi

hours="63"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
fhr1a=`expr $fhr1 - 24`
fhr2a=`expr $fhr2 - 24`
fhr3a=`expr $fhr3 - 24`
fhr4a=`expr $fhr4 - 24`
typeset -Z2 fhr1 fhr2 fhr3 fhr4 fhr1a fhr2a fhr3a fhr4a

fmdl1=/com2/nawips/prod/sref.${ymd1}/sref212_${ymdh1}_mean
fmdl2=/com2/nawips/prod/sref.${ymd2}/sref212_${ymdh2}_mean
fmdl3=/com2/nawips/prod/sref.${ymd3}/sref212_${ymdh3}_mean
fmdl4=/com2/nawips/prod/sref.${ymd4}/sref212_${ymdh4}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(add(p24menmw^${ymd1}/${cyc1}00f0${fhr1a},p24menmw),25.4)
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  SREF MEAN 48-HR PCP  $ymd1 ${cyc1}z  F${fhr1}
 DEVICE   = GIF|sref48pcptr1_${ymd1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = de 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.5;0.92/1.5;.02/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/     CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 GDPFUN   = quo(add(p24menmw^${ymd2}/${cyc2}00f0${fhr2a},p24menmw),25.4)
 TITLE    = 1//  SREF MEAN 48-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 GDPFUN   = quo(add(p24menmw^${ymd3}/${cyc3}00f0${fhr3a},p24menmw),25.4)
 TITLE    = 1//  SREF MEAN 48-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4} 
 GDPFUN   = quo(add(p24menmw^${ymd4}/${cyc4}00f0${fhr4a},p24menmw),25.4)
 TITLE    = 1//  SREF MEAN 48-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
