#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcptrnam
rm /stmpp1/Geoffrey.Manikin/meg/6pcptrnam/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcptrnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2014102118
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold
hours="24"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fhrminus3=`expr $fhr1 - 3`
fhr2minus3=`expr $fhr2 - 3`
fhr3minus3=`expr $fhr3 - 3`
fhr4minus3=`expr $fhr4 - 3`
typeset -Z2 fhrminus3 fhr2minus3 fhr3minus3 fhr4minus3

fmdl1=/com/nawips/prod/nam.${ymd1}/nam40_${ymdh}f0${fhr1}
cp /com/nawips/prod/nam.${ymd1}/nam40_${ymdh}f0${fhrminus3} file1a
fmdl2=/com/nawips/prod/nam.${ymd2}/nam40_${ymdh2}f0${fhr2}
cp /com/nawips/prod/nam.${ymd2}/nam40_${ymdh2}f0${fhr2minus3} file2a
fmdl3=/com/nawips/prod/nam.${ymd3}/nam40_${ymdh3}f0${fhr3}
cp /com/nawips/prod/nam.${ymd3}/nam40_${ymdh3}f0${fhr3minus3} file3a
fmdl4=/com/nawips/prod/nam.${ymd4}/nam40_${ymdh4}f0${fhr4}
cp /com/nawips/prod/nam.${ymd4}/nam40_${ymdh4}f0${fhr4minus3} file4a

    gdplot2 << EOF
 GDFILE   = $fmdl1 + file1a
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = add(p03i^${ymd1}/${cyc}f${fhrminus3}+2,p03i^${ymd1}/${cyc}f$fhr1)
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAM 6-HR PCP  ${ymd1} ${cyc}z  F${fhr1}
 DEVICE   = GIF|nam6pcptr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = de 
# GAREA    = 28.;-88.;44.;-66. 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.92/1.5;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2 + file2a
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM 6-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = add(p03i^${ymd2}/${cyc2}f${fhr2minus3}+2,p03i^${ymd2}/${cyc2}f$fhr2) 
 CLRBAR   = 0
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3 + file3a
 GDATTIM  = f${fhr3}
 GDPFUN   = add(p03i^${ymd3}/${cyc3}f${fhr3minus3}+2,p03i^${ymd3}/${cyc3}f$fhr3)
 TITLE    = 1//  NAM 6-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4 + file4a
 GDATTIM  = f${fhr4}
 GDPFUN   = add(p03i^${ymd4}/${cyc4}f${fhr4minus2}+2,p03i^${ymd4}/${cyc4}f$fhr4) 
 TITLE    = 1//  NAM 6-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done
#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
