#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/scape
rm /stmpp1/Geoffrey.Manikin/meg/scape/*
cd /stmpp1/Geoffrey.Manikin/meg/scape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015082412
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold3

hours="09"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs_0p50_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
#fmdl5=/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}0${fhr}00
fmdl5=/ptmpd2/Geoffrey.Manikin/com/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}0${fhr}00
fmdl6=/meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl7=/meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl8=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/gfs.${ymd}/gfs_0p50_${ymdh}f0${fhr}
fmdl9=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE 
 DEVICE   = GIF|${ymdh}scapenamgfs${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = 20.;-98.;46.;-66.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2 
 CONTUR   = 0
 SKIP     = 0
# FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FINT     = 500;1000;1500;2000;2500;3000;3500;4000;4500;5000;5500
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   GFS  SFC-BASED CAPE
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapenamrap${fhr}.gif|750;900
r

 GDFILE   = $fmdl3
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   RAP  SFC-BASED CAPE
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapenamnest${fhr}.gif|750;900
r

 GDFILE   = $fmdl4
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAM4  SFC-BASED CAPE
r

 GDFILE   = $fmdl3
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   RAP  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scaperaphrrr${fhr}.gif|750;900
r

 GDFILE   = $fmdl5
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   HRRR  SFC-BASED CAPE
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapenamx${fhr}.gif|750;900
r

 GDFILE   = $fmdl6
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAMX  SFC-BASED CAPE
r

 GDFILE   = $fmdl4
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM4  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapenam4x${fhr}.gif|750;900
r

 GDFILE   = $fmdl7
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAM4X  SFC-BASED CAPE
r

 GDFILE   = $fmdl2
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   GFS  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapegfsx${fhr}.gif|750;900
r

 GDFILE   = $fmdl8
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   GFSX  SFC-BASED CAPE
r

 GDFILE   = $fmdl5
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   HRRR  SFC-BASED CAPE
 DEVICE   = GIF|${ymdh}scapehrrrx${fhr}.gif|750;900
r

 GDFILE   = $fmdl9
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   HRRRX  SFC-BASED CAPE
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
