#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/wx20mg/plots
mkdir /stmp/wx20mg/plots/rtma
rm /stmp/wx20mg/plots/rtma/*
cd /stmp/wx20mg/plots/rtma
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=2012103000
ymd=`echo $ymdh | cut -c1-8`

ymdh1="`/meso/save/wx20mg/board/advtime $ymdh -1 -1`"
echo $ymdh1

fmdl1=/ptmp/wx20mg/rtma/rtma_${ymdh}f000
fmdl2=/ptmp/wx20mg/rtma/rtma_${ymdh1}f001

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(gust)
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ RTMA ANALYSIS WIND GUST 
 DEVICE   = GF|rtmagust_${ymdh}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 36.;-84.;44.;-60.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.25/.5;.02/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;4;26;22;5;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~ RTMA GUESS WIND GUST 
 CLRBAR   = 0
r

ex
EOF

gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm


ftp -n -v << EOF > /meso/save/wx20mg/casework/dwpfftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/sandy
mput *.gif
bye
EOF

exit
