#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/refc
rm /stmpp1/Geoffrey.Manikin/meg/refc/*
cd /stmpp1/Geoffrey.Manikin/meg/refc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2014112000
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2
counter=11

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namfirewxnest_${ymdh}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 1000 
 GVCORD   = hght 
 GDPFUN   = refd 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nestsrefd_${ymdh}f${counter}.gif | 800;850
 PROJ     = lcc/25.;-80.;25./2;2;1;1
 GAREA    = 40.;-82.7;46.4;-73.3 
 TITLE    = 1//~  4 KM NEST 1 KM REF 
 CLEAR    = y
 SCALE    = 0
 PANEL    = l
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.4;0.82/1.2;.03/1
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//~  FIRE WX NEST 1 KM REF
 PANEL    = r
 CLRBAR   = 0
r

ex
EOF

counter=`expr $counter + 1`
done
gpend
convert -loop 0 -delay 60 nests*gif nestsloop_${ymdh}.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#rm *gif
exit
