#!/bin/ksh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2021021800
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

ymdh1="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh2="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh3="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

fhr1=24
fhr2=30
fhr3=36
fhr4=42
typeset -Z2 fhr1 fhr2 fhr3 fhr4
#DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
DAPATH=/gpfs/dell2/emc/verification/noscrub/Geoffrey.Manikin/hrrrsnow
#DAPATH=/gpfs/hps/nco/ops/com/hrrr/prod/
#fmdl1=${DAPATH}/hrrr.${ymd}/conus/gempak/hrrr_${ymdh}f0${fhr1}00
#fmdl2=${DAPATH}/hrrr.${ymd1}/conus/gempak/hrrr_${ymdh1}f0${fhr2}00
#fmdl3=${DAPATH}/hrrr.${ymd2}/conus/gempak/hrrr_${ymdh2}f0${fhr3}00
#fmdl4=${DAPATH}/hrrr.${ymd3}/conus/gempak/hrrr_${ymdh3}f0${fhr4}00
fmdl1=${DAPATH}/hrrr_${ymdh}f0${fhr1}00
fmdl2=${DAPATH}/hrrr_${ymdh1}f0${fhr2}00
fmdl3=${DAPATH}/hrrr_${ymdh2}f0${fhr3}00
fmdl4=${DAPATH}/hrrr_${ymdh3}f0${fhr4}00
echo $fmdl1

garea="36.;-84.;43.;-72."
proj="lcc/25.;-78.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
# GDPFUN   = mul(sn24m,39.37)
 GDPFUN   = quo(snow${fhr1},25.4)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrsnow1time2_f${fhr1}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z HRRR  ${fhr1}-HR ACC SNOW DPTH
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5
 FINT     = 0.1;1;2;4;6;8;10;12;15;20;25
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;9
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 # GDPFUN   = mul(sn30m,39.37)
 GDPFUN   = quo(snow${fhr2},25.4)
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z HRRR  ${fhr2}-HR ACC SNOW DPTH 
 CLRBAR   = 1/H/UL/.02;0.97/1.9;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
# GDPFUN   = mul(sn36m,39.37)
 GDPFUN   = quo(snow${fhr3},25.4)
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z HRRR  ${fhr3}-HR ACC SNOW DPTH 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
# GDPFUN   = mul(sn42m,39.37)
 GDPFUN   = quo(snow${fhr4},25.4)
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z HRRR  ${fhr4}-HR ACC SNOW DPTH 
 CLRBAR   = 0
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test6/.
exit
