#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/srefcapeprob
rm /stmp/Geoffrey.Manikin/meg/srefcapeprob/*
cd /stmp/Geoffrey.Manikin/meg/srefcapeprob
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2012102912
#dayoweek=Sun
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

if [ $cycs -eq 03 ]; then
 hours="33 57 81"
elif [ $cycs -eq 09 ]; then
 hours="39"
elif [ $cycs -eq 15 ]; then
 hours="45 69"
else
 hours="39 63"
fi

for fhrs in $hours; do

fmdl1=/com/nawips/prod/sref.${ymds}/sref212_${ymdhs}_prob

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape0500PA 
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    SREF PROB of 500 CAPE 
 DEVICE   = GIF|${cycs}srefprob1_cape_f0${fhrs}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROOJ    = lcc/25;-105;25;/1;1;1;1
 GAREA    = 22.;-134.;52.;-50.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r


 GDPFUN  = CAPE1000PA 
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 1000 CAPE 
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1 
r

 GDPFUN  = CAPE2000PA
 PANEL   = t
 TITLE   = 1/-1/~    SREF PROB of 2000 CAPE 
 DEVICE  = GIF|${cycs}srefprob2_cape_f0${fhrs}.gif|750;900
 CLEAR   = y
 CLRBAR  = 0 
r

 GDPFUN  = CAPE4000PA
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 4000 CAPE 
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1
r

ex
EOF

gpend
done
mv ${cycs}*gif /stmp/Geoffrey.Manikin/meg/holdshort/.
exit
