#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
length=$2

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
mon=`cut -c 5-7 holddate`
gtime=`cut -c 12-24 holddate`
gdate=`cut -c 1-10 holddate`
gcent=`cut -c 25-28 holddate`

#da00=`cut -c 7-14 t${cyc}z`
#hr00=`cut -c 15-16 t${cyc}z`

#da00=20040609
#hr00=18

mkdir /stmpp1/wx20mg/test
cd /stmpp1/wx20mg/test

if [ $length -eq 12 ]
then
times="03 06 09 12"
else
times="03 06 09 12 15 18"
fi

counter=3
for fhr in $times; do

#fmdl=/com/nawips/prod/ruc2.${da00}/ruc2_${da00}${hr00}f0${fhr}
fmdl=/meso/save/wx20mg/gempak/nagribx/ruc2_${da00}${hr00}
fmdl2=/meso/save/wx20mg/gempak/nagribx/ruc2x_${da00}${hr00}
#fmdl2=/stmpp1/wx20mg/gempak.ruc20/ruc2_${da00}${cyc}f0${fhr}

echo $fmdl
echo $fmdl2


    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = add(s03i,c03i) 
 CINT     = .01;.1;.2;.3;.4;.5;.75 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = PS
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.2;.3;.4;.5;.75 
 FLINE    = 0;21;22;23;28;30;2;15 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RUC2 3-HR TOT PRECIP 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RUCX  3-HR TOT PRECIP 
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = add(s03i,c03i)
 TITLE    = 0
 CINT     = .01;.1;.2;.3;.4;.5;.75 
r

ex
EOF

counter=`expr $counter + 1`
done

if [ $length -eq 12 ]
then
    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f12
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = add(s12i,c12i)
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RUC  12-HR TOT PRECIP 
 DEVICE   = GIF|comparepcp_${cyc}f${counter}.gif
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.25;1.5
 FLINE    = 0;21;22;23;28;30;2;15
 TYPE     = f 
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 GDFILE   = $fmdl2
 TITLE    = 1/1/ ${fhr}-HR RUCX  12-HR TOT PRECIP
 TEXT     = 1.2/11/2/SW
 PANEL    = 0;0.;1.;0.49
r

ex
EOF
fi

gpend
mv *gif ../../ftphold/.

cat > info.html <<EOFmet
<HTML>
<HEAD>
<TITLE>RUCX GRAPHICS</TITLE>
</HEAD>
<BODY bgcolor="FFFFCC">
<HTML>
<CENTER><b><font color="#009900"><font size=+4>RUCX Graphics </H1></CENTER></font></font
></b><CENTER>
<p>
The current forecast cycle is <b><font face="Times New Roman,Times"><font size=+1><font color="#CC0000">${cyc}Z ${day} ${mon} </font><font color="#FF6600"></font></font></font></b>with graphics finished at $gtime $gdate $gcent
</CENTER>
<p>
<H3>This page displays the RUCX forecast and compares it to the RUC. When any forecast hour button on the left is activated, the following maps will be displayed:</H3>
<p>
<br>
<CENTER>
<TABLE BORDER>
<TR>
<TD><H4>Top: <font color="#CC33CC"><font size=+4>RUC</font></font></H4></TD>
</TR>
<TR>
<TD><H4>Bottom: <b><font color="#FF6600"><font size=+4>RUCX</font></H4></TD></b>
</TR>
</TABLE>
</CENTER>
<p>
<br>
<H4>NOTE: The AWIPS grid #252 (20 km Lambert Conformal) is used for all plots.
<p>
<br>
<H4>NOTE: All displayed winds are in knots.  Precipitation values are in inches.
<p>
<br>
<p>
<br>
<center> <a href='http://www.nws.noaa.gov/disclaimer1.html'>Disclaimer</a> </center>
</BODY>
</HTML>
EOFmet

mv *html ../../ftphold/.
echo abouttoexit3pcp
exit
