#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/type
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/type/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/type
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2021122412
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

times="60 61 62 63 64 65 66"
times="27"
for fhr in $times; do

fmdl=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymd}${cyc}f0${fhr}
fmdl=/gpfs/dell1/ptmp/Geoffrey.Manikin/gfs/gfs_0p25_${ymd}${cyc}f0${fhr}
echo $fmdl

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = .11;10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//~   GFS   PTYPE 
 DEVICE   = GIF|gfstype_${ymdh}f0${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-72.;25./2;2;1;1
 GAREA    = ma 
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .11;10 
 FLINE    = 0;3 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
 r

 GDPFUN   = wxtp
 FLINE    = 0;29
 r

 GDPFUN   = wxtz
 FLINE    = 0;2
 r

ex
EOF

gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test5/.
exit
