#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

vtime=2021070812
hours="96 84 72 60 48 36 24 12 00"
hours="144 132 120 108"
hours="132 144"
hours="00"
for fhr in $hours; do

dattim="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/advtime $vtime -$fhr -1`"
validtime=`echo $dattim | cut -c1-11`
ymdh=`echo $validtime | cut -c1-10`
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c9-10`

DAPATH1=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak
DAPATH2=/gpfs/dell1/nco/ops/com/ecmwf/prod/ecmwf.${ymd}/gempak
#DAPATH1=/gpfs/dell1/ptmp/Geoffrey.Manikin/gfs
#DAPATH2=/gpfs/dell1/ptmp/Geoffrey.Manikin/ecmwf

fmdl1=${DAPATH1}/gfs_0p25_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/ecmwf_0p25_${ymdh}f0${fhr}
echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sped) 
 CINT     = 0
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SLP/10m WIND
 DEVICE   = GIF|${ymdh}slpwnd2f${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-80;25;/1;1;1;1
 GAREA    = 20.;-90.;32.;-74. 
 GAREA    = 25.;-86.;37.;-70.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 20;25;30;35;40;45;50;55;60;65;70;75
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 2 
 LINE     = 4/1/3/2 
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 TYPE     = c
 CLRBAR   = 0
r

 GDFILE   = $fmdl2
 GDPFUN   = knts(sped)
 PANEL    = b
 TITLE    = 1/-1/~   ECMWF  SLP/10m WIND
 TYPE     = f
 FINT     = 20;25;30;35;40;45;50;55;60;65;70;75
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
r

 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 2 
 LINE     = 4/1/3/2 
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
