#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/namsndm
rm /stmpp1/Geoffrey.Manikin/meg/namsndm/*
cd /stmpp1/Geoffrey.Manikin/meg/namsndm
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2018032018
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
dayoweek=hold10

hours="42"
for fhr1 in $hours; do
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -18 -1`"
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`

fhr112=`expr $fhr1 - 12`
fhr212=`expr $fhr2 - 12`
fhr312=`expr $fhr3 - 12`
fhr412=`expr $fhr4 - 12`

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} ${fhr1} -1`"
typeset -Z2 fhr1 fhr2 fhr3
DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh1}
fmdl2=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh2}
fmdl3=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh3}
fmdl4=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh4}

garea="37.;-80.;47.;-66."
proj="lcc/25.;-75.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(add(swem12,swem12^${ymd1}/${cyc1}f0${fhr112},0.3937) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd1}${cyc1}namswem_f${fhr1}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL = county
 TITLE    = 1// ${ymd1} ${cyc1}z NAM   ${fhr1}-HR ACC SNOW 10:1
 CLEAR    = y
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28;32
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 TITLE    = 15/1/     CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 GDPFUN   = mul(add(swem12,swem12^${ymd2}/${cyc2}f0${fhr212}),0.3937)
 PANEL    = ur 
 CLEAR    = n
 TITLE    = 1//  ${ymd2} ${cyc2}z NAM   ${fhr2}-HR ACC SNOW 10:1 
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 GDPFUN   = mul(add(swem12,swem12^${ymd3}/${cyc3}f0${fhr312}),0.3937)
 PANEL    = ll 
 TITLE    = 1//  ${ymd3} ${cyc3}z NAM   ${fhr3}-HR ACC SNOW 10:1 
 CLRBAR   = 1/H/UL/.02;0.97/1.9;.03/1
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 GDPFUN   = mul(add(swem12,swem12^${ymd4}/${cyc4}f0${fhr412}),0.3937)
 PANEL    = lr
 TITLE    = 1//  ${ymd4} ${cyc4}z NAM   ${fhr4}-HR ACC SNOW 10:1 
 CLRBAR   = 0
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
