#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/typerap
rm /stmp/wx20mg/meg/typerap/*
cd /stmp/wx20mg/meg/typerap
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013030521
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Tue

hours="12 15 18"

for fhr in $hours; do
fmdl1=/ptmp/wx20mg/data/rap13_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 1 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//~  RAP PRECIP TYPE   
 DEVICE   = GIF|raptype_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = md- 
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDPFUN   = add(wxtr;wxts)
 FLINE    = 0;0;11
 FINT     = 0;1.9
r

 GDPFUN   = add(wxts;wxtp)
 FLINE    = 0;0;11
 FINT     = 0;1.9
r

 GDPFUN   = add(wxtp;wxtz)
 FLINE    = 0;0;11
 FINT     = 0;1.9
r

 GDPFUN   = add(wxts;wxtz)
 FLINE    = 0;0;11
 FINT     = 0;1.9
r

 GDPFUN   = add(wxtr;wxtp)
 FLINE    = 0;0;11
 FINT     = 0;1.9
r

ex
EOF
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
