#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/refc
rm /stmpp1/Geoffrey.Manikin/meg/refc/*
cd /stmpp1/Geoffrey.Manikin/meg/refc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017031318
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8
counter=11

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
for fhr in $hours; do

#fmdl1=/ptmpd2/Geoffrey.Manikin/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}
fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(refc;wxtr) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nam4refc_${ymdh}f${counter}.gif | 800;850
 PROJ     = lcc/25.;-74.;25./2;2;1;1
 GAREA    = nj 
 TITLE    = 1//~  4 KM NAM  COMPOSITE REFL 
 CLEAR    = y
 SCALE    = 0
 \$MAPFIL = county
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 1.1/11/2
 FINT     = 3;15;25;35;45;55;65
 FLINE    = 0;21;21;22;23;5;19;17;2;15
 TYPE     = f 
r
 
 GDPFUN   = mul(refc;wxts)
 FLINE    = 0;27;26;25;4;24
 CLEAR    = n
r

 GDPFUN   = mul(refc;wxtp)
 FLINE    = 0;28;28;29;30;30;30
r

 GDPFUN   = mul(refc;wxtz)
 FLINE    = 0;11;12;13;2;2;2
r

ex
EOF

counter=`expr $counter + 1`
done
gpend
convert -loop 0 -delay 60 nam*gif nam4_refcloop_${ymdh}.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#rm *gif
exit
