#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/96pcptrnam
rm /stmpp1/Geoffrey.Manikin/meg/96pcptrnam/*
cd /stmpp1/Geoffrey.Manikin/meg/96pcptrnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2019070800
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold8

hours="216"
for fhr in $hours; do

typeset -Z3 fhr

DAPATH=/meso/noscrub/Geoffrey.Manikin/barry
fmdl1=${DAPATH}/gfspcp_${ymdh}
fmdl2=${DAPATH}/gfsv14pcp_${ymdh}
fmdl3=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_0p25_${ymdh}f${fhr}

   gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p96i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 \$MAPFIL = 0
# \$MAPFIL = county
 WIND     = 0
 TITLE    = 1//  GFS 96-HR PCP  $ymd1 ${cyc}z  F${fhr}
 DEVICE   = GIF|gfs96pcpz_${ymdh}f0${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 GAREA    = 27.2;-98.;38.;-85. 
 PROJ     = lcc/25;-91;25/2;2;1;1
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.01;0.96/0.98;.02/1|0.8/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5;1
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1//  GFSv14  96-HR PCP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|gfsx96pcpz_${ymdh}f0${fhr}.gif | 800;850
r

 GDFILE   = $fmdl3
 GDPFUN   = quo(mul(pxxm,1000),25.4)
 TITLE    = 1//  ECMWF 96-HR PCP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|ecmwf96pcpz_${ymdh}f0${fhr}.gif | 800;850
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
