#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/srefpcpprob
rm /stmp/Geoffrey.Manikin/meg/srefpcpprob/*
cd /stmp/Geoffrey.Manikin/meg/srefpcpprob
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013091000
dayoweek=Mon
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

if [ $cycs -eq 03 ]; then
 hours="33 57 81"
elif [ $cycs -eq 09 ]; then
 hours="27 51 75"
elif [ $cycs -eq 15 ]; then
 hours="45 69"
else
 hours="39 63"
fi

hours="63"

for fhrs in $hours; do

#fmdl1=/com/nawips/prod/sref.${ymds}/sref212_${ymdhs}_prob
fmdl1=/ptmp/Geoffrey.Manikin/pcp/srefprob_${ymdhs}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = P24M0006PA 
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1/1/2;1
 \$MAPFIL = county
 WIND     = 0
 TITLE    = 1/-1/~    SREF PROB of 0.25"
 DEVICE   = GIF|${cycs}srefprob1_24pcp_f0${fhrs}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 33.9;-111.4;42.9;-98.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.08;.5/0.9;.03/1
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r


 GDPFUN  = P24M0012PA 
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 0.5"
 CLEAR   = n
 CLRBAR  = 0 
r

 GDPFUN  = P24M0025PA
 PANEL   = t
 TITLE   = 1/-1/~    SREF PROB of 1"
 DEVICE  = GIF|${cycs}srefprob2_24pcp_f0${fhrs}.gif|750;900
 CLEAR   = y
 CLRBAR  = 1/V/UL/.08;.5/0.9;.03/1 
r

 GDPFUN  = P24M0050PA
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 2"
 CLEAR   = n
 CLRBAR  = 0 
r

 GDPFUN  = P24M0101PA
 PANEL   = t
 TITLE   = 1/-1/~    SREF PROB of 4"
 DEVICE  = GIF|${cycs}srefprob3_24pcp_f0${fhrs}.gif|750;900
 CLEAR   = y
 CLRBAR  = 1/V/UL/.08;.5/0.9;.03/1 
r

 GDPFUN  = P24M0152PA
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 6"
 CLEAR   = n
 CLRBAR  = 0 
r

ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/coflood/$dayoweek
#mv ${cycs}*gif /stmp/Geoffrey.Manikin/meg/holdshort/.
exit
