#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrruphl
rm /stmpp1/Geoffrey.Manikin/meg/hrrruphl/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrruphl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017012206
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

hours1="08 09 10 11 12 13 14 15"
hours2="09 10 11 12 13 14 15 16"
hours3="10 11 12 13 14 15 16 17"
hours4="11 12 13 14 15 16 17 18"

hours1="04 05 06 07 08 09 10 11"
hours2="05 06 07 08 09 10 11 12"
hours3="06 07 08 09 10 11 12 13"
hours4="07 08 09 10 11 12 13 14"

hours1="01 02 03 04 05 06 07"
hours2="01 02 03 04 05 06 07 08"
hours3="02 03 04 05 06 07 08 09"
hours4="03 04 05 06 07 08 09 10"

hours1="01 02 03 04 05 06"
hours2="02 03 04 05 06 07"
hours3="03 04 05 06 07 08"
hours4="04 05 06 07 08 09"

ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/para
garea="30.;-103.;40.5;-90."
garea="29.;-87.;33.;-81."
proj="lcc/25.;-84.;25./2;2;1;1"

for fhr1 in $hours1; do

fmdl1=${DAPATH}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr1}00
 
    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = MXUPHL01
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrralluphl_4cyc_${ymdh}.gif | 800;850
 GAREA    = $garea 
 PROJ     = $proj
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z HRRR  2-5 KM MAX UPDRAFT HLCY 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 0.9/11/2
 FINT     = 25;50;75;100;125;150;175;200
 FLINE    = 0;4;26;2;15;17;10;20;5
 TYPE     = f 
r

ex 
EOF
done

 for fhr2 in $hours2; do
fmdl2=${DAPATH}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr2}00
  gdplot2 << EOF
 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 PANEL    = ur
 TITLE    = 1//  ${cyc1}z HRRR  2-5 KM MAX UPDRAFT HLCY
r

 TITLE    = 2/1/ TRACKS VALID 1-22 7z to 1-22 12z
r

ex
EOF
done

 for fhr3 in $hours3; do
fmdl3=${DAPATH}/hrrr.${ymd2}/hrrr_${ymdh2}f0${fhr3}00 
  gdplot2 << EOF
 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 PANEL    = ll 
 TITLE    = 1//  ${cyc2}z HRRR  2-5 KM MAX UPDRAFT HLCY
 CLRBAR   = 1/H/UL/.2;0.98/1.6;.03/1
r

ex
EOF
done

for fhr4 in $hours4; do
  fmdl4=${DAPATH}/hrrr.${ymd3}/hrrr_${ymdh3}f0${fhr4}00
  gdplot2 << EOF
 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 PANEL    = lr
 TITLE    = 1//  ${cyc3}z HRRR  2-5 KM MAX UPDRAFT HLCY
 CLRBAR   = 0
r
 
ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
