#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2013120600
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

times="00"
for fhr in $times; do

fmdl1=/ptmpp2/Geoffrey.Manikin/hold/rap13_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP 2-M  TEMP 
 DEVICE   = GIF|rap2mt_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-99;25;/1;1;1;1
 GAREA    = 25.;-109.;40.;-89. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.96/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = 15;20;25;30;35;40;45;50;55;60;65;70
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
# FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 FLINE    = 30;28;27;26;25;23;22;21;5;10;17;2;15

 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

rm *gif
exit
