#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefcx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018043018
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold10

hours="33"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`

cyc1=`expr $cyc - 6`
cyc2=`expr $cyc - 12`
cyc3=`expr $cyc - 18`

fhr1=`expr $fhr + 6`
fhr2=`expr $fhr + 12`
fhr3=`expr $fhr + 18`

typeset -Z2 fhr1 fhr2 fhr3
export DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
export DAPATH=/com2/nawips/prod
fmdl1=${DAPATH}/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl2=${DAPATH}/nam.${ymd1}/nam_conusnest_${ymdh1}f0${fhr1}
fmdl3=${DAPATH}/nam.${ymd2}/nam_conusnest_${ymdh2}f0${fhr2}
fmdl4=${DAPATH}/nam.${ymd3}/nam_conusnest_${ymdh3}f0${fhr3}

garea="40.;-102.;50.;-82."
garea="24.;-104.;34.;-92."
garea="34.;-101.;43.;-89"
garea="28.;-87.;37.;-75."
garea="ks+"
#garea="32.;-105;41;-93"
garea="34.;-105;43.;-93."
proj="lcc/25.;-98.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}namrefc4ct_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z NAM3   REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr1
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z NAM3   REFC 
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr2
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z NAM3   REFC 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr3
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z NAM3   REFC 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefc/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
