#!/bin/sh
echo 'into'

cyc=$1

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/smoke
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/smoke/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/smoke
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

ymdh=2023052112
ymd=`echo $ymdh | cut -c1-8`
hrrr_ver=v4.1

times="00 03 06 09 12"
times="00 06 12 18 24"
times="00 06 12 15 18 21 24"
times="12 24 36"
times="36 48"
for fhr in $times; do

fmdl1=/lfs/h1/ops/prod/com/hrrr/${hrrr_ver}/hrrr.${ymd}/conus/gempak/hrrr_${ymdh}f0${fhr}00
fmdl2=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/smoke/hrrr_${ymdh}f0${fhr}00 
echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = colmd 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   OPS HRRR COLUMN SMOKE 
 DEVICE   = GIF|hrrrsfcsmoke_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-98;25;/1;1;1;1
 GAREA    = grid 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 1000000000 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.6/1.2;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 1;4;7;11;15;20;25;30;40;50;75;150;250;500
 FLINE    = 0;27;26;25;4;23;23;21;5;20;17;16;2;15;29
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   TEST HRRR COLUMN SMOKE
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test3/.
exit
