#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/850w
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/850w/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/850w
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

ymdh=2022072512
ymd=`echo $ymdh | cut -c1-8`

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="24 25 26 27 28 29 30"
hours="18 24"
for fhr in $hours; do

fmdl1=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/floods22/hrrr_${ymdh}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrr850w1_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-92.;25./2;2;1;1
# GAREA    = 34.;-92.;46.;-70. 
 GAREA    = mo 
 TITLE    = 1//~  HRRR 850 MB  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.1;0.95/0.7;.02/1
 TEXT     = 1.1/11/2
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;26;4;22;5;10;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /8;8
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

done
gpend

#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.

exit
