#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6ptypetrnam
rm /stmpp1/Geoffrey.Manikin/meg/6ptypetrnam/*
cd /stmpp1/Geoffrey.Manikin/meg/6ptypetrnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2017011018
ymd1=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold5
hours="00 06 12 18"
hours="06 09 12"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fhrminus3=`expr $fhr1 - 3`
fhr2minus3=`expr $fhr2 - 3`
fhr3minus3=`expr $fhr3 - 3`
fhr4minus3=`expr $fhr4 - 3`
typeset -Z2 fhrminus3 fhr2minus3 fhr3minus3 fhr4minus3

DAPATH=/com2/nawips/prod
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/
fmdl1=${DAPATH}/nam.${ymd1}/nam20_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/nam.${ymd2}/nam20_${ymdh2}f0${fhr2}
fmdl3=${DAPATH}/nam.${ymd3}/nam20_${ymdh3}f0${fhr3}
fmdl4=${DAPATH}/nam.${ymd4}/nam20_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 \$MAPFIL = county
 WIND     = 0
 TITLE    = 1//  NAM PTYPE  ${ymd1} ${cyc}z  F${fhr1}
 DEVICE   = GIF|nam6ptypetr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-122;25;/1;1;1;1
# GAREA    = 28.;-88.;44.;-66. 
 GAREA    = 44.2;-124.;47.;-119.6
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
r

 GDFILE   = $fmdl2 
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM PTYPE  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = wxtr 
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 TITLE    = 16/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3 
 GDATTIM  = f${fhr3}
 GDPFUN   = wxtr 
 TITLE    = 1//  NAM PTYPE  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl4 
 GDATTIM  = f${fhr4}
 GDPFUN   = wxtr 
 TITLE    = 1//  NAM PTYPE  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
