#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefcx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018090715
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold5

hours="02 05 08 11"
hours="01 02 03 04 05 06 07"
hours="07 08 10 11 13 14 15 16 17"
hours="08 09 10"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`

cyc1=`expr $cyc - 1`
cyc2=`expr $cyc - 2`
cyc3=`expr $cyc - 3`

fhr1=`expr $fhr + 1`
fhr2=`expr $fhr + 2`
fhr3=`expr $fhr + 3`

typeset -Z2 fhr1 fhr2 fhr3
#export DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
#export DAPATH=/meso/noscrub/Geoffrey.Manikin/
export DAPATH=/gpfs/hps/nco/ops/com/hrrr/prod/
fmdl1=${DAPATH}/hrrr.${ymd}/conus/nawips/hrrr_${ymdh}f0${fhr}00
fmdl2=${DAPATH}/hrrr.${ymd1}/conus/nawips/hrrr_${ymdh1}f0${fhr1}00
fmdl3=${DAPATH}/hrrr.${ymd2}/conus/nawips/hrrr_${ymdh2}f0${fhr2}00
fmdl4=${DAPATH}/hrrr.${ymd3}/conus/nawips/hrrr_${ymdh3}f0${fhr3}00
echo $fmdl1

garea="40.;-102.;50.;-82."
garea="24.;-104.;34.;-92."
garea="34.;-101.;43.;-89"
garea="34.;-102.6;40.8;-93.4"
garea="md+"
proj="lcc/25.;-75.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 \$MAPFIL = county
 DEVICE   = GIF|${ymd}${cyc}hrrrrefc4ct_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z HRRR   REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr1
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z HRRR   REFC 
 CLRBAR   = 1/H/UL/.46;0.98/1.1;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr2
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z HRRR   REFC 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr3
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z HRRR   REFC 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefc/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
