#!/bin/ksh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssndm
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssndm/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssndm
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2022010212
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

hours="24"
for fhr in $hours; do

DAPATH=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
cp ${DAPATH}/gfs_0p25_${ymdh}f0${fhr} fmdl1
cp ${DAPATH}/gfs_0p25_${ymdh}f000 fmdl1a
cp ${DAPATH}/gfs_0p50_${ymdh}f0${fhr} fmdl2
cp ${DAPATH}/gfs_0p50_${ymdh}f000 fmdl2a
echo $fmdl1

garea="wa+"
proj="lcc/25.;-120.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = fmdl1a + fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(sub(sndm+2,sndm^${ymd}/${cyc}f000),39.37)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}gfssndm_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1// ${ymd} ${cyc}z GFS 0.25   ${fhr}-HR ACC SNOW DPTH
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28;32
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 GDFILE   = fmdl2a + fmdl2
 PANEL    = b 
 CLEAR    = n
 TITLE    = 1//  ${ymd} ${cyc}z GFS 0.50   ${fhr}-HR ACC SNOW DPTH 
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test7/.
exit
