#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/dewz
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/dewz
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = dwpf
 CINT     = 4
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|compare2dewzoom_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-105.;25./2;2;1;1
 GAREA    = 24.;-122.;50.;-84. 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.95;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -18;-12;-6;0;6;10;14;18;22;26;30;34;38;42;46;50;54;58;62;68;72;76
 FLINE    = 0;8;18;16;10;19;20;5;21;22;23;27;26;4;24;28;29;30;12;2;16;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP 2-M DEW PT
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 1/1/ ${fhr}-HR RAPX  2-M DEW PT
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 TITLE    = 4/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 GDFILE   = $fmdl2 
 GDPFUN   = dwpf
 TITLE    = 0
 CINT     = -12;-6;0;2;6;10;14;18;22;26;30;34;38;42;46;50;54;58;62;66;70;74
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexitdwpfz
exit
