#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500tr
rm /stmpp1/Geoffrey.Manikin/meg/500tr/*
cd /stmpp1/Geoffrey.Manikin/meg/500tr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
for fhr1 in $times; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2

ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

fmdl1=/com/nawips/prod/nam.${ymd1}/nam40_${ymdh}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd2}/nam40_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd3}/nam40_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd4}/nam40_${ymdh4}f0${fhr4}

fmdl5=/com/nawips/prod/gfs.${ymd1}/gfs40_${ymdh}f0${fhr1}
fmdl6=/com/nawips/prod/gfs.${ymd2}/gfs40_${ymdh2}f0${fhr2}
fmdl7=/com/nawips/prod/gfs.${ymd3}/gfs40_${ymdh3}f0${fhr3}
fmdl8=/com/nawips/prod/gfs.${ymd4}/gfs40_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl5 + $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 500 
 GVCORD   = pres
 GDPFUN   = sub(hght+2,hght) 
 CINT     = 5 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAM - GFS  500Z  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|500difftr${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 SKIP     = 0
 CLRBAR   = 0 
 CONTUR   = 0
 FINT     = -150;-120;-90;-60;-30;30;60;90;120;150
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl6 + $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM - GFS  500Z  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLEAR    = n
r

 GDFILE   = $fmdl7 + $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  NAM - GFS  500Z  $ymd3 ${cyc3}z  F${fhr3}
 CLRBAR   = 1/H/UL/.52;.86/.95;.02/-1
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl8 + $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  NAM-GFS 500Z  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
 CLRBAR   = 0
r

ex
EOF
done
gpend
mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
