#!/bin/sh
echo 'into'

ymdh=2023062512
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
rapver=v5.1

mkdir /lfs/h2/ec/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/10w
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/10w/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/10w
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

counter=11
times="03 06 09 12 15 18"
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72"
for fhr in $times; do

validtime="`/lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/advtime ${ymdh} ${fhr} -1`"
echo $validtime

fmdl1=/lfs/h1/ops/prod/com/rap/${rapver}/rap.${ymd}/gempak/rap13_${validtime}f000
fmdl1=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/smoke/rap13_${validtime}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mmsl 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP ANALYSIS 10M WIND 
 DEVICE   = GIF|10wz${counter}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-80.;25./2;2;1;1
 GAREA    = 26.;-104.;56.;-58. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1006-1060;920-1006/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 TYPE     = c 
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = kntv(wnd)
 WIND     = aK1/0.7/2/122
 TYPE     = a
 CLEAR    = n
 SKIP     = /8;8
r

ex
EOF
counter=`expr $counter + 1`
done
gpend

convert -loop 0 -delay 100 10wz*gif ${ymdh}_10wloop.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
