#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/nohrsc
rm /stmpp1/Geoffrey.Manikin/meg/nohrsc/*
cd /stmpp1/Geoffrey.Manikin/meg/nohrsc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2019022112
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold9

DAPATH1=/ptmpp1/Geoffrey.Manikin/nohrsc
fmdl1=${DAPATH1}/nohrsc24_${ymdh}.grd
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f24 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sub(sndm+2,sndm^${ymd}/${cyc}f000),100),2.54) 
 GDPFUN   = mul(snow24,39.37)
 CINT     = 2 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//~ 24-HR NOHSRC ANALSIS (IN) 
 DEVICE   = GIF|nohsrc24_${ymdh}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-80.;25./2;2;1;1
 GAREA    = 33.4;-87.;44.4;-69. 
 GAREA    = 23.;-136.;67.;-48.
 GAREA    = 31.;-88.;41.;-74. 
 GAREA    = md
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.05;0.98/.9;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.1;1;3;5;7.5;10;15;20;25;50;75;100;125
 FINT     = 0.1;1;2;4;6;8;10;12;15;20;25
# FINT     = .05;.1;.2;.4;.6;.8;1.;1.2;1.4;1.6;1.8;2;4;8
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;9
 FLINE    = 0;21;22;23;27;26;25;4;5;10;17;2;15;11
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
