#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/rtma2dew
rm /stmpp1/Geoffrey.Manikin/meg/rtma2dew/*
cd /stmpp1/Geoffrey.Manikin/meg/rtma2dew
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymd=20190720
dayoweek=hold10

cycles="00 01 02 18 21 22 23"
cycles="03"
for cyc in $cycles; do
fmdl1=/com2/rtma/prod/rtma2p5.${ymd}/nawips/rtma2p5_${ymd}${cyc}f000
#fmdl1=/ptmp/Geoffrey.Manikin/rtma/rtma_${ymdh}f000
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 0 
 LINE     = 1 
 MAP      = 1/1/2
 WIND     = 0
 TITLE    = 1/-1/~   2.5 RTMA DEW PT 
 DEVICE   = GIF|${ymd}${cyc}_2p5rtma2dewz.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-91;25;/1;1;1;1
# GAREA    = 30.;-104.;40.;-88.
 GAREA    = 33.;-103;49.;-81.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.96/0.8;.03/2
 CONTUR   = 0
 SKIP     =  
 FINT     = -30;-24;-18;-12;-6;0;6;12;18;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FINT     = -24;-18;-12;-6;0;6;12;18;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80;84 
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
