#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
length=$2

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

#da00=`cut -c 7-14 t${cyc}z`
#hr00=`cut -c 15-16 t${cyc}z`

#da00=20020214
#hr00=12

mkdir /stmpp1/wx20mg/gempak.rap13/slpdiff
rm /stmpp1/wx20mg/gempak.rap13/slpdiff/*
cd /stmpp1/wx20mg/gempak.rap13/slpdiff

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

if [ $length -eq 12 ]
then
times="00 01 02 03 06 09 12"
else
times="00 01 02 03 06 09 12 15 18"
fi

counter=0
for fhr in $times; do

#fmdl=/com/nawips/prod/ruc2.${da00}/ruc2_${da00}${hr00}f0${fhr}
fmdl=/meso/save/wx20mg/gempak/nagribx/ruc2_${da00}${hr00}
fmdl2=/meso/save/wx20mg/gempak/nagribx/ruc2x_${da00}${hr00}
#fmdl2=/stmpp1/wx20mg/gempak.rap13/ruc2_${da00}${cyc}f0${fhr}

echo $fmdl
echo $fmdl2

# negate the colors ahead of time except white and black
gpcolor << EOFC
COLORS=0=255:255:255?
COLORS=101=255:255:255;1=0:0:0
DEVICE   = GIF
r

ex
EOFC

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GFUNC    = sub(mmsl+2,mmsl) 
 CINT     = 3 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RUCX - RUC2 SLP DIFFS 
 DEVICE   = GIF|compareslpdiffs_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.08;0.8/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -3;-2.5;-2;-1.5;-1;1;1.5;2.;2.5;3
 FLINE    = 15;2;17;10;5;0;21;23;25;4;29  
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.1/11/1/SW
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

echo abouttoexit2mt
/nwprod/util/ush/stopxvfb.sh /bin/sh
                                                                                      
. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
                                                                                      
                                                                                      
ftp -n -v << EOF > /nfsuser/g01/emcsrc/wx20mg/gempak.rap13/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/ruc2/para/cases/20060105
prompt
mput *.gif
bye
EOF

exit
