#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/3pcpslp
rm /stmpp1/Geoffrey.Manikin/meg/3pcpslp/*
cd /stmpp1/Geoffrey.Manikin/meg/3pcpslp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2018091118
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold5
counter=111

hours="04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 123 126 129 132 135 138 141 144"
typeset -Z3 fhr fhr1
typeset -Z2 fhra fhrb
for fhr in $hours; do

rmdr3=`expr $fhr % 3`
rmdr6=`expr $fhr % 3`
fhr1=`expr $fhr - 3`
if [ $fhr -eq 100 -o $fhr -eq 101 -o $fhr -eq 102 ]; then
 typeset -Z3 fhra 
fi
if [ $fhr -gt 102 ]; then
 typeset -Z3 fhra fhrb
fi

if [ $rmdr6 -ne 0 -a $rmdr3 -eq 0 ]; then
  pcpfun="p03i"
elif [ $rmdr6 -eq 0 -a $rmdr3 -eq 0 ]; then
  pcpfun="sub(p06i+2,p$03i^${ymd}/${cyc}f${fhr1})"
elif [ $rmdr3 -eq 1 ]; then
  pcpfun="add(
fhra=$fhr
fhrb=$fhr1
DAPATH=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}
fmdl1=${DAPATH}/gfs_0p25_${ymdh}f${fhr}
fmdl2=${DAPATH}/gfs_0p25_${ymdh}f${fhr1}

    gdplot2 << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = $pcpfun 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|fv3pcp1slp_${ymdh}f${counter}.gif | 800;850
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = 27.;-86.;41.;-64. 
 TITLE    = 0 
 CLEAR    = y
 SCALE    = 0
# \$MAPFIL = county
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.06;0.95/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = .01;0.1;0.25;0.5;0.75;1.;1.5;2.;3.;4.;5. 
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 FLINE    = 0;21;22;23;24;25;27;28;30;7;15;17
 TYPE     = f 
r

 GDFILE   = $fmdl1
 GDPFUN   = emsl
 HILO     = ;2/;S13#/;920-1010/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CINT     = 4
 CLEAR    = n
 LINE     = 1/1/2/2 
 TEXT     = 0.9/11/2/SW
 TYPE     = c
 TITLE    = 1//~   FV3GFS  SLP 3-h PCP (in)  850MB TMP(C) 
r

 GVCORD   = pres
 GLEVEL   = 850
 GDPFUN   = tmpc
 CINT     = 3/3/15
 LINE     = 2/1/1/4
r 

 CINT     = 0/0/0
 LINE     = 29/1/1/4
r

ex
EOF

counter=`expr $counter + 1`
#if [ $counter -eq 100 ]; then
# counter=`expr $counter + 800` 
# typeset -Z3 fhra fhrb
#fi
echo $counter

done
gpend
convert -loop 0 -delay 40 fv3*gif fv3_3pcpslploop_${ymdh}.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#rm *gif
exit
