#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/rap2m
rm /stmpp1/Geoffrey.Manikin/meg/rap2m/*
cd /stmpp1/Geoffrey.Manikin/meg/rap2m
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013022512
#ymd=20130225
#dayoweek=Mon

times="00"
for fhr in $times; do

fmdl1=/com2/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/rap.${ymd}/rap32_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = tmpf
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP 2-M  TEMP
 DEVICE   = GIF|${cyc}rap132m00.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP 2-M  TEMP
 DEVICE   = GIF|${cyc}rap2m00.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = grid
 CLEAR    = y
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = tmpf
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP 2-M  TEMP
 DEVICE   = GIF|${cyc}rap132m00.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.95/0.8;.03/2
 CONTUR   = 0
 SKIP     = 0
 SKIP     = 0
# FINT     = -48;-40;-32;-24;-16;-8;0;8;16;24;32;40;48;56;64;72;80;88;96
# FINT     = -32;-24;-16;-8;0;8;16;24;32;40;48;56;64;72;80;88;96;104;112
 FINT     = 15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110;115
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = dwpf
 TITLE    = 1/-1/~  RAP 2-M DEW PT
 PANEL    = b
 CLEAR    = n
 FINT     = 50;54;58;62;66;70;74;78;82
 FLINE    = 0;21;22;23;28;29;30;2;15;5
r

 GDFILE   = $fmdl2
 CLEAR    = y
 DEVICE   = GIF|${cyc}rap322m00.gif|850;900
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 13.;-146.;69.;-40.
r

 GDPFUN   = tmpf
 CLEAR    = n
 TITLE    = 1/-1/~   RAP 2-M  TEMP
# FINT     = -48;-40;-32;-24;-16;-8;0;8;16;24;32;40;48;56;64;72;80;88;96
 FINT     = -32;-24;-16;-8;0;8;16;24;32;40;48;56;64;72;80;88;96;104;112
 FINT     = 15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110;115
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 PANEL    = t
r

ex
EOF
done
gpend

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdmedr/.
exit
