#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

mkdir /stmpp1/wx20mg/gempak.rap13/850d
rm /stmpp1/wx20mg/gempak.rap13/850d/*
cd /stmpp1/wx20mg/gempak.rap13/850d
cp /meso/save/wx20mg/casework/coltbl.xwp .

hours="00 01 02 03 04 05 06 07 08 09 12 15 18"
for fhr in $hours; do
fmdl1=/ptmpp1/wx20mg/test/rap13x_${da00}${hr00}
fmdl2=/com/nawips/prod/ruc2.${da00}/ruc13_${da00}${hr00}f0${fhr}

echo $fmdl1
echo $fmdl2

    gdcntr << EOF

 GDFILE   = ${fmdl1}+${fmdl2}
 GDATTIM  = f${fhr} 
 GLEVEL   = 850 
 GVCORD   = pres 
 GFUNC    = sub(hght+2),hght) 
 CINT     = 1 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ ${fhr}-HR   RUC2 - RAPX   850 mb Z 
 DEVICE   = GIF|compare850d_${cyc}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./1;1;1;1
 GAREA    = 16.;-126.;55.;-57.
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.10;0.95/.55;.015/
 CONTUR   = 0
 SKIP     = 0
 FINT     = -40;-30;-20;-10;10;20;30;40 
 FLINE    = 2;17;10;5;0;21;23;4;2
 CTYPE    = f 
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
export w3=emcmmb
export w4=$web


ftp -n -v << EOF > /meso/save/wx20mg/gempak.rap13/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/test
prompt
mput *.gif
bye
EOF

exit
