#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/10w
rm /stmp/wx20mg/meg/10w/*
cd /stmp/wx20mg/meg/10w
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=2013012900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Tue

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="00 06 12 18 24 30 36 42 48 54 60"
hours="06 12 18 24 30 36 42 48"
hours="03 09"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
#fmdl1=/meso/save/wx20mg/meg/namnest_${ymdh}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|conusnest10w_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-110.;25./2;2;1;1
 GAREA    = 40.2;-113.7;42.2;-111.1  
 GAREA    = co+
 TITLE    = 1//~  NAM CONUS NEST 10m WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.06;0.94/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;4;26;22;5;10;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /6;6
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

 PANEL    = B
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = knts(gust)
 TITLE    = 1//~  NAM CONUS NEST WIND GUST (KT)
 TYPE     = f
r

ex
EOF

done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
mput *gif 
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
mput *gif
bye
EOF

rm *gif
exit
