#!/bin/sh
echo 'into'

cyc=$1

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/2dewz
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/2dewz/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/2dewz
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/casework/coltbl.xwp .

ymdh=2023031600
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold

times="00 03 06 09 12"
times="00 06 12 18 24"
times="00 06 12 15 18 21 24"
times="06 12 15 18 21 24 30"
times="09 12 15 18 21 24 27 30"
times=" 09"
for fhr in $times; do

validtime="`/lfs/h2/emc/vpppg/save/geoffrey.manikin/meteograms.nam/advtime ${ymdh} ${fhr} -1`"
vymd=`echo $validtime | cut -c3-8`
vcyc=`echo $validtime | cut -c9-10`

cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/gfs_0p25_${ymdh}f0${fhr} fmdl
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/nam32_${ymdh}f0${fhr} fmdl2
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/nam_conusnest_${ymdh}f0${fhr} fmdl3
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/hrrr_${ymdh}f0${fhr}00 fmdl4
cp /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/dews/urma2p5_${validtime}f000 fmdlver

    gdplot2 << EOF
 GDFILE   = fmdlver + fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = sub(dwpf+2^${ymd}/${cyc}f0${fhr},dwpf^${vymd}/${vcyc}00)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS - URMA  2-M  DEW PT 
 DEVICE   = GIF|2dewzgfserrs_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-78;25;/1;1;1;1
 GAREA    = 36.;-85.;45.;-71. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.96/0.9;.03/1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -18;-15;-12;-9;-6;-3;3;6;9;12;15;18
 FLINE    = 15;2;17;10;20;5;0;21;23;26;4;28;30
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdlver + fmdl2
 TITLE    = 1/-1/~   NAM - URMA  2-M  DEW PT
 DEVICE   = GIF|2dewznamerrs_${ymdh}f0${fhr}.gif|850;900
r

 GDFILE   = fmdlver + fmdl3
 TITLE    = 1/-1/~   NAM3 - URMA  2-M  DEW PT
 DEVICE   = GIF|2dewznam3errs_${ymdh}f0${fhr}.gif|850;900
r

 GDFILE   = fmdlver + fmdl4
 TITLE    = 1/-1/~   HRRR - URMA  2-M  DEW PT
 DEVICE   = GIF|2dewzhrrrerrs_${ymdh}f0${fhr}.gif|850;900
r  


ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test9/.
exit
