#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/gefspcpprob
rm /stmpp1/Geoffrey.Manikin/meg/gefspcpprob/*
cd /stmpp1/Geoffrey.Manikin/meg/gefspcpprob
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015021321
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold3

if [ $cycs -eq 03 ]; then
 hours="33 57 81"
elif [ $cycs -eq 09 ]; then
 hours="27 51 75"
elif [ $cycs -eq 15 ]; then
 hours="45 69"
else
 hours="45"
fi

for fhrs in $hours; do

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/sref.${ymd}/sref212_${ymdh}_prob
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = P12M0006PA 
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    SREF PROB of 0.25"
 DEVICE   = GIF|${cycs}srefprob1_12pcp_f0${fhrs}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROOJ    = lcc/25;-70;25;/1;1;1;1
# GAREA    = 20.;-138.;52.;-48.
 GAREA    = ri
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r


 GDPFUN  = P12M0012PA 
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 0.5"
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1 
r

 GDPFUN  = P12M0025PA
 PANEL   = t
 TITLE   = 1/-1/~    SREF PROB of 1"
 DEVICE  = GIF|${cycs}srefprob2_12pcp_f0${fhrs}.gif|750;900
 CLEAR   = y
 CLRBAR  = 0 
r

 GDPFUN  = P12M0050PA
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 2"
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1
r

 GDPFUN  = P12M0101PA
 PANEL   = t
 TITLE   = 1/-1/~    SREF PROB of 4"
 DEVICE  = GIF|${cycs}srefprob3_12pcp_f0${fhrs}.gif|750;900
 CLEAR   = y
 CLRBAR  = 0
r

 GDPFUN  = P12M0152PA
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 6"
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1
r

ex
EOF

gpend
done
#mv ${cycs}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
