#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slptrsref
rm /stmpp1/Geoffrey.Manikin/meg/slptrsref/*
cd /stmpp1/Geoffrey.Manikin/meg/slptrsref
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`echo $ymdh | cut -c1-8`
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cyc1=`echo $ymdhs | cut -c9-10`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -9 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -15 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -21 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

hours="03 09 15 21 27 33 39 45 51 57 63 69 75"
for fhr1 in $hours; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr1 fhr2 fhr3 fhr4

fmdl1=/com2/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean
fmdl2=/com2/nawips/prod/sref.${ymd2}/sref212_${ymdh2}_mean
fmdl3=/com2/nawips/prod/sref.${ymd3}/sref212_${ymdh3}_mean
fmdl4=/com2/nawips/prod/sref.${ymd4}/sref212_${ymdh4}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmslenmw 
 CINT     = 4 
 LINE     = 4/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  SREF MEAN SLP  $ymd1 ${cyc1}z  F${fhr1}
 DEVICE   = GIF|srefslptr${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 18.;-130.;58.;-60.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1015-1060;920-1014/5/3;3/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  SREF MEAN SLP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  SREF MEAN SLP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  SREF MEAN SLP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done
mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
