#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/87pcpsrefmem
rm /stmp/Geoffrey.Manikin/meg/87pcpsrefmem/*
cd /stmp/Geoffrey.Manikin/meg/87pcpsrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013091103
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Wed
DAPATH=/com/nawips/prod/sref.${ymd}
DAPATH=/ptmp/Geoffrey.Manikin/hold
hours="87"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do
 
fmdl1=${DAPATH}/sref212_${ymdh}_${mdl}_ctl
fmdl2=${DAPATH}/sref212_${ymdh}_${mdl}_p1
fmdl3=${DAPATH}/sref212_${ymdh}_${mdl}_p2
fmdl4=${DAPATH}/sref212_${ymdh}_${mdl}_p3
fmdl5=${DAPATH}/sref212_${ymdh}_${mdl}_n1
fmdl6=${DAPATH}/sref212_${ymdh}_${mdl}_n2
fmdl7=${DAPATH}/sref212_${ymdh}_${mdl}_n3


    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p87i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1/1/2;1
 \$MAPFIL = county
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 33.9;-111.4;42.9;-98.
 WIND     = 0
 TITLE    = 1//  $mdl CTL 87-HR PCP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}87pcp_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.6/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8;10
 FLINE    = 0;21;22;23;4;25;27;28;29;30;15;2;11;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1// $mdl P1 87-HR PCP  $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = $fmdl3
 TITLE    = 1// $mdl P2 87-HR PCP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = $fmdl4
 TITLE    = 1// $mdl P3 87-HR PCP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = $fmdl5
 TITLE    = 1// $mdl N1 87-HR PCP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = $fmdl6
 TITLE    = 1// $mdl N2 87-HR PCP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = $fmdl7
 TITLE    = 1// $mdl N3 87-HR PCP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/2.1;.06/2
r

ex
EOF
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/coflood/$dayoweek/.
exit
