#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak


mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/scape
rm /stmpp1/Geoffrey.Manikin/meg/scape/*
cd /stmpp1/Geoffrey.Manikin/meg/scape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016052412
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold7

fhr1=108
fhr2=114
fhr3=120
fhr4=126

DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/gfs.${ymd}
fmdl1=${DAPATH}/gfs_0p25_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/gfs_0p25_${ymdh}f0${fhr2}
fmdl3=${DAPATH}/gfs_0p25_${ymdh}f0${fhr3}
fmdl4=${DAPATH}/gfs_0p25_${ymdh}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS  SFC-BASED CAPE 
 DEVICE   = GIF|${ymdh}_gfssfccapez${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = mi+
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 PANEL    = ur
 GDATTIM  = f${fhr2}
 CLEAR    = n
r

 GDFILE   = $fmdl3
 PANEL    = ll
 GDATTIM  = f${fhr3}
 CLRBAR   = 1/H/UL/.38;0.94/1.4;.02/2
r

 GDFILE   = $fmdl4
 PANEL    = lr
 GDATTIM  = f${fhr4}
 CLRBAR   = 0
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
