#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/2mtsrefmem
rm /stmp/Geoffrey.Manikin/meg/2mtsrefmem/*
cd /stmp/Geoffrey.Manikin/meg/2mtsrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014021215
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Wed

DAPATH=/com/sref/prod/sref.${ymd}/${cyc}/pgrb/
#DAPATH=/ptmp/Geoffrey.Manikin/hold/pgrb/.
#DAPATH=/ptmp/Jun.Du/com/sref/prod/sref.${ymd}/${cyc}/pgrb 
hours="00 03"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -i -grib -o mdl1
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -i -grib -o mdl2
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -i -grib -o mdl3
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -i -grib -o mdl4
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -i -grib -o mdl5
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -i -grib -o mdl6
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} | grep kpds5=11:kpds6=1:kpds7=0:TR=0 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -i -grib -o mdl7

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL SKIN T   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}skin_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 26.;-106.;50.;-76.
# GAREA    = 40.;-90.;50.;-74. 
 GAREA    = de 
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
# FINT     = -16;-12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60
 FINT     = -10;-5;0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
# FINT     = -33;-28;-23;-18;-13;-8;-3;2;7;12;17;22;27;32;37;42;47;52;57;62;67
# FLINE    = 0;11;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 1// $mdl P1 SKIN T   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = mdl3.gem
 TITLE    = 1// $mdl P2 SKIN T   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = mdl4.gem
 TITLE    = 1// $mdl P3 SKIN T   $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = mdl5.gem
 TITLE    = 1// $mdl N1 SKIN T   $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = mdl6.gem
 TITLE    = 1// $mdl N2 SKIN T   $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = mdl7.gem
 TITLE    = 1// $mdl N3 SKIN T   $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
rm mdl*
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
