#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

stations="722010 722150 724030 725010 722500 723630 723570 724560 726320 745600 727470 726620 723870 725720 727970 722740"

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch12/snd12
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch12/snd12
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="12"
counter=0
for fhr in $times; do

validtime="`/meso/save/Geoffrey.Manikin/gempak.rap13/advtime ${da00}${hr00} $fhr -1 x`"
dattim=`echo $validtime | cut -c5-11`
dattim=02/03
for stnm in $stations; do

fmdl1=/com/nawips/prod/rap.${ymd}/rap_${ymd}${cyc}.snd 
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap_${ymd}${cyc}.snd 
echo $fmdl
echo $fmdl2

    snprof << EOF
 SNFILE   = $fmdl1 
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/5
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = lift;cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1// $stnm   SOLID-RUC  DASHED-RAP
 DEVICE   = gif|rapsnd12_${cyc}f${counter}.gif|750;850
 YAXIS    = 1050/450/100/1;1;1
 XAXIS    = -25/35/10/;1
 FILTER   = 0.6
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2 
 LINE     = 2;4/2/4
 CLEAR    = n
 WINPOS   = 2
 TITLE    = 0
r 
 
ex
EOF

gpend
counter=`expr $counter + 1`
done
done

mv *gif ../../ftphold/.
echo abouttoexitsnd12
exit
