#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/6snowtrecmwf
rm /stmp/Geoffrey.Manikin/meg/6snowtrecmwf/*
cd /stmp/Geoffrey.Manikin/meg/6snowtrecmwf
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh1=2013111200
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Tue
hours="12 18 24 30 36"

ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} ${fhr1} -1`"
fhr2=`expr $fhr1 + 12`
typeset -Z2 fhr2 fhr3 fhr4

fhrminus6=`expr $fhr1 - 6`
fhr2minus6=`expr $fhr2 - 6`
typeset -Z2 fhrminus6 fhr2minus6 

fhrminus6=`expr $fhr1 - 6`
fhr2minus6=`expr $fhr2 - 6`
typeset -Z2 fhrminus6 fhr2minus6

fmdl1=/com/nawips/prod/ecmwf.${ymd1}/ecmwf_hr_${ymdh1}f0${fhr1}
cp /com/nawips/prod/ecmwf.${ymd1}/ecmwf_hr_${ymdh1}f0${fhrminus6} file1a
fmdl2=/com/nawips/prod/ecmwf.${ymd2}/ecmwf_hr_${ymdh2}f0${fhr2}
cp /com/nawips/prod/ecmwf.${ymd2}/ecmwf_hr_${ymdh2}f0${fhr2minus6} file2a
fmdl3=/com/nawips/prod/ecmwf.${ymd3}/ecmwf_hr_${ymdh3}f0${fhr3}

    gdplot2 << EOF
 GDFILE   = file1a + $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sub(snow^${ymd1}/${cyc1}f$fhr1+2,snow^${ymd1}/${cyc1}f${fhrminus6}),10000),25.4)
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  ECMWF 6-HR SNOW  ${ymd1} ${cyc1}z  F${fhr1}
 DEVICE   = GIF|ecmwf6snowtr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = ny- 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.92/1.6;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .1;1;2;3;4;6;8;10;15;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = file2a + $fmdl2 
 GDATTIM  = f${fhr2}
 TITLE    = 1//  ECMWF 6-HR SNOW  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = quo(mul(sub(snow^${ymd2}/${cyc2}f$fhr2+2,snow^${ymd2}/${cyc2}f${fhr2minus6}),10000),25.4)
 CLRBAR   = 0
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/medr/images_medr/$dayoweek/.

exit
