#!/bin/ksh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/nestsnow
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/nestsnow/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/nestsnow
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2021050900
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

ymdh1="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh2="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh3="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

fhr1=15
fhr2=21
fhr3=27
fhr4=33
typeset -Z2 fhr1 fhr2 fhr3 fhr4
#DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
#DAPATH=/gpfs/dell2/emc/verification/noscrub/Geoffrey.Manikin/nov18storm
DAPATH=/gpfs/dell1/nco/ops/com/nam/prod/
DAPATH=/gpfs/dell2/emc/verification/noscrub/Geoffrey.Manikin/mayilsnow/
fmdl1=${DAPATH}/nam.${ymd}/gempak/nam_conusnest_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/nam.${ymd1}/gempak/nam_conusnest_${ymdh1}f0${fhr2}
fmdl3=${DAPATH}/nam.${ymd2}/gempak/nam_conusnest_${ymdh2}f0${fhr3}
fmdl4=${DAPATH}/nam.${ymd3}/gempak/nam_conusnest_${ymdh3}f0${fhr4}

fmdl1=${DAPATH}/nam_conusnest_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/nam_conusnest_${ymdh1}f0${fhr2}
fmdl3=${DAPATH}/nam_conusnest_${ymdh2}f0${fhr3}
fmdl4=${DAPATH}/nam_conusnest_${ymdh3}f0${fhr4}
echo $fmdl1

garea="39.;-94.;45.;-82."
proj="lcc/25.;-90.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(swem15,.394)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}nestsnow10-1_f${fhr1}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z NAM3  ${fhr1}-HR ACC SNOW 10:1
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.8/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5
 FINT     = 0.1;1;2;4;6;8;10;12;15;20;25
 FLINE    = 0;28;26;4;21;23;20;5;10;17;2;15;9
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 GDPFUN   = mul(swem21,.394)
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z NAM3  ${fhr2}-HR ACC SNOW 10:1 
 CLRBAR   = 1/H/UL/.02;0.97/1.9;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 GDPFUN   = mul(swem27,.394)
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z NAM3  ${fhr3}-HR ACC SNOW 10:1 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 GDPFUN   = mul(swem33,.394)
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z NAM3  ${fhr4}-HR ACC SNOW 10:1 
 CLRBAR   = 0
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test6/.
exit
