#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/refc
rm /stmpp1/Geoffrey.Manikin/meg/refc/*
cd /stmpp1/Geoffrey.Manikin/meg/refc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015111600
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2
counter=0

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30"
hours="21 24 27"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
#fmdl1=/ptmp/Geoffrey.Manikin/hold/conusnest_${ymdh}f0${fhr}
fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|conusnestrefc_${ymdh}f${counter}.gif | 800;850
 PROJ     = lcc/25.;-100.;25./2;2;1;1
 GAREA    = 34.;-105.;40.;-96.
 TITLE    = 1//~  NAM CONUS NEST COMPOSITE REF 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.06;0.94/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;24;4;26;23;22;21;20;5;10;17;2;15;29
 TYPE     = f 
r

ex
EOF

counter=`expr $counter + 1`
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
