#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
rm /stmpp1/Geoffrey.Manikin/meg/hiresrefcx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresrefcx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016050919
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

hours="00 01 02 03 04 05"
hours="06 09 12"
hours="00 01 02 03 04 05 06"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`

cyc1=`expr $cyc - 1`
cyc2=`expr $cyc - 2`
cyc3=`expr $cyc - 3`

fhr1=`expr $fhr + 1`
fhr2=`expr $fhr + 2`
fhr3=`expr $fhr + 3`

typeset -Z2 fhr1 fhr2 fhr3
fmdl1=/com2/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=/com2/nawips/para/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr1}00
fmdl3=/com2/nawips/para/hrrr.${ymd2}/hrrr_${ymdh2}f0${fhr2}00
fmdl4=/com2/nawips/para/hrrr.${ymd3}/hrrr_${ymdh3}f0${fhr3}00

garea="30.;-103.;40.5;-90."
garea="ok+"
proj="lcc/25.;-98;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrrxefc_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL  = county
 TITLE    = 1//~  ${cyc}z HRRRX   REFC
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70
 FLINE    = 0;27;26;4;21;22;23;5;20;17;16;15;14;7;29
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr1
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z HRRRX   REFC 
 CLRBAR   = 1/H/UL/.46;0.96/1.1;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr2
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z HRRRX   REFC 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr3
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z HRRRX   REFC 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefc/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
