#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500trgfs
rm /stmpp1/Geoffrey.Manikin/meg/500trgfs/*
cd /stmpp1/Geoffrey.Manikin/meg/500trgfs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymdh5="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -24 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
ymd5=`echo $ymdh5 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`
cyc5=`echo $ymdh5 | cut -c9-10`

times="96 108 120 132 144 156 168 180"
for fhr1 in $times; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
fhr5=`expr $fhr1 + 24`
typeset -Z3 fhr1 fhr2 fhr3 fhr4 fhr5

fmdl1=/com2/nawips/prod/gfs.${ymd1}/gfs_${ymdh}f${fhr1}
fmdl2=/com2/nawips/prod/gfs.${ymd2}/gfs_${ymdh2}f${fhr2}
fmdl3=/com2/nawips/prod/gfs.${ymd3}/gfs_${ymdh3}f${fhr3}
fmdl4=/com2/nawips/prod/gfs.${ymd4}/gfs_${ymdh4}f${fhr4}
fmdl5=/com2/nawips/prod/gfs.${ymd5}/gfs_${ymdh5}f${fhr5}

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 500 
 GVCORD   = pres
 GFUNC    = sub(hght^${ymd1}/${cyc1}f${fhr1}+2,hght^${ymd2}/${cyc2}f${fhr2})
 CINT     = 0 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1// GFS 500Z  $ymd1${cyc} F${fhr1}  -  $ymd2${cyc2} F${fhr2}
 DEVICE   = GIF|gfs500trdiff${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-105;25;/1;1;1;1
 GAREA    = 10.;-144.;72.;-36. 
 CLEAR    = y
 PANEL    = ul
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = -250;-200;-150;-100;-50;50;100;150;200;250
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl3+$fmdl2
 GDATTIM  = f${fhr2}
 GFUNC    = sub(hght^${ymd2}/${cyc2}f${fhr2}+2,hght^${ymd3}/${cyc3}f${fhr3})
 TITLE    = 1// GFS 500Z  $ymd2${cyc2} F${fhr2}  -  $ymd3${cyc3} F${fhr3}
 PANEL    = ur 
 CLEAR    = n
r

 GDFILE   = $fmdl4+$fmdl3
 GDATTIM  = f${fhr3}
 GFUNC    = sub(hght^${ymd3}/${cyc3}f${fhr3}+2,hght^${ymd4}/${cyc4}f${fhr4})
 TITLE    = 1// GFS 500Z  $ymd3${cyc3} F${fhr3}  -  $ymd4${cyc4} F${fhr4}
 PANEL    = ll 
r

 GDFILE   = $fmdl5+$fmdl4
 GDATTIM  = f${fhr4}
 GFUNC    = sub(hght^${ymd4}/${cyc4}f${fhr4}+2,hght^${ymd5}/${cyc5}f${fhr5})
 TITLE    = 1// GFS 500Z  $ymd4${cyc4} F${fhr4}  -  $ymd5${cyc5} F${fhr5}
 PANEL    = lr
r

ex
EOF
gpend
done

mv *gif /stmpp1/Geoffrey.Manikin/meg/holdmedr/.
exit
