#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slptrgfsdiff
rm /stmpp1/Geoffrey.Manikin/meg/slptrgfsdiff/*
cd /stmpp1/Geoffrey.Manikin/meg/slptrgfsdiff
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymdh5="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -24 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
ymd5=`echo $ymdh5 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`
cyc5=`echo $ymdh5 | cut -c9-10`

times="00 06 12 18 24 30 36 42 48 54 60 66 72"
for fhr1 in $times; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
fhr5=`expr $fhr1 + 24`
typeset -Z2 fhr2 fhr3 fhr4 fhr5

fmdl1=/com2/nawips/prod/gfs.${ymd1}/gfs40_${ymdh}f0${fhr1}
fmdl2=/com2/nawips/prod/gfs.${ymd2}/gfs40_${ymdh2}f0${fhr2}
fmdl3=/com2/nawips/prod/gfs.${ymd3}/gfs40_${ymdh3}f0${fhr3}
fmdl4=/com2/nawips/prod/gfs.${ymd4}/gfs40_${ymdh4}f0${fhr4}
fmdl5=/com2/nawips/prod/gfs.${ymd5}/gfs40_${ymdh5}f0${fhr5}

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = sub(emsl^${ymd1}/${cyc1}f${fhr1}+2,emsl^${ymd2}/${cyc2}f${fhr2})
 CINT     = 0 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1// GFS SLP  $ymd1${cyc} F${fhr1}  -  $ymd2${cyc2} F${fhr2}
 DEVICE   = GIF|gfsslptrdiff${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = -15;-12;-9;-6;-3;3;6;9;12;15
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl3+$fmdl2
 GDATTIM  = f${fhr2}
 GFUNC    = sub(emsl^${ymd2}/${cyc2}f${fhr2}+2,emsl^${ymd3}/${cyc3}f${fhr3})
 TITLE    = 1// GFS SLP  $ymd2${cyc2} F${fhr2}  -  $ymd3${cyc3} F${fhr3}
 PANEL    = 0.52;0.42;1.;1.
 CLEAR    = n
r

 GDFILE   = $fmdl4+$fmdl3
 GDATTIM  = f${fhr3}
 GFUNC    = sub(emsl^${ymd3}/${cyc3}f${fhr3}+2,emsl^${ymd4}/${cyc4}f${fhr4})
 TITLE    = 1// GFS SLP  $ymd3${cyc3} F${fhr3}  -  $ymd4${cyc4} F${fhr4}
 CLRBAR   = 1/H/UL/.5;.86/.99;.02/-1
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl5+$fmdl4
 GDATTIM  = f${fhr4}
 GFUNC    = sub(emsl^${ymd4}/${cyc4}f${fhr4}+2,emsl^${ymd5}/${cyc5}f${fhr5})
 TITLE    = 1// GFS SLP  $ymd4${cyc4} F${fhr4}  -  $ymd5${cyc5} F${fhr5}
 CLRBAR   = 0
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done
mv *gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
exit
