#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/caperap
rm /stmp/Geoffrey.Manikin/meg/caperap/*
cd /stmp/Geoffrey.Manikin/meg/caperap
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013041721
#ymd=20130417
#dayoweek=Wed

times="15"
#times="00"
for fhr in $times; do

fmdl1=/com/nawips/prod/rap.${ymd}/rap20_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP SFC-BASED CAPE 
 DEVICE   = GIF|${cyc}caperap${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
# GAREA    = 25.;-105.;46.;-83.
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ok 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.15;0.95/0.7;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

rm *gif
exit
