#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hirespcpx
rm /stmpp1/Geoffrey.Manikin/meg/hirespcpx/*
cd /stmpp1/Geoffrey.Manikin/meg/hirespcpx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2019070700
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold9

hours="18"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

typeset -Z2 fhr1 fhr2 fhr3
DAPATH=/gpfs/hps/nco/ops/com/hrrr/prod/
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/hold
fmdl1=${DAPATH}/hrrr.${ymd}/conus/nawips/hrrr_${ymdh}f0${fhr}00
fmdl2=${DAPATH}/hrrr.${ymd1}/conus/nawips/hrrr_${ymdh1}f0${fhr}00
fmdl3=${DAPATH}/hrrr.${ymd2}/conus/nawips/hrrr_${ymdh2}f0${fhr}00
fmdl4=${DAPATH}/hrrr.${ymd3}/conus/nawips/hrrr_${ymdh3}f0${fhr}00

garea="44.;-124.;47.;-120."
garea="32.4;-123.;38.8;-114."
garea="33.;-103.;39.;-93."
garea="37.4;-79.;40.6;-75."
proj="lcc/25.;-75.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p18i 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrpcp_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL = county
 TITLE    = 1//~  ${cyc}z HRRR   18-HR TOT PCP
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
# FINT     = .01;.1;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;6;8
#  FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15
 FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;6;8;10
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z HRRR   18-HR TOT PCP 
 CLRBAR   = 1/H/UL/.02;0.97/2.0;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z HRRR   18-HR TOT PCP 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z HRRR   18-HR TOT PCP 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdpcp/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
