#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/750w
rm /stmpp1/Geoffrey.Manikin/meg/750w/*
cd /stmpp1/Geoffrey.Manikin/meg/750w
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017031312
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="24 25 26 27 28 29 30"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 750
 GVCORD   = pres
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|conusnest750w_${ymdh}f0${fhr}.gif | 800;850
 PROJ     = lcc/25.;-73.;25./2;2;1;1
# GAREA    = 34.;-92.;46.;-70. 
 GAREA    = 38.;-80.;46.;-66. 
 TITLE    = 1//~  NAM CONUS NEST 750 MB  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.06;0.94/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = 20;30;40;50;60;70;80;90;100
 FLINE    = 0;29;4;26;22;5;10;17;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.7/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /7;7
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
