#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcp
rm /stmpp1/Geoffrey.Manikin/meg/6pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016092812
ymd1=`echo $ymdh | cut -c1-8`
dayoweek=hold2

fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f12 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = p12i 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 12-HR PCP 
 DEVICE   = GIF|nam12pcp_${ymd1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = md
 CLEAR    = y
 PANEL    = t 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.5/.75;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 PANEL    = b 
 CLEAR    = n
 GDATTIM  = f24
 CLRBAR   = 0
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
