#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/gusttrnam4
rm /stmpp1/Geoffrey.Manikin/meg/gusttrnam4/*
cd /stmpp1/Geoffrey.Manikin/meg/gusttrnam4
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015100918
ymd1=`echo $ymdh | cut -c1-8`
cyc1=`echo $ymdh | cut -c9-10`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold4

hours="06"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fmdl1=/com/nawips/prod/nam.${ymd1}/nam_conusnest_${ymdh}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd2}/nam_conusnest_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd3}/nam_conusnest_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd4}/nam_conusnest_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = knts(gust)
 CINT     = 10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  4 KM NAM GUST  $ymd1 ${cyc1}z  F${fhr1}
 DEVICE   = GIF|nam4gusttr_${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-124;25;/1;1;1;1
 GAREA    = 42.;-139.;56.;-117.  
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.2;0.92/1.7;.02/1
 CONTUR   = 0
 SKIP     = 0
# FINT     = 10;20;30;40;50;60;70;80 
# FLINE    = 0;25;21;22;23;5;10;17;16;10;2;15;32
# FINT     = 20;30;40;50;60;70;80;90;100
 FINT      = 10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;30;28;27;25;23;21;5;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  4 KM NAM GUST  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  4 KM NAM GUST  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  4 KM NAM GUST  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
done

for fhr1 in $hours; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fmdl1=/com/nawips/prod/nam.${ymd1}/nam20_${ymdh}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd2}/nam20_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd3}/nam20_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd4}/nam20_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1}
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAM GUST  $ymd1 ${cyc1}z  F${fhr1}
 DEVICE   = GIF|namgusttr_${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.2;0.92/1.7;.02/1
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM GUST  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  NAM GUST  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  NAM GUST  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
