#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/swem
rm /stmp/wx20mg/meg/swem/*
cd /stmp/wx20mg/meg/swem
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013011912
ymd=20130119
month=01
day=19
dayoweek=Sat

times="00"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam12_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl2=/ptmp/wx20mg/data/rap13_${ymdh}f0${fhr}

echo $fmdl1
echo $fmdl2

areas="1 2 3 4 5"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="26.;-124.;56.;-62."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="ct"
proj="lcc/25.;-80.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="ia-"
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="38.;-125.;52.;-109."
proj="lcc/25.;-105.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="30.;-122.;42.;-104."
proj="lcc/25.;-115.;25./2;2;1;1"
fi
    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(mul(sndm,100),2.54) 
 CINT     = 2 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|sndm${region}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = $proj 
 GAREA    = $garea 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.39;2;3.9;9.8;20;39;59;98;197;295
 FLINE    = 0;11;27;26;25;24;28;30;7;2;14
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR NAM SNOW COVER (IN)
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAP  SNOW COVER
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2
 GDPFUN   = quo(mul(sndm,100),2.54) 
 TITLE    = 0
 CINT     = 2 
r

ex
EOF
gpend
done
done

for fhr in $times; do
for region in $areas; do
/usrx/local/im_beta/bin/convert -crop 0x0 sndm${region}f${fhr}.gif rap2sndm${region}f${fhr}.gif 
done
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput rap*gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput rap*gif
bye
EOF

exit

