#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/12pcpz
rm /stmp/wx20mg/meg/12pcpz/*
cd /stmp/wx20mg/meg/12pcpz
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013041612
ymd=20130416
dayoweek=Tue

if [ $cyc -eq 00 ]; then
 hours="36 60 12"
elif [ $cyc -eq 06 ]; then
 hours="30 54 78"
elif [ $cyc -eq 12 ]; then
 hours="24 48 72"
else
 hours="42 66"
fi
hours="54"

for fhr in $hours; do

fhr6=`expr $fhr - 6`
fmdl1=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr6}

    gdplot2 << EOF
 GDFILE   = $fmdl1+$fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = add(p06i^${ymd}/${cyc}f${fhr6}+2,p06i^${ymd}/${cyc}f$fhr)
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 12-HR TOTAL PCP
 DEVICE   = GIF|12pcpmodels_f$fhr.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = ok 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5;6
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

for fhr in $hours; do
/usrx/local/im_beta/bin/convert -crop 0x0 12pcpmodels_f${fhr}.gif gfsp12pcp_${ymdh}f${fhr}.gif
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput gfs*gif
bye
EOF

rm *gif
exit
