#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/ecmwfsnow
rm /stmpp1/Geoffrey.Manikin/meg/ecmwfsnow/*
cd /stmpp1/Geoffrey.Manikin/meg/ecmwfsnow
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2018030112
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
dayoweek=hold9

hours="48"
for fhr1 in $hours; do
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`

fhr2=`expr $fhr1 + 12`

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} ${fhr1} -1`"
typeset -Z2 fhr1 fhr2 fhr3
DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
fmdl1=${DAPATH}/ecmwf.${ymd1}/ecmwf_0p25_${ymdh1}f0${fhr1}
fmdl2=${DAPATH}/ecmwf.${ymd2}/ecmwf_0p25_${ymdh2}f0${fhr2}

fmdl1a=${DAPATH}/ecmwf.${ymd1}/ecmwf_0p25_${ymdh1}f000
fmdl2a=${DAPATH}/ecmwf.${ymd2}/ecmwf_0p25_${ymdh2}f000

#garea="37.5;-81.;47.;-67."
#proj="lcc/25.;-74.;25./2;2;1;1"

garea="40.;-80.;46.;-70."
proj="lcc/25.;-75.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1a + $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(sub(snow+2,snow^${ymd1}/${cyc1}f000),39.37)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd1}${cyc1}ecmwfsnow_f${fhr1}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1// ${ymd1} ${cyc1}z ECMWF   ${fhr1}-HR ACC SNOW DPTH
 CLEAR    = y
 SCALE    = 0
 PANEL    = t 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28;32
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f 
r

 TITLE    = 15/1/     CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2a + $fmdl2
 GDATTIM  = f$fhr2
 GDPFUN   = mul(sub(snow+2,snow^${ymd2}/${cyc2}f000),39.37)
 PANEL    = b  
 CLEAR    = n
 TITLE    = 1//  ${ymd2} ${cyc2}z ECMWF   ${fhr2}-HR ACC SNOW DPTH 
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
