#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/2mt850trnam
rm /stmp/Geoffrey.Manikin/meg/2mt850trnam/*
cd /stmp/Geoffrey.Manikin/meg/2mt850trnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2013121318
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Fri
hours="24 27 30"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fmdl1=/com/nawips/prod/nam.${ymd1}/nam_conusnest_${ymdh}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd2}/nam_conusnest_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd3}/nam_conusnest_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd4}/nam_conusnest_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p03i
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  4 KM NAM 3-HR PCP  ${ymd1} ${cyc}z  F${fhr1}
 DEVICE   = GIF|namnest2mt850tr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = md 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.92/1.5;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = tmpc
 CINT     = 1/0/0
 LINE     = 29/1/3/0
 CLEAR    = n
 TYPE     = c
r

 GLEVEL   = 2
 GVCORD   = hght
 LINE     = 4/1/3/0
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 CLEAR    = n
 TITLE    = 1//  4 KM NAM 3-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = p03i
 CLRBAR   = 0
 TYPE     = f
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = tmpc
 CINT     = 1/0/0
 LINE     = 29/1/3/0
 CLEAR    = n
 TYPE     = c
r

 GLEVEL   = 2
 GVCORD   = hght
 LINE     = 4/1/3/0
r

 GDFILE   = $fmdl3 
 GDATTIM  = f${fhr3}
 GDPFUN   = p03i
 TITLE    = 1//  4 KM NAM 3-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
 TYPE     = f
r

 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = tmpc
 CINT     = 1/0/0
 LINE     = 29/1/3/0
 CLEAR    = n
 TYPE     = c
r

 GLEVEL   = 2
 GVCORD   = hght
 LINE     = 4/1/3/0
r

 GDFILE   = $fmdl4 
 GDATTIM  = f${fhr4}
 GDPFUN   = p03i
 TITLE    = 1//  4 KM NAM 3-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
 TYPE     = f
r

 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = tmpc
 CINT     = 1/0/0
 LINE     = 29/1/3/0
 CLEAR    = n
 TYPE     = c
r

 GLEVEL   = 2
 GVCORD   = hght
 LINE     = 4/1/3/0
 TITLE    = 2/1/   FREEZING LINES:  BLUE (SFC)  PURPLE (850)
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
