#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/slpsrefmem
rm /stmp/wx20mg/meg/slpsrefmem/*
cd /stmp/wx20mg/meg/slpsrefmem
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013032409
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Sun

hours="39"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

verymdh="`/meso/save/wx20mg/meteograms.nam/advtime ${ymdh} $fhr -1`"
verymd=`echo $verymdh | cut -c1-8`
 
fmdl1=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_ctl
fmdl2=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p1
fmdl3=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p2
fmdl4=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p3
fmdl5=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n1
fmdl6=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n2
fmdl7=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n3
fmdl8=/com/nawips/prod/gdas.${verymd}/gdas_${verymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 4 
 LINE     = 4/1/3/2
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL SLP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}slpv_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 28.;-88.;50.;-58.
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/1/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl P1 SLP  $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
 LINE     = 4/1/3/2 
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl P2 SLP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
 LINE     = 4/1/3/2
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl P3 SLP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
 LINE     = 4/1/3/2
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl5
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl N1 SLP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
 LINE     = 4/1/3/2
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl6
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl N2 SLP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 LINE     = 4/1/3/2
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

 GDFILE   = $fmdl7
 GDATTIM  = f${fhr}
 TITLE    = 1// $mdl N3 SLP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 LINE     = 4/1/3/2 
 HILO     = 23;23/S12#;S13#/1020-1060;920-1016/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

 GDFILE   = $fmdl8
 GDATTIM  = f00
 CLEAR    = n
 TITLE    = 0
 LINE     = 0
 HILO     = ;2/;x/;920-1016/5/1;1/yes
 HLSYM    = 2;0/3/;1/4;2/HW
r

ex
EOF
done
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
