#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dew
rm /stmpp1/Geoffrey.Manikin/meg/2dew/*
cd /stmpp1/Geoffrey.Manikin/meg/2dew
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2017031400
dayoweek=hold8
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

ymd=`echo $ymdh | cut -c1-8`
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="00 03 06 09 12 15 18"
times="18" 
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl3=/com2/nawips/para/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl4=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl5=/com2/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl6=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl7=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl8=/com2/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl9=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f0${fhr}
fmdl10=/com2/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sped) 
 CINT     = 0 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 10m WIND SPEED 
 DEVICE   = GIF|nam10w_${ymdh}${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = nj 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CONTUR   = 0
 SKIP     = 0
 CLRBAR   = 1/H/UL/.08;0.96/0.6;.03/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~   GFS 10m WIND SPEED
 DEVICE   = GIF|gfs10w_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl3
 TITLE    = 1/-1/~   NAMX 10m WIND SPEED
 DEVICE   = GIF|namx_${ymdh}${fhr}.gi.gif|850;950
r

 GDFILE   = $fmdl4
 TITLE    = 1/-1/~   GFSX 10m WIND SPEED
 DEVICE   = GIF|gfsx10w_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl5
 TITLE    = 1/-1/~   RAP 10m WIND SPEED
 DEVICE   = GIF|rap_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl6
 TITLE    = 1/-1/~   HRRR 10m WIND SPEED
 DEVICE   = GIF|hrrr_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl7
 TITLE    = 1/-1/~   OPS NAM NEST 10m WIND SPEED
 DEVICE   = GIF|namnest_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl8
 TITLE    = 1/-1/~   PARA NAM NEST 10m WIND SPEED
 DEVICE   = GIF|namxnest10w_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl9
 GVCORD   = none
 GLEVEL   = 0
 TITLE    = 1/-1/~   ECMWF 10m WIND SPEED
 DEVICE   = GIF|ecmwf10w_${ymdh}${fhr}.gif|850;950
r

 GDFILE   = $fmdl10
 GDATTIM  = f$fhrs
 GVCORD   = hght 
 GLEVEL   = 10
 TITLE    = 1/-1/~   SREF MEAN 10m WIND SPEED
 DEVICE   = GIF|sref10w_${ymdhs}${fhrs}.gif|850;950
 GDPFUN   = knts(spedenmw)
r

ex
EOF

gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
