#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2018051612
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold7

mkdir /stmpp1/Geoffrey.Manikin/dewcape
rm /stmpp1/Geoffrey.Manikin/dewcape/*
cd /stmpp1/Geoffrey.Manikin/dewcape
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="156"
for fhr in $times; do

typeset -Z3 fhr
fmdl1=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/hold/gfs20_${ymdh}f${fhr}
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparedew2_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-125.;25./2;2;1;1
 GAREA    = or 
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.9/.8;.03/-2
 TITLE    = 1/-1/~  GFS 0p25  2m DEW PT 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -30;-24;-18;-12;-6;0;6;12;18;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~    GFS20 2m DEW PT 
 CLEAR    = n
 PANEL    = b
r

ex
EOF

gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
