#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2dewrap
rm /stmpp1/Geoffrey.Manikin/meg/2dewrap/*
cd /stmpp1/Geoffrey.Manikin/meg/2dewrap
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017070812
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold5

guesstime="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdhg=`echo $guesstime | cut -c1-10`
ymdg=`echo $guesstime | cut -c1-8`
cycg=`echo $guesstime | cut -c9-10`

fmdl1=/com2/nawips/prod/nam.${ymd}/nam20_${ymdh}f000
fmdl2=/com2/nawips/prod/rap.${ymdg}/rap20_${ymdhg}f001

echo $fmdl1
echo $fmdl2
exit

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP ANL 2-M  DEW PT 
 DEVICE   = GIF|2dewmodels.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-115;25;/1;1;1;1
 GAREA    = 21.;-121.;51.;-65. 
# GAREA    = 32.;-106.;46.;-88.
# GAREA    = 36.;-114.;50.;-90. 
 GAREA    = az+
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT    = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f01
 TITLE    = 1/-1/~  RAP GUESS 2-M DEW PT 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

    gdcntr << EOF
 GDFILE   = $fmdl2 + $fmdl1
 GDATTIM  = f00
 GLEVEL   = 2  
 GVCORD   = hght 
 GFUNC    = sub(dwpf+2,dwpf^${ymdg}/${cycg}f001)
 CINT     = 2 
 LINE     = 1
 MAP      = 1
 WIND     = bk1/0.7/2/122
 TITLE    = 1//~ 2-M DEW PT (F)   ANL - GUESS 
 DEVICE   = GIF|2dewdiff.gif | 600;650
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/H/UL/.1;.9/.8;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -20;-16;-12;-8;-4;4;8;12;16;20
 FLINE    = 30;28;26;27;22;0;5;10;17;2;15
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 2dewmodels.gif 2dew1.gif
$CONV/convert -crop 0x0 2dewdiff.gif 2dew2.gif
$CONV/montage -geometry 800x850 2dew1.gif 2dew2.gif ${ymdh_}2dewrap_gesanl.gif

scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
