#!/bin/sh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/10wz
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

version=v16.2
ymdh=2022092412
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

times="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
times="00 03 06 12 18 24"
times="24 48 72 96"
for fhr in $times; do

#fmdl1=/lfs/h1/ops/prod/com/gfs/${version}/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymdh}f0${fhr}
fmdl1=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/gfs_0p25_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 2-M  DEW 
 DEVICE   = GIF|gfs2dew_${ymdh}f0${fhr}.gif|850;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = 22.;-95.;36.;-75. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.1;0.94/0.8;.02/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -15;-10;-5;0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85
# FINT     = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
# FINT     = -24;-18;-12;-6;0;6;12;18;24;30;;36;40;44;48;52;56;60;64;68;72;76;80
 FINT     = -30;-24;-18;-12;-6;0;6;12;18;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
# FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
rm *gif
exit
