#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold2

mkdir /stmpp1/Geoffrey.Manikin/meg/ice
cd /stmpp1/Geoffrey.Manikin/meg/ice
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00"
for fhr in $times; do

#fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymd}${cyc}f0${fhr}
fmdl1=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/nam.${ymd}/nam12_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = ice 
 CINT     = 0.5 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR NAM ICE 
 DEVICE   = GIF|namice_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = nj+ 
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.1;0.9 
 FLINE    = 0;4;4 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
