#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2017031112
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slp
rm /stmpp1/Geoffrey.Manikin/meg/slp/*
cd /stmpp1/Geoffrey.Manikin/meg/slp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

hours="60 66 72 78 84"
for fhr in $hours; do

typeset -Z3 fhr
fmdl1=/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f${fhr}
fmdl2=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f${fhr}
fmdl3=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 4 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SLP 1000-500 THK 
 DEVICE   = GIF|gfsslp_${ymdh}f${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-76;25;/1;1;1;1
 GAREA    = 20.;-110.;40.;-84.
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 24.;-95.;54.;-53. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1025-1060;920-1018/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

 GDFILE   = $fmdl2
 GVCORD   = none
 GLEVEL   = 0
 GDPFUN   = pmsl
 CINT     = 4
 LINE     = 4/1/3/1
 HILO     = 23;23/S12#;S13#/1025-1060;920-1018/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLEAR    = y 
 TITLE    = 1/-1/~   NAM SLP 1000-500 THK 
 TEXT     = 1.1/11/2/SW
 DEVICE   = GIF|namslp_${ymdh}f${fhr}.gif|850;950
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r
 
ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
