#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slptrnam
rm /stmpp1/Geoffrey.Manikin/meg/slptrnam/*
cd /stmpp1/Geoffrey.Manikin/meg/slptrnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017011018
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=hold5

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

times="06 12 18"
for fhr1 in $times; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

DAPATH=/com2/nawips/prod
DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/
fmdl1=${DAPATH}/nam.${ymd1}/nam20_${ymdh}f0${fhr1}
fmdl2=${DAPATH}/nam.${ymd2}/nam20_${ymdh2}f0${fhr2}
fmdl3=${DAPATH}/nam.${ymd3}/nam20_${ymdh3}f0${fhr3}
fmdl4=${DAPATH}/nam.${ymd4}/nam20_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = emsl 
 CINT     = 4 
 LINE     = 4/1/3/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAM SLP $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|namslptr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-122.;25./2;2;1;1
 GAREA    = 40.;-129.;48.;-117. 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.7/11/1/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 23;23/S12#;S13#/1025-1060;920-1024/5/3;3/yes
 HLSYM    = 1;1/3/21;21/1;1/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
 CLRBAR   = 0
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM SLP $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 PANEL    = 0;0;0.48;0.58
 TITLE    = 1//  NAM SLP $ymd3 ${cyc3}z  F${fhr3} 
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 PANEL    = 0.52;0;1.;0.58
 TITLE    = 1//  NAM SLP $ymd4 ${cyc4}z  F${fhr4}
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
