#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch1/850
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch1/850
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 850 
 GVCORD   = pres 
 GDPFUN   = quo(hght,10)
 CINT     = 3/104/164 
 LINE     = 29/1/3/3 
 MAP      = 1
 WIND     = 0 
 TITLE    = 0 
 DEVICE   = GIF|compare850_${cyc}f${counter}.gif|850;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1 
 GAREA    = grid 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.0/1/2
 SCALE    = 0
 LATLON   = 0
 HILO     = 1/S12#;S13#/155-180;110-140/7/4;4/yes 
 HLSYM    = 1;1/2/21;21/4;2/HW 
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = /6;6 
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = knts(sped)
 CINT     = 50;100
 LINE     = 0
 CLEAR    = n
 FINT     = 50;100
 FLINE    = 0;10;2
 TITLE    = 1/1/ RAP  ${fhr}-HR FCST 850 MB HGT/WIND (kt)
 TEXT     = 1.2/11/2
 TYPE     = f/c
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = kntv(wnd) 
 TYPE     = B
 WIND     = BK2/0.7/2/122
 TITLE    = 0
 HILO     = 0
 HLSYM    = 0
 CLEAR    = n
r

 TITLE    = 23/-1/ FCST MADE ${cyc}Z  ${month}/$day
 GDPFUN   = blurk
 TEXT     = 1.1/11/1/SW
 CLEAR    = n
r

 GDFILE   = $fmdl2 
 PANEL    = 0;0;1;.49
 GDPFUN   = quo(hght,10) 
 LINE     = 29/1/3/3
 CINT     = 3/104/164
 TEXT     = 1.0/1/2
 GAREA    = 16.;-126.;55.;-57.
 TITLE    = 0
 CLRBAR   = 0
 HILO     = 1/S12#;S13#/155-180;110-140/7/4;4/yes
 HLSYM    = 1;1/2/21;21/4;2/HW
 TYPE     = c
r

 GDPFUN   = knts(sped)
 CINT     = 50;100
 LINE     = 0
 CLEAR    = n
 FINT     = 50;100
 FLINE    = 0;10;2
 TYPE     = f/c
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = kntv(wnd) 
 TYPE     = b
 HILO     = 0  
 HLSYM    = 0 
 TEXT     = 1.2/11/2
 TITLE    = 1/1/ RAPX  ${fhr}-HR FCST 850 MB HGT/WINDS (kt) 
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexit850
exit
