#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak


mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6cpcp
rm /stmpp1/Geoffrey.Manikin/meg/6cpcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6cpcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016052412
ymd1=20160524
dayoweek=hold7

fmdl1=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}

fhr1=108
fhr2=114
fhr3=120
fhr4=126

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = c06i
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 6-HR CNVCT PCP 
 DEVICE   = GIF|gfs6cpcp_${ymdh}2.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
# GAREA    = 32.;-84.;48.;-62. 
 GAREA    = mi
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 PANEL    = ur 
 GDATTIM  = f${fhr2} 
 CLEAR    = n
r

 PANEL    = ll
 GDATTIM  = f${fhr3}
 CLRBAR   = 1/H/UL/.08;0.94/1.4;.02/2
r

 PANEL    = lr
 GDATTIM  = f${fhr4}
 CLRBAR   = 0
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
