#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/72pcptrgfs
rm /stmpp1/Geoffrey.Manikin/meg/72pcptrgfs/*
cd /stmpp1/Geoffrey.Manikin/meg/72pcptrgfs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017081918
ymd1=`echo $ymdh | cut -c1-8`
cyc1=`echo $ymdh | cut -c9-10`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold5

hours="210"
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
echo $fhr1 $fhr2
#typeset -Z3 fhr2 fhr3 fhr4
#typeset -Z2 fhr1 fhr2
typeset -Z3 fhr3 fhr4
echo $fhr2 $fhr3 $fhr4

DAPATH=/meso/save/Geoffrey.Manikin/meg/harvey
fmdl1=${DAPATH}/gfspcpmr_${ymdh}
fmdl2=${DAPATH}/gfspcpmr_${ymdh2}
fmdl3=${DAPATH}/gfspcpmr_${ymdh3}
fmdl4=${DAPATH}/gfspcpmr_${ymdh4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p66i
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1/1/2 + 1/1/1
# \$MAPFIL = 0
 \$MAPFIL = states + county
 WIND     = 0
 TITLE    = 1//  GFS 66-HR PCP  $ymd1 ${cyc1}z  F${fhr1}
 DEVICE   = GIF|gfs72pcptrz_${ymd1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 21.;-105.;35.;-87.
# GAREA    = 24.;-102.;34.;-88.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.04;0.92/2.0;.02/1|0.8/1 
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
# FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15;20
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5;1
 FINT     = 0.1;.5;1;2;4;6;8;10;15;20;25;30;35;40;50;60
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5;1
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
 CLRBAR   = 0
r

 CLEAR    = n
 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 GDPFUN   = p72i
 TITLE    = 1//  GFS 72-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLEAR    = n
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  GFS 72-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  GFS 72-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
