#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/2diffak
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/2diffak
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

cyc=`cut -c 15-16 /meso/save/Geoffrey.Manikin/gempak.rap13/NMCDATE`
echo $cyc

counter=0
times="00 01 02 03 06 09 12 15 18"
for fhr in $times; do

cp /com/nawips/prod/rap.${ymd}/rap32_${ymd}${cyc}f0${fhr} fmdl1
cp /ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap32_${ymd}${cyc}f0${fhr} fmdl2

    gdcntr << EOF
 GDFILE   = fmdl1 + fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght
 GFUNC    = sub(tmpf+2,tmpf) 
 CINT     = 3 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RAPX - RAP 2-M TEMP DIFFS 
 DEVICE   = GIF|compare2mak_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = str/90;-140;0;/1;1;1;1
 GAREA    = 42.;-172.;70.;-106.
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.9;0.9/.7;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -18;-15;-12;-9;-6;-3;3;6;9;12;15;18
 FLINE    = 30;28;4;25;23;21;0;5;10;17;2;15;11
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR  RAPX - RAP 2-M DEW POINT DIFFS
 TEXT     = 1.1/11/2/SW
 PANEL    = 0;0;1;.49
 GFUNC    = sub(dwpf+2,dwpf)
 FLINE    = 11;15;2;17;10;5;0;21;23;25;4;28;30
 CINT     = 3 
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

cyc=`cut -c 15-16 /meso/save/Geoffrey.Manikin/gempak.rap13/NMCDATE`
echo $cyc

/u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/gempak.rap13/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/para/${cyc}z/images
prompt
mput *.gif
bye
EOF


#mv *gif ../../ftphold/.
echo abouttoexit2mt
exit
