#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch2/925
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch2/925
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 925 
 GVCORD   = pres 
 GDPFUN   = relh 
 CINT     = 50;60;70;80;90 
 LINE     = 0 
 MAP      = 1
 WIND     = BK2/0.7/2/122 
 TITLE    = 0 
 DEVICE   = GIF|compare925_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.0/1/1
 SCALE    = 0 
 LATLON   = 0
 HILO     = 1/H#;L#/830-930;630-730/5/4;4/yes
 HLSYM    = 3;1//21;21/4;2/HW
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;60;70;80;90 
 FLINE    = 0;5;19;21;22;23 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = hght 
 CINT     = 30
 LINE     = 4/1/3/4
 TITLE    = 0
 CLEAR    = n
 HILO     = 0
 HLSYM    = 0
 FINT     = 0
 FLINE    = 0
 CTYPE    = c
r

 GDPFUN   = wnd
 TYPE     = b
 TITLE    = 0
r

 TITLE    = 1/1/ ${fhr}-HR RAP FCST 925 RH/HEIGHT/WIND
 TEXT     = 1.2/11/2
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day   
 TEXT     = 1.1/11/1/SW
r


 GDFILE   = $fmdl2
 TITLE    = 1/1/ ${fhr}-HR RAPX  FCST 925 RH/OMEGA/HEIGHT
 TEXT     = 1.2/11/2
 GAREA    = 16.;-126.;55.;-57.
 PANEL    = 0;0;1;.49
 CINT     = -2000/-2000/-2000
r

 GDATTIM  = f$fhr
 GLEVEL   = 925 
 GVCORD   = pres
 GDPFUN   = relh
 CINT     = 50;60;70;80;90
 LINE     = 0
 MAP      = 1
 TITLE    = 0
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 TEXT     = 1.0/1/1
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;60;70;80;90
 FLINE    = 0;5;19;21;22;23
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = hght
 LINE     = 4/1/3/4
 CINT     = 30
 TITLE    = 0
 HILO     = 0
 HLSYM    = 0
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 GDPFUN   = wnd
 TYPE     = b
 TITLE    = 0
r


exit
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexit925
exit
