#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /ptmpp1/wx20mg/animate
rm /ptmpp1/wx20mg/animate/*
cd /ptmpp1/wx20mg/animate

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -i << EOF > /meso/save/wx20mg/gempak.rap13/animate.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/para/00z 
prompt
mget trw*animate*
bye
EOF

ftp -n -i << EOF > /meso/save/wx20mg/gempak.rap13/animate.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/para/00z
prompt
mget *east*animate*
bye
EOF

mv trw.animate.html tmp1.html
mv 2mteast.animate.html tmp2.html

cycles="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
prev=00
for cyc in $cycles; do

cp tmp1.html trw.animate.html
cp tmp2.html 2mteast.animate.html

vi trw.animate.html << EOF > /dev/null
:1,\$ s/${prev}f/${cyc}f
:wq
EOF

vi 2mteast.animate.html << EOF > /dev/null
:1,\$ s/${prev}f/${cyc}f
:wq
EOF

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -i << EOF > /meso/save/wx20mg/gempak.rap13/ftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/para/${cyc}z
prompt
mput *animate* 
bye
EOF
done

exit
