#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/10soilmsrefmem
rm /stmp/wx20mg/meg/10soilmsrefmem/*
cd /stmp/wx20mg/meg/10soilmsrefmem
cp /meso/save/wx20mg/casework/coltbl.xwp .
cp /meso/save/wx20mg/meg/*tbl .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013051409
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Tue

DAPATH=/ptmp/wx20jd/com/sref/prod/sref.${ymd}/${cyc}/pgrb
hours="00"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -i -grib -o mdl1
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -i -grib -o mdl2
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -i -grib -o mdl3
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -i -grib -o mdl4
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -i -grib -o mdl5
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -i -grib -o mdl6
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} | grep kpds5=144:kpds6=112:kpds7=10 | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -i -grib -o mdl7

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 0:10 
 GVCORD   = dpth 
 GDPFUN   = soim 
 CINT     = 4 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1// $mdl CTL 0-10 SOILM  $ymd ${cyc}z F${fhr}
 DEVICE   = GIF|parasref${mdl}10soilm_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1
# GAREA    = 28.;-96.;48.;-60.
 GAREA    = mo-
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .02;.05;.1;.15;.2;.25;.3;.35;.4;.45;.5
 FLINE    = 0;18;16;17;10;5;20;21;22;23;27;4
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 1// $mdl P1 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m2 
r

 GDFILE   = mdl3.gem
 TITLE    = 1// $mdl P2 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m3 
r

 GDFILE   = mdl4.gem
 TITLE    = 1// $mdl P3 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m4
r

 GDFILE   = mdl5.gem
 TITLE    = 1// $mdl N1 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m5
r

 GDFILE   = mdl6.gem
 TITLE    = 1// $mdl N2 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = mdl7.gem
 TITLE    = 1// $mdl N3 0-10 SOILM  $ymd ${cyc}z F${fhr}
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
rm mdl*
done
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
