#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/cape
rm /stmpp1/Geoffrey.Manikin/meg/cape/*
cd /stmpp1/Geoffrey.Manikin/meg/cape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2018032000
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold10
counter=11

hours="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72"
for fhr in $hours; do

fmdl1=/com2/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|nam500slp${counter}.gif | 800;850
 PROJ     = lcc/25.;-74.;25./2;2;1;1
 GAREA    = 34.;-84.;48.;-66. 
 TITLE    = 1//~  NAM REFC SLP 
 CLEAR    = y
 SCALE    = 0
 PANEL    = l
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 1.1/11/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65
 FLINE    = 0;24;4;26;23;22;21;20;5;10;17;2;15;29
 TYPE     = f 
r

 GDPFUN   = pmsl
 CLEAR    = n
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 GVCORD   = pres
 GDPFUN   = avor
 GLEVEL   = 500 
 CINT     = 2/10/46
 PANEL    = r 
 SCALE    = 5
 LATLON   = 0
 PROJ     = lcc/25.;-74.;25./2;2;1;1
 GAREA    = 30.;-88.;58.;-4.
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CONTUR   = 0
 TITLE    = 1//~  NAM 500 mb
 SKIP     = 0
 FINT     = 20;24;28;32;36;40
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/3
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

ex
EOF

counter=`expr $counter + 1`
done
gpend
convert -loop 0 -delay 90 nam*gif nam_slp500loop_${ymdh}.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#rm *gif
exit
