#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

#da00=`cut -c 7-14 t${cyc}z`
#hr00=`cut -c 15-16 t${cyc}z`

#da00=20020214
#hr00=12

mkdir /stmpp1/wx20mg/gempak.rap13/direct2mt
rm /stmpp1/wx20mg/gempak.rap13/direct2mt/*
cd /stmpp1/wx20mg/gempak.rap13/direct2mt
cp /meso/save/wx20mg/casework/coltbl.xwp .

times="00 01 02 03 06 09 12"
counter=0
for fhr in $times; do

fmdl=/meso/save/wx20mg/gempak/nagribx/rap13x_${da00}${hr00}
#fmdl2=/nfsuser/g01/wx20mg/gempak/nagribx/ruc2x_${da00}${hr00}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|compare2mt_${cyc}f${counter}.gif 
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-100.;25./2;2;1;1
 GAREA    = grid 
 CLEAR    = y
! PANEL    = 0.;.51;1.;1.
 PANEL    = 0
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RUC2 2-M TEMP
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r
  
 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r
  
 TITLE    = 1/1/ ${fhr}-HR RUCX  2-M TEMP
 GDFILE   = $fmdl2
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
!r
  
 GDFILE   = $fmdl2
 GDPFUN   = tmpf
 TITLE    = 0
 CINT     = 5 
!r

ex
EOF

counter=`expr $counter + 1`
gpend
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
                                                                                        
ftp -n -v << EOF > /meso/save/wx20mg/gempak.rap13/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/rap13/para/${cyc}z/images
prompt
mput *.gif
bye
EOF

exit
