#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/2dewsrefmem
rm /stmp/wx20mg/meg/2dewsrefmem/*
cd /stmp/wx20mg/meg/2dewsrefmem
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013031609
ymd=`echo $ymdh | cut -c1-8`

DAPATH=/ptmp/wx20jd/com/sref/prod/sref.${ymd}/${cyc}/pgrb
hours="00 09"
models="nmm"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -grib -o mdl1
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -grib -o mdl2
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -grib -o mdl3
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -grib -o mdl4
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -grib -o mdl5
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -grib -o mdl6
wgrib -i -d 12 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -grib -o mdl7

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL 2-M DEW   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}2dew_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-90;25;/1;1;1;1
 GAREA    = 26.;-110.;48.;-70.
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 1// $mdl P1 2-M DEW   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = mdl3.gem
 TITLE    = 1// $mdl P2 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = mdl4.gem
 TITLE    = 1// $mdl P3 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = mdl5.gem
 TITLE    = 1// $mdl N1 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = mdl6.gem
 TITLE    = 1// $mdl N2 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = mdl7.gem
 TITLE    = 1// $mdl N3 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
rm mdl*
done
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/$ymd
mput *gif
bye
EOF

exit
