#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/rtma2mt
rm /stmpp1/Geoffrey.Manikin/meg/rtma2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/rtma2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymd=20190720
dayoweek=hold10

cycles="00 01 02 03 18 21 22 23"
for cyc in $cycles; do
fmdl1=/com2/rtma/prod/rtma2p5.${ymd}/nawips/rtma2p5_${ymd}${cyc}f000
#fmdl1=/ptmp/Geoffrey.Manikin/rtma/rtma_${ymdh}f000
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 0 
 LINE     = 1 
 MAP      = 1/1/2
 WIND     = 0
 TITLE    = 1/-1/~   2.5 RTMA TMPF 
 DEVICE   = GIF|${ymd}${cyc}_2p5rtma2mtz.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-91;25;/1;1;1;1
# GAREA    = 30.;-104.;40.;-88.
 GAREA    = 33.;-103;49.;-81.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.96/0.8;.03/2
 CONTUR   = 0
 SKIP     =  
# FINT     = 10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
# FINT     = 36;40;44;48;52;56;60;64;68;72;76;80;84;88;92;96;100;104;108;112
# FINT     = -34;-28;-22;-16;-10;-4;2;8;14;20;26;32;38;44;50;56;62;68;74;80;86
 FINT     = 48;51;54;57;60;63;66;69;72;75;78;81;84;87;90;93;96;99;102;105;108
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
