#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch15/pcpwest
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch15/pcpwest
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="03 06 09 12 15 18"
counter=1
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = add(s03i,c03i) 
 CINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparepcpwest_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-113.;25./2;2;1;1
 GAREA    = 26.;-126.;50.;-100. 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5 
 FLINE    = 0;21;22;23;28;30;2;15;10;5 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP 3-HR TOT PRECIP 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAPX  3-HR TOT PRECIP 
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = add(s03i,c03i)
 TITLE    = 0
 CINT     = .01;.1;.2;.3;.4;.5;.75;1.;1.5 
r

ex
EOF

counter=`expr $counter + 1`
done

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f18
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = add(s18i,c18i)
 CINT     = 0.25
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RAP  18-HR TOT PRECIP
 DEVICE   = GIF|comparepcpwest_${cyc}f${counter}.gif
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-113.;25./2;2;1;1
 GAREA    = 26.;-126.;50.;-100.
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.25;1.5;2.;2.5;3.
 FLINE    = 0;21;22;23;4;26;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
 CLEAR    = n
 CLRBAR   = 0
r

 GDFILE   = $fmdl2
 TITLE    = 1/1/ ${fhr}-HR RAPX  18-HR TOT PRECIP
 TEXT     = 1.2/11/2/SW
 PANEL    = 0;0.;1.;0.49
r

ex
EOF

gpend
mv *gif ../../ftphold/.
echo abouttoexit1pcp
exit
