#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/slp
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

vtime=2021070900
hours="24"
for fhr in $hours; do

dattim="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/advtime $vtime -$fhr -1`"
validtime=`echo $dattim | cut -c1-11`
ymdh=`echo $validtime | cut -c1-10`
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c9-10`

DAPATH1=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak
DAPATH2=/gpfs/dell1/nco/ops/com/ecmwf/prod/ecmwf.${ymd}/gempak
DAPATH3=/gpfs/dell1/nco/ops/com/nam/prod/nam.${ymd}/gempak
DAPATH4=/gpfs/hps/nco/ops/com/hrrr/prod/hrrr.${ymd}/conus/gempak
DAPATH5=/gpfs/hps/nco/ops/com/hiresw/prod/hiresw.${ymd}/gempak

cp /gpfs/hps/nco/ops/com/hur/prod/hwrf.2021070700/gempak/elsa05l/hwrfn_2021070700f024_elsa05l

fmdl1=${DAPATH1}/gfs_0p25_${ymdh}f0${fhr}
fmdl2=${DAPATH2}/ecmwf_0p25_${ymdh}f0${fhr}
fmdl3=${DAPATH3}/nam32_${ymdh}f0${fhr}
fmdl4=${DAPATH3}/nam_conusnest_${ymdh}f0${fhr}
fmdl5=${DAPATH4}/hrrr_${ymdh}f0${fhr}00
fmdl6=${DAPATH5}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl7=${DAPATH5}/hiresw_conusarwmem2_${ymdh}f0${fhr}
fmdl8=${DAPATH5}/hiresw_conusfv3_${ymdh}f0${fhr}

echo $fmdl1
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = refc
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS SLP / REFC
 DEVICE   = GIF|${ymdh}slprefc1_f${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 34.;-82.;42.;-68. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.9/11/1/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65 
 FLINE    = 0;24;4;26;23;22;21;20;5;10;17;2;15;29 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = pmsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = c
r

 GDFILE   = $fmdl2
 GDPFUN   = refc
 TITLE    = 1/-1/~   ECMWF SLP / REFC
 TYPE     = f
 HILO     = 0 
 HLSYM    = 0 
 PANEL    = b
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2  
r

 GDPFUN   = pmsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0
 TYPE     = c
r

 GDFILE   = $fmdl3
 GDPFUN   = refc
 DEVICE   = GIF|${ymdh}slprefc2_f${fhr}.gif|750;900
 CLEAR    = y
 TITLE    = 1/-1/~   NAM SLP / REFC
 TYPE     = f
 HILO     = 0 
 HLSYM    = 0 
 PANEL    = t
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2  
r

 GDPFUN   = pmsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = c
r

 GDFILE   = $fmdl4
 GDPFUN   = refc
 TITLE    = 1/-1/~   NAM3 SLP / REFC
 TYPE     = f
 HILO     = 0 
 HLSYM    = 0 
 PANEL    = b
r

 GDPFUN   = emsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = c
r

 GDFILE   = $fmdl5
 GDPFUN   = refc
 DEVICE   = GIF|${ymdh}slprefc3_f${fhr}.gif|750;900
 CLEAR    = y
 TITLE    = 1/-1/~   HRRR SLP / REFC
 TYPE     = f
 HILO     = 0 
 HLSYM    = 0 
 PANEL    = t
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2  
r

 GDPFUN   = pmsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = c
r

 GDFILE   = $fmdl6
 GDPFUN   = refc
 TITLE    = 1/-1/~   ARW SLP / REFC
 TYPE     = f
 HILO     = 0 
 HLSYM    = 0 
 PANEL    = b
r

 GDPFUN   = emsl
 LINE     = 4/1/2/4
 HILO     = ;2/;S13#/;920-1016/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLEAR    = n
 CLRBAR   = 0
 TYPE     = c
r
 
ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
