#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mt
rm /stmpp1/Geoffrey.Manikin/meg/2mt/*
cd /stmpp1/Geoffrey.Manikin/meg/2mt
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015011612
ymd=20150116
dayoweek=hold2
counter=1

times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
for fhr in $times; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}
echo $counter

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 2-M  TMPF 
 DEVICE   = GIF|t2z${counter}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-100;25;/1;1;1;1
 GAREA    = ne- 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.95/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = -15;-10;-5;0;5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80
 FINT     = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
counter=`expr $counter + 1`
done
gpend

/usrx/local/ImageMagick/6.8.3-3/bin/convert -loop 0 -delay 100 t2z*gif ${ymdh}_2mtzloop.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp 122mtz1.gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
