#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /ptmpp1/wx20mg/menu
rm /ptmpp1/wx20mg/menu/*
cd /ptmpp1/wx20mg/menu

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

cycles="00 01 02 03 04 05 06 07 08 09 10 11 12 13 15 16 17 18 19 20 21 22 23"
for cyc in $cycles; do

ftp -n -i << EOF > /meso/save/wx20mg/gempak.ruc13/animate.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/ruc2/para/14z
prompt
mget inc*
bye
EOF

vi inc.animate.html << EOF > /dev/null
:1,\$ s/14f/${cyc}f
:wq
EOF

ftp -n -i << EOF > /meso/save/wx20mg/gempak.ruc13/animate.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/ruc2/para/${cyc}z
prompt
mput *animate* 
bye
EOF
done

exit
