#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/typesrefmem
rm /stmp/wx20mg/meg/typesrefmem/*
cd /stmp/wx20mg/meg/typesrefmem
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012121109
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Tue

hours="60"

for fhr in $hours; do
fmdl1=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_nmm_ctl
fmdl2=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_nmb_ctl
fmdl3=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_em_ctl

#fmdl1=/ptmp/wx20mg/hold/sreftestnmmctl_${ymdh}f0${fhr}
#fmdl2=/ptmp/wx20mg/hold/sreftestnmbctl_${ymdh}f0${fhr}
#fmdl3=/ptmp/wx20mg/hold/sreftestemctl_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 1 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NMM CTL TYPE   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|srefopstype_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 28.;-126.;62.;-64.
# GAREA    = nj- 
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1// NMB CTL TYPE   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl3
 TITLE    = 1// EM CTL  TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

ex
EOF
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
