#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/sref24pcptr
rm /stmpp1/Geoffrey.Manikin/meg/sref24pcptr/*
cd /stmpp1/Geoffrey.Manikin/meg/sref24pcptr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=2014012721
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=Mon

hours="39"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
echo $verymdh
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fmdl1=/com/nawips/prod/sref.${ymd1}/sref212_${ymdh}_mean
fmdl2=/com/nawips/prod/sref.${ymd2}/sref212_${ymdh2}_mean
fmdl3=/com/nawips/prod/sref.${ymd3}/sref212_${ymdh3}_mean
fmdl4=/com/nawips/prod/sref.${ymd4}/sref212_${ymdh4}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(p24menmw,25.4) 
 CINT     = 4 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF MEAN 24-HR PCP  
 DEVICE   = GIF|sref24pcp_${ymd}f0${fhr1}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = al 
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 PANEL    = ur
 CLEAR    = n
 TITLE    = 1/-1/~   SREF MEAN 24-HR PCP 
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 PANEL    = ll 
 CLRBAR   = 1/H/UL/.3;.98/1.4;.02/-1
 TITLE    = 1/-1/~   SREF MEAN 24-HR PCP 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 PANEL    = lr 
 CLRBAR   = 0
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
