#!/bin/ksh
echo 'into'

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6ptypetrgfs
rm /stmpp1/Geoffrey.Manikin/meg/6ptypetrgfs/*
cd /stmpp1/Geoffrey.Manikin/meg/6ptypetrgfs
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2015011800
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold2
hours="00 06 12 18"
hours="12 15"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fmdl1=/com/nawips/prod/gfs.${ymd1}/gfs40_${ymdh}f0${fhr1}
fmdl2=/com/nawips/prod/gfs.${ymd2}/gfs40_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/gfs.${ymd3}/gfs40_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/gfs.${ymd4}/gfs40_${ymdh4}f0${fhr4}

div1=`expr $fhr1 % 6`
 if [ $div1 -eq 0 ]
 then
 gfsvar1="06"
 else
 gfsvar1="03"
 fi

div2=`expr $fhr2 % 6`
 if [ $div2 -eq 0 ]
 then
 gfsvar2="06"
 else
 gfsvar2="03"
 fi

div3=`expr $fhr3 % 6`
 if [ $div3 -eq 0 ]
 then
 gfsvar3="06"
 else
 gfsvar3="03"
 fi

div4=`expr $fhr4 % 6`
echo $div4
 if [ $div4 -eq 0 ]
 then
 gfsvar4="06"
 else
 gfsvar4="03"
 fi

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr${gfsvar1} 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  GFS PTYPE  ${ymd1} ${cyc}z  F${fhr1}
 DEVICE   = GIF|gfs6ptypetr${ymd1}f${fhr1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = nj+ 
# GAREA    = 28.;-88.;44.;-66. 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts${gfsvar1}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar1}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar1}
 FLINE    = 0;2
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
r

 GDFILE   = $fmdl2 
 GDATTIM  = f${fhr2}
 TITLE    = 1//  GFS PTYPE  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 GDPFUN   = wxtr${gfsvar2} 
 FLINE    = 0;3
r

 GDPFUN   = wxts${gfsvar2}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar2}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar2}
 FLINE    = 0;2
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3 
 GDATTIM  = f${fhr3}
 GDPFUN   = wxtr${gfsvar3} 
 TITLE    = 1//  GFS PTYPE  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
 FLINE    = 0;3
r

 GDPFUN   = wxts${gfsvar3}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar3}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar3}
 FLINE    = 0;2
r

 GDFILE   = $fmdl4 
 GDATTIM  = f${fhr4}
 GDPFUN   = wxtr${gfsvar4} 
 TITLE    = 1//  GFS PTYPE  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
 FLINE    = 0;3
r

 GDPFUN   = wxts${gfsvar4}
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp${gfsvar4}
 FLINE    = 0;29
r

 GDPFUN   = wxtz${gfsvar4}
 FLINE    = 0;2
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
