#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/24pcpsrefmem
rm /stmp/wx20mg/meg/24pcpsrefmem/*
cd /stmp/wx20mg/meg/24pcpsrefmem
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013041509
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Mon

hours="27"
for fhr in $hours; do

cp /com/nawips/prod/sref.${ymd}/sref212_${ymdh}_em_ctl fmdl1
cp /com/nawips/prod/sref.${ymd}/sref212_${ymdh}_nmm_ctl fmdl2
cp /com/nawips/prod/sref.${ymd}/sref212_${ymdh}_nmb_ctl fmdl3 
fmdl4=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_mean

    gdplot2 << EOF
 GDFILE   = fmdl1 + fmdl2 + fmdl3
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(add(add(p24i+3,p24i+2),p24i),3) 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  3CTL 24-HR PCP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|srefctl24pcp_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = 28.;-102.;50.;-68.
 CLEAR    = y
 PANEL    = t 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;.5/.9;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl4
 GDPFUN   = quo(p24menmw,25.4)
 CLEAR    = n
 PANEL    = b
 TITLE    = 1// SREF MEAN 24-HR PCP  $ymd ${cyc}z  F${fhr}
 CLRBAR   = 0
r

ex
EOF
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
