#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch6/hlcy
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch6/hlcy
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 3000:0 
 GVCORD   = hght 
 GDPFUN   = hlcy 
 CINT     = 50;100;150;200;250;300;400;500;600;700;800;900 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparehel_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;100;150;200;250;300;400;500;600;700;800;900 
 FLINE    = 0;24;25;21;22;23;5;10;17;16;2;15;32 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP 0-3 KM HELICITY 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 4/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAPX  0-3 KM HELICITY 
 GVCORD   = hght
 GLEVEL   = 3000:0
 GDFILE   = $fmdl2 
 GAREA    = 16.;-126.;55.;-57.
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = hlcy 
 TITLE    = 0
 CINT     = 46;50;54;58;62;66;70
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexithel
exit
