#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/sfc
rm /stmp/wx20mg/meg/sfc/*
cd /stmp/wx20mg/meg/sfc
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013052000
ymd=20130520
dayoweek=Sun

fmdl1=/com/nawips/prod/rtma2p5.${ymd}/rtma2p5_${ymdh}f000
fmdl1=/ptmp/wx20mg/rtma/rtma2p5_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~ 2.5 RTMA SLP/ 2M DEW POINT / 10M WIND
 DEVICE   = GIF|sfc.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 25.;-105.;46.;-83.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 0.8/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.8/.5;.02/2 
 CONTUR   = 0
 SKIP     = /20;20 
 FINT     = 50;54;58;62;66;70;74;78;82
 FLINE    = 0;21;22;23;28;29;30;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 10
 GVCORD   = HGHT
 WIND     = ak1/0.6/2/122/0.7
 GDPFUN   = wnd
 TYPE     = a
 HILO     = 0
 HLSYM    = 0
 CLEAR    = n
 CLRBAR   = 0
 SCALE    = 0
 FINT     = 0
 FLINE    = 0
 TEXT     = 0
r

 GDPFUN   = quo(pres,100)
 GLEV     = 0
 GVCORD   = none 
 CINT     = 4 
 LINE     = 4/1/2/3
 TITLE    = 0
 HILO     = 18;18/S12#;S13#/1015-1060;920-1014/5/1;1/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 TYPE     = c
r

ex
EOF

gpend
/usrx/local/im_beta/bin/convert -crop 0x0 sfc.gif rtmasfc${ymdh}.gif

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput rtma*gif
bye
EOF

rm *gif
exit
