#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtsrefmem
rm /stmpp1/Geoffrey.Manikin/meg/2mtsrefmem/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtsrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016021509
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

hours="21"
models="arw nmb"
members="ctl p1 p2 p3 p4 p5 p6 n1 n2 n3 n4 n5 n6"

for fhr in $hours; do
for mdl in $models; do
                      
fmdl1=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_ctl
fmdl2=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p1 
fmdl3=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p2 
fmdl4=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p3 
fmdl5=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p4 
fmdl6=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p5 
fmdl7=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_p6
fmdl8=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n1
fmdl9=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n2
fmdl10=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n3
fmdl11=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n4
fmdl12=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n5
fmdl13=/com2/nawips/prod/sref.${ymd}/sref132_${ymdh}_${mdl}_n6

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr} 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 4 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL 2-M TEMP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}2mt1_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 24.;-155.;68.;-75.
 GAREA   = md 
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
# FINT     = 5;8;11;14;17;20;23;26;29;32;35;38;41;44;47;50;53;56;59
 FINT     = 0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72
# FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 FLINE    = 0;12;30;29;28;4;25;26;27;23;22;3;21;5;20;10;17;16;2;15;14;32

 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1// $mdl P1 2-M TEMP  $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = $fmdl3
 TITLE    = 1// $mdl P2 2-M TEMP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = $fmdl4
 TITLE    = 1// $mdl P3 2-M TEMP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = $fmdl5
 TITLE    = 1// $mdl P4 2-M TEMP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = $fmdl6
 TITLE    = 1// $mdl P5 2-M TEMP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = $fmdl7
 TITLE    = 1// $mdl P6 2-M TEMP  $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL 2-M TEMP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}2mt2_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 CLEAR    = y
 PANEL    = m1
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl8
 TITLE    = 1// $mdl N1 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m2
r

 GDFILE   = $fmdl9
 TITLE    = 1// $mdl N2 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m3
r

 GDFILE   = $fmdl10
 TITLE    = 1// $mdl N3 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m4
r

 GDFILE   = $fmdl11
 TITLE    = 1// $mdl N4 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m5
r

 GDFILE   = $fmdl12
 TITLE    = 1// $mdl N5 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = $fmdl13
 TITLE    = 1// $mdl N6 2-M TEMP  $ymd ${cyc}z  F${fhr}
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
