#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrrsnow
rm /stmpp1/Geoffrey.Manikin/meg/hrrrsnow/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrrsnow
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2018030200
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold9

hours="36"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

typeset -Z2 fhr1 fhr2 fhr3
DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
DAPATH=/ptmpp1/Geoffrey.Manikin/hold
fmdl1=${DAPATH}/hrrr.${ymd}/hrrrx_${ymdh}f0${fhr}00
fmdl2=${DAPATH}/hrrr.${ymd1}/hrrrx_${ymdh1}f0${fhr}00
fmdl3=${DAPATH}/hrrr.${ymd2}/hrrrx_${ymdh2}f0${fhr}00
fmdl4=${DAPATH}/hrrr.${ymd3}/hrrrx_${ymdh3}f0${fhr}00

garea="44.;-124.;47.;-120."
garea="ny+"
garea="40.;-80.;46.;-70."
proj="lcc/25.;-75.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(snow36,39.37)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrxsnow_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 \$MAPFIL = county
 TITLE    = 1//  ${ymd} ${cyc}z HRRRX  36-HR ACC SNOW DPTH
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 0.1;1;2;3;4;6;8;10;12;16;20;24;28
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5
 TYPE     = f 
r

 GDFILE   = $fmdl2
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//  ${ymd1} ${cyc1}z HRRRX  36-HR ACC SNOW DPTH 
 CLRBAR   = 1/H/UL/.02;0.97/1.9;.03/1
r

 GDFILE   = $fmdl3
 PANEL    = ur 
 TITLE    = 1//  ${ymd2} ${cyc2}z HRRRX  36-HR ACC SNOW DPTH 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 PANEL    = ul
 TITLE    = 1//  ${ymd3} ${cyc3}z HRRRX  36-HR ACC SNOW DPTH 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdpcp/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
