#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/prob
rm /stmp/wx20mg/meg/prob/*
cd /stmp/wx20mg/meg/prob
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=2012091709

times="51"
for fhr in $times; do

fmdl=/ptmp/wx20mg/hold/ensprod/srefprob3_$ymdh
fmdl2=/ptmp/wx20mg/hold/ensprod/srefprob2_$ymdh

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p24m 
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    SREF PROB of 4"
 DEVICE   = GIF|srefprob_24pcp_${ymdh}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
! GAREA    = 39.;-78.;44.;-70. 
! GAREA    = 36.;-81.;41.;-74.
 GAREA    = 35.;-85.;49.;-65.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.04;0.4/0.8;.03/2
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r


 GDFILE  = $fmdl2
 PANEL   = b
 TITLE   = 1/-1/~    SREF PROB of 2"
 CLEAR   = n
 CLRBAR  = 0
r

ex
EOF

gpend
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/dwpfftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *.gif
bye
EOF

exit
