#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hiresmaxwx
rm /stmpp1/Geoffrey.Manikin/meg/hiresmaxwx/*
cd /stmpp1/Geoffrey.Manikin/meg/hiresmaxwx
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /meso/save/Geoffrey.Manikin/meg/NMCDATE`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATE`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2017061418
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
dayoweek=hold5

hours="00 01 02 03 04 05"
hours="28 30 33 36"
for fhr in $hours; do
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} -18 -1`"
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

fhr2=`expr $fhr + 6`
fhr3=`expr $fhr + 12`
fhr4=`expr $fhr + 18`

typeset -Z2 fhr1 fhr2 fhr3
fmdl1=/com2/nawips/prod/nam.${ymd1}/nam_conusnest_${ymdh1}f0${fhr}
fmdl2=/com2/nawips/prod/nam.${ymd1}/nam_conusnest_${ymdh2}f0${fhr2}
fmdl3=/com2/nawips/prod/nam.${ymd2}/nam_conusnest_${ymdh3}f0${fhr3}
fmdl4=/com2/nawips/prod/nam.${ymd3}/nam_conusnest_${ymdh4}f0${fhr4}

garea="34.;-103.;41.;-92.8"
proj="lcc/25.;-97.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sqrt(add(mul(maxuw01,maxuw01),mul(maxvw01,maxvw01))))
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd1}${cyc1}namnest10mxwnd_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc1}z NAM3  10-M MAX WIND SPEED 
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.8/11/2
 FINT     = 10;20;30;40;50;60;70;80
 FLINE    = 0;30;28;26;23;21;5;10;2;15
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc2}z NAM3  10-M MAX WIND SPEED 
 CLRBAR   = 1/H/UL/.46;0.96/1.1;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 PANEL    = ur 
 TITLE    = 1//~  ${cyc3}z NAM3  10-M MAX WIND SPEED 
 CLRBAR   = 0 
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 PANEL    = ul
 TITLE    = 1//~  ${cyc4}z NAM3  10-M MAX WIND SPEED 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdmaxw/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
