#!/bin/sh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssnd
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssnd/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/gfssnd
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2022013112
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`
stations="724080"

cp /gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_${ymd}${cyc}.snd fmdl1

times="60 61 62 63 64 65 66"
times="96"
for fhr in $times; do

validtime="`/gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/advtime ${ymdh} $fhr -1 x`"
echo $validtime
dattim=`echo $validtime | cut -c5-11`
for stnm in $stations; do

    snprof << EOF
 SNFILE   = fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/6
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = lift;cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1// $stnm   GFS 
 DEVICE   = gif|gfs_${ymdh}f${fhr}.gif|750;850
 YAXIS    = 1050/250/100/1;1;1
 XAXIS    = -25/30/10/;1
 FILTER   = 0.6
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

ex
EOF

gpend
done
done

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test5/.
