#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/namuphl
rm /stmpp1/Geoffrey.Manikin/meg/namuphl/*
cd /stmpp1/Geoffrey.Manikin/meg/namuphl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017040500
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold7

hours1="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30"

#hours1="01 02 03 04 05 06"
#hours2="02 03 04 05 06 07"
#hours3="03 04 05 06 07 08"
#hours4="04 05 06 07 08 09"

ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`

DAPATH=/com2/nawips/prod
#DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/para
garea="30.;-103.;40.5;-90."
garea="27.;-88.;36.;-76."
proj="lcc/25.;-83.;25./2;2;1;1"

for fhr1 in $hours1; do

fmdl1=${DAPATH}/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr1}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = MXUPHL01
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|namalluphl_4cyc_${ymdh}.gif | 800;850
 GAREA    = $garea 
 PROJ     = $proj
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z NAM4  2-5 KM MAX UPDRAFT HLCY 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = ul 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0 
 TEXT     = 0.9/11/2
 FINT     = 25;50;75;100;125;150;175;200
 FLINE    = 0;4;26;2;15;17;10;20;5
 TYPE     = f 
r

ex 
EOF
done

 for fhr2 in $hours2; do
fmdl2=${DAPATH}/nam.${ymd1}/nam_conusnest_${ymdh1}f0${fhr2}
  gdplot2 << EOF
 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 PANEL    = ur
 TITLE    = 1//  ${cyc1}z NAM4  2-5 KM MAX UPDRAFT HLCY
r

 TITLE    = 2/1/ TRACKS VALID 1-22 18z to 1-23 02z
r

ex
EOF
done

 for fhr3 in $hours3; do
fmdl3=${DAPATH}/nam.${ymd2}/nam_conusnest_${ymdh2}f0${fhr3}
  gdplot2 << EOF
 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 PANEL    = ll 
 TITLE    = 1//  ${cyc2}z NAM4  2-5 KM MAX UPDRAFT HLCY
 CLRBAR   = 1/H/UL/.2;0.98/1.6;.03/1
r

ex
EOF
done

for fhr4 in $hours4; do
  fmdl4=${DAPATH}/nam.${ymd3}/nam_conusnest_${ymdh3}f0${fhr4}
  gdplot2 << EOF
 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 PANEL    = lr
 TITLE    = 1//  ${cyc3}z NAM4  2-5 KM MAX UPDRAFT HLCY
 CLRBAR   = 0
r
 
ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
