#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
cyc2=$2

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/vis
rm /stmp/wx20mg/meg/vis/*
cd /stmp/wx20mg/meg/vis
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
ymdh2=`cut -c 7-16 /com/date/t${cyc2}z`
ymd2=`cut -c 7-14 /com/date/t${cyc2}z`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013042903
ymd=20130429
ymdh2=2013042909
ymd2=20130429
dayoweek=Mon

fhr=09
fhr2=03

fmdl1=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_mean
fmdl2=/com/nawips/prod/sref.${ymd2}/sref212_${ymdh2}_mean

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(quo(vsbyenmw,1000),0.62137) 
 CINT     = 1;2;3;4;5;10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/ ${ymd} ${cyc}z ${fhr}-HR  SREF MEAN VISIBILITY (miles)
 DEVICE   = GIF|${ymd}sref2vis${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
# GAREA    = 20.;-124.;55.;-61. 
 GAREA    = ms
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 1;2;3;4;5;10 
 FLINE    = 2;17;5;21;26;28;0 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/-1/ ${cyc2}z ${fhr2}-HR SREF MEAN  VISIBILITY (miles)
 GDATTIM  = f$fhr2
 PANEL    = b
 GDFILE   = $fmdl2 
 CLEAR    = n
 PANEL    = 0;0;1;.49
 GDFILE   = $fmdl2 
 CLRBAR   = 0
r

ex
EOF

gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
