#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc1=00
stnm=725035
stid=isp

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/meteograms
rm /stmpp1/Geoffrey.Manikin/meg/meteograms/*
cd /stmpp1/Geoffrey.Manikin/meg/meteograms
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh1=`cut -c 7-16 /com/date/t${cyc1}z`
ymdh1=2016121700
ymd1=`echo $ymdh1 | cut -c1-8`
day1=`echo $ymdh1 | cut -c7-8`

ymdhend="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh1} 24 -1`"
dayend=`echo $ymdhend | cut -c7-8`
cycend=`echo $ymdhend | cut -c9-10`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold5

fmdl1=/com/nawips/prod/nam.${ymd1}/nam_${ymdh1}.sfc
fmdl2=/com2/nawips/prod/gfs.${ymd1}/gfs_${ymdh1}.sfc
fmdl3=/com/nawips/prod/nam.${ymd1}/nam_conusnest_${ymdh1}.sfc
fmdl4=/com2/nawips/prod/rap.${ymd1}/rap_${ymdh1}.sfc
fmdl5=/com2/nawips/prod/hrrr.${ymd1}/hrrr_${ymdh1}.sfc
fmdl6=/com2/nawips/para/nam.${ymd1}/nam_conusnest_${ymdh1}.sfc.tm00
fmdl7=/dcom/us007003/ldmdata/gempak/hrly/${ymd1}.hrly

sfgram << EOF 
SFFILE	= $fmdl1 
DATTIM	= ${day1}/${cyc1}-${dayend}/${cycend} 
STATION = @$stnm
TRACE1  = t2ms:1:4/2/-10;10;5
NTRACE	= 1 
TAXIS	= ${day1}/${cyc1}-${dayend}/${cycend}
BORDER	= 1//2
MARKER	= 0
TITLE   = 1/+3/ $stnm   2-M TEMP NAM-red   GFS-BLUE   RAP-LT GREEN  NAMXNEST-DASH
CLEAR	= yes
DEVICE  = GIF|${stnm}_meteogram.gif | 900;800
PANEL	= 0
TEXT	= medium/22/2////HW 
r

SFFILE  = $fmdl2
TRACE1  = t2ms:1:4/25/-10;10;5
TITLE   = 1/+2/ $stnm   2-M TEMP  NAM4-ORANGE   HRRR-DK GREEN   OBS-BLACK
CLEAR   = n
r

SFFILE  = $fmdl3
TRACE1  = t2ms:1:4/17/-10;10;5
r

SFFILE  = $fmdl4
TRACE1  = t2ms:1:4/21/-10;10;5
r

SFFILE  = $fmdl5
TRACE1  = t2ms:1:4/23/-10;10;5
r

SFFILE  = $fmdl6
TRACE1  = t2ms:2:4/17/-10;10;5
r

SFFILE  = $fmdl7
AREA    = @${stid}
TRACE1  = tmpc:1:5/1/-10;10;5
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
