#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/36pcpectr
rm /stmpp1/Geoffrey.Manikin/meg/36pcpectr/*
cd /stmpp1/Geoffrey.Manikin/meg/36pcpectr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymd=`cut -c 7-14 /com/date/t12z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymd=20180321
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold10

hours="36"

for fhr in $hours; do
fhr36=`expr $fhr - 36`
fhr2=`expr $fhr + 12`
echo $fhr2
fhr36m12=`expr $fhr2 - 36`
typeset -Z3 fhr fhr2 fhr36 fhr36m12
fmdl1=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_0p25_${ymd}12f${fhr}
cp /com2/nawips/prod/ecmwf.${ymd}/ecmwf_0p25_${ymd}12f${fhr36} fmdl2
fmdl3=/com2/nawips/prod/ecmwf.${ymd}/ecmwf_0p25_${ymd}00f${fhr2}
echo $fhr36m12
cp /com2/nawips/prod/ecmwf.${ymd}/ecmwf_0p25_${ymd}00f${fhr36m12} fmdl4

echo $fmdl1
echo $fmdl3

    gdplot2 << EOF
 GDFILE   = fmdl2 + $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = sub(quo(mul(pxxm+2,1000),25.4),quo(mul(pxxm^${ymd}/12f${fhr36},1000),25.4) 
 CINT     = 4
 LINE     = 1
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  ECMWF 36-HR PCP  $ymd 12z  F${fhr}
 DEVICE   = GIF|ec36pcptrz_${ymd}.gif | 800;850
 SATFIL   =
 RADFIL   =
 GAREA    = 36.;-82.;46.;-67. 
 PROJ     = lcc/25;-75;25/2;2;1;1
 CLEAR    = y 
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;4;5;6;8
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = fmdl4 + $fmdl3
 GDATTIM  = f$fhr2
 TITLE    = 1/-1/ ECMWF 36-HR PCP  $ymd 00z  F${fhr2}
 GDPFUN   = sub(quo(mul(pxxm+2,1000),25.4),quo(mul(pxxm^${ymd}/00f${fhr36m12},1000),25.4)
 PANEL    = t
 CLRBAR   = 1/V/UL/.08;0.45/0.9;.03/1 
 CLEAR    = n
r

ex
EOF
done
gpend

echo $dayoweek
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
