#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/2mtsrefspag
rm /stmpp1/Geoffrey.Manikin/meg/2mtsrefspag/*
cd /stmpp1/Geoffrey.Manikin/meg/2mtsrefspag
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014030109
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Sat

ymdhp="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} 3 -1`"
ymdp=`echo $ymdhp | cut -c1-8`
cycp=`echo $ymdhp | cut -c9-10`

ymdhn="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymdn=`echo $ymdhn | cut -c1-8`
cycn=`echo $ymdhn | cut -c9-10`

DAPATH=/com/sref/para/sref.${ymd}/${cyc}/pgrb/
hours="51"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

fhrp=`expr $fhr - 3`
fhrn=`expr $fhr + 3`
typeset -Z2 fhrp fhrn

wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -grib -o mdl1
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -grib -o mdl2
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -grib -o mdl3
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -grib -o mdl4
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -grib -o mdl5
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -grib -o mdl6
wgrib -i -d 11 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -grib -o mdl7

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

fmdl1=/com/nawips/prod/nam.${ymdp}/nam20_${ymdhp}f0${fhrp}
fmdl2=/com/nawips/prod/nam.${ymdn}/nam20_${ymdhn}f0${fhrn}
fmdl3=/com/nawips/prod/gfs.${ymdp}/gfs40_${ymdhp}f0${fhrp}
fmdl4=/com/nawips/prod/gfs.${ymdn}/gfs40_${ymdhn}f0${fhrn}
fmdl5=/com/nawips/para/sref.${ymd}/sref212_${ymdh}_mean

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 1/32/32/
 LINE     = 2/1/1/0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1// 0C  2-M T   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|srefx2mtspag_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 25.;-105.;46.;-83.
# GAREA    = 26.;-106.;50.;-76.
 GAREA    = md
 CLEAR    = n
 PANEL    = 0 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 5;10;15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105
 FINT     = -4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 0 
r

 GDFILE   = mdl3.gem
 TITLE    = 0
r

 GDFILE   = mdl4.gem
 TITLE    = 0 
r

 GDFILE   = mdl5.gem
 TITLE    = 0 
r

 GDFILE   = mdl6.gem
 TITLE    = 0  
r

 GDFILE   = mdl7.gem
 TITLE    = 0 
r

 GDFILE   = $fmdl1
 LINE     = 22/1/2/0
 GDATTIM  = f${fhrp}
r

 GDFILE   = $fmdl2
 LINE     = 22/1/2/0
 GDATTIM  = f${fhrn}
r

 GDFILE   = $fmdl3
 LINE     = 29/1/2/0
 GDATTIM  = f${fhrp}
r

 GDFILE   = $fmdl4
 LINE     = 29/1/2/0
 GDATTIM  = f${fhrn}
r

 GDFILE   = $fmdl5
 LINE     = 16/1/3/0
 GDATTIM  = f${fhr}
 GDPFUN   = add(mul(1.8,(sub(273.15,tmpkenmw))),32)
r
 
ex
EOF
rm mdl*
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
