#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
length=$2

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

mkdir /stmpp1/wx20mg/gempak.rap13/sfcp
rm /stmpp1/wx20mg/gempak.rap13/sfcp/*
cd /stmpp1/wx20mg/gempak.rap13/sfcp
cp /meso/save/wx20mg/casework/coltbl.xwp .

times="00 01 02 03 06"
times="01"

for fhr in $times; do

fmdl1=/com/nawips/prod/ruc2.${da00}/ruc13_${da00}${hr00}f0${fhr}
fmdl2=/meso/save/wx20mg/gempak/nagribx/rap13x_${da00}${hr00}

echo $fmdl1
echo $fmdl2

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = pres 
 CINT     = 4 
 LINE     = 23/1/3/4 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RUC2 SFC PRESSURE 
 DEVICE   = GIF|comparesfcp_${cyc}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 1;1/2/21;21/4;2/HW
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 700;725;750;775;800;823;850;875;900;925;950;975;1000;1025
 FLINE    = 7;30;28;4;26;24;23;21;22;5;20;10;17;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 2/-1/  FCST MADE ${cyc}Z  ${month}/$day
 GDPFUN   = blurk
 CLEAR    = n
 TEXT     = 1.1/11/1/SW
r

 GDFILE   = $fmdl2
 GDPFUN   = pres
 PANEL    = 0;0;1;.49
 TITLE    = 0
 CLRBAR   = 0
 TEXT     = 1.2/11/2/SW
 TITLE    = 1/1/ ${fhr}-HR RAPX SFC PRESSURE 
r


ex
EOF

    gdcntr << EOF

 GDFILE   = $fmdl1 + $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GFUNC    = sub(pres+2,pres)
 CINT     = 3
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RAPX - RUC2 SFC PRESSURE DIFFS
 DEVICE   = GIF|sfcpdiff_${cyc}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.9;0.9/.7;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -18;-15;-12;-9;-6;-3;3;6;9;12;15;18
 FINT     = -95;-75;-55;-35;-15;-5;5;15;35;55;75;95
 FLINE    = 30;28;4;25;23;21;0;5;10;17;2;15;11
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF

gpend
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
export w3=emcmmb
export w4=$web

ftp -n -v << EOF > /meso/save/wx20mg/gempak.rap13/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/sfcp
prompt
mput *.gif
bye
EOF

exit
