#!/bin/sh
echo 'into'

ymdh=2021120312
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/winds
rm /gpfs/dell1/stmp/Geoffrey.Manikin/winds/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/winds
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

times="12 13 14 15 16"
times="18"
counter=0
for fhr in $times; do

fmdl1=/gpfs/dell1/ptmp/Geoffrey.Manikin/hrrr/hrrr_${ymd}${cyc}f0${fhr}00
fmdl1=/gpfs/hps/nco/ops/com/hrrr/prod/hrrr.${ymd}/conus/gempak/hrrr_${ymd}${cyc}f0${fhr}00
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = nones 
 GDPFUN   = knts(gust) 
 CINT     = 10
 LINE     = 0 
 MAP      = 1
 WIND     = 0 
 TITLE    = 1/1/ HRRR  ${fhr}-HR FCST GUST (kt) 
 DEVICE   = GIF|comparehrrrwind2_${ymdh}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-92.;25./2;2;1;1 
 GAREA    = 41.;-89.2;43.6;-86. 
 GAREA    = 46.;-93.2;49.;-89.6
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 1.0/1/2
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 1;1/2/21;21/4;2/HW 
 CLRBAR   = 1/V/UL/.05;0.95/.9;.02/-1
 CONTUR   = 0
 SKIP     = /6;6 
 FINT     = 10;15;20;25;30;35;40;45;50;55;60
 FLINE    = 0;30;28;4;25;23;21;10;17;2;15 
 TYPE     = f 
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 23/-1/ FCST MADE ${cyc}Z  ${month}/$day
 GDPFUN   = blurk
 TEXT     = 1.1/11/1/SW
 CLEAR    = n
r

 PANEL    = ur 
 GLEVEL   = 10
 GVCORD   = hght
 GDPFUN   = knts(sped)
 TITLE    = 1/1/ HRRR  ${fhr}-HR FCST 10-M WIND (kt) 
 TEXT     = 1.0/1/2
 CLRBAR   = 0
r

 PANEL    = lr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = knts(sub(gust,sped%hght@10) 
 TITLE    = 1/1/ HRRR  ${fhr}-HR FCST GUST-10m SPEED (kt)
r

 PANEL    = ll 
 GLEVEL   = 0 
 GDPFUN   = zpbl 
 GVCORD   = none 
 FINT     = 50;100;250;500;750;1000;1500
 FLINE    = 0;29;4;22;5;17;2;15 
 TITLE    = 1/1/ HRRR  ${fhr}-HR FCST PBL HEIGHT 
 CLRBAR   = 1/V/UL/.05;0.95/.9;.02/-1
r
ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test7/.
exit
