#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch3/rich3
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch3/rich3
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2
    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 350:300 
 GVCORD   = pres
 GDPFUN   = rich(wnd) 
 CINT     = 0.25;0.5;0.75;1 
 LINE     = 4/1/2/0 
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparerich3_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.25;0.5;0.75;1 
 FLINE    = 2;5;3;4;0
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP 350-300 RICH #
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAPX  350-300 RICH # 
 GAREA    = 16.;-126.;55.;-57.
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = rich(wnd) 
 TITLE    = 0
 CINT     = 0.25;0.5;0.75;1
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexitrich3
exit
