#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/capesrefmem
rm /stmp/Geoffrey.Manikin/meg/capesrefmem/*
cd /stmp/Geoffrey.Manikin/meg/capesrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013042909
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Mon

DAPATH=/com/sref/prod/sref.${ymd}/${cyc}/pgrb
hours="15"
models="em nmm nmb"
models="em"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

 if [ $mdl -eq em ]; then
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -grib -o mdl1
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -grib -o mdl2
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -grib -o mdl3
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -grib -o mdl4
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -grib -o mdl5
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -grib -o mdl6
wgrib -i -d 23 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -grib -o mdl7
 else
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -grib -o mdl1
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -grib -o mdl2
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -grib -o mdl3
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -grib -o mdl4
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -grib -o mdl5
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -grib -o mdl6
wgrib -i -d 24 ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -grib -o mdl7
fi

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL SFC CAPE   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}sfccape_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
# GAREA    = 26.;-106.;50.;-76.
 GAREA    = ia-
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 1// $mdl P1 SFC CAPE   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = mdl3.gem
 TITLE    = 1// $mdl P2 SFC CAPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = mdl4.gem
 TITLE    = 1// $mdl P3 SFC CAPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = mdl5.gem
 TITLE    = 1// $mdl N1 SFC CAPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = mdl6.gem
 TITLE    = 1// $mdl N2 SFC CAPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = mdl7.gem
 TITLE    = 1// $mdl N3 SFC CAPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
rm mdl*
done
done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
