#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrrcape
rm /stmpp1/Geoffrey.Manikin/meg/hrrrcape/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrrcape
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017012219
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6

hours="00 01 02 03 04 05"
hours="02"
for fhr in $hours; do
ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -1 -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`

cyc1=`expr $cyc - 1`
cyc2=`expr $cyc - 2`
cyc3=`expr $cyc - 3`

fhr1=`expr $fhr + 1`
fhr2=`expr $fhr + 2`
fhr3=`expr $fhr + 3`

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr} -1`"

typeset -Z2 fhr1 fhr2 fhr3
export DAPATH=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod
export DAPATH=/com2/nawips/prod
fmdl1=${DAPATH}/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl2=${DAPATH}/hrrr.${ymd1}/hrrr_${ymdh1}f0${fhr1}00
fmdl3=${DAPATH}/hrrr.${ymd2}/hrrr_${ymdh2}f0${fhr2}00
fmdl4=${DAPATH}/hrrr.${ymd3}/hrrr_${ymdh3}f0${fhr3}00

garea="40.;-102.;50.;-82."
garea="27.;-86.;35.;-76."
proj="lcc/25.;-82.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrsfccape_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  ${cyc}z HRRR   SFC CAPE
 CLEAR    = y
 SCALE    = 0
 PANEL    = lr 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 0
 TEXT     = 0.9/11/2
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f 
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr1
 PANEL    = ll
 CLEAR    = n
 TITLE    = 1//~  ${cyc1}z HRRR   SFC CAPE 
 CLRBAR   = 1/H/UL/.15;0.98/1.7;.03/1
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr2
 PANEL    = ur 
 TITLE    = 1//~  ${cyc2}z HRRR   SFC CAPE 
 CLRBAR   = 0 
r

TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr3
 PANEL    = ul
 TITLE    = 1//~  ${cyc3}z HRRR   SFC CAPE 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /stmpp1/Geoffrey.Manikin/meg/holdrefc/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
