#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

dayoweek=hold7

mkdir /stmpp1/Geoffrey.Manikin/meg/
mkdir /stmpp1/Geoffrey.Manikin/meg/500f
cd /stmpp1/Geoffrey.Manikin/meg/500f
rm /stmpp1/Geoffrey.Manikin/meg/500f/*
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

vtime=2017091000
fhr1=228
fhr2=`expr $fhr1 - 12`
fhr3=`expr $fhr1 - 24`
fhr4=`expr $fhr1 - 36`
fhr5=`expr $fhr1 - 48`
fhr6=`expr $fhr1 - 60`
fhr7=`expr $fhr1 - 72`
fhr8=`expr $fhr1 - 84`
fhr9=`expr $fhr1 - 96`
fhr10=`expr $fhr1 - 108`
fhr11=`expr $fhr1 - 120`
fhr12=`expr $fhr1 - 132`
fhr13=`expr $fhr1 - 144`
fhr14=`expr $fhr1 - 156`
fhr15=`expr $fhr1 - 168`
fhr16=`expr $fhr1 - 180`
fhr17=`expr $fhr1 - 192`
fhr18=`expr $fhr1 - 204`
fhr19=`expr $fhr1 - 216`
fhr20=`expr $fhr1 - 228`

typeset -Z3 fhr2
typeset -Z3 fhr3
typeset -Z3 fhr4
typeset -Z3 fhr5
typeset -Z3 fhr6
typeset -Z3 fhr7
typeset -Z3 fhr8
typeset -Z3 fhr9
typeset -Z3 fhr10
typeset -Z3 fhr11
typeset -Z3 fhr12
typeset -Z3 fhr13
typeset -Z3 fhr14
typeset -Z3 fhr15
typeset -Z3 fhr16
typeset -Z3 fhr17
typeset -Z3 fhr18
typeset -Z3 fhr19
typeset -Z3 fhr20

ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr1} -1`"
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr2} -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr3} -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr4} -1`"
ymdh5="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr5} -1`"
ymdh6="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr6} -1`"
ymdh7="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr7} -1`"
ymdh8="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr8} -1`"
ymdh9="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr9} -1`"
ymdh10="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr10} -1`"
ymdh11="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr11} -1`"
ymdh12="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr12} -1`"
ymdh13="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr13} -1`"
ymdh14="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr14} -1`"
ymdh15="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr15} -1`"
ymdh16="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr16} -1`"
ymdh17="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr17} -1`"
ymdh18="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr18} -1`"
ymdh19="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr19} -1`"
ymdh20="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${vtime} -${fhr20} -1`"

ymd1=`echo $ymdh1 | cut -c1-8`
ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
ymd5=`echo $ymdh5 | cut -c1-8`
ymd6=`echo $ymdh6 | cut -c1-8`
ymd7=`echo $ymdh7 | cut -c1-8`
ymd8=`echo $ymdh8 | cut -c1-8`
ymd9=`echo $ymdh9 | cut -c1-8`
ymd10=`echo $ymdh10 | cut -c1-8`
ymd11=`echo $ymdh11 | cut -c1-8`
ymd12=`echo $ymdh12 | cut -c1-8`
ymd13=`echo $ymdh13 | cut -c1-8`
ymd14=`echo $ymdh14 | cut -c1-8`
ymd15=`echo $ymdh15 | cut -c1-8`
ymd16=`echo $ymdh16 | cut -c1-8`
ymd17=`echo $ymdh17 | cut -c1-8`
ymd18=`echo $ymdh18 | cut -c1-8`
ymd19=`echo $ymdh19 | cut -c1-8`
ymd20=`echo $ymdh20 | cut -c1-8`

DAPATH=/gpfs/hps/nco/ops/com/nawips/prod/
fmdl1=${DAPATH}/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr1}
fmdl2=${DAPATH}/gfs.${ymd2}/gfs_0p25_${ymdh2}f${fhr2}
fmdl3=${DAPATH}/gfs.${ymd3}/gfs_0p25_${ymdh3}f${fhr3}
fmdl4=${DAPATH}/gfs.${ymd4}/gfs_0p25_${ymdh4}f${fhr4}
fmdl5=${DAPATH}/gfs.${ymd5}/gfs_0p25_${ymdh5}f${fhr5}
fmdl6=${DAPATH}/gfs.${ymd6}/gfs_0p25_${ymdh6}f${fhr6}
fmdl7=${DAPATH}/gfs.${ymd7}/gfs_0p25_${ymdh7}f${fhr7}
fmdl8=${DAPATH}/gfs.${ymd8}/gfs_0p25_${ymdh8}f${fhr8}
fmdl9=${DAPATH}/gfs.${ymd9}/gfs_0p25_${ymdh9}f${fhr9}
fmdl10=${DAPATH}/gfs.${ymd10}/gfs_0p25_${ymdh10}f${fhr10}
fmdl11=${DAPATH}/gfs.${ymd11}/gfs_0p25_${ymdh11}f${fhr11}
fmdl12=${DAPATH}/gfs.${ymd12}/gfs_0p25_${ymdh12}f${fhr12}
fmdl13=${DAPATH}/gfs.${ymd13}/gfs_0p25_${ymdh13}f${fhr13}
fmdl14=${DAPATH}/gfs.${ymd14}/gfs_0p25_${ymdh14}f${fhr14}
fmdl15=${DAPATH}/gfs.${ymd15}/gfs_0p25_${ymdh15}f${fhr15}
fmdl16=${DAPATH}/gfs.${ymd16}/gfs_0p25_${ymdh16}f${fhr16}
fmdl17=${DAPATH}/gfs.${ymd17}/gfs_0p25_${ymdh17}f${fhr17}
fmdl18=${DAPATH}/gfs.${ymd18}/gfs_0p25_${ymdh18}f${fhr18}
fmdl19=${DAPATH}/gfs.${ymd19}/gfs_0p25_${ymdh19}f${fhr19}
fmdl20=${DAPATH}/gfs.${ymd20}/gfs_0p25_${ymdh20}f${fhr20}

echo $fmdl1
echo $fmdl2
echo $fmdl3
echo $fmdl4
echo $fmdl5
echo $fmdl6
echo $fmdl7
echo $fmdl8
echo $fmdl9
echo $fmdl10
echo $fmdl11
echo $fmdl12
echo $fmdl13
echo $fmdl14
echo $fmdl15
echo $fmdl16
echo $fmdl17
echo $fmdl18
echo $fmdl19
echo $fmdl20
exit

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = quo(hght,10) 
 CINT     = 3 
 LINE     = 1/1/1/3 
 MAP      = 1
 WIND     = 0 
 TITLE    = 1//~  GFS 500 HGHT 
 DEVICE   = GIF|compare500_${vtime}_11.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-90.;25./2;2;1;1
 GAREA    = 6.;-128.;56.;-30. 
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 0.9/1/1
 SCALE    = 0-
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 540;543;546;549;552;555;558;561;564;567;570;573;576;579;582;585;588 
 FLINE    = 25;25;25;25;25;25;25;0;0;0;0;0;0;0;0;0;0;17;17;17 
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 DEVICE   = GIF|compare500_${vtime}_12.gif|900;900
 CLEAR    = n
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 DEVICE   = GIF|compare500_${vtime}_13.gif|900;900
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 DEVICE   = GIF|compare500_${vtime}_14.gif|900;900
r

 GDFILE   = $fmdl5
 GDATTIM  = f$fhr5
 DEVICE   = GIF|compare500_${vtime}_15.gif|900;900
r

 GDFILE   = $fmdl6
 GDATTIM  = f$fhr6
 DEVICE   = GIF|compare500_${vtime}_16.gif|900;900
r

 GDFILE   = $fmdl7
 GDATTIM  = f$fhr7
 DEVICE   = GIF|compare500_${vtime}_17.gif|900;900
r

 GDFILE   = $fmdl8
 GDATTIM  = f$fhr8
 DEVICE   = GIF|compare500_${vtime}_18.gif|900;900
r

 GDFILE   = $fmdl9
 GDATTIM  = f$fhr9
 DEVICE   = GIF|compare500_${vtime}_19.gif|900;900
r

 GDFILE   = $fmdl10
 GDATTIM  = f$fhr10
 DEVICE   = GIF|compare500_${vtime}_20.gif|900;900
r

 GDFILE   = $fmdl11
 GDATTIM  = f$fhr11
 DEVICE   = GIF|compare500_${vtime}_21.gif|900;900
r

 GDFILE   = $fmdl12
 GDATTIM  = f$fhr12
 DEVICE   = GIF|compare500_${vtime}_22.gif|900;900
r

 GDFILE   = $fmdl13
 GDATTIM  = f$fhr13
 DEVICE   = GIF|compare500_${vtime}_23.gif|900;900
r

 GDFILE   = $fmdl14
 GDATTIM  = f$fhr14
 DEVICE   = GIF|compare500_${vtime}_24.gif|900;900
r

 GDFILE   = $fmdl15
 GDATTIM  = f$fhr15
 DEVICE   = GIF|compare500_${vtime}_25.gif|900;900
r

 GDFILE   = $fmdl16
 GDATTIM  = f$fhr16
 DEVICE   = GIF|compare500_${vtime}_26.gif|900;900
r

 GDFILE   = $fmdl17
 GDATTIM  = f$fhr17
 DEVICE   = GIF|compare500_${vtime}_27.gif|900;900
r

 GDFILE   = $fmdl18
 GDATTIM  = f$fhr18
 DEVICE   = GIF|compare500_${vtime}_28.gif|900;900
r

 GDFILE   = $fmdl19
 GDATTIM  = f$fhr19
 DEVICE   = GIF|compare500_${vtime}_29.gif|900;900
r

 GDFILE   = $fmdl30
 GDATTIM  = f$fhr30
 DEVICE   = GIF|compare500_${vtime}_30.gif|900;900
r

exit
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
