#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850z
rm /stmpp1/Geoffrey.Manikin/meg/850z/*
cd /stmpp1/Geoffrey.Manikin/meg/850z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2018052212
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

times="120 144 168"
times="120"
for fhr in $times; do

typeset -Z3 fhr
DAPATH=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}
DAPATH=/ptmpp1/Geoffrey.Manikin/hold
DAPATH=/meso/noscrub/Geoffrey.Manikin/alberto
fmdl1=${DAPATH}/gfs_0p25_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = quo(hght,10) 
 CINT     = 3 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 850 mb  HGHT 
 DEVICE   = GIF|gfs850z_${ymdh}f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = 14.;-100.;40.;-58. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 1//21;//HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 CINT     =
 WIND     = BK1/0.8/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /7;7
 TYPE     = b
 TITLE    = 0
 CLEAR    = n
r

ex
EOF

done
gpend
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
