#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/swemb
rm /stmp/Geoffrey.Manikin/meg/swemb/*
cd /stmp/Geoffrey.Manikin/meg/swemb
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2013120900
dayoweek=Mon

ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`

times="03"
for fhr in $times; do

#fmdl1=/com/nawips/prod/nam.${ymd}/nam12_${ymdh}f0${fhr}
fmdl1=/ptmp/Geoffrey.Manikin/hold/ndas12_${ymdh}f0${fhr}

echo $fmdl1
echo $fmdl2

areas="1 2 3 4 5"
areas="6"
for region in $areas; do

if [ $region -eq 1 ]
then
garea="26.;-124.;56.;-62."
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 2 ]
then
garea="ct"
proj="lcc/25.;-80.;25./2;2;1;1"
elif [ $region -eq 3 ]
then
garea="ia-"
proj="lcc/25.;-95.;25./2;2;1;1"
elif [ $region -eq 4 ]
then
garea="38.;-125.;52.;-109."
proj="lcc/25.;-105.;25./2;2;1;1"
elif [ $region -eq 5 ]
then
garea="30.;-122.;42.;-104."
proj="lcc/25.;-115.;25./2;2;1;1"
elif [ $region -eq 6 ]
then
garea="md"
proj="lcc/25.;-75.;25./2;2;1;1"
fi
    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = popz 
 CINT     = 10 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|popz${region}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = $proj 
 GAREA    = $garea 
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.9/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;28;26;22;20;2
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/~ ${fhr}-HR NDAS % of FRZ PCP 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN   = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 1/1/~ ${fhr}-HR NDAS 3-HR PCP 
 GDFILE   = $fmdl1 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDPFUN   = p03i 
 TITLE    = 0
 CINT     = 0.10
 FINT     = 0.01;0.10;0.25;0.50;0.75;1.
 FLINE    = 0;21;22;23;24;25;10;2 
 CLRBAR   = 1/V/UL/.15;0.9/.8;.03/-1
r

ex
EOF
gpend
done
done


for fhr in $times; do
for region in $areas; do
CONV=/usrx/local/ImageMagick/6.8.3-3/bin
$CONV/convert -crop 0x0 popz${region}f${fhr}.gif ${cyc}ndas${ymdh}popz${region}f${fhr}.gif
done
scp ${cyc}ndas*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
done
exit

