#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/60pcptrnest
rm /stmpp1/Geoffrey.Manikin/meg/60pcptrnest/*
cd /stmpp1/Geoffrey.Manikin/meg/60pcptrnest
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2015100118
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold3

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

fhr1=60
fmdl1=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh2}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh3}
fmdl4=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p60i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  4 KM NAM 60-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|namnest60pcptrz2_${ymd1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-83;25;/1;1;1;1
 GAREA    = sc+ 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.01;.94/2.4;.02/-1 
# CLRBAR   = 1/V/UL/.02;.7/1.5;.02/-1
 CONTUR   = 0
 SKIP     = 0
# FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5;4;5
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;10;5
 FINT     = .01;.25;.5;1;1.5;2;3;4;5;7.5;10;12.5;15;20;25;30
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;17;10;5;32;1
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr1}
 TITLE    = 1//  4 KM NAM 60-HR PCP  $ymd2 ${cyc2}z  F${fhr1}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0 
 CLEAR    = n
r

# TITLE    = 2/1/VERIFYING TIME   $verymdh
#r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr1}
 TITLE    = 1//  4 KM NAM 60-HR PCP  $ymd3 ${cyc3}z  F${fhr1}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr1}
 TITLE    = 1//  4 KM NAM 60-HR PCP  $ymd4 ${cyc4}z  F${fhr1}
 PANEL    = 0.52;0;1.;0.58
 CLRBAR   = 0
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
