#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/hrrruphl
rm /stmpp1/Geoffrey.Manikin/meg/hrrruphl/*
cd /stmpp1/Geoffrey.Manikin/meg/hrrruphl
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017012217
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold6
lasthr=11

hours="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
hours="01 02 03 04 05 06 07 08 09 10 11"
for fhr in $hours;do

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl1=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 5000:2000 
 GVCORD   = hght 
 GDPFUN   = MXUPHL01
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|hrrruphl_${ymdh}f${lasthr}.gif | 800;850
 GAREA    = 34.;-105.;40.;-96.
 GAREA    = 26.;-88.;36.;-78. 
 GAREA    = 27.5;-86.;32.;-79.5
 PROJ     = "lcc/25.;-83.;25./2;2;1;1"
 MAP      = 1/1/2;1
 TITLE    = 1//  ${cyc}z HRRR  2-5 KM MAX UPDRAFT HLCY 
 CLEAR    = n 
 SCALE    = 0
 PANEL    = 0 
 HILO     = 0
 HLSYM    = 0 
# CLRBAR   = 1/V/UL/.02;0.95/0.9;.03/1
 CLRBAR   = 1/H/UL/.2;.95/0.6;.03/1
 TEXT     = 0.9/11/2
 FINT     = 25;50;75;100;125;150;175;200
 FLINE    = 0;4;26;2;15;17;10;20;5
 TYPE     = f 
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
