#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/sref24pcp
rm /stmp/Geoffrey.Manikin/meg/sref24pcp/*
cd /stmp/Geoffrey.Manikin/meg/sref24pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

ymdh=2015021321
ymd=`echo $ymdh | cut -c1-8`

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold3

hours="45"
for fhrs in $hours; do

fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/sref.${ymd}/sref212_${ymdh}_mean

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(p24menmw,25.4) 
 CINT     = 4 
 LINE     = 4/1/2/3 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   SREF MEAN 24-HR PCP  
 DEVICE   = GIF|sref24pcp_${ymdh}f0${fhrs}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-70;25;/1;1;1;1
 GAREA    = ri 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 1/h/UL/.06;.95/.9;.02/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
