#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/srefxpcpprob
rm /stmpp1/Geoffrey.Manikin/meg/srefxpcpprob/*
cd /stmpp1/Geoffrey.Manikin/meg/srefxpcpprob
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2014031612
#dayoweek=Sun
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

if [ $cycs -eq 03 ]; then
 hours="33 57 81"
elif [ $cycs -eq 09 ]; then
 hours="27 51 75"
elif [ $cycs -eq 15 ]; then
 hours="45 69"
else
 hours="39 63"
fi

for fhrs in $hours; do

fmdl1=/com/nawips/prod/sref.${ymds}/sref212_${ymdhs}_prob
fmdl2=/meso/save/Geoffrey.Manikin/meg/srefx212_${ymdhs}_prob

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = P24M0006PA 
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    SREF PROB of 0.25"
 DEVICE   = GIF|${cycs}srefxprob1_24pcp_f0${fhrs}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROOJ    = lcc/25;-105;25;/1;1;1;1
 GAREA    = 20.;-138.;52.;-48.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~    SREFX PROB of 0.25"
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1
r

 GDFILE  = $fmdl1
 GDPFUN  = P24M0012PA 
 PANEL   = t
 DEVICE   = GIF|${cycs}srefxprob2_24pcp_f0${fhrs}.gif|750;900
 TITLE   = 1/-1/~    SREF PROB of 0.5"
 CLRBAR  = 0
 CLEAR   = y
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~    SREFX PROB of 0.5"
 CLRBAR   = 1/H/UL/.2;.99/0.6;.03/1
r

 GDFILE   = $fmdl1
 GDPFUN   = P24M0025PA
 PANEL    = t
 DEVICE   = GIF|${cycs}srefxprob3_24pcp_f0${fhrs}.gif|750;900
 TITLE    = 1/-1/~    SREF PROB of 1.0"
 CLRBAR   = 0
 CLEAR    = y
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~    SREFX PROB of 1.0"
 CLRBAR   = 1/H/UL/.2;.99/0.6;.03/1
r

 GDFILE   = $fmdl1
 GDPFUN   = P24M0050PA
 PANEL    = t
 DEVICE   = GIF|${cycs}srefxprob4_24pcp_f0${fhrs}.gif|750;900
 TITLE    = 1/-1/~    SREF PROB of 2.0"
 CLRBAR   = 0
 CLEAR    = y
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~    SREFX PROB of 2.0"
 CLRBAR   = 1/H/UL/.2;.99/0.6;.03/1
r

 GDFILE   = $fmdl1
 GDPFUN   = P24M0101PA
 PANEL    = t
 DEVICE   = GIF|${cycs}srefxprob5_24pcp_f0${fhrs}.gif|750;900
 TITLE    = 1/-1/~    SREF PROB of 4.0"
 CLRBAR   = 0
 CLEAR    = y
r

 GDFILE   = $fmdl2
 PANEL    = b
 CLEAR    = n
 TITLE    = 1/-1/~    SREFX PROB of 4.0"
 CLRBAR   = 1/H/UL/.2;.99/0.6;.03/1
r

ex
EOF

gpend
done
mv ${cycs}*gif /stmpp1/Geoffrey.Manikin/meg/holdshortx/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

exit
