#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/2mtsrefmem
rm /stmp/Geoffrey.Manikin/meg/2mtsrefmem/*
cd /stmp/Geoffrey.Manikin/meg/2mtsrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014040303
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Thu

DAPATH=/com/sref/prod/sref.${ymd}/${cyc}/pgrb
hours="00 03 09"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.ctl.f${fhr} -i -grib -o mdl1
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p1.f${fhr} -i -grib -o mdl2
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p2.f${fhr} -i -grib -o mdl3
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.p3.f${fhr} -i -grib -o mdl4
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n1.f${fhr} -i -grib -o mdl5
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n2.f${fhr} -i -grib -o mdl6
wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} | grep kpds5=17:kpds6=105  | wgrib ${DAPATH}/sref_${mdl}.t${cyc}z.pgrb212.n3.f${fhr} -i -grib -o mdl7

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = mdl1.gem 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = mdl2
GDOUTF  = mdl2.gem
r

GBFILE  = mdl3
GDOUTF  = mdl3.gem
r

GBFILE  = mdl4                           
GDOUTF  = mdl4.gem
r

GBFILE  = mdl5
GDOUTF  = mdl5.gem
r

GBFILE  = mdl6                           
GDOUTF  = mdl6.gem
r

GBFILE  = mdl7                           
GDOUTF  = mdl7.gem
r

exit
EOF

    gdplot2 << EOF
 GDFILE   = mdl1.gem
 GDATTIM  = f${fhr} 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = dwpf 
 CINT     = 4 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL 2-M DEW   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}2dew_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
# GAREA    = 28.;-96.;48.;-60.
 GAREA    = sc- 
 PROJ     = lcc/25;-80.;25/1;1;1;1
# GAREA    = 21.;-121.;51.;-65.
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = -12;-8;-4;0;4;8;12;16;20;24;28;32;36;40;44;48;52;56;60;64;68;72;76;80
# FINT     = -76;-68;-60;-52;-44;-36;-28;-20;-12;-4;4;12;20;28;36;44;52;60;68;76
 FLINE    = 0;11;9;12;7;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;32
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = mdl2.gem
 TITLE    = 1// $mdl P1 2-M DEW   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
r

 GDFILE   = mdl3.gem
 TITLE    = 1// $mdl P2 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
r

 GDFILE   = mdl4.gem
 TITLE    = 1// $mdl P3 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
r

 GDFILE   = mdl5.gem
 TITLE    = 1// $mdl N1 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
r

 GDFILE   = mdl6.gem
 TITLE    = 1// $mdl N2 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 CLRBAR   = 0
r

 GDFILE   = mdl7.gem
 TITLE    = 1// $mdl N3 2-M DEW   $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 CLRBAR   = 1/H/UL/.99;.6/1.4;.06/2
r

ex
EOF
rm mdl*
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
