#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

da00=20060602
hr00=21

mkdir /stmpp1/wx20mg/gempak.ruc20/cape
rm /stmpp1/wx20mg/gempak.ruc20/cape/*
cd /stmpp1/wx20mg/gempak.ruc20/cape

times="01"

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

for fhr in $times; do

fmdl=/meso/save/wx20mg/gempak/nagribx/ruc2x_${da00}${hr00}f0${fhr}
echo $fmdl
echo $fmdl2

# negate the colors ahead of time except white and black
gpcolor << EOFC
COLORS=0=255:255:255?
COLORS=101=255:255:255;1=0:0:0
DEVICE   = GF
r

ex
EOFC

    gdcntr << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GFUNC    = cape 
 CINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000;5500 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//~   SFC-BASED CAPE 
 DEVICE   = GF|comparerucxcape_${da00}f1.gif
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-105.;25./2;2;1;1
 GAREA    = 31.;-110.;43.;-96. 
 CLEAR    = y
 PANEL    = 0;0;1;.49
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;.85/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000;5500 
 FLINE    = 0;0;25;21;22;23;5;10;17;16;2;15;32 
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 GLEVEL   = 255:0
 GVCORD   = pdly
 PANEL    = 0.;.51;1.;1.
 CLEAR    = n
 TITLE    = 1//~    BEST CAPE
r

ex
EOF

gpend
done
/nwprod/util/ush/stopxvfb.sh /bin/sh

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
                                                                                     
ftp -n -v << EOF > /meso/save/wx20mg/gempak.ruc20/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/ruccape
prompt
mput *.gif
bye
EOF

exit
