#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/skin
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch9/skin
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none 
 GDPFUN   = tmpf 
 CINT     = 5
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|compareskin_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110;115
 FLINE    = 0;11;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP SKIN TEMP 
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAPX  SKIN TEMP 
 GDFILE   = $fmdl2 
 GAREA    = 16.;-126.;55.;-57.
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = tmpf
 TITLE    = 0
 CINT     = 5 
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.

cat > info.html <<EOFmet
<HTML>
<HEAD>
<TITLE>RAPX GRAPHICS</TITLE>
</HEAD>
<BODY bgcolor="FFFFCC">
<HTML>
<CENTER><b><font color="#009900"><font size=+4>RAPX Graphics </H1></CENTER></font>
</font
></b><CENTER>
<p>
The current forecast cycle is <b><font face="Times New Roman,Times"><font size=+1>
<font color="#CC0000">${cyc}Z ${day} ${mon} </font><font color="#FF6600"></font></
font></font></b>with graphics finished at $gtime $gdate $gcent
</CENTER>
<p>
<H3>This page displays the new Rapid Refresh (RAPX) forecast and compares it to the operational RUC. When any forecast hour button on the left is activated, the following maps wiwill be displayed:</H3>
<p>
<br>
<CENTER>
<TABLE BORDER>
<TR>
<TD><H4>Top: <font color="#CC33CC"><font size=+4>RUC</font></font></H4></TD>
</TR>
<TR>
<TD><H4>Bottom: <b><font color="#FF6600"><font size=+4>RAPX</font></H4></TD></b>
</TR>
</TABLE>
</CENTER>
<p>
<br>
<H4>NOTE: The AWIPS grid #252 (20 km Lambert Conformal) is used for all plots.
<p>
<br>
<H4>NOTE: All displayed winds are in knots.  Precipitation values are in inches.
<p>
<br>
<p>
<br>
<center> <a href='http://www.nws.noaa.gov/disclaimer1.html'>Disclaimer</a> </cente
r>
</BODY>
</HTML>
EOFmet

mv *html ../../ftphold/.
echo abouttoexitskin
exit
