#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850z
rm /stmpp1/Geoffrey.Manikin/meg/850z/*
cd /stmpp1/Geoffrey.Manikin/meg/850z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2018051712
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

times="96 120 144 168 192 216"
times="150 156 162 174 180 186"
times="96 104 110 116 120 126 132 138 144 150 156 162 174 180 186 192 198 204 210 216"
for fhr in $times; do

typeset -Z3 fhr
DAPATH=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}
DAPATH=/ptmpp1/Geoffrey.Manikin/hold
fmdl1=${DAPATH}/gfs_0p25_${ymdh}f${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = avor
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 850 mb  Z/AVOR
 DEVICE   = GIF|gfs850_${ymdh}f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-85;25;/1;1;1;1
 GAREA    = 8.;-100.;34.;-60. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-96;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36;40;44;48
 FLINE    = 0;23;21;5;19;17;16;2;15;14
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 3
 LINE     = 4/1/3/1
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.1/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

ex
EOF

done
gpend
scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
