#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/visprob
rm /stmp/Geoffrey.Manikin/meg/visprob/*
cd /stmp/Geoffrey.Manikin/meg/visprob
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014011418
dayoweek=Tue
ymdhs="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

hours="18 21"

for fhrs in $hours; do

fmdl1=/com/nawips/para/sref.${ymds}/sref212_${ymdhs}_prob
#fmdl1=/ptmp/Geoffrey.Manikin/test/sref212_${ymdhs}_prob

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhrs
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = VSBY1609PB
 CINT     = 10
 LINE     = 21/1/3/5 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~    SREFX PROB of VIS < 1 MILE
 DEVICE   = GIF|${cycs}srefxprob1_vsby_f0${fhrs}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 24.;-105.;36.;-85. 
 GAREA    = de-
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 4/3 
 SKIP     = 0
 FINT     = 10;30;50;70;90 
 FLINE    = 0;21;23;28;30;2 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN  = VSBY 3218PB
 PANEL   = b
 TITLE   = 1/-1/~    SREFX PROB of VIS < 2 MILE
 CLEAR   = n
 CLRBAR  = 1/H/UL/.2;.99/0.6;.03/1 
r

ex
EOF

gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#mv ${cycs}*gif /stmp/Geoffrey.Manikin/meg/holdshort/.
exit
