#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/12cpcptrnam
rm /stmpp1/Geoffrey.Manikin/meg/12cpcptrnam/*
cd /stmpp1/Geoffrey.Manikin/meg/12cpcptrnam
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2019071300
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold8

hours="24"
for fhr in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr} -1`"
fhr2=`expr $fhr + 6`
fhr3=`expr $fhr + 12`
fhr4=`expr $fhr + 18`
typeset -Z2 fhr2 fhr3 fhr4

DAPATH=/meso/noscrub/Geoffrey.Manikin/barry
fmdl1=${DAPATH}/nampcp_${ymdh}
fmdl2=${DAPATH}/gfspcp_${ymdh}
fmdl3=${DAPATH}/gfsv14pcp_${ymdh}
fmdl4=/gpfs/hps/nco/ops/com/rap/prod/rap.2019071303/nawips/rap13_${ymdh}f021
fmdl4a=/gpfs/hps/nco/ops/com/rap/prod/rap.2019071303/nawips/rap13_${ymdh}f009

   gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = c12i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 \$MAPFIL = 0
# \$MAPFIL = county
 WIND     = 0
 TITLE    = 1//  NAM 12-HR CNVCT PCP  $ymd1 ${cyc}z  F${fhr}
 DEVICE   = GIF|nam12cpcpz_${ymdh}f0${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 GAREA    = 27.2;-98.;38.;-85. 
 PROJ     = lcc/25;-91;25/2;2;1;1
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.05;0.96/0.9;.02/1|0.8/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
# FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 FINT     = .01;.25;.5;0.75;1.;1.5;2;2.5;3;4;5;7.5;10;12.5;15;20
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5;1
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1//  GFS 12-HR CNVCT PCP  $ymd ${cyc}z  F${fhr}
 CLEAR    = y
 DEVICE   = GIF|gfs12cpcpz_${ymdh}f0${fhr}.gif | 800;850
r

 GDFILE   = $fmdl3
 TITLE    = 1//  GFSv14  12-HR CNVCT PCP  $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|gfsx12cpcpz_${ymdh}f0${fhr}.gif | 800;850
r

 GDFILE   = $fmdl4a + $fmdl4
 GDPFUN   = sub(c21i,c09i) 
 TITLE    = 1//  RAP 12-HR CNVCT PCP  $ymd ${cyc}z  F21
 DEVICE   = GIF|rap12cpcpz_${ymdh}f0${fhr}.gif | 800;850
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
