#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2016050915
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
stnm=723555

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/snd
rm /stmpp1/Geoffrey.Manikin/meg/snd/*
cd /stmpp1/Geoffrey.Manikin/meg/snd
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#ymdh=`cut -c 7-16 /com/date/t${cyc}z`
#ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold6

#cp /meso2/noscrub/Jacob.Carley/com/nawips/rt/namrr.${ymd}/namrr_conusnest_${ymdh}.snd.tm00 fmdl1
cp /ptmpd2/Geoffrey.Manikin/com2/nawips/para/namrr.${ymd}/namrr_conusnest_${ymdh}.snd.tm00 fmdl1

times="03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18"
times="00 01 02 03 04 05 06"
times="07 08 09"
for time in $times; do

validtime="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} $time -1 x`"
echo validtime = $validtime
dattim=`echo $validtime | cut -c5-11`
echo dattim = $dattim

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = fmdl1
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/7
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM 
 DEVICE   = gif|namrr_${ymdh}snd${stnm}_$fhr.gif | 800;850
 YAXIS    = 1000/600/50/1;1;1
 XAXIS    = 0/30/5/;1
 FILTER   = 0.9 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 0.8 
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/cases/${ymd}/.
exit
