#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2008030500
ymd=`echo $ymdh | cut -c 1-8`
stations="724050 724030 724080 805"
mkdir /stmpp1/wx20mg/gempak.ruc20/direct
rm /stmpp1/wx20mg/gempak.ruc20/direct/*
cd /stmpp1/wx20mg/gempak.ruc20/direct

times="09"

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

for fhr in $times; do
counter=0
validtime="`/meso/save/wx20mg/board/advtime ${ymdh} $fhr -1 x`"
dattim=`echo $validtime | cut -c5-11`

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

for stnm in $stations; do

fmdl=/com/nawips/prod/ruc2.${ymd}/ruc2_${ymdh}.snd
fmdl2=/ptmpp1/wx20mg/ruc2/ruc2a.${ymd}/ruc2_${ymdh}.snd
echo $fmdl
echo $fmdl2

# negate the colors ahead of time except white and black
gpcolor << EOFC
COLORS=0=255:255:255?
COLORS=101=255:255:255;1=0:0:0
DEVICE   = GF
r

ex
EOFC

    snprof << EOF
 SNFILE   = $fmdl
 DATTIM   = $dattim
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/1/5
 PTYPE    = skewt
 VCOORD   = PRES
 STNDEX   = lift;cape;cins
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 1
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1// $stnm   SOLID-ops  DASHED-exper
 DEVICE   = gf|rucsnd${stnm}_${cyc}f${fhr}.gif|650;750 
 YAXIS    = 1050/250/100/1;1;1
 XAXIS    = -25/35/10/;1
# YAXIS    = 1050/350/100/1;1;1
# XAXIS    = -25/35/10/;1
 FILTER   = 0.6
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.0
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 LINE     = 2;4/10/4
 CLEAR    = n
 WINPOS   = 2
 TITLE    = 0
r 
 
ex
EOF

gpend
counter=`expr $counter + 1`
done
done

/nwprod/util/ush/stopxvfb.sh /bin/sh

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/gempak.ruc20/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/ruc2/para/cases/${ymd}
prompt
mput *.gif
bye
EOF

echo abouttoexitsnd
exit
