#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/12pcptrnam4
rm /stmpp1/Geoffrey.Manikin/meg/12pcptrnam4/*
cd /stmpp1/Geoffrey.Manikin/meg/12pcptrnam4
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2016020412
cyc=12
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`
dayoweek=hold6

hours="36"
ymd2=`echo $ymdh2 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`

for fhr1 in $hours; do

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"
fhr2=`expr $fhr1 + 12`
typeset -Z2 fhr2 

fmdl1=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh
fmdl2=/meso/save/Geoffrey.Manikin/meg/hireswnmmbpcp_$ymdh
fmdl3=/meso/save/Geoffrey.Manikin/meg/hireswarwpcp_$ymdh2
fmdl4=/meso/save/Geoffrey.Manikin/meg/hireswnmmbpcp_$ymdh2

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p24i 
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  ARW 24-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|hiresw24pcptrz_${ymd1}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
# GAREA    = 37.;-94.;45.;-82. 
 GAREA    = nj 
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.5;0.92/1.5;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
 CLEAR    = n
 CLRBAR   = 0
r

 GDFILE   = $fmdl2
 TITLE    = 1//  NMMB24-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr2}
 TITLE    = 1//  ARW 24-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 TITLE    = 1//  NMMB 24-HR PCP  $ymd1 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend
done
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
