#!/bin/ksh
echo 'into'

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/hrrrsnow
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

ymdh=2020102700
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold8

hours="24"
for fhr in $hours; do

DAPATH=/com2/nawips/prod
DAPATH=/gpfs/dell1/ptmp/Geoffrey.Manikin/hrrrx
fmdl1=${DAPATH}/hrrrx_${ymdh}f0${fhr}00

garea="37.5;-81.;47.;-67."
garea="ok"
proj="lcc/25.;-97.;25./2;2;1;1"

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = mul(sn${fhr}m,39.37)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|${ymd}${cyc}hrrrwinter_f${fhr}.gif | 800;850
 PROJ     = $proj 
 GAREA    = $garea 
 TITLE    = 1//~  HRRRv4   ${fhr}-HR ACC SNOW DPTH
 CLEAR    = y
 SCALE    = 0
 PANEL    = ur 
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.02;0.95/0.9;.03/1 
 TEXT     = 0.7/11/2
 FINT     = 1;2;3;4;6;8;10;12;18;24 
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;16;17;10;5
 TYPE     = f 
r

 GDPFUN   = p${fhr}i
 PANEL    = ul 
 CLEAR    = n
 TITLE    = 1//~  HRRRv4   ${fhr}-HR TOTAL PCP 
 FINT     = 0.01;0.10;0.25;0.5;0.75;1;1.5;2;2.5;3;3.5;4;5;6;8
 CLRBAR   = 0 
r

 PANEL    = ll 
 GDPFUN   = quo(zr${fhr}m,25.4) 
 TITLE    = 1//~  HRRRv4   ${fhr}-HR FREEZING RAIN 
 CLRBAR   = 1/H/UL/.02;0.97/1.9;.03/1
r

 PANEL    = lr 
 GDPFUN   = quo(gr${fhr}m,25.4)
 TITLE    = 1//~  HRRRv4   ${fhr}-HR SLEET 
 CLRBAR   = 0
r

ex
EOF
done
gpend

#mv *gif /gpfs/dell1/stmp/Geoffrey.Manikin/meg/holdpcp/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
