#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch1/500
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch1/500
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
times="12"

counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = trop 
 GDPFUN   = pres 
 CINT     = 50 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 0
 DEVICE   = GIF|comparebase_nco_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;100;150;200;250;300;350;400;450;500;550 
 FLINE    = 0;15;2;17;5;20;21;23;25;24;29;30
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 1/1/ ${fhr}-HR RAP TROP PRESSURE
 TEXT     = 1.2/11/2
 CLEAR    = n
 GDPFUN     = blurk
 CINT     = -2000/-2000/-2000
 CLRBAR   = 0
r

 TITLE    = 4/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAPX TROP PRESSURE 
 GDFILE   = $fmdl2 
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
r

 GDFILE   = $fmdl2 
 GDPFUN   = pres 
 TITLE    = 0
 CINT     = 50 
r

ex
EOF

counter=`expr $counter + 1`
gpend
done
                                                                                       
mv *gif ../../ftphold/.
echo abouttoexittrop
exit
