#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch15/jetdiff
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch15/jetdiff
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

cp /com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr} fmdl1
cp /ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr} fmdl2

    gdcntr << EOF
 GDFILE   = fmdl1 + fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 350 
 GVCORD   = pres 
 GFUNC    = knts(sub(sped+2,sped)) 
 CINT     = 3 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RAPX - RAP  350 WIND DIFFS 
 DEVICE   = GIF|comparejet_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-1
 CONTUR   = 0
 SKIP     = 0
 FINT     = -25;-20;-15;-10;-5;5;10;15;20;25
 FLINE    = 15;2;17;10;5;0;21;23;25;4;29  
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR  RAPX - RAP 250 WIND DIFFS 
 GAREA    = 16.;-126.;55.;-57.
 TEXT     = 1.1/11/2/SW
 PANEL    = 0;0;1;.49
 GLEVEL   = 250 
 CLRBAR   = 0
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexitjet
exit
