#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/nest850t
rm /stmp/wx20mg/meg/nest850t/*
cd /stmp/wx20mg/meg/nest850t
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=2012102912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Mon

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30"
hours="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 850 
 GVCORD   = pres 
 GDPFUN   = tmpc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|conusnest850t_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 33.;-88.;47.;-60. 
 TITLE    = 1//~  NAM CONUS NEST 850 mb T 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.06;0.97/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = -10;-8;-6;-4;-2;0;2;4;6;8;10;12;14;16;18;20
 FLINE    = 12;30;29;28;4;25;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f 
r

ex
EOF
done
gpend

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
mput *gif 
bye
EOF

rm *gif
exit
