#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/stormpcptr
rm /stmp/Geoffrey.Manikin/meg/stormpcptr/*
cd /stmp/Geoffrey.Manikin/meg/stormpcptr
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`echo $ymdh | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

fhr1="42"
length="42"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fmdl1=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh}
fmdl2=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh2}
fmdl3=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh3}
fmdl4=/meso/save/Geoffrey.Manikin/meg/nampcp_${ymdh4}

fmdl5=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh}
fmdl6=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh2}
fmdl7=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh3}
fmdl8=/meso/save/Geoffrey.Manikin/meg/gfspcp_${ymdh4}

fmdl9=/meso/save/Geoffrey.Manikin/meg/nambpcp_${ymdh}
fmdl10=/meso/save/Geoffrey.Manikin/meg/nambpcp_${ymdh3}

fmdl11=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh}
fmdl12=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh2}
fmdl13=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh3}
fmdl14=/meso/save/Geoffrey.Manikin/meg/namnestpcp_${ymdh4}


    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr1} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = p${length}i
 CINT     = 0.25 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAM ${length}-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|namstormpcptr.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 16.;-121.;52.;-65.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl2
 GDATTIM  = f${fhr2}
 TITLE    = 1//  NAM ${length}-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr3}
 TITLE    = 1//  NAM ${length}-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl4
 GDATTIM  = f${fhr4}
 TITLE    = 1//  NAM ${length}-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF

    gdplot2 << EOF
 GDFILE   = $fmdl5
 GDATTIM  = f${fhr1}
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p${length}i
 CINT     = 0.25
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  GFS ${length}-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|gfsstormpcptr${counter}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 16.;-121.;52.;-65.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl6
 GDATTIM  = f${fhr2}
 TITLE    = 1//  GFS ${length}-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl7
 GDATTIM  = f${fhr3}
 TITLE    = 1//  GFS ${length}-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl8
 GDATTIM  = f${fhr4}
 TITLE    = 1//  GFS ${length}-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF

    gdplot2 << EOF
 GDFILE   = $fmdl9
 GDATTIM  = f${fhr1}
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p${length}i
 CINT     = 0.25
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  NAMB ${length}-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|nambstormpcptr.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 16.;-121.;52.;-65.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl10
 GDATTIM  = f${fhr3}
 TITLE    = 1//  NAMB ${length}-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

ex
EOF

    gdplot2 << EOF
 GDFILE   = $fmdl11
 GDATTIM  = f${fhr1}
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = p${length}i
 CINT     = 0.25
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  4 KM NAM ${length}-HR PCP  $ymd1 ${cyc}z  F${fhr1}
 DEVICE   = GIF|namneststormpcptr.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 16.;-121.;52.;-65.
 CLEAR    = y
 PANEL    = 0.;0.42;0.48;1.
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1;1.5;2;2.5;3;3.5
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 CLEAR    = n
 GDFILE   = $fmdl12
 GDATTIM  = f${fhr2}
 TITLE    = 1//  4 KM NAM ${length}-HR PCP  $ymd2 ${cyc2}z  F${fhr2}
 PANEL    = 0.52;0.42;1.;1.
 CLRBAR   = 0
 CLEAR    = n
r

 GDFILE   = $fmdl13
 GDATTIM  = f${fhr3}
 TITLE    = 1//  4 KM NAM ${length}-HR PCP  $ymd3 ${cyc3}z  F${fhr3}
 PANEL    = 0;0;0.48;0.58
r

 GDFILE   = $fmdl14
 GDATTIM  = f${fhr4}
 TITLE    = 1//  4 KM NAM ${length}-HR PCP  $ymd4 ${cyc4}z  F${fhr4}
 PANEL    = 0.52;0;1.;0.58
r

ex
EOF
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *gif
bye
EOF

exit
