#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/Geoffrey.Manikin/meg
mkdir /stmp/Geoffrey.Manikin/meg/nestslpz
rm /stmp/Geoffrey.Manikin/meg/nestslpz/*
cd /stmp/Geoffrey.Manikin/meg/nestslpz
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014010112
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Wed

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="00 06 12 18 24 30 36 42 48 54 60"
hours="00 12 24 36 42 45 48 51 54 60"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = emsl 
 CINT     = 2 
 LINE     = 1/1/4/2 
 DEVICE   = GIF|${cyc}slpnestz${fhr}.gif | 800;850
 PROJ     = lcc/25;-70;25;/1;1;1;1
 GAREA    = 28.;-88.;50.;-50.
# GAREA    = 24.;-121.;52.;-61.
 TITLE    = 1//~  NAM CONUS NEST SLP 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 2;2/S12#;S13#/1015-1060;920-1014/5/1;1/yes
 HLSYM    = 2;2/3/21;21/4;2/HW
 CLRBAR   = 1/H/UL/.06;0.94/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c 
r

ex
EOF

done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
