#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/typesrefmem
rm /stmpp1/Geoffrey.Manikin/meg/typesrefmem/*
cd /stmpp1/Geoffrey.Manikin/meg/typesrefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2014031409
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Fri

DAPATH=/com/sref/prod/sref.${ymd}/${cyc}/pgrb/
hours="69"
models="em nmm nmb"
members="ctl p1 p2 p3 n1 n2 n3"

for fhr in $hours; do
for mdl in $models; do

fmdl1=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_ctl
fmdl2=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p1
fmdl3=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p2
fmdl4=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_p3
fmdl5=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n1
fmdl6=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n2
fmdl7=/com/nawips/prod/sref.${ymd}/sref212_${ymdh}_${mdl}_n3

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = f${fhr} 
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = wxtr 
 CINT     = 1 
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL TYPE   $ymd ${cyc}z  F${fhr}
 DEVICE   = GIF|sref${mdl}type_${ymdh}f${fhr}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = de 
# GAREA    = nj- 
 CLEAR    = y
 PANEL    = m1 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0.11;10
 FLINE    = 0;3 
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 CLEAR    = n
 GDFILE   = $fmdl2
 TITLE    = 1// $mdl P1 TYPE   $ymd ${cyc}z  F${fhr} 
 PANEL    = m2 
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl3
 TITLE    = 1// $mdl P2 TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m3 
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl4
 TITLE    = 1// $mdl P3 TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m4
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl5
 TITLE    = 1// $mdl N1 TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m5
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl6
 TITLE    = 1// $mdl N2 TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m6
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

 GDFILE   = $fmdl7
 TITLE    = 1// $mdl N3 TYPE   $ymd ${cyc}z  F${fhr}  
 PANEL    = m7
 GDPFUN   = wxtr
 FLINE    = 0;3
r

 GDPFUN   = wxts
 CLEAR    = n
 FLINE    = 0;26
r

 GDPFUN   = wxtp
 FLINE    = 0;29
r

 GDPFUN   = wxtz
 FLINE    = 0;2
r

ex
EOF
rm mdl*
done
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
