#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
storm="sandy18l"

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/slp
rm /stmp/wx20mg/meg/slp/*
cd /stmp/wx20mg/meg/slp
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012102800
ymd=20121028
dayoweek=Sun

times="72 84 96"
times="00 18 24 30 36 42 48 60 72 84"
ymdhs="`/meso/save/wx20mg/meteograms.nam/advtime ${ymdh} -3 -1`"
ymds=`echo $ymdhs | cut -c1-8`
cycs=`echo $ymdhs | cut -c9-10`

for fhr in $times; do

fhrs=`expr $fhr + 3`
fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/sref.${ymds}/sref212_${ymdhs}_mean
fmdl4=/com/nawips/prod/ecmwf.${ymd}/ecmwf_hr_${ymdh}f0${fhr}
fmdl5=/com/nawips/prod/ukmet.${ymd}/ukmet_${ymdh}f0${fhr}
fmdl6=/com/nawips/prod/hwrf.${ymd}/${storm}/hwrfc_${ymdh}f0${fhr}_${storm}
fmdl7=/com/nawips/prod/gefs.${ymd}/geavg_${ymdh}f0${fhr}
fmdl8=/meso/save/wx20mg/meg/namb_${ymdh}
fmdl9=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 0 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  RED-nam  PINK-namb  ORANGE-sref
 DEVICE   = GIF|slpplot_f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 30.;-86.;46.;-56. 
! GAREA    = 20.;-82.;36.;-56.
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.9/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1/-2/ LT GREEN-ecmwf  DK GREEN-ukmet LT BLUE-hwrf 
 HILO     = ;4/;S13#/;920-1000/5/2;2/yes 
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhrs
 GDPFUN   = pmslenmw
 CLEAR    = n
 TITLE    = 1/-3/ DK PUR-gefs  DK BLUE-gfs  LT PUR-nam4
 HILO     = ;17/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr
 GDPFUN   = pmsl
 CLEAR    = n
 TITLE    = 0
 HILO     = ;21/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl5
 CLEAR    = n
 TITLE    = 0
 HILO     = ;23/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl6
 CLEAR    = n
 TITLE    = 0
 HILO     = ;26/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl7
 CLEAR    = n
 HILO     = ;30/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl8
 CLEAR    = n
 HILO     = ;11/;S13#/;920-1000/5/2;2/yes
r

 GDFILE   = $fmdl9
 CLEAR    = n
 HILO     = ;28/;S13#/;920-1000/5/2;2/yes
r

ex
EOF
done
gpend

for fhr in $times; do

/usrx/local/im_beta/bin/convert -crop 0x0 slpplot_f0${fhr}.gif allslp_${ymdh}f0${fhr}.gif
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput all*gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput all*gif
bye
EOF

exit
