#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/6pcp
rm /stmpp1/Geoffrey.Manikin/meg/6pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/6pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2016020518
ymd1=`echo $ymdh | cut -c1-8`
dayoweek=hold7

ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -6 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -12 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} -18 -1`"

ymd2=`echo $ymdh2 | cut -c1-8`
ymd3=`echo $ymdh3 | cut -c1-8`
ymd4=`echo $ymdh4 | cut -c1-8`
cyc2=`echo $ymdh2 | cut -c9-10`
cyc3=`echo $ymdh3 | cut -c9-10`
cyc4=`echo $ymdh4 | cut -c9-10`

hours="72"
for fhr1 in $hours; do

fhr2=`expr $fhr1 + 6`
fhr3=`expr $fhr1 + 12`
fhr4=`expr $fhr1 + 18`
typeset -Z2 fhr2 fhr3 fhr4

fhr1b=`expr $fhr1 - 3`
fhr2b=`expr $fhr2 - 3`
fhr3b=`expr $fhr3 - 3`
fhr4b=`expr $fhr4 - 3`
typeset -Z2 fhr1b fhr2b fhr3b fhr4b

verymdh="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymdh} ${fhr1} -1`"

fmdl1=/com/nawips/prod/nam.${ymd1}/nam32_${ymdh}f0${fhr1}
fmdl1b=/com/nawips/prod/nam.${ymd1}/nam32_${ymdh}f0${fhr1b} 
fmdl2=/com/nawips/prod/nam.${ymd2}/nam32_${ymdh2}f0${fhr2}
fmdl2b=/com/nawips/prod/nam.${ymd2}/nam32_${ymdh2}f0${fhr2b}
fmdl3=/com/nawips/prod/nam.${ymd3}/nam32_${ymdh3}f0${fhr3}
fmdl3b=/com/nawips/prod/nam.${ymd3}/nam32_${ymdh3}f0${fhr3b}
fmdl4=/com/nawips/prod/nam.${ymd4}/nam32_${ymdh4}f0${fhr4}
fmdl4b=/com/nawips/prod/nam.${ymd4}/nam32_${ymdh4}f0${fhr4b}

    gdplot2 << EOF
 GDFILE   = $fmdl1 + $fmdl1b
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = add(p03i^${ymd1}/${cyc}f${fhr1b}+2,p03i^${ymd1}/${cyc}f$fhr1)
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 6-HR PCP 
 DEVICE   = GIF|namslp6pcp_${ymd1}f${fhr1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-65;25;/1;1;1;1
 GAREA    = 24.;-82.;50.;-50. 
 CLEAR    = y
 PANEL    = ul 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl1
 GDPFUN   = pmsl 
 TITLE    = 0 
 CLEAR    = n
 CINT     = 4
 LINE     = 4/1/2/3
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 TITLE    = 15/1/ CYCLES RUN ON   $ymd1
r

 PANEL    = ll
 GDFILE   = $fmdl3 + $fmdl3b
 GDPFUN   = add(p03i^${ymd3}/${cyc3}f${fhr3b}+2,p03i^${ymd3}/${cyc3}f$fhr3)
 HILO     = 0
 HLSYM    = 0
 TYPE     = f
 CLRBAR   = 1/H/UL/.3;0.95/1.5;.03/1
 TITLE    = 1/-1/~   NAM 6-HR PCP
r

 GDFILE   = $fmdl3
 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

 PANEL    = ur
 GDFILE   = $fmdl2 + $fmdl2b
 GDPFUN   = add(p03i^${ymd2}/${cyc2}f${fhr2b}+2,p03i^${ymd2}/${cyc2}f$fhr2)
 HILO     = 0
 HLSYM    = 0
 TYPE     = f
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAM 6-HR PCP
r

 GDFILE   = $fmdl2
 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

  TITLE    = 2/1/VERIFYING TIME   $verymdh
r

 PANEL    = lr
 GDATTIM  = f$fhr4
 GDFILE   = $fmdl4 + $fmdl4b
 GDPFUN   = add(p03i^${ymd4}/${cyc4}f${fhr4b}+2,p03i^${ymd4}/${cyc4}f$fhr4) 
 HILO     = 0
 HLSYM    = 0
 TYPE     = f
 TITLE    = 1/-1/~   NAM 6-HR PCP
r

 GDFILE   = $fmdl4
 GDPFUN   = pmsl
 TITLE    = 0
 CLEAR    = n
 LINE     = 4/1/2/3
 CINT     = 4
 HILO     = ;2/;S13#/;920-1000/5/2;2/yes
 HLSYM    = 2;1/3/1;1/3;2/HW
 TYPE     = c
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
