#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch2/slp
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch2/slp
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = mmsl 
 CINT     = 4 
 LINE     = 23/1/3/4 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ ${fhr}-HR RAP SEA LEVEL PRESSURE 
 DEVICE   = GIF|compareslp_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 1/S12#;S13#/1015-1060;920-1014/5/5;5/yes
 HLSYM    = 1;1/2/21;21/4;2/HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 
 FLINE    =  
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

 TITLE    = 2/-1/  FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.1/11/1/SW
r

 GDFILE   = $fmdl2
 GAREA    = 16.;-126.;55.;-57.
 PANEL    = 0;0;1;.49
 TITLE    = 0
 TEXT     = 0.8/11/1/SW
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

 CINT     = 6/546/600
 LINE     = 2/2/1/3
r

 GDATTIM  = f$fhr
 GLEVEL   = 0
 GVCORD   = none
 GDPFUN   = mmsl
 CINT     = 4
 LINE     = 23/1/3/4
 TITLE    = 1/1/ ${fhr}-HR RAPX SEA LEVEL PRESSURE 
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 TEXT     = 1.2/11/2/SW
 HILO     = 1/S12#;S13#/1015-1060;920-1014/5/5;5/yes
 HLSYM    = 1;1/2/21;21/4;2/HW
r


ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexitslp
exit
