#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=$1
ymd=`echo $ymdh | cut -c1-8`
month=`echo $ymdh | cut -c5-6`
day=`echo $ymdh | cut -c7-8`
cyc=`echo $ymdh | cut -c9-10`

mkdir /stmpp1/Geoffrey.Manikin/gempak.rap13/launch5/10e
cd /stmpp1/Geoffrey.Manikin/gempak.rap13/launch5/10e
cp /meso/save/Geoffrey.Manikin/gempak.rap13/coltbl.xwp .

times="00 01 02 03 06 09 12 15 18"
counter=0
for fhr in $times; do

fmdl=/com/nawips/prod/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
fmdl2=/ptmpp1/Geoffrey.Manikin/com/nawips/para/rap.${ymd}/rap13_${ymd}${cyc}f0${fhr}
echo $fmdl
echo $fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl
 GDATTIM  = f$fhr
 GLEVEL   = 10 
 GVCORD   = hght 
 GDPFUN   = knts(sped) 
 CINT     = 10;20;30 
 LINE     = 0
 MAP      = 1
 WIND     = ak29/0.6/2/122/0.7 
 TITLE    = 0
 DEVICE   = GIF|compare10e_${cyc}f${counter}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-80.;25./2;2;1;1
 GAREA    = 23.;-94.;49.;-60.
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.2/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.15;0.5/.8;.03/-2
 CONTUR   = 0
 SKIP     = /4;4 
 FINT     = 10;20;30
 FLINE    = 0;5;10;2
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = wnd
 TYPE     = a
 TITLE    = 1/1/ ${fhr}-HR RAP 10-M WINDS (KT)
 CLEAR    = n
r

 TITLE    = 23/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
 CLEAR    = n
r

 GDFILE   = $fmdl2
 PANEL    = 0;0;1;.49
 GDPFUN   = knts(sped)
 TEXT     = 1.2/11/2/SW
 TITLE    = 0
 CLRBAR   = 0
 TYPE     = f/c
r

 GDPFUN   = wnd
 TYPE     = a
 TITLE    = 1/1/ ${fhr}-HR RAPX  10-M WINDS (KT)
r

ex
EOF

counter=`expr $counter + 1`
gpend
done

mv *gif ../../ftphold/.
echo abouttoexit10e
exit

