#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

da00=`cut -c 7-14 /com/date/t${cyc}z`
hr00=`cut -c 15-16 /com/date/t${cyc}z`
month=`cut -c 11-12 /com/date/t${cyc}z`
day=`cut -c 13-14 /com/date/t${cyc}z`

#da00=`cut -c 7-14 t${cyc}z`
#hr00=`cut -c 15-16 t${cyc}z`

#da00=20040609
#hr00=18

mkdir /stmpp1/wx20mg/gempak.ruc20/launch2/diffs
rm /stmpp1/wx20mg/gempak.ruc20/launch2/diffs/*
cd /stmpp1/wx20mg/gempak.ruc20/launch2/diffs

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

#fmdl=/com/nawips/prod/ruc2.${da00}/ruc2_${da00}${hr00}f0${fhr}
fmdl=/meso/save/wx20mg/gempak/nagribx/ruc2_${da00}${hr00}
fmdl2=/meso/save/wx20mg/gempak/nagribx/ruc2x_${da00}${hr00}
#fmdl2=/stmpp1/wx20mg/gempak.ruc20/ruc2_${da00}${cyc}f0${fhr}

echo $fmdl1
echo $fmdl2

/nwprod/util/ush/startxvfb.sh /bin/sh
. ./STARTXVFB

# negate the colors ahead of time except white and black
gpcolor << EOFC
COLORS=0=255:255:255?
COLORS=101=255:255:255;1=0:0:0
DEVICE   = GF
r

ex
EOFC

    gdcntr << EOF

 GDFILE   = ${fmdl1}+${fmdl2}
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none
 GFUN     = sub(mmsl+2,mmsl) 
 CINT     = 1 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   SEA LEVEL PRESSURE DIFF
 DEVICE   = GF|comparediff_${cyc}f0.gif
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./1;1;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.10;0.82/.55;.015/
 CONTUR   = 0
 SKIP     = 0
 FINT     = -3;-2;-1;1;2;3 
 FLINE    = 2;17;5;0;22;25;29 
 CTYPE    = f 
 LUTFIL   =
 STNPLT   =
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.0/11/1/SW
 CLEAR    = n
r

 GFUN     = sub(relh+2,relh)
 GVCORD   = pdly 
 GLEV     = 30:0 
 CINT     = 10
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX    BNDY LAYER  RH DIFF
 PANEL    = b
 FINT     = -30;-20;-10;10;20;30
r

 GFUN     = sub(hght+2,hght)
 GLEVEL   = 850
 GVCORD   = pres
 CINT     = 10
 CLEAR    = y
 PANEL    = t 
 TEXT     = 1.1/11/2/SW
 DEVICE   = GF|comparediff_${cyc}f1.gif
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   850 HEIGHT DIFF
 SCALE    = 0
 FINT     = -15;-10;-5;5;10;15
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.0/11/1/SW
 CLEAR    = n
r

# GFUN     = knts(sub(sped+2,sped))
 GFUNC    = sub(tmpc+2,tmpc)
 CINT     = 1 
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   850 TEMP DIFF 
 FINT     = -4;-3;-2;-1;1;2;3;4
 FLINE    = 15;2;17;5;0;22;25;28;30
r

 GFUN     = sub(hght+2,hght)
 GLEVEL   = 500
 GVCORD   = pres
 CINT     = 10
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 DEVICE   = GF|comparediff_${cyc}f2.gif
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   500 HEIGHT DIFF 
 SCALE    = 0
 FINT     = -50;-30;-10;10;30;50 
 FLINE    = 2;17;5;0;22;25;29
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.0/11/1/SW
 CLEAR    = n
r

 GFUN     = knts(sub(sped+2,sped)) 
 CINT     = 5
 CLEAR    = n
 PANEL    = b
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   500 WIND DIFF
 FINT     = -15;-10;-5;5;10;15
r

 GFUN     = knts(sub(sped+2,sped)) 
 GLEVEL   = 250
 PANEL    = t
 CLEAR    = y
 DEVICE   = GF|comparediff_${cyc}f3.gif
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   250 WIND DIFF        
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.0/11/1/SW
 CLEAR    = n
r

 GLEVEL   = 350
 PANEL    = b
 CLEAR    = n
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX  350 WIND DIFF
r

 GFUN     = sub(tmpf+2,tmpf)
 GLEVEL   = 2
 GVCORD   = hght
 CINT     = 2 
 PAN      = t
 CLEAR    = y
 DEVICE   = GF|comparediff_${cyc}f4.gif
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   2 M TEMP DIFF          
 FINT     = -10;-8;-6;-4;-2;2;4;6;8;10
 FLINE    = 15;2;17;5;20;0;21;23;26;25;29
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.0/11/1/SW
r

 GFUN     = sub(dwpf+2,dwpf)
 PAN      = b
 TEXT     = 1.1/11/2/SW
 FINT     = -15;-12;-10;-8;-6;-4;-2;2;4;6;8;10;12;15
 FLINE    = 15;2;16;17;10;5;20;0;21;22;23;26;25;28;30
 TITLE    = 1/1/ 00-HR    RUC2 - RUCX   2 M DEW PT DIFF          
r

 GFUN     = knts(sub(sped+2,sped)) 
 GLEVEL   = 10 
 CINT     = 5 
 GAREA    = 23.;-94.;49.;-60.
 CLEAR    = y
 PANEL    = t
 DEVICE   = GF|comparediff_${cyc}f5.gif
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR    RUC2 - RUCX   10 M WIND DIFF
 FINT     = -15;-10;-5;5;10;15
 FLINE    = 2;17;5;0;22;25;29
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.0/11/1/SW
r

 GAREA    = 23.;-130.;49;-92. 
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR     RUC2 - RUCX   10 M WIND DIFF
 PANEL    = b
r

 GFUN     = sub(cape+2,cape)
 GLEVEL   = 0 
 GVCORD   = none
 CINT     = 500 
 GAREA    = 20.;-115.;52.;-65.
 CLEAR    = y
 PANEL    = t
 DEVICE   = GF|comparediff_${cyc}f6.gif
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR    RUC2 - RUCX   CAPE DIFF
 FINT     = -2000;-1500;-1000;-500;500;1000;1500;2000
 FLINE    = 2;17;10;5;0;21;23;25;29
r
          
 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.0/11/1/SW
r
          
 TEXT     = 1.1/11/2/SW
 CINT     = 100 
 GFUN     = sub(cins+2,cins)
 TITLE    = 1/1/ 00-HR     RUC2 - RUCX   CIN DIFF
 FINT     = -300;-200;-100;100;200;300
 FLINE    = 2;17;5;0;22;25;29 
 PANEL    = b
r

 GFUN     = mul(quo(sub(vsby+2,vsby),1000),0.62137)
 GLEVEL   = 0 
 GVCORD   = none 
 CINT     = 1
 PAN      = t
 GAREA    = grid
 CLEAR    = y
 DEVICE   = GF|comparediff_${cyc}f7.gif
 TEXT     = 1.1/11/2/SW
 TITLE    = 1/1/ 00-HR   RUC2 - RUCX   VISIBILITY DIFF
 FINT     = -8;-6;-4;-2;2;4;6;8
 FLINE    = 15;2;17;5;0;21;23;25;29
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 CLEAR    = n
 TEXT     = 1.0/11/1/SW
r
                                                                        
 TEXT     = 1.1/11/2/SW
 GLEVEL   = 925
 GVCORD   = pres
 CINT     = 10 
 GFUN     = sub(relh+2,relh)
 TITLE    = 1/1/ 00-HR     RUC2 - RUCX   925 mb RELH DIFF
 FINT     = -30;-20;-10;10;20;30
 FLINE    = 2;17;5;0;22;25;29
 PANEL    = b
r

ex
EOF

gpend

mv *gif ../../ftphold/.
/nwprod/util/ush/stopxvfb.sh /bin/sh
echo abouttoexitdiffs
exit
