#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500z
rm /stmpp1/Geoffrey.Manikin/meg/500z/*
cd /stmpp1/Geoffrey.Manikin/meg/500z
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017020700
ymd=20170207
dayoweek=hold8

times="00 06 12 18 24 30 36 42 48 54 60"
times="36"
for fhr in $times; do

fmdl1=/com2/nawips/prod/gfs.${ymd}/gfs40_${ymdh}f0${fhr}
fmdl1=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f0${fhr}
fmdl1=/ptmpp1/Geoffrey.Manikin/hold/gfs_0p25_${ymdh}f0${fhr}
echo $fmdl1

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = avor
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFSX 500 mb  Z/AVOR
 DEVICE   = GIF|gfsx500_${ymdh}f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 22.;-124.;58.;-54. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 1/V/UL/.04;0.22/.4;.02/2
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/3
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
