#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/1pcp
rm /stmpp1/Geoffrey.Manikin/meg/1pcp/*
cd /stmpp1/Geoffrey.Manikin/meg/1pcp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd1=`cut -c 7-14 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh1=2017062506
ymd1=`echo $ymdh1 | cut -c1-8`
cyc1=`echo $ymdh1 | cut -c9-10`
dayoweek=hold7

hours="117 123 129"
for fhr1 in $hours; do

fhr2=`expr $fhr1 + 3`

typeset -Z3 fhr1 fhr2
fmdl1=/com2/nawips/prod/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr1}
fmdl1=/meso/noscrub/Geoffrey.Manikin/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr1}
fmdl2=/meso/noscrub/Geoffrey.Manikin/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr2}
cp /meso/noscrub/Geoffrey.Manikin/gfs.${ymd1}/gfs_0p25_${ymdh1}f${fhr2} fmdl2

    gdplot2 << EOF
 GDFILE   = $fmdl1 
 GDATTIM  = last 
 GLEVEL   = 0 
 GVCORD   = none
 GDPFUN   = p03i
 CINT     = 4 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 3-HR TOT PCP 
 DEVICE   = GIF|gfs1pcp_${ymdh1}f${fhr1}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-95;25;/1;1;1;1
 GAREA    = 24.;-84.;50.;-52. 
 GAREA    = il
 GAREA    = 38.5;-96.;46.;-85.
 GAREA    = 37.;-100;44.4;-90
# GAREA    = 39.;-95.;47.;-85.
 CLEAR    = y
 PANEL    = t 
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = .01;.1;.25;.5;.75;1.;1.5;2.;2.5;3.;3.5;4.
 FLINE    = 0;21;22;23;25;27;28;30;2;15;10;5;0
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = c03i 
 TITLE    = 1/-1/~   GFS 3-HR CNVCT PCP 
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 1/H/UL/.1;0.95/0.8;.03/1
r

 GDFILE   = $fmdl1 + fmdl2
 GDATTIM  = f${fhr2}
 GDPFUN   = sub(p06i+2,p03i^${ymd1}/${cyc1}f${fhr1}) 
 DEVICE   = GIF|gfs1pcp_${ymdh1}f${fhr2}.gif|750;900
 CLEAR    = y
 TITLE    = 1/-1/~   GFS 3-HR TOTAL PCP
 PANEL    = t
 CLRBAR   = 0
r

 GDPFUN   = sub(c06i+2,c03i^${ymd1}/${cyc1}f${fhr1}) 
 TITLE    = 1/-1/~   GFS 3-HR CNVCT PCP 
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 1/H/UL/.1;0.95/0.8;.03/1
r

ex
EOF

done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
