#!/bin/ksh
echo 'into'

mkdir /lfs/h2/emc/stmp/geoffrey.manikin
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h2/emc/stmp/geoffrey.manikin/meg/refc/
rm /lfs/h2/emc/stmp/geoffrey.manikin/meg/refc/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/meg/refc
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

ymdh=2022072812
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

hours="00 01 02 03 04 05 06 07 08 09 10 11 12"
hours="00 01 02 03 04 05 06"
hours="168 171 174 177 180"
hours="177"
for fhr in $hours; do

typeset -Z3 fhr fhr3
fhr3=`expr $fhr - 3`
DAPATH=/lfs/h1/ops/prod/com/gfs/v16.2/gfs.${ymd}/${cyc}/atmos/gempak
cp ${DAPATH}/gfs_0p25_${ymdh}f${fhr} fmdl1
cp ${DAPATH}/gfs_0p25_${ymdh}f${fhr3} fmdl2

    gdplot2 << EOF
 GDFILE   = fmdl12 + fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = sub(p${fhr}i^${ymd}/${cyc}f${fhr}+2,p${fhr}i^${ymd}/${cyc}f${fhr3}} 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|gfspcp2mt_${ymdh}f${fhr}.gif | 800;850
 PROJ     = lcc/25.;-98.;25./2;2;1;1
 GAREA    = ia 
 TITLE    = 1//~  GFS  3-HR PCP 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.05;0.94/0.8;.03/1
 TEXT     = 1.1/11/2
 FINT     = .01;.05;.1;.2;.3;.4;.5;.75;1;1.5;2;2.5;3
 FLINE    = 0;21;22;23;4;25;27;28;29;30;2;15;12;17;10;5
 TYPE     = f 
r

 GLEVEL   = 2
 GVCORD   = hght
 GDPFUN   = sub(tmpf^${ymd}/${cyc}f${fhr}+2,tmpf^${ymd}/${cyc}f${fhr3}}
 CLEAR    = n
 PANEL    = b
 FINT     = -20;-15;-10;-5;5;10;15;20 
 FLINE    = 2;17;10;5;0;21;23;4;2
r

ex
EOF
done
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
exit
