#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmp/wx20mg/meg
mkdir /stmp/wx20mg/meg/2dew
rm /stmp/wx20mg/meg/2dew/*
cd /stmp/wx20mg/meg/2dew
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2012112812
dayoweek=Wed

ymd=`echo $ymdh | cut -c1-8`
times="00 03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84"
times="00 03 06 09 12 15 18"
for fhr in $times; do

#fmdl1=/com/nawips/prod/nam.${ymd}/nam32_${ymdh}f0${fhr}
fmdl1=/ptmp/wx20mg/hold/nam32_${ymdh}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 925 
 GVCORD   = pres 
 GDPFUN   = knts(sped) 
 CINT     = 0 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM 10 WIND SPEED 
 DEVICE   = GIF|${cyc}nam925wz${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-145;25;/1;1;1;1
# GAREA    = 39.;-78.;43.;-70. 
 GAREA    = 56.;-154.;64.;-138. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CONTUR   = 0
 SKIP     = 0
 CLRBAR   = 1/H/UL/.08;0.96/0.6;.03/2
 FINT     = 5;10;15;20;25;30;35;40;45;50;55
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 CINT     = 
 WIND     = AK1/0.5/1/122
 GDPFUN   = kntv(wnd)
 SKIP     = /10;10
 TYPE     = a
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

gpend
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
#cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput ${cyc}*gif
bye
EOF

ftp -n -v << EOF > /meso/save/wx20mg/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
