#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymd=20120320
cyc=21

mkdir /stmpp1/wx20mg/gempak.rap13/700
cd /stmpp1/wx20mg/gempak.rap13/700
cp /meso/save/wx20mg/casework/coltbl.xwp .

times="00"

for fhr in $times; do

fmdl1=/stmpp1/wx20mg/rappost/rap_${ymd}${cyc}f0${fhr}
fmdl2=/stmpp1/wx20mg/rappost/raptest_${ymd}${cyc}f0${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl1
 GDATTIM  = f$fhr
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = avor(wnd) 
 CINT     = 2/10/46 
 LINE     = 0 
 MAP      = 1
 WIND     = 0 
 TITLE    = 0 
 DEVICE   = GIF|compare500_${ymd}${cyc}f${fhr}.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = grid
 CLEAR    = y
 PANEL    = 0.;.51;1.;1.
 TEXT     = 1.0/1/1
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/3
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.4/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r


 TITLE    = 1/1/ ${fhr}-HR RAP POST-DFI FCST 500 HT/VORT
 LINE     = 0
 TEXT     = 1.2/11/2
r

 TITLE    = 7/-1/ FCST MADE ${cyc}Z  ${month}/$day
 TEXT     = 1.1/11/1/SW
r

 TITLE    = 1/1/ ${fhr}-HR RAP PRE-DFI  FCST 500 HT/VORT
 TEXT     = 1.2/11/2
 PANEL    = 0;0;1;.49
 GAREA    = 16.;-126.;55.;-57.
 CINT     = -2000/-2000/-2000
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = avor(wnd)
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 TITLE    = 0
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 TEXT     = 1.0/1/1
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-46;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/3
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 FINT     = 0
 FLINE    = 0
 TEXT     = 1.4/11/2
 TYPE     = c
r

exit
EOF

    gdcntr << EOF

 GDFILE   = ${fmdl1}+${fmdl2}
 GDATTIM  = f00
 GLEVEL   = 500 
 GVCORD   = pres 
 GFUNC    = sub(hght+2),hght)
 CINT     = 1
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/1/ 00-HR   PREDFI - POSTDFI   500z DIFF
 DEVICE   = GIF|compare500diff_${ymd}${cyc}f00.gif|900;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./1;1;1;1
 GAREA    = 16.;-126.;55.;-57.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0
 HLSYM    = 0
 CLRBAR   = 1/V/UL/.10;0.82/.55;.015/
 CONTUR   = 0
 SKIP     = 0
 FINT     = -50;-30;-10;10;30;50
 FLINE    = 2;17;5;0;22;25;29
 CTYPE    = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm
export w3=emcmmb
export w4=$web

ftp -n -v << EOF > /meso/save/wx20mg/gempak.rap13/rzftp.out
open rzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/rap/snd
prompt
mput *.gif
bye
EOF

exit
