#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/tmpf
rm /stmpp1/Geoffrey.Manikin/meg/tmpf/*
cd /stmpp1/Geoffrey.Manikin/meg/tmpf
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2015081512
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

hours="00 03 06 09"
for fhr in $hours; do

fmdl1=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl2=/com/nawips/prod/gfs.${ymd}/gfs_0p50_${ymdh}f0${fhr}
fmdl3=/com/nawips/prod/rap.${ymd}/rap13_${ymdh}f0${fhr}
fmdl4=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl5=/com2/nawips/prod/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl6=/meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam20_${ymdh}f0${fhr}
fmdl7=/meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${ymd}/nam_conusnest_${ymdh}f0${fhr}
fmdl8=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/gfs.${ymd}/gfs_${ymdh}f0${fhr}
fmdl9=/ptmpd2/Geoffrey.Manikin/com2/nawips/para/hrrr.${ymd}/hrrr_${ymdh}f0${fhr}00
fmdl10=/com/nawips/prod/hiresw.${ymd}/hiresw_conusarw_${ymdh}f0${fhr}
fmdl11=/com/nawips/prod/hiresw.${ymd}/hiresw_conusnmmb_${ymdh}f0${fhr}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 2 
 GVCORD   = hght 
 GDPFUN   = tmpf 
 CINT     = 5 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM  2M TEMP 
 DEVICE   = GIF|${ymdh}tmpfnamgfs${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-99;25;/1;1;1;1
 GAREA    = 38.;-107.;50.;-89. 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 15;20;25;30;35;40;45;50;55;60;65;70;75;80;85;90;95;100;105;110
 FLINE    = 0;12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   GFS  2M TEMP
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfnamrap${fhr}.gif|750;900
r

 GDFILE   = $fmdl3
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   RAP  2M TEMP
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfnamnest${fhr}.gif|750;900
r

 GDFILE   = $fmdl4
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAM4  2M TEMP
r

 GDFILE   = $fmdl3
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   RAP  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfraphrrr${fhr}.gif|750;900
r

 GDFILE   = $fmdl5
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   HRRR  2M TEMP
r

 GDFILE   = $fmdl1
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfnamx${fhr}.gif|750;900
r

 GDFILE   = $fmdl6
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAMX  2M TEMP
r

 GDFILE   = $fmdl4
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   NAM4  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfnam4x${fhr}.gif|750;900
r

 GDFILE   = $fmdl7
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NAM4X  2M TEMP
r

 GDFILE   = $fmdl2
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   GFS  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfgfsx${fhr}.gif|750;900
r

 GDFILE   = $fmdl8
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   GFSX  2M TEMP
r

 GDFILE   = $fmdl5
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   HRRR  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfhrrrx${fhr}.gif|750;900
r

 GDFILE   = $fmdl9
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   HRRRX  2M TEMP
r

 GDFILE   = $fmdl10
 CLEAR    = y
 PANEL    = t
 TITLE    = 1/-1/~   ARW  2M TEMP
 CLRBAR   = 1/V/UL/.03;0.5/1.0;.03/2
 DEVICE   = GIF|${ymdh}tmpfhiresw${fhr}.gif|750;900
r

 GDFILE   = $fmdl11
 CLEAR    = n
 PANEL    = b
 CLRBAR   = 0
 TITLE    = 1/-1/~   NMMB  2M TEMP
r

ex
EOF
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
