#!/bin/ksh
#
#PBS -N gfs_nagrib1
#PBS -o /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/gfs_nagrib.out1
#PBS -e /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/gfs_nagrib.err1
#PBS -l select=1:ncpus=10:mpiprocs=1:mem=50GB
#PBS -q dev
#PBS -l walltime=00:30
#PBS -A VERF-DEV

set -x

ymd=20220925
version=v16.2

DAPATH=/lfs/h1/ops/prod/com/gfs/${version}/gfs.${ymd}
#DAPATH=/lfs/h2/emc/ptmp/geoffrey.manikin/gfs/gfs.${ymd}
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib1
rm /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib1/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib1/

export DAPATH 

cycles="00 06 12 18"
cycles="00 12"
cycles="12"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132"
#fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192"
#fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="30 36 42 48 54 60 66 72 78 84 90 96"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240"
#fhrs="06 12 18 24 30 36 42 48"
fhrs="78 84 90 96 102 108 114 120"

for cyc in $cycles
do
for fhr in $fhrs
do

typeset -Z3 fhr
cp ${DAPATH}/${cyc}/atmos/gfs.t${cyc}z.pgrb2.0p25.f${fhr} . 

nagrib2 << EOF
GBFILE  = gfs.t${cyc}z.pgrb2.0p25.f${fhr} 
INDXFL  =
GDOUTF  = dummygfs${cyc}.grd 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = 18.;-100.;48.;-60. 
MAXGRD  = 12000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF
done

  gddelt << EOF
GDFILE  = dummygfs${cyc}.grd
GVCORD  = pres
GLEV    = all
GFUN    = all
GDATTIM = all
r

GVCORD  = hght
r

GVCORD  = hybl
r

GVCORD  = sgma
r

GVCORD  = trop
r

GVCORD  = dpth
r

GVCORD  = PBLY
r

GVCORD  = POTV
r

GVCORD  = FRZL
r

GVCORD  = HTFL
r

GVCORD  = MCTL
r

GVCORD  = LCTL
r

GVCORD  = HCTL
r

GVCORD  = MCBL
r

GVCORD  = MCLY
r

GVCORD  = PDLY
r

GVCORD  = ATMO
r

GVCORD   = MWSL
r

GVCORD   = TOPA
r

GVCORD   = CEIL
r

GVCORD   = none
GFUN     = p${fhr}m
r

exit
EOF

done
mv dummygfs${cyc}.grd /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/gfspcp_${ymd}${cyc}
gpend
exit
