#!/bin/ksh

set -x
mkdir /stmpp1/Geoffrey.Manikin/nagrib3
rm /stmpp1/Geoffrey.Manikin/nagrib3/*
cd /stmpp1/Geoffrey.Manikin/nagrib3

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
ymd=20160122

DAPATH=/com/gfs/prod/gfs.${ymd}

export DAPATH DAPATH2
. /nwprod/gempak/.gempak

cycles="00 06 12 18"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72"
ffhrs="60 66 72 78 84 90 96 102"
fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162"
for cyc in $cycles
do
for fhr in $fhrs
do

typeset -Z3 fhr
cp ${DAPATH}/gfs.t${cyc}z.pgrb2.0p50.f${fhr} .
/nwprod/util/exec/cnvgrib -g21 gfs.t${cyc}z.pgrb2.0p50.f${fhr} gfs.t${cyc}z.pgrb.0p50.f${fhr}.grib1
wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr}.grib1 | grep kpds5=61 | wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr}.grib1 -i -grib -o mdl1

nagrib << EOF
GBFILE  = mdl1 
INDXFL  =
GDOUTF  = dummygfs.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

done
mv dummygfs.grd gfspcp_${ymd}${cyc}
mv gfspcp_${ymd}${cyc} /meso/save/Geoffrey.Manikin/meg/.
done
gpend
exit
