#!/bin/ksh

set -x

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/nagrib2
rm /stmpp1/Geoffrey.Manikin/nagrib2/*
cd /stmpp1/Geoffrey.Manikin/nagrib2
cp /meso/save/Geoffrey.Manikin/gempak/nagrib2/*tbl .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2015100818
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

DAPATH=/ptmpd2/Geoffrey.Manikin/hold
DAPATH=/com/nam/prod/nam.${ymd}
export DAPATH
. /nwprod/gempak/.gempak

fhrs="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15"
fhrs="00 01 02 03 06 09"
fhrs="26"
for fhr in $fhrs
do

   nagrib2 << EOF
GBFILE  = ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2 
INDXFL  =
GDOUTF  = nam_conusnest_${ymdh}f0${fhr}
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF
done

mv nam* /ptmpd2/Geoffrey.Manikin/com2/nawips/prod/nam.${ymd}/
exit
