#!/bin/ksh

set -x

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/nagribnssl
rm /stmpp1/Geoffrey.Manikin/nagribnssl/*
cd /stmpp1/Geoffrey.Manikin/nagribnssl
cp /meso/save/Geoffrey.Manikin/gempak/nagrib/*129*l .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

#ymdh=2014082500
#ymd=20140825

DAPATH=/dcom/us007003/${ymd}/wgrbbul/nssl_wrf
#DAPATH=/ptmp/Geoffrey.Manikin/hold3/

export DAPATH
. /nwprod/gempak/.gempak

fhrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
for fhr in $fhrs
do

fhrr=$fhr
fhr1=`expr $fhr - 1`
if [ $fhr -lt 10 ]; then
 typeset -Z1 fhrr
else
 typeset -Z2 fhrr
fi 
echo $fhr $fhrr
wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr} | grep kpds5=61:kpds6=1:kpds7=0:TR=4:P1=${fhr1}:P2=${fhrr} | wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr} -i -grib -o new${fhr}.fil
cat new${fhr}.fil new.fil > pcp.grd
mv pcp.grd new.fil
done

   nagrib << EOF
GBFILE  = new.fil 
INDXFL  =
GDOUTF  = dummyhires1.grd 
PROJ    =
GRDAREA =
KXKY    = 
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

fhrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36"
for fhr in $fhrs
do

wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr} | grep kpds5=211:kpds6=105 | wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr}  -i -grib -o new2${fhr}.fil
wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr} | grep kpds5=212:kpds6=200 | wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr}  -i -grib -o new3${fhr}.fil
wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr} | grep kpds5=227:kpds6=106 | wgrib ${DAPATH}/wrf4nssl_${ymdh}.f${fhr}  -i -grib -o new4${fhr}.fil
cat new2${fhr}.fil new3${fhr}.fil new4${fhr}.fil new2.fil > ref.grd
mv ref.grd new2.fil
done

   nagrib << EOF
GBFILE  = new2.fil
INDXFL  =
GDOUTF  = dummyhires2.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

#rm new*.fil

mv dummyhires1.grd nsslwrfpcp_${ymdh}
mv dummyhires2.grd nsslwrf_${ymdh}
mv nsslw* /meso/save/Geoffrey.Manikin/meg/.
exit
