#!/bin/ksh --login
#
#BSUB -oo /meso/save/Geoffrey.Manikin/meg/gemmedr.out
#BSUB -eo /meso/save/Geoffrey.Manikin/meg/gemmedr.out
#BSUB -J megmedr
#BSUB -n 9 
#BSUB -R span[ptile=4]
#BSUB -W 00:30
#BSUB -P GFS-T2O
#BSUB -R "affinity[core(4):distribute=balance]"
#BSUB -q "dev"
#BSUB -x
#BSUB -a poe
#

set -x

export HOLDIN=/stmpp1/Geoffrey.Manikin
export GBexec=/nwprod/util/exec

echo intoscript
rm -rf /stmpp1/Geoffrey.Manikin/meg/*
mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/holdmedr
cyc=`cut -c 15-16 /meso/save/Geoffrey.Manikin/meg/NMCDATEMR`
ymd=`cut -c 7-14 /meso/save/Geoffrey.Manikin/meg/NMCDATEMR`
export cyc

ymdhm1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${ymd}${cyc} -1 -1`"
ymdm1=`echo $validtime | cut -c1-8`

set +x
set -x

cd $HOLDIN/meg

set -x

rm poescript

echo "/meso/save/Geoffrey.Manikin/meg/launchmedr1 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr2 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr3 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr4 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr5 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr6 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr7 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr8 ${cyc}" >> poescript
echo "/meso/save/Geoffrey.Manikin/meg/launchmedr9 ${cyc}" >> poescript

chmod 775 poescript
export MP_PGMMODEL=mpmd
export MP_CMDFILE=poescript
#
# Execute the script.

echo beforelsf
mpirun.lsf
echo pastlsf
bsub < /meso/save/Geoffrey.Manikin/meg/run_ftp_medr
exit
