#!/bin/ksh
#
#PBS -N nam_nagrib1
#PBS -o /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/nam_nagrib.out1
#PBS -e /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/nam_nagrib.err1
#PBS -l select=1:ncpus=10:mpiprocs=1:mem=50GB
#PBS -q dev
#PBS -l walltime=00:30
#PBS -A VERF-DEV

set -x

ymd=20220926
version=v4.2

DAPATH=/lfs/h1/ops/prod/com/nam/${version}/nam.${ymd}
DAPATH=/lfs/h2/emc/ptmp/geoffrey.manikin/nam
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/namnagrib1
rm /lfs/h2/emc/stmp/geoffrey.manikin/namnagrib1/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/namnagrib1/

export DAPATH 

cycles="12"
fhrs="12 24 36 48 60 72 84"

for cyc in $cycles
do
for fhr in $fhrs
do

cp ${DAPATH}/nam.t${cyc}z.awip32${fhr}.tm00.grib2 . 

   nagrib2 << EOF
GBFILE  = nam.t${cyc}z.awip32${fhr}.tm00.grib2 
INDXFL  =
GDOUTF  = dummynampcp${cyc}.grd 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 8000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF
done 

  gddelt << EOF
GDFILE  = dummynampcp${cyc}.grd
GVCORD  = pres
GLEV    = all
GFUN    = all
GDATTIM = all
r

GVCORD  = hght
r

GVCORD  = hybl
r

GVCORD  = sgma
r

GVCORD  = trop
r

GVCORD  = dpth
r

GVCORD  = PBLY
r

GVCORD  = POTV
r

GVCORD  = FRZL
r

GVCORD  = HTFL
r

GVCORD  = MCTL
r

GVCORD  = LCTL
r

GVCORD  = HCTL
r

GVCORD  = MCBL
r

GVCORD  = MCLY
r

GVCORD  = PDLY
r

GVCORD  = ATMO
r

GVCORD   = MWSL
r

GVCORD   = TOPA
r

GVCORD   = CEIL
r

GVCORD   = LCLV
r

GVCORD   = CLDT
r

GVCORD   = CLDL
r

GVCORD   = CCBL
r

exit
EOF

mv dummynampcp${cyc}.grd /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/nampcp_${ymd}${cyc}
done

cycles="06 18"
cycles=""
hours1="03 06 09 12 15 18 21 24 27 30 33 36 39 42"

for cyc in $cycles
do
for fhr in $hours1
do

cp ${DAPATH}/nam.t${cyc}z.awip32${fhr}.tm00.grib2 .

   nagrib2 << EOF
 GBFILE  = nam.t${cyc}z.awip32${fhr}.tm00.grib2
 INDXFL  =
 GDOUTF  = dummynampcp${cyc}.grd
 PROJ    =
 GRDAREA =
 KXKY    =
 GAREA   = grid
 MAXGRD  = 15000
 CPYFIL  = gds
 OUTPUT  = T
 GBTBLS  =
 GBDIAG  =
r

ex
EOF
done

     gddelt << EOF
 GDFILE  = dummynampcp${cyc}.grd
 GVCORD  = pres
 GLEV    = all
 GFUN    = all
 GDATTIM = all
r

 GVCORD  = hght
r

 GVCORD  = hybl
r

 GVCORD  = sgma
r

 GVCORD  = trop
r

 GVCORD  = dpth
r

 GVCORD  = PBLY
r

 GVCORD  = POTV
r

 GVCORD  = FRZL
r

 GVCORD  = HTFL
r

 GVCORD  = MCTL
r

 GVCORD  = LCTL
r

 GVCORD  = HCTL
r

 GVCORD  = MCBL
r

 GVCORD  = MCLY
r

 GVCORD  = PDLY
r

 GVCORD   = MWSL
r

 GVCORD   = TOPA
r

 GVCORD   = CEIL
r

 GVCORD   = LCLV
r

 GVCORD   = CLDT
r

 GVCORD   = CLDL
r

 GVCORD   = CCBL
r

exit
EOF

hours2="45 48 51 54 57 60 63 66 69 72 75 78 81 84"
hours=""
for fhr in $hours2
do

cp ${DAPATH}/nam.t${cyc}z.awip32${fhr}.tm00.grib2 .

   nagrib2 << EOF
 GBFILE  = nam.t${cyc}z.awip32${fhr}.tm00.grib2
 INDXFL  =
 GDOUTF  = dummynampcp${cyc}.grd
 PROJ    =
 GRDAREA =
 KXKY    =
 GAREA   = grid
 MAXGRD  = 15000
 CPYFIL  = gds
 OUTPUT  = T
 GBTBLS  =
 GBDIAG  =
r

ex
EOF
done

   gddelt << EOF
 GDFILE  = dummynampcp${cyc}.grd
 GVCORD  = pres
 GLEV    = all
 GFUN    = all
 GDATTIM = all
r

 GVCORD  = hght
r

 GVCORD  = hybl
r

 GVCORD  = sgma
r

 GVCORD  = trop
r

 GVCORD  = dpth
r

 GVCORD  = PBLY
r

 GVCORD  = FRZL
r

 GVCORD  = HTFL
r

 GVCORD  = MCTL
r

 GVCORD  = LCTL
r

 GVCORD  = HCTL
r

 GVCORD  = MCBL
r

 GVCORD  = MCLY
r

 GVCORD  = PDLY
r

 GVCORD   = MWSL
r

 GVCORD   = TOPA
r

 GVCORD   = CEIL
r

 GVCORD   = LCLV
r

 GVCORD   = CLDT
r

 GVCORD   = CLDL
r

 GVCORD   = CCBL
r

ex
EOF

mv dummynampcp${cyc}.grd /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/nampcp_${ymd}${cyc}
done
gpend
exit

