#!/bin/ksh

set -x

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/testpcp
rm /lfs/h2/emc/stmp/geoffrey.manikin/testpcp/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/testpcp/

ymdh=2022092800
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
version=v8.1

#DAPATH=/com2/hiresw/prod/hiresw.${ymd}
DAPATH=/lfs/h1/ops/prod/com/hiresw/${version}/hiresw.${ymd}
DAPATH=/lfs/h2/emc/stmp/geoffrey.manikin/hold
OUT=/lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/ian/
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48"
for fhr in $fhrs
do

typeset -Z2 fhra fhr3
fhr3=`expr $fhr - 3`
if [ $fhr3 -lt 10 -a $fhr3 -gt 0 ]; then
typeset -Z1 fhr3
fi

fhra=$fhr
if [ $fhr -lt 10 ]; then
typeset -Z1 fhra
fi

if [ $fhr -eq 03 ]; then
fhr3=0
typeset -Z1 fhr3
fi

if [ $fhr -eq 3 ];then
 echo "APCP:surface:0-3 hour acc fcst" >> pcp.fil
else
 echo "APCP:surface:${fhr3}-${fhra} hour acc fcst" >> pcp.fil
fi

wgrib2 ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2 | grep -F -f pcp.fil | wgrib2 -i -grib new.fil ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2

   nagrib2 << EOF
GBFILE  = new.fil 
INDXFL  =
GDOUTF  = dummynest.grd 
PROJ    =
GRDAREA =
KXKY    = 
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

ex
EOF
rm new.fil pcp.fil
done
mv dummynest.grd $OUT/namnestpcp_${ymdh}
exit
