#!/bin/ksh
#
#PBS -N nest_nagrib4
#PBS -o /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/nest_nagrib.out4
#PBS -e /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/nest_nagrib.err4
#PBS -l select=1:ncpus=10:mpiprocs=1:mem=50GB
#PBS -q dev
#PBS -l walltime=00:30
#PBS -A VERF-DEV

set -x

ymd=20230412
version=v4.2

DAPATH=/lfs/h1/ops/prod/com/nam/${version}/nam.${ymd}
#DAPATH=/lfs/h2/emc/stmp/geoffrey.manikin/hold
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/nestnagrib2
#rm /lfs/h2/emc/stmp/geoffrey.manikin/nestnagrib2/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/nestnagrib2/

export DAPATH 

cycles="18"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132"
#fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192"
fhrs="18 21 24 27 30 33 36 39 42 45 48"
#fhrs="30 36 42 48 54 60 66 72 78 84 90 96"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
#fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
fhrs="03 06 09 12 15 18"

for cyc in $cycles
do
for fhr in $fhrs
do

cp ${DAPATH}/nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2 . 

   nagrib2 << EOF
GBFILE  = nam.t${cyc}z.conusnest.hiresf${fhr}.tm00.grib2 
INDXFL  =
GDOUTF  = dummynest${cyc}.grd 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 18000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

  gddelt << EOF
GDFILE = dummynest${cyc}.grd
GVCORD = pres
GLEV   = all
GFUN   = all
r

GVCORD  = hght
r

GVCORD  = hybl
r

GVCORD  = sgma
r

GVCORD  = trop
r

GVCORD  = dpth
r

GVCORD  = PBLY
r

GVCORD  = POTV
r

GVCORD  = FRZL
r

GVCORD  = HTFL
r

GVCORD  = MCTL
r

GVCORD  = LCTL
r

GVCORD  = HCTL
r

GVCORD  = MCBL
r

GVCORD  = MCLY
r

GVCORD  = HCLY
r

GVCORD  = LCLY
r

GVCORD  = PDLY
r

GVCORD  = ATMO
r

GVCORD  = MWSL
r

GVCORD  = TOPA
r

GVCORD  = RPBL 
r

GVCORD  = LCLV
r

GVCORD  = CLDT
r

GVCORD  = CLDL
r

GVCORD  = CCBL
r

GVCORD  = CEIL
r


exit
EOF
done

mv dummynest${cyc}.grd /lfs/h2/emc/vpppg/noscrub/geoffrey.manikin/fll/namnestpcp_${ymd}${cyc}
done
gpend
exit
