#!/bin/ksh

set -x

cyc=$1

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymdh=2016012100
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

DAPATH=/ptmpp2/Geoffrey.Manikin/hold
#DAPATH=/com/nam/prod/nam.${ymd}
COMOUT=/ptmpd2/Geoffrey.Manikin/com2/nawips/prod/gfs.${ymd}
export DAPATH COMOUT
. /nwprod/gempak/.gempak

mkdir $COMOUT
mkdir /ptmpp2/Geoffrey.Manikin/nagrib2
rm /ptmpp2/Geoffrey.Manikin/nagrib2/*
cd /ptmpp2/Geoffrey.Manikin/nagrib2
cp /meso/save/Geoffrey.Manikin/gempak/nagrib2/*tbl .

fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72"
fhrs=""

for fhr in $fhrs
do

typeset -Z3 fhr

nagrib2 << EOF
GBFILE  = ${DAPATH}/gfs.t${cyc}z.pgrb2.0p25.f${fhr}
INDXFL  =
GDOUTF  = dummy.grd 
PROJ    =
GRDAREA =
KXKY    = 
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

   gddelt << EOF
 GDFILE   = dummy.grd 
 GDATTIM  = f${fhr}
 GLEVEL   = all 
 GVCORD   = pdly 
 GFUNC    = all
r

# GVCORD   = pres 
#r

# GVCORD   = hght
#r

 GVCORD   = dpth
r

 GVCORD   = mwsl
r

 GVCORD   = trop
r

 GVCORD   = sgma
r
 
 GVCORD   = frzl
r

 GVCORD   = topa
r

 GVCORD   = dtcl
r
 
 GVCORD   = dbcl
r

 GVCORD   = stcl
r
 
 GVCORD   = sbcl
r

 GFUNC    = hght
 GVCORD   = all
r

 GFUNC    = p03m
r

 GFUNC    = c03m
r

ex
EOF

mv dummy.grd gfs_0p25_${ymdh}f0${fhr}
done
mv gfs* ${COMOUT}/. 

#fhrs="12 24 36 48 60 72 84"
fhrs="03 06 09 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72"

for fhr in $fhrs
do

typeset -Z3 fhr
/nwprod/util/exec/cnvgrib -g21 ${DAPATH}/gfs.t${cyc}z.pgrb2.0p25.f${fhr} gfs.t${cyc}z.pgrb.0p25.f${fhr}
wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=61:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new1.fil
wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=63:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new2.fil

nagrib << EOF
GBFILE  = new1.fil 
INDXFL  =
GDOUTF  = dummygfs.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new2.fil
r

exit
EOF
done
mv dummygfs.grd ${COMOUT}/gfspcp_${ymd}${cyc}
exit
