#! /bin/ksh
#
#BSUB -J wafs.ftp
#BSUB -oo /meso/save/Geoffrey.Manikin/meg/shortftp.out
#BSUB -eo /meso/save/Geoffrey.Manikin/meg/shortftp.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -P NAM-T2O
#BSUB -R "affinity[core]"
#BSUB -q transfer
#BSUB -R "rusage[mem=300]"

set -x

cd /stmpp1/Geoffrey.Manikin/meg/holdshort

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *html wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/.

exit

