#!/bin/ksh

set -x

ymd=20220922
version=v16.2

DAPATH=/lfs/h1/ops/prod/com/gfs/${version}/gfs.${ymd}
#DAPATH=/lfs/h2/emc/ptmp/geoffrey.manikin/gfs/gfs.${ymd}
CNVGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/cnvgrib
WGRIB=/apps/ops/prod/libs/intel/19.1.3.304/grib_util/1.2.2/bin/wgrib

mkdir /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib2
rm /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib2/*
cd /lfs/h2/emc/stmp/geoffrey.manikin/gfsnagrib2/

export DAPATH 

cycles="00 06 12 18"
cycles="00 12"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132"
#fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192"
#fhrs="06 12 18 24 30 36 42 48 54 60"
#fhrs="30 36 42 48 54 60 66 72 78 84 90 96"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240"
fhrs="120"

for cyc in $cycles
do
for fhr in $fhrs
do

ls ${DAPATH}/${cyc}/atmos/gfs.t${cyc}z.pgrb2.0p25.f${fhr}
typeset -Z3 fhr
${CNVGRIB} -g21 ${DAPATH}/${cyc}/atmos/gfs.t${cyc}z.pgrb2.0p25.f${fhr} gfs.t${cyc}z.pgrb.0p25.f${fhr}
exit
${WGRIB} gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=61:kpds6=1 | ${WGRIB} gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new1.fil
${WGRIB} gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=63:kpds6=1 | ${WGRIB} gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new2.fil

nagrib << EOF
GBFILE  = new1.fil 
INDXFL  =
GDOUTF  = dummygfs.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new2.fil
r

exit
EOF
done
#mv dummygfs.grd /meso/save/geoffrey.manikin/meg/gfspcp_${ymd}${cyc}
mv dummygfs.grd /lfs/h2/emc/vppgb//noscrub/geoffrey.manikin/ian/gfspcp_${ymd}${cyc}
done
gpend
exit
