#!/bin/ksh

set -x

ymd=20160123
#DAPATH=/com/gfs/prod/gfs.${ymd}
#DAPATH=/ptmpd3/emc.glopara/pr4devb
DAPATH=/global2/noscrub/Kate.Howard/archive/prblizzard16

mkdir /stmpp1/Geoffrey.Manikin/gfsnagrib2
rm /stmpp1/Geoffrey.Manikin/gfsnagrib2/*
cd /stmpp1/Geoffrey.Manikin/gfsnagrib2/

export DAPATH 
. /nwprod/gempak/.gempak

cycles="00 06 12 18"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96"
fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120"
#fhrs="06 12 18 24 30"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84"
#fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192 198 204 210 216 222 228 234 240 246 252 258 264"
for cyc in $cycles
do
for fhr in $fhrs
do

typeset -Z3 fhr
cp ${DAPATH}/pgrbq${fhr}.gfs.${ymd}${cyc}.grib2 pgbf${fhr}.gfs.${ymd}${cyc} 
/nwprod/util/exec/cnvgrib -g21 pgbf${fhr}.gfs.${ymd}${cyc} gfs.t${cyc}z.pgrb.0p50.f${fhr}
wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr} | grep kpds5=61:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr} -i -grib -o new1.fil
wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr} | grep kpds5=63:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p50.f${fhr} -i -grib -o new2.fil

nagrib << EOF
GBFILE  = new1.fil 
INDXFL  =
GDOUTF  = dummygfs.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new2.fil
r

exit
EOF
done
mv dummygfs.grd /meso/save/Geoffrey.Manikin/meg/gfsxpcp_${ymd}${cyc}
done
gpend
exit
