#!/bin/ksh

set -x

cyc=$1

cd /meso/save/Geoffrey.Manikin/meg
ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`cut -c 7-14 /com/date/t${cyc}z`

DAPATH=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/

export DAPATH
. /nwprod/gempak/.gempak

fhrs="06 12 18 24 30 36 42 48 54 60 66 72 78 84 90 96 102 108 114 120 126 132 138 144 150 156 162 168 174 180 186 192"

for fhr in $fhrs
do

typeset -Z3 fhr
/nwprod/util/exec/cnvgrib -g21 ${DAPATH}/${cyc}/gfs.t${cyc}z.pgrb2.0p25.f${fhr} gfs.t${cyc}z.pgrb.0p25.f${fhr}
wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=61:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new1.fil
wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} | grep kpds5=63:kpds6=1 | wgrib gfs.t${cyc}z.pgrb.0p25.f${fhr} -i -grib -o new2.fil

nagrib << EOF
GBFILE  = new1.fil
INDXFL  =
GDOUTF  = dummygfs.grd
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

GBFILE  = new2.fil
r

exit
EOF
done
mv dummymr.grd /meso/save/Geoffrey.Manikin/meg/gfspcpmr_${ymd}${cyc}
exit

