#! /bin/ksh
#
#BSUB -J megmedr.ftp
#BSUB -oo /meso/save/Geoffrey.Manikin/meg/medrftp.out
#BSUB -eo /meso/save/Geoffrey.Manikin/meg/medrftp.out
#BSUB -n 1
#BSUB -W 00:10
#BSUB -P GFS-T2O
#BSUB -R "affinity[core]"
#BSUB -q transfer
#BSUB -R "rusage[mem=300]"

set -x

cd /stmpp1/Geoffrey.Manikin/meg/holdmedr

date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/medr/images_medr/today/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/medr/images_medr/$dayoweek/.
scp *html wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/medr
exit

