#!/bin/ksh

set -x

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/nagrib
rm /stmpp1/Geoffrey.Manikin/nagrib/*
cd /stmpp1/Geoffrey.Manikin/nagrib
cp /meso/save/Geoffrey.Manikin/gempak/nagrib2/* .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`

ymdh=2015071212
ymd=`echo $ymdh | cut -c1-8`

COMOUT=/ptmpd1/Geoffrey.Manikin/com/nawips/prod/hiresw.${ymd}
DAPATH=/com/hiresw/prod/hiresw.${ymd}
DAPATH=/ptmpp2/Geoffrey.Manikin/hold

export DAPATH
. /nwprod/gempak/.gempak

fhrs="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"
fhrs="00 03 06 09 12 15 18 21 24 27 30 33 36"
for fhr in $fhrs
do

fhrr=$fhr
fhr1=`expr $fhr - 1`
if [ $fhr -lt 10 ]; then
 typeset -Z1 fhrr
else
 typeset -Z2 fhrr
fi
echo $fhr $fhrr

   nagrib2 << EOF
GBFILE  = ${DAPATH}/conusnmmb.t${cyc}z.awp5kmf${fhr}.grib2 
INDXFL  =
GDOUTF  = hiresw_conusnmmb_${ymdh}f0${fhr}
PROJ    =
GRDAREA =
KXKY    = 
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF
done

for fhr in $fhrs
do

fhrr=$fhr
fhr1=`expr $fhr - 1`

if [ $fhr -lt 10 ]; then
 typeset -Z1 fhrr
else
 typeset -Z2 fhrr
fi
echo $fhr $fhrr

   nagrib2 << EOF
GBFILE  = ${DAPATH}/conusarw.t${cyc}z.awp5kmf${fhr}.grib2
INDXFL  =
GDOUTF  = hiresw_conusarw_${ymdh}f0${fhr} 
PROJ    =
GRDAREA =
KXKY    =
GAREA   = grid
MAXGRD  = 5000
CPYFIL  = gds
OUTPUT  = T
GBTBLS  =
GBDIAG  =
r

exit
EOF

done
mv hiresw* ${COMOUT}/.

exit

