#!/bin/sh
echo 'into'

ymdh=2021090200
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold

mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg
mkdir /gpfs/dell1/stmp/Geoffrey.Manikin/meg/250wv
rm /gpfs/dell1/stmp/Geoffrey.Manikin/meg/250wv/*
cd /gpfs/dell1/stmp/Geoffrey.Manikin/meg/250wv
cp /gpfs/dell2/emc/verification/save/Geoffrey.Manikin/meg/coltbl.xwp .

fmdl1=/gpfs/dell1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymdh}f000
fmdl2=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/gempak/rap13_${ymdh}f000
fmdl1=/gpfs/dell1/ptmp/Geoffrey.Manikin/gfs/gfs_0p25_${ymdh}f000
fmdl2=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/gempak/rap13_${ymdh}f000
#fmdl2=/com2/nawips/prod/nam.${ymd}/nam12_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 250
 GVCORD   = pres
 GDPFUN   = knts(sped)
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|250verf_${ymdh}.gif | 800;850
 PROJ     = lcc/25;-75;25;/1;1;1;1                     
 GAREA    = 18.;-116.;60.;-48.   
 GAREA    = nj-
 TITLE    = 1//~   GFS  250 MB  WIND (KT) 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/0.2;0.95/0.6;0.02/1
 TEXT     = 1.1/11/2
 FINT     = 70;80;90;100;110;120;130;140;150;160;170;180
 FINT     = 50;60;70;80;90;100;110;120;130;140;150;160
 FLINE    = 0;30;28;27;25;23;21;5;10;17;11;2;15
 TYPE     = f 
r

 CINT     = 
 WIND     = BK1/0.8/2/122
 GDPFUN   = kntv(wnd)
 SKIP     = /7;7
 TYPE     = b
 TITLE    = 0
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test7/.

rm *gif
exit
