#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2017061603
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
day=`echo $ymdh | cut -c7-8`
dayoweek=hold5

mkdir /stmpp1/Geoffrey.Manikin/gempak.rtma
mkdir /stmpp1/Geoffrey.Manikin/gempak.rtma/test
rm /stmpp1/Geoffrey.Manikin/gempak.rtma/test/*
cd /stmpp1/Geoffrey.Manikin/gempak.rtma/test
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

garea="28.;-100.;48.;-64."
#garea="29.;-110.;49.;-80."
garea="28.;-90.;38.;-76."
#garea="23.;-100.;49.;-60."
#garea="26.;-108.;46.;-84"
#garea="38.;-107.;50.;-89."
garea="35.;-103.;41.;-92.8"
proj="lcc/25.;-98;25./1;1;1;1"

     sfmap << EOF
 AREA     = $garea
 GAREA    = $garea
 SATFIL   =
 RADFIL   =
 SFPARM   = pmsl 
 DATTIM   = ${day}/${cyc}
! SFFILE   = /ptmpp1/Geoffrey.Manikin/obs/${ymd}.sfc 
 SFFILE   = /dcom/us007003/ldmdata/gempak/hrly/${ymd}.hrly 
 COLORS   = 1 
 MAP      = 1
 LATLON   = 0
 TITLE    = 1/-1/~   SLP OBSERVATIONS 
 CLEAR    = no 
 PANEL    = 0 
 DEVICE   = GIF|${ymdh}_2mt.gif|750;850 
 PROJ     = $proj 
 FILTER   = none 
 TEXT     = 0.9/21/2.0/SW
 LUTFIL   =
 STNPLT   =
 CLRBAR   =
r

 SFFILE   = /dcom/us007003/ldmdata/gempak/ship/${ymd}${cyc}.ship
 SFPARM   = pmsl<$base
 COLORS   = 14
 TITLE    = 0
r
  
 SFPARM   = pmsl<$basem1
 COLORS   = 15
r
  
 SFPARM   = pmsl<$basem2
 COLORS   = 2
r
  
 SFPARM   = pmsl<$basem3
 COLORS   = 16
r
  
 SFPARM   = pmsl<$basem4
 COLORS   = 17
r
  
 SFPARM   = pmsl<$basem5
 COLORS   = 10
r

 SFPARM   = pmsl<$basem5
 COLORS   = 10
r

 SFPARM   = pmsl<$basem6
 COLORS   = 20
r

 SFPARM   = pmsl<$basem7
 COLORS   = 5
r

 SFPARM   = pmsl<$basem8
 COLORS   = 21
r

 SFPARM   = pmsl<$basem9
 COLORS   = 22
r

 SFPARM   = pmsl<$basem10
 COLORS   = 23
r

 SFPARM   = pmsl<$basem11
 COLORS   = 24
r

 SFPARM   = pmsl<$basem12
 COLORS   = 27
r

 SFPARM   = pmsl<$basem13
 COLORS   = 26
r

 SFPARM   = pmsl<$basem14
 COLORS   = 25
r

 SFPARM   = pmsl<$basem15
 COLORS   = 4
r

 SFPARM   = pmsl<$basem16
 COLORS   = 28
r

 SFPARM   = pmsl<$basem17
 COLORS   = 29
r

 SFPARM   = pmsl<$basem18
 COLORS   = 30
r

 SFPARM   = pmsl<$basem19
 COLORS   = 12
r

 SFPARM   = pmsl<$basem20
 COLORS   = 1
r
  
ex
EOF

count="1 2 3 4 5 6 7"
for counter in $count; do
 if [ $counter -lt 10 ]
  then
   file="/ptmpp1/Geoffrey.Manikin/mesonet2/msonet${cyc}.gem.00${counter}"
  else
   file="/ptmpp1/Geoffrey.Manikin/mesonet2/msonet${cyc}.gem.0${counter}"
 fi
 
     sfmap << EOF
 AREA     = $garea
 GAREA    = $garea
 SATFIL   =
 RADFIL   =
 SFPARM   = pmsl
 DATTIM   = last
 SFFILE   = $file 
 COLORS   = 1
 MAP      = 1
 LATLON   = 0
 TITLE    = 1/1/~  TEMPERATURE OBS 
 CLEAR    = $clear 
 PANEL    = $panel 
 DEVICE   = GIF|${ymdh}_2mt.gif|750;850
 PROJ     = $proj
 FILTER   = none
 TEXT     = 0.9/21/2.0/SW
 LUTFIL   =
 STNPLT   =
 CLRBAR   =
r
          
 SFPARM   = pmsl<$base
 COLORS   = 14
 CLEAR    = n
 TITLE    = 0
r

 SFPARM   = pmsl<$basem1
 COLORS   = 15
r
          
 SFPARM   = pmsl<$basem2
 COLORS   = 2
r
          
 SFPARM   = pmsl<$basem3
 COLORS   = 16
r
          
 SFPARM   = pmsl<$basem4
 COLORS   = 17
r
          
 SFPARM   = pmsl<$basem5
 COLORS   = 10
r
          
 SFPARM   = pmsl<$basem5
 COLORS   = 10
r

 SFPARM   = pmsl<$basem6
 COLORS   = 20
r

 SFPARM   = pmsl<$basem7
 COLORS   = 5
r

 SFPARM   = pmsl<$basem8
 COLORS   = 21
r

 SFPARM   = pmsl<$basem9
 COLORS   = 22
r

 SFPARM   = pmsl<$basem10
 COLORS   = 23
r

 SFPARM   = pmsl<$basem11
 COLORS   = 24
r

 SFPARM   = pmsl<$basem12
 COLORS   = 27
r

 SFPARM   = pmsl<$basem13
 COLORS   = 26
r

 SFPARM   = pmsl<$basem14
 COLORS   = 25
r

 SFPARM   = pmsl<$basem15
 COLORS   = 4
r

 SFPARM   = pmsl<$basem16
 COLORS   = 28
r

 SFPARM   = pmsl<$basem17
 COLORS   = 29
r

 SFPARM   = pmsl<$basem18
 COLORS   = 30
r

 SFPARM   = pmsl<$basem19
 COLORS   = 12
r

 SFPARM   = pmsl<$basem20
 COLORS   = 1
r

ex
EOF
done

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
