#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

validtime=2012080500
dayoweek=Mon
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c9-10`
mdlymdh=2012080400
mdlymd=`echo $mdlymdh | cut -c1-8`

mkdir /stmpp1/Geoffrey.Manikin/gempak.sound
rm /stmpp1/Geoffrey.Manikin/gempak.sound/*
cd /stmpp1/Geoffrey.Manikin/gempak.sound
cp /meso/save/Geoffrey.Manikin/casework/*xwp .
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl1=/com/nawips/prod/gfs.${mdlymd}/gfs_${mdlymdh}.snd
fmdl2=/ptmpp1/hpcops/obs/$ymd.snd
fmdl3=/ptmpp1/Geoffrey.Manikin/gfs/gfstest_${mdlymdh}.snd
echo $fmdl

stations="724560 745600 723570 725580"
stations="723570"
times="24"
for stnm in $stations; do
stn=`echo $stnm | cut -c1-5`
for time in $times; do

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = cape
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  OPS GFS DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|gfs${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/200/50/1;1;1
 XAXIS    = -25/45/10/;1
 FILTER   = 0.7
 CLEAR    = y
 PANEL    = t
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6 
 AREA     = @${stn}
r

 SNFILE   = $fmdl3
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = cape
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  TEST GFS DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|gfs${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/200/50/1;1;1
 XAXIS    = -25/45/10/;1
 FILTER   = 0.7
 CLEAR    = n
 PANEL    = b
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6
 AREA     = @${stn}
r

ex
EOF

done
done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/meg/rzftp5t.out
open rzdm
user $w1 $w2
binary
cd /home/www/emc/htdocs/mmb/gmanikin/meg/cases/$mdlymd
mput *.gif
bye
EOF

exit
