#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

dayoweek=Sun
mdlymdh=2013051900
mdlymd=`echo $mdlymdh | cut -c1-8`
mdlstnm=746470
obsstnm=74646

mkdir /stmpp1/Geoffrey.Manikin/gempak.sound
rm /stmpp1/Geoffrey.Manikin/gempak.sound/*
cd /stmpp1/Geoffrey.Manikin/gempak.sound
cp /meso/save/Geoffrey.Manikin/casework/*xwp .
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl=/com/nawips/prod/gfs.${mdlymd}/gfs_${mdlymdh}.snd
#fmdl=/ptmpp1/Geoffrey.Manikin/hold/ruc2_${ymdh}.snd
echo $fmdl

times="18"
for time in $times; do

dattim="`/meso/save/Geoffrey.Manikin/board/advtime ${mdlymdh} $time -1 x`"
validtime=`echo $dattim | cut -c1-11`
ymd=`echo $validtime | cut -c1-8`
cyc=`echo $validtime | cut -c10-11`
fmdl2=/ptmpp1/hpcops/obs/$ymd.snd

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl
 DATTIM   = $ymd/$cyc
 AREA     = @${mdlstnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = capv;cinv;lclp
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  OPS GFS DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|gfs${obsstnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/200/50/1;1;1
 XAXIS    = -20/40/10/;1
 FILTER   = 0.7
 CLEAR    = y
 PANEL    = 0
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6 
 AREA     = @${obsstnm}
r

ex
EOF

done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/meg/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/www/emc/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *.gif
bye
EOF

exit
