#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2019112912
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold9

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850t
rm /stmpp1/Geoffrey.Manikin/meg/850t/*
cd /stmpp1/Geoffrey.Manikin/meg/850t
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

DAPATH=/meso/noscrub/Geoffrey.Manikin/
fmdl1=${DAPATH}/gfs.${ymd}/gfs_0p25_${ymdh}f000
fmdl2=${DAPATH}/rap.${ymd}/rap_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = tmpc 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|850tverf_${ymdh}.gif | 800;850
 PROJ     = lcc/25;-96;25;/1;1;1;1
 GAREA    = 32.;-100.;48.;-79.
 GAREA    = ne-
 TITLE    = 1//~   GFS  850 MB  TMPC 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
# CLRBAR   = 1/V/UL/.06;0.5/1.0;.03/2
 CLRBAR   = 1/V/UL/.02;0.95/1.0;.03/2
 TEXT     = 1.1/11/2
 FINT     = -16;-14;-12;-10;-8;-6;-4;-2;0;2;4;6;8;10;12;14
 FLINE    = 0;12;30;29;28;4;25;27;24;23;21;5;20;10;17;16;2;15;32
 TYPE     = f 
r

 CINT     = 0/0/0
 LINE     = 1/1/4/1
 CLEAR    = n
 TYPE     = c
r

 PANEL    = b
 GDFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//~   RAP  850 MB   TMPC 
 CLRBAR   = 0
 TYPE     = f
r

 CINT     = 0/0/0
 LINE     = 1/1/4/1
 CLEAR    = n
 TYPE     = c
r


ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
