#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

times="24 30 36 48 54 60 66 72 78 84"
ymdh=2013032512
ymd=`echo $ymdh | cut -c1-8`
dayoweek=Mon

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/vslp
rm /stmpp1/Geoffrey.Manikin/meg/vslp/*
cd /stmpp1/Geoffrey.Manikin/meg/vslp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

for fhr in $times; do
dattim="`/meso/save/Geoffrey.Manikin/board/advtime $ymdh -$fhr -1`"
mdlymdh=`echo $dattim | cut -c1-10`
mdlymd=`echo $dattim | cut -c1-8`
mdlcyc=`echo $dattim | cut -c9-10`

fmdl1=/com/nawips/prod/nam.${mdlymd}/nam40_${mdlymdh}f0${fhr}
fmdl2=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 4 
 LINE     = 2/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM f${fhr} SLP (red)   GDAS SLP (green)
 DEVICE   = GIF|verfnamslp_${ymdh}f0${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-75.;25./2;2;1;1
 GAREA    = 24.;-94.;52.;-54. 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 15;15/S12#;S13#/1015-1060;920-1014/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 3/1/3/2
 TITLE    = 0
 HILO     = 23;23/S12#;S13#/1015-1060;920-1014/5/3;4/yes
 HLSYM    = 2;1/3/21;21/4;2/HW
r

ex
EOF
done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput ${cyc}*gif
bye
EOF

rm *gif
exit
