#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2019071512
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/capev
rm /stmpp1/Geoffrey.Manikin/meg/capev/*
cd /stmpp1/Geoffrey.Manikin/meg/capev
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

DAPATH1=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/nawips
#DAPATH1=/meso/noscrub/Geoffrey.Manikin/rap.${ymd}
fmdl1=${DAPATH1}/rap13_${ymdh}f000
fmdl2=/com2/nawips/prod/nam.${ymd}/nam20_${ymdh}f000
echo $fmdl1
echo

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP  SFC-BASED CAPE 
 DEVICE   = GIF|scapeverf_${ymdh}.gif|750;900
 SATFIL   =
 RADFIL   =
# PROJ     = lcc/25;-97;25;/1;1;1;1
# GAREA    = 21.;-120.;51.;-66. 
 PROJ     = lcc/25;-90;25;/1;1;1;1
 GAREA    = 33.;-108.;51.;-84. 
 GAREA    = 27.;-88.;35.6;-76.
 GAREA    = 28.;-90.;38.;-76.
 GAREA    = la 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 TITLE    = 1/-1/~  NAM  SFC-BASED CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
