#!/bin/sh
echo 'into'

ymdh=2022072812
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold

mkdir /lfs/h1/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h1/emc/stmp/geoffrey.manikin/meg/pwat
rm /lfs/h1/emc/stmp/geoffrey.manikin/meg/pwat/*
cd /lfs/h1/emc/stmp/geoffrey.manikin/meg/pwat
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

#fmdl1=/lfs/h1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymdh}f000
fmdl1=/lfs/h2/emc/vpppg/noscrub//geoffrey.manikin/floods22/gfs_0p25_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = quo(pwtr,25.4) 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|pwverf_${ymdh}.gif | 800;850
 PROJ     = lcc/25.;-85.;25./2;2;1;1
 GAREA    = 20.;-124.;50.;-62. 
 GAREA    = 26.;-98.5;34.;-87.5
 GAREA    = 32.;-99;43.;-83 
 GAREA    = ky
 TITLE    = 1//~   GFS PCP WATER 
 CLEAR    = y
 SCALE    = 0
 PANEL    = 0
 HILO     = 0
 HLSYM    = 0 
# CLRBAR   = 1/V/UL/.02;0.5/1.0;.03/2
 CLRBAR   = 1/H/UL/.02;0.96/0.95;.03/2
 TEXT     = 1.1/11/2
 FINT     = .25;.5;.75;1.;1.25;1.5;1.75;2.;2.25;2.5
 FLINE    = 0;21;22;23;28;30;2;15;10;5;31
 TYPE     = f 
r

ex
EOF

gpend
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.
rm *gif
exit
