#!/bin/sh
echo 'into'

ymdh=2022072800
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
dayoweek=hold8

mkdir /lfs/h1/emc/stmp/geoffrey.manikin/meg
mkdir /lfs/h1/emc/stmp/geoffrey.manikin/meg/500z
rm /lfs/h1/emc/stmp/geoffrey.manikin/meg/500z/*
cd /lfs/h1/emc/stmp/geoffrey.manikin/meg/500z
cp /lfs/h2/emc/vpppg/save/geoffrey.manikin/meg/coltbl.xwp .

#fmdl1=/lfs/h1/nco/ops/com/gfs/prod/gfs.${ymd}/${cyc}/atmos/gempak/gfs_0p25_${ymdh}f000
fmdl1=/lfs/h2/emc/vpppg/noscrub//geoffrey.manikin/floods22/gfs_0p25_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = avor
 CINT     = 2/10/46
 LINE     = 0
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS 500 mb  Z/AVOR
 DEVICE   = GIF|500verf_${ymdh}.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-85.;25./2;2;1;1
# GAREA    = 24.;-100.;50.;-60. 
 GAREA    = 18.;-120.;64.;-42.
# GAREA    = 25.;-100.;57.;-54. 
 GAREA    = ky- 
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 5
 LATLON   = 0
 HILO     = 2/x#;/14-76;/5//yes
 HLSYM    = 1//21;//HW
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36;40;44
 FLINE    = 0;23;21;5;19;17;16;2;15
 TYPE     = f/c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 4/1/3/1
 TITLE    = 0
 CLEAR    = n
 SCALE    = 0
 HILO     = 0
 HLSYM    = 2;2//2/4/SW
 TEXT     = 1.2/11/2
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r
ex
EOF

gpend
#scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/test8/.

exit
