#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2016092900
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold2

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/capev
rm /stmpp1/Geoffrey.Manikin/meg/capev/*
cd /stmpp1/Geoffrey.Manikin/meg/capev
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl1=/com2/nawips/prod/rap.${ymd}/rap13_${ymdh}f000
fmdl2=/com/nawips/prod/nam.${ymd}/nam20_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 180:0 
 GVCORD   = pdly 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP  BEST CAPE 
 DEVICE   = GIF|bcapeverf_${ymdh}.gif|750;900
 SATFIL   =
 RADFIL   =
# PROJ     = lcc/25;-95;25;/1;1;1;1
# GAREA    = 21.;-120.;51.;-66. 
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 33.;-108.;51.;-84. 
 GAREA    = md 
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.01;0.4/0.8;.03/2 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 50;500;1000;1500;2000;2500;3000;3500;4000;4500;5000
 FLINE    = 0;25;21;22;23;5;10;17;16;2;15;32
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr
 TITLE    = 1/-1/~  NAM  BEST CAPE 
 PANEL    = b
 CLRBAR   = 0
 CLEAR    = n
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
