#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2014110700
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/sfc
rm /stmpp1/Geoffrey.Manikin/meg/sfc/*
cd /stmpp1/Geoffrey.Manikin/meg/sfc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#fmdl1=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000
fmdl1=/com/nawips/prod/gfs.${ymd}/gfs_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 4 
 LINE     = 4/1/3/1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GDAS SLP 1000-500 THK 
 DEVICE   = GIF|verfslp_${ymdh}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = str/90;-145;0;/1;1;1;1
 GAREA    = 35.;-190.;75.;-118.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 2;2/S12#;S13#/1015-1060;900-1014/5/3;4/yes
 HLSYM    = 2;2/3/1;21/4;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(sub(hght@500,hght@1000),10)
 GVCORD   = pres
 GLEVEL   = 500
 CINT     = 6/546/600
 LINE     = 2/2/1/3
 CLEAR    = n
 TITLE    = 0
 SCALE    = 0
 HILO     = 0
 HLSYM    = 0
 TEXT     = 0.8/11/1
 FINT     = 0
 FLINE    = 0
 TYPE     = c
r

 CINT     = 6/498/540
 LINE     = 4/2/1/3
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
