#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2013052019
ymd=`echo $ymdh | cut -c1-8`
cyc=`echo $ymdh | cut -c9-10`
day=`echo $ymdh | cut -c7-8`
month=`echo $ymdh | cut -c5-6`
dayoweek=Mon

mkdir /stmpp1/Geoffrey.Manikin/gempak.rtma
mkdir /stmpp1/Geoffrey.Manikin/gempak.rtma/test
rm /stmpp1/Geoffrey.Manikin/gempak.rtma/test/*
cd /stmpp1/Geoffrey.Manikin/gempak.rtma/test/
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

garea="ok+"
proj="lcc/25.;-98.;25./2;2;1;1"

     sfmap << EOF
 AREA     = $garea
 GAREA    = $garea
 SATFIL   =
 RADFIL   =
 SFPARM   = brbk:0.7:2 
 DATTIM   = ${day}/${cyc}
 SFFILE   = /ptmpp1/hpcops/obs/${ymd}.hrly 
! SFFILE   = /ptmpp1/Geoffrey.Manikin/obs/${ymd}.sfc
 COLORS   = 2 
 \$MAPFIL  = county
 MAP      = 1 + 22
 LATLON   = 0
 TITLE    = 1/-1/~   ALL OBS 
 CLEAR    = no 
 PANEL    = 0 
 DEVICE   = GIF|${ymdh}_10obs.gif|800;800
 PROJ     = $proj 
 FILTER   = none 
 TEXT     = 1.0/21/2/SW
 LUTFIL   =
 STNPLT   =
 CLRBAR   =
r

ex
EOF

count="1 2 3 4 5 6"
for counter in $count; do
 if [ $counter -lt 10 ]
  then
   file="/ptmpp1/Geoffrey.Manikin/mesonet2/msonet${cyc}.gem.00${counter}"
  else
   file="/ptmpp1/Geoffrey.Manikin/mesonet2/msonet${cyc}.gem.0${counter}"
 fi

     sfmap << EOF
 AREA     = $garea
 GAREA    = $garea
 SATFIL   =
 RADFIL   =
 SFPARM   = brbk:0.7:2 
 DATTIM   = last 
 SFFILE   = $file 
 COLORS   = 15 
 MAP      = 1
 LATLON   = 0
 TITLE    = 0
 CLEAR    = NO 
 PANEL    = 0 
 DEVICE   = GIF|${ymdh}_10obs.gif|800;800
 PROJ     = $proj
 FILTER   = none
 TEXT     = 1.0/21/2/SW
 LUTFIL   =
 STNPLT   =
 CLRBAR   =
r

ex
EOF
done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/rtma_alaska/rzftp5t.out
open emcrzdm
user $w1 $w2
binary
cd /home/www/emc/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek
mput *.gif
bye
EOF

exit
