#!/bin/sh
echo 'into'
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/plots
mkdir /stmpp1/Geoffrey.Manikin/plots/sfc
rm /stmpp1/Geoffrey.Manikin/plots/sfc/*
cd /stmpp1/Geoffrey.Manikin/plots/sfc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=2017010709
day=`echo $ymdh | cut -c7-8`
hr=`echo $ymdh | cut -c9-10`
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold7
area="32.;-99.;46.;-77."
area="33.5;-81.4;40.;-75."
obsfile=${ymd}.sfc
echo obsfile = $obsfile

   sfmap << EOF
 AREA      = $area 
 GAREA     = $area 
 SATFIL    =       
 RADFIL    =         
 SFPARM    = wsym<80 
 DATTIM    = ${day}/${hr}
 SFFILE   = /dcom/us007003/ldmdata/gempak/hrly/${ymd}.hrly
 DEVICE    = GIF|${ymd}${hr}_obstype.gif | 800;850
 COLORS    = 4 
 MAP       = 1
 \$MAPFIL = county
 LATLON    = 0
 TITLE     = 1/-1/~
 CLEAR     = y 
 PANEL     = 0 
 PROJ      = MER/0;0;0/2;2;0;1
 FILTER    = n 
 TEXT      = 1.0/21/2/HW
 LUTFIL    = 
 STNPLT    =  
 CLRBAR    =
r

 SFPARM    = wsym < 70
 COLORS    = 2
 CLEAR     = n
r

 SFPARM    = wsym < 65
 COLORS    = 3
r

 SFPARM    = wsym < 50
 COLORS    = 28
r

 SFPARM    = wsym < 11 
 COLORS    = 5 
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
