#!/bin/ksh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/500srefmem
rm /stmpp1/Geoffrey.Manikin/meg/500srefmem/*
cd /stmpp1/Geoffrey.Manikin/meg/500srefmem
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

ymdh=2015121518
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold4

fmdl1=/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = last 
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = quo(hght,10) 
 CINT     = 1/558/558
 LINE     = 1/1/4/0
 MAP      = 1
 WIND     = 0
 TITLE    = 1//  $mdl CTL 500 Z  $ymd ${cyc}z  F00 
 DEVICE   = GIF|gfs500_${ymdh}f00.gif | 800;850
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-92;25;/1;1;1;1
 GAREA   = 24.;-122.;56.;-74. 
 CLEAR    = y
 PANEL    = 0 
 TEXT     = 0.7/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend

scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
