#!/bin/sh
echo 'into'
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/plots
mkdir /stmpp1/Geoffrey.Manikin/plots/sfc
rm /stmpp1/Geoffrey.Manikin/plots/sfc/*
cd /stmpp1/Geoffrey.Manikin/plots/sfc
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

ymdh=20170314
day=`echo $ymdh | cut -c7-8`
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8
area="38.;-78;42.;-72."

hours="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21"
for hr in $hours; do

   sfmap << EOF
 AREA      = $area 
 GAREA     = $area 
 SATFIL    =       
 RADFIL    =         
 SFPARM    = wsym<80 
 DATTIM    = ${day}/${hr}
 SFFILE   = /dcom/us007003/ldmdata/gempak/hrly/${ymd}.hrly
 DEVICE    = GIF|${hr}_obstype.gif | 800;850
 COLORS    = 29 
 MAP       = 1
 LATLON    = 0
 TITLE     = 1/-1/~
 CLEAR     = y 
 PANEL     = 0 
 PROJ      = MER/0;0;0/2;2;0;1
 FILTER    = n 
 TEXT      = 0.9/21/2/HW
 LUTFIL    = 
 STNPLT    =  
 CLRBAR    =
r

 SFPARM    = wsym < 75
 COLORS    = 4
 CLEAR     = n
r

 SFPARM    = wsym < 70 
 COLORS    = 2
r

 SFPARM    = wsym < 65 
 COLORS    = 3 
r

 SFPARM    = wsym < 60
 COLORS    = 1
r

 SFPARM    = wsym < 11 
 COLORS    = 5 
r

ex
EOF
done
gpend

/usrx/local/ImageMagick/6.8.3-3/bin/convert -loop 0 -delay 100 *obstype*gif ${ymd}_obs.gif
scp *loop*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
