#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

dayoweek=Fri
mdlymdh=2013120612
mdlymd=`echo $mdlymdh | cut -c1-8`
stations="744550 726320 722150"
stations="723570 723400 724560 726590"
stations="723270 724400 723400"
stations="725620 722080 726450 722300 722150 722350"
stations="724560 744550 725580 724400"
#stations="725580 724560 744550 745600 726490"
stations="725010"

mkdir /stmpp1/Geoffrey.Manikin/gempak.sound
rm /stmpp1/Geoffrey.Manikin/gempak.sound/*
cd /stmpp1/Geoffrey.Manikin/gempak.sound
cp /meso/save/Geoffrey.Manikin/casework/*xwp .
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl1=/com/nawips/prod/nam.${mdlymd}/nam_${mdlymdh}.snd.tm00
fmdl2=/ptmpp1/hpcops/obs/$ymd.snd
fmdl3=/ptmpp1/Geoffrey.Manikin/gfs/gfstest_${mdlymdh}.snd
echo $fmdl

times="00"

for time in $times; do
for stnm in $stations; do
stn=`echo $stnm | cut -c1-5`

if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = cape
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  NAM DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|nam${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/300/50/1;1;1
 XAXIS    = -40/20/10/;1
 FILTER   = 0.7
 CLEAR    = y
 PANEL    = t
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6 
 AREA     = @${stn}
r

 SNFILE   = $fmdl3
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = cape
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  TEST GFS DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|nam${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/200/50/1;1;1
 XAXIS    = -25/45/10/;1
 FILTER   = 0.7
 CLEAR    = n
 PANEL    = b
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6
 AREA     = @${stn}
r

ex
EOF

done
done
gpend

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/meg/rzftp5t.out
open emcrzdm
user $w1 $w2
binary
cd /home/www/emc/htdocs/mmb/gmanikin/meg/cases/$mdlymd
mput *.gif
bye
EOF

exit
