#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1

ymdh=2019070618
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold8

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/capev
rm /stmpp1/Geoffrey.Manikin/meg/capev/*
cd /stmpp1/Geoffrey.Manikin/meg/capev
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

DAPATH1=/gpfs/hps/nco/ops/com/rap/prod/rap.${ymd}/nawips
DAPATH1=/ptmpp1/Geoffrey.Manikin/rap
fmdl1=${DAPATH1}/rap13_${ymdh}f000
fmdl2=/com2/nawips/prod/nam.${ymd}/nam20_${ymdh}f000
echo $fmdl1
echo

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = cape 
 CINT     = 500 
 LINE     = 1 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   RAP ANALYSIS SFC-BASED CAPE 
 DEVICE   = GIF|scapeverf_${ymdh}.gif|750;900
 SATFIL   =
 RADFIL   =
# PROJ     = lcc/25;-97;25;/1;1;1;1
# GAREA    = 21.;-120.;51.;-66. 
 PROJ     = lcc/25;-86;25;/1;1;1;1
 GAREA    = 33.;-108.;51.;-84. 
 GAREA    = 27.;-88.;35.6;-76.
 GAREA    = 40.;-95.;50.;-81.
 GAREA    = 19.;-122.;51.;-64.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0 
 CLRBAR   = 1/H/UL/.01;0.95/0.9;.03/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 100;250;500;1000;1500;2000;2500;3000;3500;4000;4500
 FLINE    = 0;4;25;27;22;31;5;20;17;2;14;29
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

ex
EOF
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
