#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

ymdh=2018060715
ymd=`echo $ymdh | cut -c1-8`
dayoweek=hold

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/850wv
rm /stmpp1/Geoffrey.Manikin/meg/850wv/*
cd /stmpp1/Geoffrey.Manikin/meg/850wv
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

fmdl1=/gpfs/hps/nco/ops/com/nawips/prod/gfs.${ymd}/gfs_0p25_${ymdh}f000
fmdl2=/com2/nawips/prod/rap.${ymd}/rap13_${ymdh}f000
#fmdl2=/com2/nawips/prod/nam.${ymd}/nam12_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f00
 GLEVEL   = 850
 GVCORD   = pres
 GDPFUN   = thte 
 CINT     = 5 
 LINE     = 0 
 DEVICE   = GIF|850thteverf_${ymdh}.gif | 800;850
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 20.;-124.;50.;-62. 
 GAREA    = 26.;-98.5;34.;-87.5
 GAREA    = ok
 TITLE    = 1//~   GFS   850 MB  THTE 
 CLEAR    = y
 SCALE    = 0
 PANEL    = t
 HILO     = 0
 HLSYM    = 0 
 CLRBAR   = 1/V/UL/.06;0.5/1.0;.03/2
 TEXT     = 1.1/11/2
 FINT     = 304;308;312;316;320;324;328;332;336;340;344;348;352
 FLINE    = 12;30;29;28;4;25;26;27;24;23;22;21;5;20;10;17;16;2;15;14;
 TYPE     = f 
r

 PANEL    = b
 GDFILE   = $fmdl2
 CLEAR    = n
 TITLE    = 1//~   RAP  850 MB  THTE 
 CLRBAR   = 0
r

ex
EOF

gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
rm *gif
exit
