#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

dayoweek=hold
mdlymdh=2014101706
mdlymd=`echo $mdlymdh | cut -c1-8`
stations="744550 726320 722150"
stations="723570 723400 724560 726590"
stations="725580 726490 726590"
stations="722490 723400 723570"
stations="724030"
stations="723630 722650 724510"

mkdir /stmpp1/Geoffrey.Manikin/gempak.sound
rm /stmpp1/Geoffrey.Manikin/gempak.sound/*
cd /stmpp1/Geoffrey.Manikin/gempak.sound
cp /meso/save/Geoffrey.Manikin/casework/*xwp .
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

times="06"
for time in $times; do
for stnm in $stations; do

dattim="`/meso/save/Geoffrey.Manikin/board/advtime ${mdlymdh} $time -1`"
ymdh=`echo $dattim | cut -c1-10`
ymd=`echo $dattim | cut -c1-8`
cyc=`echo $dattim | cut -c9-10`
fmdl1=/com/nawips/prod/nam.${mdlymd}/nam_conusnest_${mdlymdh}.snd
fmdl2=/ptmpp1/wpc.ops/obs/$ymd.snd

stn=`echo $stnm | cut -c1-5`
if [ $time -lt 10 ]
then
fhr=0${time}
else
fhr=$time
fi

    snprof << EOF
 SNFILE   = $fmdl1
 DATTIM   = $ymd/$cyc
 AREA     = @${stnm}
 SNPARM   = tmpc;dwpc
 LINE     = 2;4/2/6
 PTYPE    = skewt
 VCOORD   = PRES
# STNDEX   = lift;cape;cins
 STNDEX   = cape
 STNCOL   = 24
 WIND     = bk1
 WINPOS   = 2
 MARKER   = 0
 BORDER   = 1//2
 TITLE    = 1//  OPS NAM CONUS NEST DASHED   OBS SOLID/LEFT WINDS
 DEVICE   = gif|namnestz${stnm}_${mdlymdh}f$fhr.gif|1000;1000
 YAXIS    = 1050/500/50/1;1;1
 XAXIS    = -25/35/5/;1
 FILTER   = 0.7
 CLEAR    = y
 PANEL    = 0
! TEXT     = 1.0/11/2/SW
 TEXT     = 1.1/23/SW
 THTALN   = 8/3/1/250/500/5
 THTELN   = 23/1/1/250/500/5
 MIXRLN   = 17/10/2/0/40./1.
r

 SNFILE   = $fmdl2
 CLEAR    = n
 WINPOS   = 1
 LINE     = 2;4/1/6 
 AREA     = @${stn}
r

ex
EOF

done
done
gpend
scp *gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.
exit
