#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/slp
rm /stmpp1/Geoffrey.Manikin/meg/slp/*
cd /stmpp1/Geoffrey.Manikin/meg/slp
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

verymdh=2013032518
verymd=`echo $verymdh | cut -c1-8`
verday=`echo $verymdh | cut -c7-8`
verhr=`echo $verymdh | cut -c9-10`
dayoweek=Sun

lead=1
fhr1=42
fhr2=`expr $fhr1 - 6`
fhr3=`expr $fhr1 - 12`
fhr4=`expr $fhr1 - 18`

ymdh1="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${verymdh} -$fhr1 -1`"
ymd=`echo $ymdh1 | cut -c1-8`
ymdh2="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${verymdh} -$fhr2 -1`"
ymdh3="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${verymdh} -$fhr3 -1`"
ymdh4="`/meso/save/Geoffrey.Manikin/meteograms.nam/advtime ${verymdh} -$fhr4 -1`"

fmdl1=/com/nawips/prod/nam.${ymd}/nam40_${ymdh1}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd}/nam40_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd}/nam40_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd}/nam40_${ymdh4}f0${fhr4}
fmdl5=/com/nawips/prod/gdas.${verymd}/gdas_${verymdh}f000


    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 GLEVEL   = 0 
 GVCORD   = none 
 GDPFUN   = pmsl 
 CINT     = 0 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/ NAM $ymd RED-00z BLUE-06z GREEN-12z PUR-18z BRO-obs
 DEVICE   = GIF|lowplot1.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-75;25;/1;1;1;1
 GAREA    = 34.;-82.;46;-64. 
 GAREA    = de+ 
 CLEAR    = y
 PANEL    = t
 TEXT     = 0.8/11/2/SW
 SCALE    = 0
 LATLON   = 0
 HILO     = ;2/;S13#/;920-1008/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0 
 FLINE    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 TITLE    = 1/1/  VERIFYING TIME   $verymdh
 CLEAR    = n
 TITLE    = 0 
 HILO     = ;4/;S13#/;920-1008/5/1;1/yes 
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 HILO     = ;22/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 HILO     = ;29/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl5
 GDATTIM  = f00 
 HILO     = ;8/;S13#/;920-1008/5/1;1/yes
r

ex
EOF

fmdl1=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh1}f0${fhr1}
fmdl2=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh2}f0${fhr2}
fmdl3=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh3}f0${fhr3}
fmdl4=/com/nawips/prod/nam.${ymd}/nam_conusnest_${ymdh4}f0${fhr4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 WIND     = 0
 TITLE    = 0 
 DEVICE   = GIF|lowplot2.gif|850;950
 CLEAR    = y
 PANEL    = t
 HILO     = ;2/;S13#/;920-1008/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 TITLE    = 1/1/  VERIFYING TIME   $verymdh
 CLEAR    = n
 HILO     = ;4/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 HILO     = ;22/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 TITLE    = 1/-1/ NAM NEST $ymd RED-00z BLUE-06z GREEN-12z PUR-18z BRO-obs
 HILO     = ;29/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 HILO     = ;8/;S13#/;920-1008/5/1;1/yes
 TITLE    = 0
r

ex
EOF

fmdl1=/meso/save/Geoffrey.Manikin/meg/namb_${ymdh1}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namb_${ymdh3}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 WIND     = 0
 TITLE    = 1/-1/ NAMB $ymd RED-00z  GREEN-12z  BRO-obs
 DEVICE   = GIF|lowplot3.gif|850;950
 CLEAR    = y
 PANEL    = t
 HILO     = ;2/;S13#/;920-1008/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 CLEAR    = n
 TITLE    = 0
 HILO     = ;22/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 HILO     = ;8/;S13#/;920-1008/5/1;1/yes
r

ex
EOF

fmdl1=/meso/save/Geoffrey.Manikin/meg/namx_${ymdh1}
fmdl2=/meso/save/Geoffrey.Manikin/meg/namx_${ymdh2}
fmdl3=/meso/save/Geoffrey.Manikin/meg/namx_${ymdh3}
fmdl4=/meso/save/Geoffrey.Manikin/meg/namx_${ymdh4}

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f$fhr1
 WIND     = 0
 TITLE    = 1/-1/ NAMX $ymd RED-00z  GREEN-12z  BRO-obs
 DEVICE   = GIF|lowplot4.gif|850;950
 CLEAR    = y
 PANEL    = t
 HILO     = ;2/;S13#/;920-1008/5/1;1/yes
 HLSYM    = 1;1/3/1;1/3;2/HW
r

 GDFILE   = $fmdl2
 GDATTIM  = f$fhr2
 TITLE    = 1/1/  VERIFYING TIME   $verymdh
 CLEAR    = n
 HILO     = ;4/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl3
 GDATTIM  = f$fhr3
 HILO     = ;22/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl4
 GDATTIM  = f$fhr4
 HILO     = ;29/;S13#/;920-1008/5/1;1/yes
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 HILO     = ;8/;S13#/;920-1008/5/1;1/yes
r

ex
EOF
gpend

/usrx/local/im_beta/bin/convert -crop 0x0 lowplot1.gif namslpday${lead}_${verymdh}.gif
/usrx/local/im_beta/bin/convert -crop 0x0 lowplot2.gif namnestslpday${lead}_${verymdh}.gif
/usrx/local/im_beta/bin/convert -crop 0x0 lowplot3.gif nambslpday${lead}_${verymdh}.gif
/usrx/local/im_beta/bin/convert -crop 0x0 lowplot4.gif namxslpday${lead}_${verymdh}.gif

. /u/Geoffrey.Manikin/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp2.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/today
mput *slp*gif
bye
EOF

ftp -n -v << EOF > /meso/save/Geoffrey.Manikin/casework/rzftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/${dayoweek}
mput *slp*gif
bye
EOF

exit
