#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
times="12 18 24 30 36 42 48 54 60 66 72 78 84"

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013052600
#ymd=`echo $ymdh | cut -c1-8`
#dayoweek=Sun

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/v500
rm /stmpp1/Geoffrey.Manikin/meg/v500/*
cd /stmpp1/Geoffrey.Manikin/meg/v500
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

#scp tide:/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000 .
for fhr in $times; do
dattim="`/meso/save/Geoffrey.Manikin/meg/advtime $ymdh -$fhr -1`"
mdlymdh=`echo $dattim | cut -c1-10`
mdlymd=`echo $dattim | cut -c1-8`
mdlcyc=`echo $dattim | cut -c9-10`

fmdl1=/com/nawips/prod/nam.${mdlymd}/nam32_${mdlymdh}f0${fhr}
fmdl2=/com2/nawips/prod/gfs.${mdlymd}/gfs_${mdlymdh}f0${fhr}
fmdl3=/com/nawips/prod/ecmwf.${mdlymd}/ecmwf_hr_${mdlymdh}f0${fhr}
cp /meso2/noscrub/Eric.Rogers/com/nawips/para/nam.${mdlymd}/nam32_${mdlymdh}f0${fhr} fmdl4
#fmdl5=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000
fmdl5=/com2/nawips/prod/gfs.${ymd}/gfs_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = quo(hght,10) 
 CINT     = 6 
 LINE     = 2/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~  NAM 500Z (red)  GDAS (green)
 DEVICE   = GIF|ver1${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 10.;-138.;70.;-18.
 CLEAR    = y
 PANEL    = t
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 HILO     = 0
 HLSYM    = 0 
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

 GDFILE   = $fmdl2
 GDATTIM  = f${fhr}
 LINE     = 2/1/3/2
 TITLE    = 1/-1/~   GFS f${fhr} 500Z (red)   GDAS (green)
 PANEL    = b
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

 GDFILE   = $fmdl3
 GDATTIM  = f${fhr}
 LINE     = 2/1/3/2
 DEVICE   = GIF|ver2${fhr}.gif|850;950
 TITLE    = 1/-1/~   ECMWF f${fhr} 500Z (red)   GDAS (green)
 PANEL    = t
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

 GDFILE   = fmdl4
 GDATTIM  = f${fhr}
 LINE     = 2/1/3/2
 TITLE    = 1/-1/~   NAMX f${fhr} 500Z (red)   GDAS (green)
 PANEL    = b
r

 GDFILE   = $fmdl5
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

ex
EOF
done
gpend

CONV=/usrx/local/ImageMagick/6.8.3-3/bin
for fhr in $times; do
  $CONV/convert -trim ver1${fhr}.gif  5001${fhr}.gif 
  $CONV/convert -crop 0x0 ver2${fhr}.gif  5002${fhr}.gif
  $CONV/montage -geometry 800x850 5001${fhr}.gif 5002${fhr}.gif ${cyc}ver500${fhr}.gif
done

mv ${cyc}*gif /stmpp1/Geoffrey.Manikin/meg/holdshort/.
#scp ${cyc}*gif wd20mg@emcrzdm:/home/people/emc/www/htdocs/mmb/gmanikin/meg/short/images_short/$dayoweek/.

rm *gif
exit
