#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

cyc=$1
times="12 18 24 30 36 42 48 54 60 66 72 78 84"

ymdh=`cut -c 7-16 /com/date/t${cyc}z`
ymd=`echo $ymdh | cut -c1-8`
date
date > holddate
echo $holddate
dayoweek=`cut -c 1-3 holddate`

#ymdh=2013052600
#ymd=`echo $ymdh | cut -c1-8`
#dayoweek=Sun

mkdir /stmpp1/Geoffrey.Manikin/meg
mkdir /stmpp1/Geoffrey.Manikin/meg/v500
rm /stmpp1/Geoffrey.Manikin/meg/v500/*
cd /stmpp1/Geoffrey.Manikin/meg/v500
cp /meso/save/Geoffrey.Manikin/casework/coltbl.xwp .

for fhr in $times; do
dattim="`/meso/save/Geoffrey.Manikin/board/advtime $ymdh -$fhr -1`"
mdlymdh=`echo $dattim | cut -c1-10`
mdlymd=`echo $dattim | cut -c1-8`
mdlcyc=`echo $dattim | cut -c9-10`

fmdl1=/com2/nawips/prod/nam.${mdlymd}/nam32_${mdlymdh}f0${fhr}
fmdl2=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = quo(hght,10) 
 CINT     = 6 
 LINE     = 2/1/3/2 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   NAM f${fhr} 500Z (red)   GDAS (green)
 DEVICE   = GIF|verfnam500${fhr}.gif|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 10.;-138.;70.;-20.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 CLRBAR   = 0 
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 HILO     = 0
 HLSYM    = 0 
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

ex
EOF
done

for fhr in $times; do
dattim="`/meso/save/Geoffrey.Manikin/board/advtime $ymdh -$fhr -1`"
mdlymdh=`echo $dattim | cut -c1-10`
mdlymd=`echo $dattim | cut -c1-8`
mdlcyc=`echo $dattim | cut -c9-10`

fmdl1=/com/nawips/prod/gfs.${mdlymd}/gfs_${mdlymdh}f0${fhr}
fmdl2=/com/nawips/prod/gdas.${ymd}/gdas_${ymdh}f000

    gdplot2 << EOF
 GDFILE   = $fmdl1
 GDATTIM  = f${fhr}
 GLEVEL   = 500
 GVCORD   = pres
 GDPFUN   = quo(hght,10)
 CINT     = 6
 LINE     = 2/1/3/2
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   GFS f${fhr} 500Z (red)   GDAS (green)
 DEVICE   = GIF|verfgfs500${fhr}.gif|850;950|850;950
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25.;-95.;25./2;2;1;1
 GAREA    = 12.;-136.;66.;-22.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 1.1/11/2/SW
 SCALE    = 0
 LATLON   = 0
 CLRBAR   = 0
 CONTUR   = 0
 SKIP     = 0
 FINT     = 16;20;24;28;32;36
 FLINE    = 0;23;21;5;19;17;16
 HILO     = 0
 HLSYM    = 0
 TYPE     = c
 LUTFIL   =
 STNPLT   =
r

 GDFILE   = $fmdl2
 GDATTIM  = f00
 CLEAR    = n
 LINE     = 22/1/3/2
 TITLE    = 0
r

ex
EOF
done
gpend

CONV=/usrx/local/imajik/bin
for fhr in $times; do
 $CONV/montage -geometry 800x850 verfnam500${fhr}.gif verfgfs500${fhr}.gif ${cyc}ver500${fhr}.gif 
done

rm *gif
exit
